### ISSUE TITLE
Button alignment in Modals - how can I override footer item alignment?

### ISSUE THREAD

**Issue by v79** [themesberg/flowbite-svelte#1001]
## Summary

In Modal dialogues, the footer can contain buttons. But unlike most systems, Flowbite-svelte left-aligns everything in the footer slot. How can I pull this to the right, where most other UI frameworks put them?

### Basic example

Current:
![Screenshot 2023-08-19 155435](https://github.com/themesberg/flowbite-svelte/assets/18570/d17ef7a8-2e58-4ac5-9ae1-e55c02a58b9b)
Desired:
![Screenshot 2023-08-19 155435 desired](https://github.com/themesberg/flowbite-svelte/assets/18570/127b8eca-7ea7-4666-b579-a933c756b1d2)

### Motivation

Most UI frameworks align modal dialog buttons to the right hand side. It's very jarring for flowbite to do it differently.

**Comment by gi4no** [comment]
you can just wrap your buttons in a element and align them

```svelte
<svelte:fragment slot="footer">
    <div class="flex justify-end w-full gap-x-4">
      <Button on:click={() => alert('Handle "success"')}>I accept</Button>
      <Button color="alternative">Decline</Button>
    </div>
  </svelte:fragment>
```
