### ISSUE TITLE
Modal: "dismissable" does not exist in type

### ISSUE THREAD

**Issue by sspilleman** [themesberg/flowbite-svelte#1024]
### Describe the bug

I have the following:
```html
<Modal bind:open outsideclose size="xl" placement="top-center" dismissable={false}>
	{#if strings}
		<Stringseditor {strings} on:save={stringsChanged}></Stringseditor>
	{/if}
	{#if query}
		<Videolist total={0} index="movies" {query}></Videolist>
	{/if}
</Modal>
```
I get the following error message in VSCode

`Object literal may only specify known properties, and '"dismissable"' does not exist in type`
This should be there right? (according to the docs)

### Reproduction

None available unfortunately

### Flowbite version and System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 11.39 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.5.1 - /opt/homebrew/bin/node
    npm: 9.8.0 - /opt/homebrew/bin/npm
    pnpm: 8.6.12 - ~/Library/pnpm/pnpm
  Browsers:
    Safari: 16.5.2
  npmPackages:
    @sveltejs/kit: 1.23.0 => 1.23.0 
    flowbite-svelte: 0.44.4 => 0.44.4 
    svelte: 4.2.0 => 4.2.0 
    vite: 4.4.9 => 4.4.9
```

**Comment by jjagielka** [comment]
I can't reproduce that. It seems `Modal` props are correctly inheriting from `Dismissable`:
```ts
interface $$Props extends ComponentProps<Frame>, Dismissable 
```

**Comment by sspilleman** [comment]
Let me try to create a reproducible repo...

**Comment by ByteDream** [comment]
It seems that it got renamed to `permanent` and inverted (so `dismissable={false}` is `permanent={true}` and `dismissable={true}` is `permanent={false}`) in newer versions.

**Comment by sspilleman** [comment]
That works! It is weird, because if I look in the source code it is called dismissable....

[Modal](https://github.com/themesberg/flowbite-svelte/blob/main/src/lib/modals/Modal.sveltel)
[types.ts](https://github.com/themesberg/flowbite-svelte/blob/main/src/lib/types.ts)
