### ISSUE TITLE
Button component raises violation warning in console

### ISSUE THREAD

**Issue by patrickklaeren** [themesberg/flowbite-svelte#1026]
### Describe the bug

When using any `Button` component, a violation warning in the dev tools console appears.

> [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

### Reproduction

1. Place `Button` component

```svelte
<Button type="button">Hello world</Button>
```

2. Check console.

### Flowbite version and System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 14.71 GB / 31.96 GB
  Binaries:
    Node: 19.4.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.12.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (116.0.1938.54)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @sveltejs/kit: ^1.20.4 => 1.23.0
    flowbite-svelte: ^0.44.4 => 0.44.4
    svelte: ^4.0.5 => 4.2.0
    vite: ^4.4.2 => 4.4.9
```

**Comment by shinokada** [comment]
Hi Patrick,

I'm not able to produce this error on Chrome, Firefox and Safari.

**Comment by shinokada** [comment]
I will fix this in the next version.

Thank you for your contribution.

**Comment by shinokada** [comment]
v44.14 should solve this issue.
Please check it and let me know.
