### ISSUE TITLE
Clarify installation steps.

### ISSUE THREAD

**Issue by ysk3a** [themesberg/flowbite-svelte#1028]
## Summary

I think this is a feature request more so than a bug so I selected Feature Requestion Issue option.

The landing page https://flowbite-svelte.com/ shows 
`npm i flowbite flowbite-svelte`
![flowbite-svelte-home cleaned](https://github.com/themesberg/flowbite-svelte/assets/53593899/0f6ed01e-ae58-43aa-8088-7951693b1dae)

but when you click on get started to get to https://flowbite-svelte.com/docs/pages/quickstart it shows
`pnpm i -D flowbite-svelte`
![flowbite-svelte-quickstart cleaned](https://github.com/themesberg/flowbite-svelte/assets/53593899/79f223fb-9c5e-4f92-901f-645031773d7c)

excluding that one page uses npm and another shows pnpm, the commands are different where one is using -D (pnpm) or --save-dev (npm) and another is not using any flags.

also one installs flowbite & flowbite-svelte while the pnpm only installs flowbite-svelte as devDep.

Should I be installing both flowbite and flowbite-svelte and as devDep. ? 
i.e. PNPM: `pnpm add -D flowbite flowbite-svelte` NPM: `npm i --save-dev flowbite flowbite-svelte`.

### Motivation

Clarify installation steps.

**Comment by shinokada** [comment]
Thanks. I will update it using `pnpm` throughout.

**Comment by shinokada** [comment]
Thank you for your contribution.
Please feel free to open a new issue.
