### ISSUE TITLE
Closable/Deletable Accordions

### ISSUE THREAD

**Issue by stratosgear** [themesberg/flowbite-svelte#1038]
## Summary

I want the ability to dynamically/programmatically remove Accordion Items

### Basic example

I thought I would be able to manually create the UI for such a feature and I was able to construct something like:

![image](https://github.com/themesberg/flowbite-svelte/assets/193463/09eff4a4-7e94-473d-964b-34d0f1c65651)

Unfortunately, the Trash Badge components are **not** clickable (capturing the click would allow me to remove that AccordionItem) since the Accordion Header captures **all** the clicks in the header and just opens/closes the Accordion. :(
 
Is there a way such a feature could be added?  Or maybe a way to capture that click so I can remove the AccordionItem myself?

Thanks!

**Comment by jjagielka** [comment]
Why that would not work for you?
```svelte
<AccordionItem>
    <span slot="header">My Header 2 <button on:click|stopPropagation={()=>alert('click')}>Trash icon</button></span>
    <p class="mb-2 text-gray-500 dark:text-gray-400">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo ab necessitatibus sint explicabo ...</p>
....
```

**Comment by stratosgear** [comment]
Well, surprisingly it works!  Had to actually use a plain DOM element (not a custom component) but I reworked the theme/styling and it worked! 

No idea how I missed the stopPropagation option.

Still, I believe that this is not the cleanest or most straightforward implementation, so I am not sure if it is worth closing the issue, in case someone wants to natively offer something like this builtin to the Accordion component. Otherwise, I am "fine" for now!

Thanks!

**Comment by shinokada** [comment]
I close the issue for now.
Thank you for your contribution.
