### ISSUE TITLE
[Feature][Table] Allow overriding thead classes

### ISSUE THREAD

**Issue by dennismphil** [themesberg/flowbite-svelte#105]
**Feature request**

Thank you for the redesign of the Table component. This is much more flexible. Just noting down a minor improvement if we can include.

As an example, for changing the Table Header background color, 

```jsx
<Table>
  <TableHead class="bg-white">
              ...
  </TableHead>
  ...
</Table>
```

renders

```html
...
<thead class="bg-gray-50 text-xs uppercase text-gray-700 dark:bg-gray-700 dark:text-gray-400 bg-white">
  ...
</thead>
...
```

There is no way now to override the [default supplied classes](https://github.com/themesberg/flowbite-svelte/blob/main/src/lib/tables/TableHead.svelte#L8-L9).

It would be great if all the Table element classes are designed in a way that it overrides the default classes instead of merging them

**Comment by shinokada** [comment]
You can use the [`divClass`](https://flowbite-svelte.com/tables#Props) to change the Table style.
Can you try it and let me know.

**Comment by dennismphil** [comment]
Thank you for the response.

If I am understanding this right, the `divClass` style applies as a wrapper to the table. The enhancement I am pointing to is we are unable to override the  [default  supplied](https://github.com/themesberg/flowbite-svelte/blob/main/src/lib/tables/TableHead.svelte#L8) `thead` classes.
