### ISSUE TITLE
Carousel on iPad problem

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite-svelte#1050]
### Describe the bug

Carousel on an iPad does not work as expected.

Images are enlarged, no caption, thumbnails not displayed.

### Reproduction

iPad

### Flowbite version and System Info

```shell
Ipad
```

**Comment by jjagielka** [comment]
Was it working ok before today’s change?

**Comment by shinokada** [comment]
It's from this [PR](https://github.com/themesberg/flowbite-svelte/pull/1032).
You can see it on Safari.
On iPad, it happens Safari, Firefox and Chrome.


![carousel-1](https://github.com/themesberg/flowbite-svelte/assets/147320/f464c2fc-a436-4d9e-88db-693ce3f55c4a)
![carousel-2](https://github.com/themesberg/flowbite-svelte/assets/147320/1e019368-3453-470d-97b2-cd4e4a64a866)
