### ISSUE TITLE
Button inside tooltip component is not resizeable

### ISSUE THREAD

**Issue by frailbongat** [themesberg/flowbite-svelte#106]
**Describe the bug**
We should be able to manipulate button sizes as we please. E.g. making it full width

**Screenshots**
Current
![Screen Shot 2022-06-21 at 11 07 02 PM](https://user-images.githubusercontent.com/45723778/174834106-23f7e681-056f-48f8-aadc-c305ee425ef9.jpg)

Expected (if we want to make the button full width)
![Screen Shot 2022-06-21 at 11 07 24 PM](https://user-images.githubusercontent.com/45723778/174834215-b5bc8067-c16e-4788-9ab4-bb7081c07fa3.jpg)

**Comment by frailbongat** [comment]
Hi maintainer, if you agree to this you can assign it to me so I can push a PR. Cheers 🍻

**Comment by jjagielka** [comment]
Issue is connected with the "w-fit" class set on button in Button.svelte.
This will disappear in one of upcoming PRs.

**Comment by shinokada** [comment]
I close the issue for now since it it merged.
