### ISSUE TITLE
link to the github component(s) links in the docs

### ISSUE THREAD

**Issue by Ennoriel** [themesberg/flowbite-svelte#1066]
## Summary

I'd like the doc to display link(s) to the github component source files directly in the documentation to see the actual implementation.

### Motivation

Sometimes there is no clearer way to understand a component than through its implementation. For example, I wanted to see there is a way to tweak the Tabs component to use them as links and render the tab content as pages. I didn't find the answer in the doc but I can maybe wrap the component or I don't know find another solution by looking at the component implementation ;)

**Comment by shinokada** [comment]
From where do we need to add a link?
Do you have any suggestions?

**Comment by Ennoriel** [comment]
Under reference and/or at the top of the documentation page right below the title could be awesome!

title
<img width="532" alt="flowbite-svelte-title" src="https://github.com/themesberg/flowbite-svelte/assets/23211596/76ba5aac-1734-4f8b-b243-a3b5e3cb1254">

reference:
<img width="357" alt="flowbite-svelte-references" src="https://github.com/themesberg/flowbite-svelte/assets/23211596/86db3789-5e20-4865-b908-545b5eed806d">
