### ISSUE TITLE
If bg-gradient is used for light mode, dark class is not honored.

### ISSUE THREAD

**Issue by iwarsam** [themesberg/flowbite-svelte#1068]
### Describe the bug

If bg-gradient is used for light mode, dark class is not honored.

### Reproduction

`	<body class="bg-gradient-to-r from-rose-400 via-fuchsia-500 to-indigo-500 dark:bg-gray-700">
		<div style="display: contents">%sveltekit.body%</div>
	</body> `

### Flowbite version and System Info

```shell
The latest version, flowbite fresh installed.
```

bg-gradient info - https://tailwindcss.com/docs/background-image

**Comment by shinokada** [comment]
Try this adding `dark:bg-none`:

```
<body data-sveltekit-preload-data="hover" class="bg-gradient-to-r from-rose-400 via-fuchsia-500 to-indigo-500 dark:bg-gray-700 dark:bg-none">
```

**Comment by iwarsam** [comment]
Hey, that did the trick, thanks!

**Comment by iwarsam** [comment]
Checking now using a gradient for light and dark is still not honored.

`
<body data-sveltekit-preload-data="hover"
	class="bg-gradient-to-r from-cyan-500 to-blue-500 dark:bg-gradient-to-r from-purple-500 to-pink-500 dark:bg-none">
`

**Comment by iwarsam** [comment]
It's working with
`<body data-sveltekit-preload-data="hover" class="bg-gradient-to-r from-gray-100 to-gray-300 dark:from-gray-700 dark:via-gray-900 dark:to-black>
`

**Comment by shinokada** [comment]
I close the issue for now.
Thank you for your contribution.
