### ISSUE TITLE
close event not working on Modal

### ISSUE THREAD

**Issue by farao** [themesberg/flowbite-svelte#1069]
### Describe the bug

When using Modal, the close event callback never gets called - even though the documentation/tutorial says "Opening and closing the modal will trigger the show and close events".

### Reproduction

Create a modal with a close event handler and then close it.

`<Modal title="XYZ" bind:open={enabled} on:close={() => alert("hello")}>...</Modal>`

### Flowbite version and System Info

```shell
"flowbite": "^1.6.6"
"flowbite-svelte": "^0.38.2"
```

**Comment by gi4no** [comment]
it's fixed in the v0.44.15

**Comment by farao** [comment]
Affirmed. Thanks!

**Comment by shinokada** [comment]
I close the issue for now.
Thank you for your contribution.
