### ISSUE TITLE
performance concerns

### ISSUE THREAD

**Issue by Ennoriel** [themesberg/flowbite-svelte#1075]
### Describe the bug

I reproduced the first Get Starting example in 4 different scenarios:

- with Flowbite Svelte, named import from the library (`import { Alert } from 'flowbite-svelte';`)
- with Flowbite Svelte, direct import from the library component (`import Alert from 'flowbite-svelte/Alert.svelte';`)
- with Tailwind alone
- with vanilla CSS

I installed and built the project with pnpm.

The build time and generated file sizes are as follow (on the same laptop):

|                                | module transformed | build time | css layout size | _page.svelte.js size |
|--------------------------------|--------------------|------------|-----------------|----------------------|
| Flowbite Svelte, named import  | 266                | 37.02s     | 121.65 kB       | 82.63 kB             |
| Flowbite Svelte, direct import | 104                | 17.55s     | 121.65 kB       | 82.63 kB             |
| Tailwind alone                 | 84                 | 13.72s     | 5.53 kB         | 0.55 kB              |
| vanilla CSS                    | 84                 | 12.34s     | 0               | 1.11 kB              |

The build time is largely improved by directly importing the components (time divded by more than 2). However the css and js generated stay the same. I don't know how Tailwind exactly works but I guess it generate the style for all the components however we import the components. I don't really know what's included in the js part. It's also related to tailwind, maybe tailwind merge?

The css and js size are not a problem on large apps which imports a lot of the components but it's a little bit big on small projects.

What are the recommandations? 

### Reproduction

<details>
  <summary>Code</summary>

## Flowbite Svelte, named import

```svelte
<script>
  import { Alert } from 'flowbite-svelte';
</script>

<div class="p-8">
  <Alert>
    <span class="font-medium">Info alert!</span>
    Change a few things up and try submitting again.
  </Alert>
</div>
```

## Flowbite Svelte, direct import

```svelte
<script>
  import Alert from 'flowbite-svelte/Alert.svelte';
</script>

<div class="p-8">
  <Alert>
    <span class="font-medium">Info alert!</span>
    Change a few things up and try submitting again.
  </Alert>
</div>
```

## Tailwind alone

```svelte
<div class="p-8">
  <div class="bg-primary-50 dark:bg-gray-800 text-primary-800 dark:text-primary-400 rounded-lg border-primary-500 dark:border-primary-200 divide-primary-500 dark:divide-primary-200 p-4 gap-3 text-sm">
    <span class="font-medium">Info alert!</span>
    Change a few things up and try submitting again.
  </div>
</div>
```

## vanilla CSS

```svelte
  <div class="wrapper">
    <div class="inner">
      <span>Info alert!</span>
      Change a few things up and try submitting again.
    </div>
  </div>

  <style>
    .wrapper {
        padding: 32px;
    }

    .inner {
        background-color: rgb(255, 245, 242);
        border-radius: 8px;
        border: 0px solid rgb(254, 121, 93);
        box-sizing: border-box;
        color: rgb(204, 69, 34);
        display: block;
        font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
        font-feature-settings: normal;
        font-size: 14px;
        font-variation-settings: normal;
        height: 52px;
        line-height: 20px;
        padding: 16px;
        tab-size: 4;
    }

    span {
        font-weight: 500;
    }
  </style>
```

</details>

### Flowbite version and System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 6.66 GB / 15.85 GB
  Binaries:
    Node: 18.17.1 - C:\Users\mdupo\nodejs\node.EXE
    npm: 9.6.7 - C:\Users\mdupo\nodejs\npm.CMD
    pnpm: 8.7.4 - C:\Users\mdupo\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (117.0.2045.31)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/kit: ^1.20.4 => 1.25.0
    flowbite-svelte: ^0.44.15 => 0.44.15
    svelte: ^4.0.0 => 4.2.0
    vite: ^4.3.6 => 4.4.9
```

**Comment by shinokada** [comment]
Have you tried [this](https://flowbite-svelte.com/docs/pages/faq-and-tips#My_compiled_CSS_size_is_more_than_120K._How_can_I_make_it_smaller?)?

**Comment by Ennoriel** [comment]
I didn't know this library. After the tests:

|                                | module transformed | build time | css layout size | _page.svelte.js size |
|--------------------------------|--------------------|------------|-----------------|----------------------|
| Flowbite Svelte, named import  | 266                | 37.02s     | 121.65 kB       | 82.63 kB             |
| Flowbite Svelte, named import & purgeCss  | 266                | 48.53s     | 4.10 kB       | 82.63 kB             |
| Flowbite Svelte, direct import | 104                | 17.55s     | 121.65 kB       | 82.63 kB             |
| Flowbite Svelte, direct import & purgeCss | 104                | 33.95s     | 30.76 kB       | 82.63 kB             |
| Tailwind alone                 | 84                 | 13.72s     | 5.53 kB         | 0.55 kB              |
| vanilla CSS                    | 84                 | 12.34s     | 0               | 1.11 kB              |

When using purgeCss with named imports, the gain is the best (-96%) with an increase in the build time (+25%).
When using purgeCss with direct import, the gain is less important (-75%) and the increase in the build time is very important (+100%).

**Comment by shinokada** [comment]
I close the issue for now.
Thank you for your contribution.
