### ISSUE TITLE
NavHamburger is not showing 

### ISSUE THREAD

**Issue by xmlking** [themesberg/flowbite-svelte#108]
with the following Navbar code, `NavHamburger` is not visible 

I guess `md:hidden` CSS might be causing this.

can you also remove `container` class so that  NavBar can fit full space ?

```
 <Navbar let:hidden let:toggle>
	<NavHamburger on:click={toggle} />
	<NavBrand href="/">
		<img
			src="https://flowbite.com/docs/images/logo.svg"
			class="mr-3 h-6 sm:h-9"
			alt="Flowbite Logo"
		/>
		<span class="self-center whitespace-nowrap text-xl font-semibold dark:text-white">
			ThreatZero
		</span>
	</NavBrand>

	<NavUl {hidden}>
		<NavLi href="/" >Home</NavLi>
		<NavLi href="/dashboard" active={true}>Dashboard</NavLi>
		<NavLi href="/dashboard/policies">Policies</NavLi>
		<NavLi href="/dashboard/agents">Agents</NavLi>
		<NavLi href="/dashboard/users">Users</NavLi>
	</NavUl>
</Navbar>
```

<img width="1568" alt="Screen Shot 2022-06-24 at 2 30 06 AM" src="https://user-images.githubusercontent.com/627951/175507428-6f429b90-4aae-4376-9191-f8476f4d1086.png">

**Comment by shinokada** [comment]
Hi,

`md:hidden` means it is hidden above `md` breakpoint. This means it will be hidden more than 768px. It should show less than 768px width. Let me know.

Regarding `container` CSS, you can change it by using `navDivClass` prop.

```
<Navbar navDivClass='flex flex-wrap justify-between items-center'>
...
</Navbar>
```

**Comment by xmlking** [comment]
looks like behavier for `fluid` prop reversed 

`<Navbar let:hidden let:toggle >`  or default 
<img width="2555" alt="image" src="https://user-images.githubusercontent.com/627951/175801884-504faa8b-d49b-4806-970f-62653a02785f.png">

`<Navbar let:hidden let:toggle fluid={false}>`

<img width="2555" alt="image" src="https://user-images.githubusercontent.com/627951/175801743-f0fbf130-4da0-4301-bd6b-c1da2f9d1561.png">

Why is the search box showing  at the end in my environment,  instead of showing in the middle? 

your example in at  https://flowbite-svelte.com/navbar rendered diffrently then mine for same code:
<img width="837" alt="image" src="https://user-images.githubusercontent.com/627951/175801972-2315a945-2bae-4836-9252-8fe47a2a10b2.png">


```
<Navbar let:hidden let:toggle >
	<NavBrand href="/">
		<img
			src="https://flowbite.com/docs/images/logo.svg"
			class="mr-3 h-6 sm:h-9"
			alt="Flowbite Logo"
		/>
		<span class="self-center whitespace-nowrap text-xl font-semibold dark:text-white">
			Flowbite
		</span>
	</NavBrand>
	<div class="flex md:order-2">
		<Button color="none" data-collapse-toggle="mobile-menu-3" aria-controls="mobile-menu-3" aria-expanded="false" class="md:hidden text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm p-2.5 mr-1" >
			<Search variation='solid' />
		</Button>
		<div class="hidden relative md:block">
			<div class="flex absolute inset-y-0 left-0 items-center pl-3 pointer-events-none">
				<Search />
			</div>
			<Input id="search-navbar" class="pl-10" placeholder="Search..." />
		</div>
		<NavHamburger on:click={toggle} />
	</div>
	<NavUl {hidden}>
		<NavLi href="/" active={true}>Home</NavLi>
		<NavLi href="/about">About</NavLi>
		<NavLi href="/services">Services</NavLi>
	</NavUl>
</Navbar>
```

**Comment by xmlking** [comment]
I am using sveltejs/kit  `1.0.0-next.352`  and  flowbite-svelte `0.19.4`

**Comment by xmlking** [comment]
when reduced to minimal screen size,  `NavHamburger` shows two times. also, search don't show the text area rendering it useless 


<img width="502" alt="image" src="https://user-images.githubusercontent.com/627951/175802522-64e64d4d-5375-4ae9-ae65-7fab9ae7f850.png">

**Comment by xmlking** [comment]
Navbar menu items are vertically aligned to the **top**. I think they look good when aligned **center** by default. 


<img width="1633" alt="image" src="https://user-images.githubusercontent.com/627951/175823424-763b8752-1e02-45a2-bf0e-de0c0e037259.png">

<img width="1633" alt="image" src="https://user-images.githubusercontent.com/627951/175823417-50139631-2530-4b2e-ab69-1ced30f2df2f.png">

**To reproduce** 

```svelte
<Navbar let:hidden let:toggle fluid={false}  rounded={true}>
	<NavBrand href="/">
		<img
			src="https://flowbite.com/docs/images/logo.svg"
			class="mr-3 h-6 sm:h-9"
			alt="Flowbite Logo"
		/>
		<span class="self-center whitespace-nowrap text-xl font-semibold dark:text-white">
			Flowbite
		</span>
	</NavBrand>
	<div>
		<Button color="none" data-collapse-toggle="mobile-menu-3" aria-controls="mobile-menu-3" aria-expanded="false" class="md:hidden text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm p-2.5 mr-1" >
			<Search variation='solid' />
		</Button>
		<div class="hidden relative md:block">
			<div class="flex absolute inset-y-0 left-0 items-center pl-3 pointer-events-none">
				<Search />
			</div>
			<Input id="search-navbar" class="pl-10" placeholder="Search..." />
		</div>
		<NavHamburger on:click={toggle} />
	</div>
	<NavUl {hidden}>
		<NavLi href="/" active={true}>Home</NavLi>
		<NavLi href="/about">About</NavLi>
		<NavLi href="/services">Services</NavLi>
		<div>
			<Dropdown arrowIcon={false} inline={true}>
				<Avatar {avatar} slot="label" />
				<DropdownHeader>
					<span class="block text-sm"> Bonnie Green </span>
					<span class="block truncate text-sm font-medium"> name@flowbite.com </span>
				</DropdownHeader>
				<DropdownItem>Dashboard</DropdownItem>
				<DropdownItem>Settings</DropdownItem>
				<DropdownItem>Earnings</DropdownItem>
				<DropdownDivider />
				<DropdownItem>Sign out</DropdownItem>
			</Dropdown>
			<NavHamburger on:click={toggle} />
		</div>
	</NavUl>
</Navbar>
```

**Comment by shinokada** [comment]
The recent update should have solved this issue.
I close this for now.
Thank you for the contribution.
