### ISSUE TITLE
Dismissable alerts close button is left aligned

### ISSUE THREAD

**Issue by vsergeev** [themesberg/flowbite-svelte#1084]
### Describe the bug

Due to the removal of the `ml-auto` class, the close button on dismissable alerts is currently scrunched up to the left by the alert text.

I'm not sure if this was intentional, but I found the previous design with the button at a repeatable location on the right to both look better and be easier to use.

### Reproduction

https://flowbite-svelte.com/docs/components/alert#Dismissable_alerts

### Flowbite version and System Info

```shell
npmPackages:
    flowbite-svelte: ^0.44.17 => 0.44.17 
    svelte: ^4.0.0 => 4.2.0 
    vite: ^4.0.0 => 4.4.9 
```

**Comment by shinokada** [comment]
Thank you for pointing out the bug.
