### ISSUE TITLE
Label in SvelteKit

### ISSUE THREAD

**Issue by auliabismar** [themesberg/flowbite-svelte#109]
Thanks for taking the time to fill out this bug report!

**Describe the bug**
Label in SvelteKit will produce not valid SSR component.

`Error: <Label> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules`

**Expected behavior**
Label will render

**Comment by shinokada** [comment]
Can you show me your code please?

**Comment by auliabismar** [comment]
`<script>
  import { Input, Label } from 'flowbite-svelte';
</script>
<form action="/" method="post" class="w-1/2 mx-auto mt-24">
  <div class="mb-6">
    <Label for="name" class="mb-2" />
    <Input  id="name" placeholder="Nama"/>
  </div>
</form>`

**Comment by shinokada** [comment]
This [REPL](https://svelte.dev/repl/e90fa3986dfe4aa2a7c0f7abd8c5d544?version=3.48.0) doesn't show any error.

Please see [Getting started](https://flowbite-svelte.com/pages/getting-started)

**Comment by shinokada** [comment]
I close the issue for now.
Please let us know if you have an issue.
Thank you.
