### ISSUE TITLE
allow for html in the label of a FloatingLabelInput

### ISSUE THREAD

**Issue by kryptus36** [themesberg/flowbite-svelte#1092]
## Summary

I want to use icons in my labels.

### Basic example

```
<FloatingLabelInput label="<i class='fa fa-envelope'/> Email" />
```

### Motivation

It's a very simple change that allows more flexibility.  100% backwards compatible.

I'm wondering if I did a pr if it would get accepted?

**Comment by shinokada** [comment]
Please make a PR and I will see what I can do.
