### ISSUE TITLE
References links not correct for forms

### ISSUE THREAD

**Issue by metafab** [themesberg/flowbite-svelte#1093]
### Describe the bug

In the References section of Forms components, the link to the component's source code is not correct.

For example, the href for "FloatingLabelInput component on GitHub" is https://github.com/themesberg/flowbite-svelte/blob/main/src/lib/floating-label/FloatingLabelInput.svelte while it should be https://github.com/themesberg/flowbite-svelte/blob/main/src/lib/forms/FloatingLabelInput.svelte

GitHubCompoLinks.svelte used in the References section does not work well for the components under Forms because the directory structure is not the same in `docs` and in `src`.

### Reproduction

1. Go to the documentation page for any of the component under Forms, such as https://flowbite-svelte.com/docs/forms/floating-label
2. Click on the link labeled  "FloatingLabelInput component on GitHub"

### Flowbite version and System Info

```shell
Version 0.44.17
```

**Comment by shinokada** [comment]
Thanks. I will fix them.
Please let me know if you find more.

**Comment by Ennoriel** [comment]
There is also a fix linked for buttons. There is a missing "s"

**Comment by metafab** [comment]
> Thanks. I will fix them. Please let me know if you find more.

Thanks

**Comment by shinokada** [comment]
Fixed.

**Comment by Ennoriel** [comment]
Thanks!

**Comment by metafab** [comment]
Well done!
