### ISSUE TITLE
Charts on iPad Safari 

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite-svelte#1095]
### Describe the bug

When the [chart page](https://flowbite-svelte.com/docs/plugins/charts) is displayed on iPad Safari, every chart start expanding and not able to display any charts

![chart](https://github.com/themesberg/flowbite-svelte/assets/147320/43a2f219-3e37-4bfc-9b35-8859f9e7757d)

### Reproduction

iPad Safari

### Flowbite version and System Info

```shell
n/a
```

**Comment by gi4no** [comment]
@shinokada 
I think it's the preview with Iframe and the chart height set to 100%, if you try to set the height in px the graph doesn't expand; Possible solutions are either to disable the iframe preview or to give a height in px to each graph.

**Comment by shinokada** [comment]
@gi4no Can you create a PR?

**Comment by shinokada** [comment]
@gi4no Thank you for the PR.
