### ISSUE TITLE
Missing utilities from node_modules\flowbite-svelte\utils

### ISSUE THREAD

**Issue by acconway1** [themesberg/flowbite-svelte#1098]
### Describe the bug

Sometime between v0.34.10 and v0.44.17, several Svelte components were dropped from node_modules\flowbite-svelte\utils.

Reviewing the index.js, I see that this (v0.34.10 example)

///
// utils
export { default as CloseButton } from './utils/CloseButton.svelte';
export { default as ChevronDown } from './utils/ChevronDown.svelte';
export { default as ChevronLeft } from './utils/ChevronLeft.svelte';
export { default as ChevronRight } from './utils/ChevronRight.svelte';
export { default as ChevronUp } from './utils/ChevronUp.svelte';
export { default as Chevron } from './utils/Chevron.svelte';
export { default as InformationCircle } from './utils/InformationCircle.svelte';
export { default as MenuButton } from './utils/MenuButton.svelte';
export { default as UserCircle } from './utils/UserCircle.svelte';
///

Has become this (v0.44.17)

///
// utils
export { default as CloseButton } from './utils/CloseButton.svelte';
export { default as Frame } from './utils/Frame.svelte';
///

Was the removal of MenuButton, etc. intentional?

### Reproduction

E.g., compare the "node_modules\flowbite-svelte\utils" resulting from this: https://github.com/huntabyte/modern-saas

To the "node_modules\flowbite-svelte\utils" resulting from the "Using SvelteKit" quickstart guide here: https://flowbite-svelte.com/docs/pages/introduction#Using_SvelteKit

### Flowbite version and System Info

```shell
v0.34.10 and v0.44.17
```

**Comment by shinokada** [comment]
Yes, it is. We don't use utils/Menu any more.
We have navbar/Menu but it is used internally by NavHamburger component.

**Comment by acconway1** [comment]
Thank you.
