### ISSUE TITLE
Cannot resize images in carousel component

### ISSUE THREAD

**Issue by nash-an** [themesberg/flowbite-svelte#1099]
### Describe the bug

You cannot resize images. They are forced to fit the full width/height of the carousel element.

For some reason, the example of how to do this *does* work on the Flowbite-Svelte docs, but it cannot be reproduced, atleast by copying. 

### Reproduction

[Expected Behavior](https://flowbite-svelte.com/docs/components/carousel#Basic_customization)
[Reproduction](https://stackblitz.com/edit/sveltejs-kit-template-default-3zvse2?file=src%2Froutes%2F%2Bpage.svelte)

### Flowbite version and System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 5.04 GB / 15.94 GB
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.7.4 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Spartan (44.22621.2283.0), Chromium (117.0.2045.43)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/kit: ^1.20.4 => 1.24.1
    flowbite-svelte: ^0.44.17 => 0.44.17
    svelte: ^4.0.5 => 4.2.0
    vite: ^4.4.2 => 4.4.9
```

**Comment by shinokada** [comment]
Please update to the latest version.

```
pnpm up --latest
// or
pnpm i -D flowbite-svelte@latest
```

And let me know.

**Comment by nash-an** [comment]
It's working as expected now. Thank you!
