### ISSUE TITLE
Toggle button / Checkbox button

### ISSUE THREAD

**Issue by uherman** [themesberg/flowbite-svelte#1103]
## Summary

A button that works as a checkbox/toggle component. Changing apperance when in a checked/unchecked state.

### Basic example

[REPL](https://svelte.dev/repl/3b198f5eede14c0f9abab31912313aaf?version=4.2.1)

### Motivation

This feature is common amongst other UI libraries and quite easy to implement.

In some cases a user want a toggle button instead of using a checkbox or toggle component.

**Comment by jjagielka** [comment]
Please take a look at those:
- https://flowbite-svelte.com/docs/forms/radio#RadioButton
- https://flowbite-svelte.com/docs/forms/checkbox#CheckboxButton

Comments?

**Comment by uherman** [comment]
> Please take a look at those:
> 
> * https://flowbite-svelte.com/docs/forms/radio#RadioButton
> * https://flowbite-svelte.com/docs/forms/checkbox#CheckboxButton
> 
> Comments?

They look awsome! Great job! Closing this 👍
