### ISSUE TITLE
MultiSelect on:selected clearThisOption weirdness

### ISSUE THREAD

**Issue by KaTaiHo** [themesberg/flowbite-svelte#1104]
### Describe the bug

If you click on the entries in the multiple select in console it will print correctly. When you deselect each selected element one by one the updated state of the selected items are wrong. 

I don't fully understand why this is the case. Am I doing something wrong or is this a bug?

![Screenshot 2023-10-01 172317](https://github.com/themesberg/flowbite-svelte/assets/14283418/196d8756-f70a-4c26-b05e-149772dfe74c)

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-l6ket7?file=src%2Froutes%2F%2Bpage.svelte  

### Flowbite version and System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
    Memory: 42.52 GB / 63.89 GB
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.7.1 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.2283.0), Chromium (117.0.2045.43)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/kit: ^1.20.4 => 1.24.1
    flowbite-svelte: ^0.44.8 => 0.44.8
    svelte: ^4.0.5 => 4.2.0
    vite: ^4.4.2 => 4.4.9
```

**Comment by gi4no** [comment]
@KaTaiHo try this https://stackblitz.com/edit/sveltejs-kit-template-default-xsycjg?file=src%2Froutes%2F%2Bpage.svelte

**Comment by KaTaiHo** [comment]
That works too. I ended up doing something like 
```
$: handleChange(selectedPostTypes)
```
I am not sure what is best practice for this. I am always curious why the event handler doesn't work as expected but requires using "$:". Just curious. Thanks!
