### ISSUE TITLE
DeviceMockup VSCode problem

### ISSUE THREAD

**Issue by Story-MathieuD** [themesberg/flowbite-svelte#1118]
### Describe the bug

When I put : `<DeviceMockup device="ios">` VSCode say : `Type '{ device: "ios"; }' is missing the following properties from type '{ device?: "default" | "ios" | "android" | "tablet" | "laptop" | "desktop" | "smartwatch"; defaultDiv?: string; defaultSlot?: string; iosDiv?: string; iosSlot?: string; androidDiv?: string; androidSlot?: string; ... 35 more ...; desktopBotUnder?: string; }': androidTop, androidLeftTop, androidLeftMid, androidLeftBot, and 15 more.`

but it work on my browser ... so i don't understand :/ 
![image](https://github.com/themesberg/flowbite-svelte/assets/90247892/1fb949a0-f98d-4441-ad29-4c2df02ef9ed)
![image](https://github.com/themesberg/flowbite-svelte/assets/90247892/0977df4b-b8b6-420e-9d3f-c6fda868eaa6)

### Reproduction

create a DeviceMockup Element like `<DeviceMockup device="ios"></DeviceMockup>`

### Flowbite version and System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 16.59 GB / 31.92 GB
  Binaries:
    Node: 18.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.2283.0), Chromium (117.0.2045.60)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    flowbite-svelte: ^0.36.5 => 0.36.5
    svelte: ^3.57.0 => 3.59.1
    vite: ^4.3.2 => 4.3.9
```

**Comment by gi4no** [comment]
@Story-MathieuD the component `<DeviceMockup>` it was added on version [v0.44.18](https://github.com/themesberg/flowbite-svelte/releases/tag/v0.44.18)
https://github.com/themesberg/flowbite-svelte/commit/fec1f4caa5da33259766312dda95a7fdaeb291eb

**Comment by jjagielka** [comment]
We can close that one.
