### ISSUE TITLE
`FooterLink` ignores the rule `last:mr-0` when `Tooltip` is introduced.

### ISSUE THREAD

**Issue by Ashvith10** [themesberg/flowbite-svelte#1137]
### Describe the bug

This is related to themesberg/flowbite-svelte-blocks#51. The default classes for `FooterLink` are `mr-4 last:mr-0 md:mr-6`. When the `Tooltip` element is introduced, since the last `FooterLink` is no longer the last element anymore, it ignores the rule for `last:mr-0`. This can cause a flickering effect.

### Reproduction

The demo page for [Default dashboard footer](https://flowbite-svelte-blocks.vercel.app/application/dashboard-footer#Default_dashboard_footer) has this exact example. For reference, I will also attach a video.

[Screencast from 2023-10-30 01-32-29.webm](https://github.com/themesberg/flowbite-svelte/assets/113123021/166217d2-1aee-4420-a9ad-b454f2876f13)

### Flowbite version and System Info

```shell
System:
    OS: Linux 6.1 NixOS 23.11 (Tapir) 23.11 (Tapir)
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 3.48 GB / 7.53 GB
    Container: Yes
    Shell: 5.2.15 - /run/current-system/sw/bin/bash
  Binaries:
    Node: 18.17.1 - /nix/store/1l03gdg4w3cvkygvbxsq9i19flnp1p3y-nodejs-18.17.1/bin/node
    npm: 9.6.7 - /nix/store/1l03gdg4w3cvkygvbxsq9i19flnp1p3y-nodejs-18.17.1/bin/npm
    pnpm: 8.5.1 - /nix/store/pw1lyxbamcg3i5pkgm2n5w3f5zz0hrdk-pnpm-8.5.1/bin/pnpm
  npmPackages:
    @sveltejs/kit: ^1.27.1 => 1.27.1 
    flowbite-svelte: ^0.44.18 => 0.44.18 
    svelte: ^4.2.2 => 4.2.2 
    vite: ^4.5.0 => 4.5.0
```

**Comment by jjagielka** [comment]
Two issues here:
- flickering: try to add `placement="bottom-end"` to the last tooltip
- right margin: try to add class `last-of-type:mr-0` to that `FooterLink`

Tell me if that helps.

**Comment by Ashvith10** [comment]
@jjagielka looks like adding `last-of-type:mr-0` to `classLi` fixes the flickering for me. We can remove `last:mr-0`, which is the default class, as it does nothing here. The last tool-tip looks kinda odd with `placement="bottom"`, but interestingly, it works just fine with `placement="bottom-start"`.

**Comment by jjagielka** [comment]
I think we can close that ticket.
