### ISSUE TITLE
Navbar problem with navigating between several (group) layouts

### ISSUE THREAD

**Issue by hkyselov** [themesberg/flowbite-svelte#1144]
### Describe the bug

Page content doesn't unload and appends to top of page during navigation between two groups of layouts with navbars and active link: $: activeUrl = $page.url.pathname;   

![image](https://github.com/themesberg/flowbite-svelte/assets/3939357/91282704-428a-46ff-b6a4-de7b52786abb)

### Reproduction

https://github.com/hkyselov/my-app

### Flowbite version and System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
    Memory: 925.22 MB / 7.89 GB
  Binaries:
    Node: 21.1.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.1.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 118.0.5993.118
    Edge: Spartan (44.19041.3570.0), Chromium (118.0.2088.76)
    Internet Explorer: 11.0.19041.3570
  npmPackages:
    @sveltejs/kit: ^1.20.4 => 1.27.2
    flowbite-svelte: ^0.44.19 => 0.44.19
    svelte: ^4.0.5 => 4.2.2
    vite: ^4.4.2 => 4.5.0
```

**Comment by jjagielka** [comment]
@hkyselov This should be now fixed. Can you please check?

**Comment by hkyselov** [comment]
work well now, thanks @jjagielka
