### ISSUE TITLE
NavHamburger menuClass prop does not apply styles to the menu

### ISSUE THREAD

**Issue by galaczi** [themesberg/flowbite-svelte#1196]
### Describe the bug

Unless I misunderstand something, the ``menuClass``  prop should change the look of the dropdown menu. However, it changes only the button.

### Reproduction

``<NavHamburger menuClass="bg-red-300" />``

### Flowbite version and System Info

```shell
Ubuntu
flowbite 0.44.20
Node v20.10.0
```

**Comment by jjagielka** [comment]
`menuClass` provides styling to `NavHamburger` button: [NavHamburger_styling](https://flowbite-svelte.com/docs/components/navbar#NavHamburger_styling)

Dropdown menu is `NavUl`:  [NavUl styling](https://flowbite-svelte.com/docs/components/navbar#NavUl_styling)
