### ISSUE TITLE
Modal custom classes don't apply to title section

### ISSUE THREAD

**Issue by galaczi** [themesberg/flowbite-svelte#1197]
### Describe the bug

I would like to customize the background of the Modal in dark mode. I am also using using the title prop. The custom classes only apply to the body of the modal. The title section cannot be styled. I would expect the classes would apply to that section too.

I am working around this by not using the title prop and adding my title to the body.

### Reproduction

<Modal
	title="My title"
	bind:open
	size="sm"
	autoclose={true}
	class="bg-green-500"
	outsideclose
>
Modal body
</Modal>

### Flowbite version and System Info

```shell
Ubuntu
flowbite 0.44.20
Node v20.10.0
```

**Comment by jjagielka** [comment]
`Modal` is designed to use `color` property  [Colors](https://flowbite-svelte.com/docs/components/modal#Colors)

Yes, the choice is limited, but that's how it's implemented right now.

**Comment by galaczi** [comment]
In addition to colors, it has options for overwriting classes: https://flowbite-svelte.com/docs/components/modal#Modal_styling

It's just not applied to the title section.

**Comment by jjagielka** [comment]
Try: `<Modal color="none" class="bg-green-500" ...>`

**Comment by galaczi** [comment]
The above solution works.
