### ISSUE TITLE
Radio component checked prop doesn't change the checked element.

### ISSUE THREAD

**Issue by joe-ervin05** [themesberg/flowbite-svelte#1219]
### Describe the bug

If you have a group of radio components for a form, the last component will always be checked. Even if you set a different component to be checked, it won't be checked but the last component will.

Based on the vanilla HTML radio input element's behavior and the flowbite-svelte docs, it is clear that this is not the intended behavior.

ex.
```
<Radio name="example"/>
<Radio name="example" checked />
<Radio name="example"/>
```
Even though the second radio component is expected to be checked here, the last one is what is checked instead.

The fix I have found for this is to remove the group prop from the component. I am not sure what the group prop even does but I assume it serves some purpose so that isn't a permanent solution.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-q2qude?file=src%2Froutes%2F%2Bpage.svelte

### Flowbite version and System Info

```shell
System:
    OS: Linux 6.5 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (12) x64 AMD Ryzen 5 2600X Six-Core Processor
    Memory: 8.55 GB / 15.53 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    bun: 1.0.7 - ~/.bun/bin/bun
  Browsers:
    Chrome: 118.0.5993.88
  npmPackages:
    @sveltejs/kit: ^2.0.0 => 2.3.2 
    flowbite-svelte: ^0.44.21 => 0.44.21 
    svelte: ^4.2.7 => 4.2.8 
    vite: ^5.0.3 => 5.0.11
```

**Comment by jjagielka** [comment]
Please check the svelte docs how to handle radio buttons.

https://svelte.dev/docs/element-directives#bind-group
