### ISSUE TITLE
Uneffective `open` variable binding in Toast

### ISSUE THREAD

**Issue by Isax03** [themesberg/flowbite-svelte#1225]
### Describe the bug

When the Toast component is set as not dismissable (dismissable is false), the open variable is not properly binded. As a result, the desired transition behavior may not be achieved when attempting to close the Toast.

### Reproduction

1. Create a Toast component with dismissable set to false.
2. Attempt to use the open variable to control the visibility or transition of the Toast.
3. Observe that the open variable does not behave as expected in this scenario.

### Flowbite version and System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 5.17 GB / 15.70 GB
  Binaries:
    Node: 20.4.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.14.1 - ~\AppData\Local\pnpm\pnpm.CMD
  Browsers:
    Edge: Chromium (100.0.1185.36)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/kit: ^2.0.0 => 2.4.1
    flowbite-svelte: ^0.44.22 => 0.44.22
    svelte: ^4.2.7 => 4.2.9
    vite: ^5.0.3 => 5.0.12
```

**Comment by josepchetrit12** [comment]
:arrow_up: I agree that the open prop does not work. As an example, you can check your documentation and we will see that it does not work. https://flowbite-svelte.com/docs/components/toast#Autohide_example

Only works if the toast is `dismissable`.
