### ISSUE TITLE
Dropdown: click outside not working on mobile

### ISSUE THREAD

**Issue by gregg-cbs** [themesberg/flowbite-svelte#1237]
### Describe the bug

On a mobile device when tapping away from a dropdown to close it, it does not close.

I have checked this in Safari and Chrome on IOS.

This behavior can be exhibited on the flowbite svelte dropdown page itself.
Checked with @JHorlamide

### Reproduction

https://flowbite-svelte.com/docs/components/dropdown

### Flowbite version and System Info

```shell
"flowbite-svelte": "^0.44.22"
```

**Comment by masar3141** [comment]
neither working one Safari for macos here

**Comment by MrRoyce** [comment]
You can work around this by adding an `id` to the Dropdown and then closing the popup when an element is clicked with 
`document.getElementById('<Dropdown id>').style.display = 'none';`
