### ISSUE TITLE
Carousel controls and indicators invisible in light mode

### ISSUE THREAD

**Issue by mcmikecreations** [themesberg/flowbite-svelte#1252]
### Describe the bug

The website I am designing supports both light and dark modes. I wanted to have a carousel of testimonials instead of images, no background (apart from what's already the document body background). I guess you can think of it as me using white images inside the carousel in light mode and black images in dark mode.

In dark mode, the controls and indicators look fine. Indicators are light gray dots and controls are light arrows with gray rings on the dark background.

However, in light mode, they are white dots, white arrows and light rings on white background, making them pretty much invisible.
An example can be seen [here](https://github.com/themesberg/flowbite-svelte/blob/7f34738df99c886a59afca5d56951fa36dcdf927/src/lib/carousel/ControlButton.svelte#L8) with `text-white`.

**Edit**: I know I can manually change the styles of controls and indicators to make them correct, but I do wish fore a more sensible default.

### Reproduction

[StackBlitz](https://stackblitz.com/edit/sveltejs-kit-template-default-ztzcq4?file=src%2Froutes%2F%2Bpage.svelte) - click on DarkMode button to toggle light and dark. In dark, the controls and indicators can be seen. In light, they are invisible.

A more sensible default would be to have dark controls with slightly lighter rings in light mode.

### Flowbite version and System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 2.25 GB / 15.86 GB
  Binaries:
    Node: 18.16.0 - C:\Soft\nodejs\node.EXE
    Yarn: 3.6.0 - C:\Soft\nodejs\yarn.CMD
    npm: 9.5.1 - C:\Soft\nodejs\npm.CMD
    pnpm: 8.15.1 - C:\Soft\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (121.0.2277.128)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/kit: ^2.0.0 => 2.4.3
    flowbite-svelte: ^0.44.22 => 0.44.22
    svelte: ^4.2.7 => 4.2.9
    vite: ^5.0.3 => 5.0.12
```

**Comment by mcmikecreations** [comment]
Hey @shinokada , as I've stated in the issue:
> I know I can manually change the styles of controls and indicators to make them correct, but I do wish fore a more sensible default.

The problem is not the advanced customization, I can change it. The problem is having default values that make sense to newcomers and work out-of-the-box. Having `text-white` over `bg-white` does not make sense as a default.

**Comment by shinokada** [comment]
All the default styling are from https://flowbite.com/docs/components/carousel/ . 
So do you want to create an issue at https://github.com/themesberg/flowbite/issues?

**Comment by mcmikecreations** [comment]
Thanks for letting me know! Yup, that makes sense, you can close this issue.

**Comment by shinokada** [comment]
We try to have flexibility by exporting variables so that uses can modify the style. But it's never be perfect, I'm afraid.
