### ISSUE TITLE
Cannot effect the height of a tab item

### ISSUE THREAD

**Issue by evancaldwell** [themesberg/flowbite-svelte#1271]
### Describe the bug

When using the Flowbite-svelte tabs component I want to set the height of the tab item to "h-full" but there is a `<div>` element between the `<div>` that applies the 'contentClass' and my content within the tab item. So even if I set the 'contentClass' to "h-full" and my content to "h-full", my content never goes full height because there is no way to style the `<div>` in between. 

### Reproduction

https://stackblitz.com/edit/flowbite-tab-item-height-issue?file=src%2Froutes%2F%2Bpage.svelte

### Flowbite version and System Info

```shell
System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 55.45 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.8.1 - ~/.volta/tools/image/node/20.8.1/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 10.1.0 - ~/.volta/tools/image/npm/10.1.0/bin/npm
  Browsers:
    Chrome: 122.0.6261.94
    Safari: 16.6
  npmPackages:
    flowbite-svelte: ^0.44.19 => 0.44.19
    svelte: ^4.0.5 => 4.2.1
    vite: ^4.4.5 => 4.4.10
```

**Comment by evancaldwell** [comment]
<img width="951" alt="flowbit_tabitem_issue" src="https://github.com/themesberg/flowbite-svelte/assets/805800/d05299e5-5063-4ff3-8de9-8f0b86ad6142">

**Comment by evancaldwell** [comment]
This issue was solved in `flowbite-react` here: https://github.com/SophanySC/flowbite-react-sophany/commit/d40614ff36acd992f4267fe8374d72221a8d8134

**Comment by TimKieu** [comment]
This Tabs bug should be fixed soon please.

**Comment by KelvinSan** [comment]
Any update ?

**Comment by shinokada** [comment]
I added `divClass` and a new version v0.46.16 is released.
