### ISSUE TITLE
Image Skeleton should be only Image and not include text

### ISSUE THREAD

**Issue by tsekiguchi** [themesberg/flowbite-svelte#1275]
## Summary

When using the image placeholder skeleton, there is loading text underneath it. However, in the video placeholder, there is no loading text. The developer should be able to choose and customize whether text should be included in this skeleton or not.

Additionally, because of the text, it looks like the picture and layout jumps when it's finally loaded, even though this is just visual.

### Motivation

The developer should be able to choose and customize whether text should be included in this Image Skeleton or not.

**Comment by shinokada** [comment]
Please create an issue on Flowbite.com.
https://github.com/themesberg/flowbite/issues
