### ISSUE TITLE
Prop `style` of <Tab> conflicts with native attribute

### ISSUE THREAD

**Issue by binury** [themesberg/flowbite-svelte#1277]
The property of [Tab](https://github.com/themesberg/flowbite-svelte/blob/main/src/lib/tabs/Tabs.svelte
) that receives a style string conflicts with our old friend [the built-in native](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/style).

This doesn't have any runtime impact, but will break tooling that is expecting `style` to be the CSS attr e.g., `postCSS` will warn about being unable to parse:

<img width="832" alt="ss 2024-03-11 at 20 13 12@2x" src="https://github.com/themesberg/flowbite-svelte/assets/1146921/004b326f-2916-4662-a05c-abb13a778d49">

**Comment by shinokada** [comment]
Please use `props` to style components.

**Comment by NormandoHall** [comment]
@shinokada remains the same with style in 0.46.0

**Comment by shinokada** [comment]
Can you show me your screenshot?

**Comment by NormandoHall** [comment]
Yes, with `style` and  `tabStyle`

![image](https://github.com/themesberg/flowbite-svelte/assets/2943127/8763c94f-4d85-46b9-85bc-039921b91210)


![image](https://github.com/themesberg/flowbite-svelte/assets/2943127/2916d08c-7484-43e7-839a-1b977b9cbc48)

**Comment by shinokada** [comment]
Can you restart IDE or remove node_modules and pnpm-lock.yaml and run `pnpm `?

**Comment by NormandoHall** [comment]
You are right, restarting IDE fixes the issue! Thanks

**Comment by shinokada** [comment]
You could reload the windows if you IDE has it.
