### ISSUE TITLE
🔥 NPM package version for 0.44.24 doesn't match github release!

### ISSUE THREAD

**Issue by 2bitmarv** [themesberg/flowbite-svelte#1279]
### Describe the bug

Updated my project files on 03.15.2024 to flowbite-svelte version 0.44.24 via npm. Was in need of the latest modified version of the modal component and was wondering why still after the update the source files didn't present any changes.

Removed node_modules and package-lock.json, cleared npm chache and tried a fresh install...no difference!

Made a compare on the files in this repo here and the files delivered by npm. Version number is equal, but sources are NOT!

identified by https://github.com/themesberg/flowbite-svelte/pull/1253. Changed modal properties 

### Reproduction

<img width="786" alt="image" src="https://github.com/themesberg/flowbite-svelte/assets/37209176/36715593-0c48-4f5f-8a42-b6b6351fabb9">

### Flowbite version and System Info

```shell
0.44.24
```

**Comment by shinokada** [comment]
It says Code (Beta) on the tab.

**Comment by 2bitmarv** [comment]
hold on, you presume that this code-tab shows wrong code? Might be, but as i've written:  if I install this version from NPM, the code actually IS what is shown in the tab, although the version number pretends to be the assumed one.

**Comment by shinokada** [comment]
Please let me know the latest version has the same issue.
Thanks.

**Comment by shinokada** [comment]
I close the issue for now since the npm code is beta version.
Thank you for your contribution.
