### ISSUE TITLE
Sidebar component

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite-svelte#13]
Add [Sidbar](https://flowbite.com/docs/components/sidebar/) component.

- [x] Default sidebar
- [x] Multi-level dropdown
- [x] Content separator
- [x] CTA button
- [x] Logo branding

**Comment by shinokada** [comment]
Completed for now.

**Comment by Gildedter** [comment]
Any chance for customizing the main side bar color? Including the links colors as well

**Comment by shinokada** [comment]
I added `ulClass` in `SidebarItem` and `divClass` to `Sidebar.svelte`.
Please check and let me know. v0.16.13.

**Comment by Gildedter** [comment]
> I added `ulClass` in `SidebarItem` and `divClass` to `Sidebar.svelte`. Please check and let me know. v0.16.13.

Works, only missing customization is for the button text, I can't seem to change the top-level button text color, both `aClass` and `childClass` works for top-level links and the nested ones within, but they don't change the drop down button text color

**Comment by Gildedter** [comment]
Oh by any chance, do you know why the `slate` colors aren't applying? I tried restarting my dev server but `slate` doesn't seem to exist, so I substituted it with `gray` for now

**Comment by shinokada** [comment]
You need to extend it in `app.css`.
Flowbite doesn't have that color.

**Comment by shinokada** [comment]
I'm working on a new component structure at the moment.
Can you wait a bit.
It will be more flexible.

**Comment by shinokada** [comment]
@Gildedter I'm going to update the sidebar components soon and it will a breaking change. I just wanted to give you a warning.

**Comment by Gildedter** [comment]
> I'm working on a new component structure at the moment. Can you wait a bit. It will be more flexible.

Will do, I'll update once its out

**Comment by Gildedter** [comment]
The `SidebarDropdownWrapper`'s `icon`, isn't working for me, my icon components look like this:
```
<script>
    import Icon from '@iconify/svelte';
</script>

<Icon icon="icon-park:bank-card" width="1.6rem" height="1.6rem" />
```

**Comment by shinokada** [comment]
I use `svelte:component`:

```
...
<svelte:component
  this={icon.name}
  size={icon.size}
  color={icon.color}
  class="mr-2 {icon.class}"
/>
...
```

Icon needs to be a svelte component. Is the icon you are using a svelte component?

**Comment by Gildedter** [comment]
I'm using it like so:
```
<SidebarDropdownWrapper label="Card" icon={BankCardIcon}>
        <SidebarDropdownItem label="Card Lists" href="/cards" />
        <SidebarDropdownItem label="Holders" href="/cards/holders" />
```
Where `BankCardIcon` is a svelte component wrapper that contains [this](https://github.com/themesberg/flowbite-svelte/issues/13#issuecomment-1149416786).

I tried:
```
<SidebarItem label="Users" icon={{ name: BankCardIcon }} />
```
but I'm getting this error: 
```
(property) IconType.name: string
Type 'typeof BankCardIcon__SvelteComponent_' is not assignable to type 'string'.ts(2322)
```

**Comment by shinokada** [comment]
Can you try any icon from svelte-heros and let me know.

```
<script>
import {  ChartPie  } from 'svelte-heros';
</script>

<SidebarItem label="Users" icon={{ name: ChartPie }} />
```

If this works, then your library is not svelte:component compatible.

You can use any icons from this [website](https://svelte-svg-icons.vercel.app/).

**Comment by Gildedter** [comment]
I tried both and, they work without any compile errors, but my editor keeps giving false positives till now, I did change it to this:
```
<SidebarDropdownWrapper label="Card" icon={{ name: BankCardIcon }}>
```
Thanks for the tip.

Oh and the logo part of the sidebar isn't showing, how do I bring it back?

**Comment by shinokada** [comment]
Glad you fixed it.
For brand, you need to use [`SidebarBrand`](https://flowbite-svelte.com/sidebars#Logo_branding).

**Comment by Gildedter** [comment]
I found out why its giving false positives, its due to these:

https://github.com/themesberg/flowbite-svelte/blob/de539173749b8fd9ddbfd233bb382679ff6f1e8a/src/lib/types.ts#L103
https://github.com/themesberg/flowbite-svelte/blob/de539173749b8fd9ddbfd233bb382679ff6f1e8a/src/lib/types.ts#L109

both `name` being of type string, not sure what's the appropriate type called

**Comment by shinokada** [comment]
Thank you for the catch.

I updated them to `typeof SvelteComponent`.

**Comment by kuchaguangjie** [comment]
Hey, how the width of sidebar decided ?
What's the proper way to set width of the sidebar? Currently I do that by setting `max-width` of a `<div>` that wraps the `<Sidebar>`.

**Comment by kuchaguangjie** [comment]
And, is there an easy way to highlight currently selected item in sidebar? e.g show a different background color ?

**Comment by kuchaguangjie** [comment]
(Another possible sub feature:)
Is it possible to link `<Sidebar>` and `<Breadcrumb>`, to auto generate the `<Breadcrumb>` from some property (e.g `href`) of `<Sidebar>`?

**Comment by shinokada** [comment]
1. Regarding sidebar width, you can change [the Sidebar component's asideClass](https://flowbite-svelte.com/sidebars#Props).
2. Highlighting an item, you can add own CSS to the item finding from URI.
3. To autogenerate the Breadcrumb, you can split the URL and use them for the Breadcrumb?

**Comment by kuchaguangjie** [comment]
> 1. Regarding sidebar width, you can change [the Sidebar component's asideClass](https://flowbite-svelte.com/sidebars#Props).
> 2. Highlighting an item, you can add own CSS to the item finding from URI.
> 3. To autogenerate the Breadcrumb, you can split the URL and use them for the Breadcrumb?

Yeah, these can be done I think, wondering is there a plan to make these features built-in.
I'll try them, if succeed, might share too.
