### ISSUE TITLE
Text color of `Select` component not changed when disabled

### ISSUE THREAD

**Issue by cpsoinos** [themesberg/flowbite-svelte#1302]
### Describe the bug

When you have a disabled `Select` component, the selected option's text color does not change to appear disabled. This is particularly noticeable in Safari, where the user-agent stylesheet doesn't apply `opacity: 0.7;` to disabled `select` inputs.

State | Chrome | Safari
--- | --- | ---
Enabled | <img width="178" alt="image" src="https://github.com/themesberg/flowbite-svelte/assets/10081464/09a1fba9-fc7e-4319-898d-3b782a53aefa"> | <img width="178" alt="image" src="https://github.com/themesberg/flowbite-svelte/assets/10081464/a1e0868c-4584-4e4c-a2b5-c5bdb95533b1">
Disabled | <img width="178" alt="image" src="https://github.com/themesberg/flowbite-svelte/assets/10081464/038cd868-fef3-4fee-8d88-d65b844de393"> | <img width="178" alt="image" src="https://github.com/themesberg/flowbite-svelte/assets/10081464/bbaaa8fa-a083-413f-a1fc-2f61399ca6c2">

I intend to submit a PR to address this.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-skxcco?file=src%2Froutes%2F%2Bpage.svelte

### Flowbite version and System Info

```shell
System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 411.61 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.0 - ~/.nvm/versions/node/v20.12.0/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.5.2 - ~/.nvm/versions/node/v20.12.0/bin/npm
    bun: 1.0.36 - /opt/homebrew/bin/bun
  Browsers:
    Brave Browser: 117.1.58.135
    Chrome: 123.0.6312.107
    Edge: 123.0.2420.81
    Safari: 17.4.1
  npmPackages:
    @sveltejs/kit: ^2.5.5 => 2.5.5
    flowbite-svelte: ^0.44.24 => 0.44.24
    svelte: ^4.2.13 => 4.2.13
    vite: ^5.2.8 => 5.2.8
```

**Comment by shinokada** [comment]
Why stackblitz doesn't work on Safari?
