### ISSUE TITLE
Svelte 3 support

### ISSUE THREAD

**Issue by pasevin** [themesberg/flowbite-svelte#1304]
### Describe the bug

Hey in `v0.44.12` you dropped the support for Svelte 3. Is this necessary or was it an oversight? We are still using Svelte 3 and this just prevents us from upgrading to higher versions of the library. Could you bring it back?

I tried asking on Discord, but it doesn't seem to be active.

https://github.com/themesberg/flowbite-svelte/compare/v0.44.11...v0.44.12#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L71

### Reproduction

Try using `v0.44.12` with Svelte 3.

### Flowbite version and System Info

```shell
Svelte 3
flowbite-svelte `v0.44.12` and up.
```

**Comment by shinokada** [comment]
The reason is that I don't test it on v3, any more. Does the lib still works on v3?
I just removed v3 from peer dependencies. If it is working you just ignore the terminal warning.

**Comment by pasevin** [comment]
Thanks for the reply. The library compiles the components extending `SvelteComponent` in Svelte 4 instead of `SvelteComponentTyped`, supported in v3 and v4.

Before `v0.44.12`:
```
export default class Alert extends SvelteComponentTyped<AlertProps, AlertEvents, AlertSlots> {...
```

After `v0.44.12`:
```
export default class Alert extends SvelteComponent<AlertProps, AlertEvents, AlertSlots> {
```

This causes an error in VSCode for example:
<img width="983" alt="image" src="https://github.com/themesberg/flowbite-svelte/assets/1058469/a58fb161-c438-4b69-88fb-336f0fbf498c">

The compilation seems to be working and the component is rendered, but `svelte-check` will not pass with this error:
```
Error: JSX element type 'Alert' does not have any construct or call signatures. (ts)
<div class="p-8">
  <Alert>
    <span class="font-medium">Info alert!</span>
```

This prevents the deployment process for us. So I was wondering if it's still possible to bring v3 back or is this a final decission?

**Comment by shinokada** [comment]
Do you think adding v3 will solve the problem?

```
 "peerDependencies": {
    "svelte": "^3.55.1 || ^4.0.0"
  },
```

Can you change your `node_modules/flowbite-svelte`'s `package.json` and test it?

**Comment by pasevin** [comment]
Yes that's the main culprit. Just replacing it won't help, but once re-built then `SvelteComponentTyped` is used instead of `SvelteComponent` which is supported in Svelte v3.

So bringing `"svelte": "^3.55.1 || ^4.0.0"` and releasing a new package, would fix this.
