### ISSUE TITLE
Modal component does not have headerClass props

### ISSUE THREAD

**Issue by khiemgluong** [themesberg/flowbite-svelte#1305]
### Describe the bug

There is a headerClass and classHeader prop from the [svelte-flowbite documentation page](https://flowbite-svelte.com/docs/components/modal) and this prop does exist in the [repo](https://github.com/themesberg/flowbite-svelte/blob/main/src/lib/modal/Modal.svelte). But the dist version does not. 

### Flowbite version and System Info

```shell
package.json dependencies:
"flowbite-svelte": "^0.44.24",
```

**Comment by shinokada** [comment]
Can you remove the `node_modules` and run `pnpm i` again?

**Comment by khiemgluong** [comment]
Thank you for fixing it in version 0.45.0. Deleting the `node_modules/.pnpm` folder and running `pnpm i ` with "flowbite-svelte": "^0.45.0",
