### ISSUE TITLE
Update Dark Mode documentation for configuring strategy in tailwind.config.js

### ISSUE THREAD

**Issue by khiemgluong** [themesberg/flowbite-svelte#1311]
### Describe the bug

I ran into some problems using the `'class'` strategy for [DarkMode](https://flowbite-svelte.com/docs/components/darkmode) with tailwind.config.js, being that its very inconsistent and sometimes toggle certain elements and sometimes not. That was because as of [tailwind 3.4.1, the 'class' strategy has been replaced with 'selector'](https://tailwindcss.com/docs/dark-mode).

the documentation should add a note on top of of the strategy configuration which mentions this, something like what I wrote below:

_The selector strategy replaced the class strategy in Tailwind CSS v3.4.1._
```
// tailwind.config.cjs
const config = {
  darkMode: 'class' //'selector'
  // ...
};
```

### Reproduction

...

### Flowbite version and System Info

```shell
flowbite-svelte: 0.45.0
```

**Comment by shinokada** [comment]
Thanks. Please use the latest version.
