### ISSUE TITLE
[MultiSelect] `on:change` is triggered twice

### ISSUE THREAD

**Issue by freearhey** [themesberg/flowbite-svelte#1337]
### Describe the bug

The `change` event is triggered twice in a row.

### Reproduction

```
<script>
  import { MultiSelect } from 'flowbite-svelte';

  let selected = [];
  let countries = [
    { value: 'us', name: 'United States' },
    { value: 'ca', name: 'Canada' },
    { value: 'fr', name: 'France' },
    { value: 'jp', name: 'Japan' },
    { value: 'en', name: 'England' }
  ];
</script>

<MultiSelect items={countries} bind:value={selected} on:change={() => console.log('triggered')} />
```[](url)

### Flowbite version and System Info

```shell
Node: 18.18.2
npm: 10.5.2
@sveltejs/kit: 2.0.0
flowbite-svelte: 0.46.1
svelte: 4.2.7
vite: 5.0.3
```

**Comment by jumtp** [comment]
Unable to reproduce this bug. can you provide a link to a repo that can reproduce the problem you ran into? Use [this Stackblitz template](https://stackblitz.com/edit/sveltejs-kit-template-default-xxqndk) to add your code.

**Comment by freearhey** [comment]
It turns out that the bug only appears if you nest `MultiSelect` in some other component, in my case it was `Sidebar`:

```
<Sidebar>
  <MultiSelect items={countries} bind:value={selected} on:change={() => console.log('triggered')} />
</Sidebar>
```

Reproduction: https://stackblitz.com/edit/sveltejs-kit-template-default-fodah2?file=src%2Froutes%2F%2Bpage.svelte
