### ISSUE TITLE
Add Svelte 5 as a Peer Dependency

### ISSUE THREAD

**Issue by JacobSilasBentley** [themesberg/flowbite-svelte#1342]
## Summary

Add the latest version of svelte as a peer dependency.

### Basic example

```
...
  "peerDependencies": {
    "svelte": "^3.55.1 || ^4.0.0 || ^5.0.0"
  },
...
```

### Motivation

Allows those using svelte 5 (currently in release candidate stage) to easily use the library

**Comment by shinokada** [comment]
Flowbite-Svelte works with Svelte 5 but it will shows warnings and it is not made for Svelte 5.
Please use [Svelte 5 UI lib](https://svelte-5-ui-lib.codewithshin.com/).
