### ISSUE TITLE
Accordion Heading Accessibility

### ISSUE THREAD

**Issue by jame5cross** [themesberg/flowbite-svelte#1351]
### Describe the bug

The h2 that wraps the accordion buttons should either be made a configurable tag so that it can be changed to a div or an h3 for example. Or just changed to a div. They are not necessarily headings. Also they could quite possibly have FAQ as an h2 title above the accordion which would make the heading ranking invalid.

### Reproduction

-

### Flowbite version and System Info

```shell
All
```

**Comment by cintek** [comment]
@shinokada I think this can be closed.
