### ISSUE TITLE
Is there something wrong with the testing mechanism?

### ISSUE THREAD

**Issue by mikwee** [themesberg/flowbite-svelte#136]
### Discussed in https://github.com/themesberg/flowbite-svelte/discussions/135

<div type='discussions-op-text'>

<sup>Originally posted by **mikwee** July  8, 2022</sup>
Hi!
I wanna contribute, but first I had to install `@playwright/test` (Sholdn't that already be installed?). Then, when I tried to test it, it told me to go and switch the scripts from `svelte-kit` to `vite`. I've done it before, and I could do it now, but I don't wanna mess with the repository *too* much for my PR. Can anybody explain why all of this is happening?
Thanks.</div>

**Comment by shinokada** [comment]
So far I got a quite few PRs and none of them had an issue.
It could be your dev environment.

**Comment by shinokada** [comment]
Close the issue for now for too little information.
