### ISSUE TITLE
Only include css of components that are being used

### ISSUE THREAD

**Issue by gregg-cbs** [themesberg/flowbite-svelte#1361]
## Summary
When doing the following in the tailwind.config.js the general css file size tripples.
`content: ['./node_modules/flowbite-svelte/**/*.{html,js,svelte,ts}'],`

It looks like this is including all components css even if components arent being used. This means the browser is downloading the entire flowbite library worth of components tailwindcss without needing it.

It would be nice if we could leverage tailwinds class shedding to only include css of components we use, when we use them.

### Motivation
Lighthouse is complaining about unused css. The css file size is 150kbs, naturally its 50kbs. Its not a crushing change but it is something to note that is happening and i hope we can look into it at some point.

**Comment by shinokada** [comment]
Did you read [this](https://flowbite-svelte.com/docs/pages/faq-and-tips#My_compiled_CSS_size_is_more_than_120K._How_can_I_make_it_smaller?)?

**Comment by gregg-cbs** [comment]
Thats a good find, i think that information should be upfront in the setup. Thanks for showing me.

Something im still wondering about - in the example in the faq its a little different to the setup examples:
```js
// this does not shed any css because of the (node_modules content inclusion)
export default {
  content: ['./src/**/*.{html,js,svelte,ts}', './node_modules/flowbite-svelte/**/*.{html,js,svelte,ts}'],
  plugins: [
    require('@tailwindcss/aspect-ratio'),
    require('flowbite/plugin')
  ],
}
// this works and reduces the css load (removed the './node_modules/flowbite-svelte/**/*.{html,js,svelte,ts}' from content)
export default {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  plugins: [
    require('@tailwindcss/aspect-ratio'),
    require('flowbite/plugin')
  ],
}


```

**Comment by gregg-cbs** [comment]
Good find and thanks for sharing. I think that information should be part of the setup documentation, i dont think anyone wants extra bloated css?

Also this seems to shed a couple kbs but not as much as I was hoping. I will look into this.

**Comment by shinokada** [comment]
I will close the issue for now. Please feel free to open a new issue.
