### ISSUE TITLE
Radio component checked prop isn't working

### ISSUE THREAD

**Issue by therealsujitk** [themesberg/flowbite-svelte#1372]
### Describe the bug

The `checked` prop in the `<Radio />` component doesn't seem to be working. ~ [Docs](https://flowbite-svelte.com/docs/components/forms#Radio_buttons)

<img width="865" alt="Screenshot 2024-06-22 at 16 18 41" src="https://github.com/themesberg/flowbite-svelte/assets/60378235/b7c1eb7c-8724-4754-a83b-4da7f10857d5">

### Reproduction

https://github.com/themesberg/flowbite-svelte/blob/main/src/routes/docs/components/forms.md#radio-buttons

### Flowbite version and System Info

```shell
-
```

**Comment by shinokada** [comment]
Thanks.
