### ISSUE TITLE
MultiSelect dropdown doesn't open when clicking associated label

### ISSUE THREAD

**Issue by MeoMix** [themesberg/flowbite-svelte#1378]
### Describe the bug

If I spawn a Label with for="foo" and spawn a MultiSelect with id="foo" then I expect clicking the label to open the dropdown. This doesn't occur because the select behind the scenes has the id and isn't what is visually shown to the user.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-gpadvx?file=src%2Froutes%2F%2Bpage.svelte

### Flowbite version and System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 1700X Eight-Core Processor
    Memory: 43.55 GB / 63.95 GB
  Binaries:
    Node: 22.0.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.19041.3636
```

**Comment by shinokada** [comment]
1. Clicking a label won't open a dropdown.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select

2. MultiSelect component doesn't have id.
https://github.com/themesberg/flowbite-svelte/blob/main/src/lib/forms/MultiSelect.svelte

**Comment by shinokada** [comment]
I will close the issue for now. Please feel free to open a new issue.
