### ISSUE TITLE
Textarea: when it has a slot the 'class' prop is applied differently

### ISSUE THREAD

**Issue by gregg-cbs** [themesberg/flowbite-svelte#1380]
### Describe the bug
The class should still be applied to the textarea as expected and specified in the docs but its behaving differently. If you inspect the dom you can the see the classes are getting applied in different places depending on if a slot is present or not.

```svelte
<!-- this will apply the classes to the textarea -->
<Textarea class="bg-red-600" />

<!-- this wont apply the classes to the textarea -->
<Textarea class="bg-red-600">
   <slot name="footer" slot="footer"/>
</Textarea>
```

![image](https://github.com/themesberg/flowbite-svelte/assets/57114335/c5379221-c07c-484f-b156-c015b7804cf4)

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-tbx5dc?file=src%2Froutes%2F%2Bpage.svelte

### Flowbite version and System Info

```shell
0.46.1
```

**Comment by shinokada** [comment]
Please try:

```
pnpm add -D flowbite-svelte@latest
```

```

<div class='p-9'>
  <!-- this will apply the classes -->
  <Textarea class="bg-red-600" />

  <!-- this wont apply the classes -->
  <Textarea class="bg-red-600" footerClass='border-red-600' innerWrappedClass=''>
    <slot slot="footer">
      Footer Content
    </slot>
  </Textarea>
</div>
```

![image](https://github.com/themesberg/flowbite-svelte/assets/147320/77026546-5ff8-4605-ac1d-312b2237c544)

**Comment by shinokada** [comment]
Closing this issue as inactive. 
Feel free to reopen if you have any further updates.
