### ISSUE TITLE
Dropdown: positioning inconsistent on ios safari

### ISSUE THREAD

**Issue by gregg-cbs** [themesberg/flowbite-svelte#1381]
### Describe the bug

On IOS Safari (i cant speak for other mobile devices) the dropdown does not position properly. It works fine on desktop.

I am using dropdown with the triggeredBy property to show the dropdown in a table row.

Screenshot of the issue:
![image](https://github.com/themesberg/flowbite-svelte/assets/57114335/9e6d5aa2-3f42-4b1e-9939-c217f71ec530)

Video recording of the issue:
https://github.com/themesberg/flowbite-svelte/assets/57114335/5de0ca16-359e-41cc-990a-c578001cba43

### Reproduction
https://stackblitz.com/edit/sveltejs-kit-template-default-37aty2?file=src%2Froutes%2F%2Bpage.svelte

### Flowbite version and System Info
```shell
"flowbite": "^2.3.0"
"flowbite-svelte": "^0.46.4"
```

**Comment by shinokada** [comment]
'setActiveOrder' is not defined.

**Comment by gregg-cbs** [comment]
@shinokada - sorry fixed it

**Comment by shinokada** [comment]
The following works. Use `id` for the `triggered`.

```
<script>
  import { Table, TableBody, TableBodyCell, TableBodyRow, TableHead, TableHeadCell, Button, Dropdown, DropdownItem  } from 'flowbite-svelte';
  import { ChevronDownOutline, DotsVerticalOutline } from 'flowbite-svelte-icons';
</script>

<Table>
  <TableHead>
    <TableHeadCell>Product name</TableHeadCell>
    <TableHeadCell>Color</TableHeadCell>
    <TableHeadCell>Category</TableHeadCell>
    <TableHeadCell>Price</TableHeadCell>
  </TableHead>
  <TableBody tableBodyClass="divide-y">
    {#each  {length: 9} as _, i}
    <TableBodyRow>
      <TableBodyCell>Apple MacBook Pro 17"</TableBodyCell>
      <TableBodyCell>Sliver</TableBodyCell>
      <TableBodyCell>Laptop</TableBodyCell>
      <TableBodyCell>
        <Button
          color="none"
          size="xs"
          id='fs-{i}'
          class="dropdown-actions rounded-none"
          >
          <DotsVerticalOutline size="sm" class="w-5" />
        </Button>
      </TableBodyCell>
    </TableBodyRow>
    <Dropdown triggeredBy={`#fs-${i}`} placement="bottom-end">
      <DropdownItem>Dashboard</DropdownItem>
      <DropdownItem>Settings</DropdownItem>
      <DropdownItem>Earnings</DropdownItem>
    </Dropdown>
    {/each}
  </TableBody>
</Table>

```

**Comment by gregg-cbs** [comment]
Thanks, I was trying to avoid having to create a dropdown for every row. I dont need a dropdown for every row, i need one dropdown that shows at the triggers location.

The dropdown works fine on desktop, its only mobile that is having this issue.

**Comment by shinokada** [comment]
I will close the issue for now. Please feel free to open a new issue.

**Comment by gregg-cbs** [comment]
Unfortunately not. We are moving away from Flowbite svelte and looking for a more headless solution as we are rebuilding our UI. Even when looking at other UI libraries like Melt-UI there are a lot of open bugs but it offers an interesting approach and some lessons can be taken from there.

I think your best bet is to pick and choose components from libraries you like. It does unfortunately come with some overhead because every when importing just a component from a library you are importing other assets and packages as well.

Melt dropdown, unstyled so you can style it but some interesting code:
https://www.melt-ui.com/docs/builders/dropdown-menu

Shadcn dropdown, styled so you dont have to:
https://next.shadcn-svelte.com/docs/components/dropdown-menu
