### ISSUE TITLE
Close Button on Alerts is not colored

### ISSUE THREAD

**Issue by ptrxyz** [themesberg/flowbite-svelte#139]
**Describe the bug**

The colored, dismiss-able alert boxes do not color the close button. However they are colored in the non-svelte versions of Flowbite.

Svelte Version:
![image](https://user-images.githubusercontent.com/209056/178945818-b4b29735-6231-4386-a4ec-fd6cd1912141.png)

Flowbite Version: 
![image](https://user-images.githubusercontent.com/209056/178945883-10f10f0d-782c-45a3-b37c-9466036ac760.png)

(See the color of the "X" symbol)

**Comment by shinokada** [comment]
@jjagielka Can you have a look at this?

**Comment by shinokada** [comment]
@ptrxyz Can you check it please.

**Comment by shinokada** [comment]
Updated for the new version.
