### ISSUE TITLE
Conflict with global styles

### ISSUE THREAD

**Issue by michael-meetkai** [themesberg/flowbite-svelte#1394]
### Describe the bug

Hello!
So I'm building a svelte + babylonjs website and it looks flowbite defines some global styles for inputs/selects
Like my flowbite UI looks perfect, but it breaks my babylonjs scene inspector panel because if modifies the form elements by using global styles. Is there a way to scope the styles ?

Thanks

![Screenshot 2024-07-19 234033](https://github.com/user-attachments/assets/ba60ce07-7362-4f33-8311-65d58b536cfa)
![Screenshot 2024-07-19 234422](https://github.com/user-attachments/assets/9ce92ec3-617f-463b-ac05-c735fb23f2b3)

### Reproduction

Just create a new svelte flowbite app and use any inputs, you will see global styles added by using the browser inspector

### Flowbite version and System Info

```shell
"flowbite": "^2.4.1",
"flowbite-svelte": "^0.46.14",
"flowbite-svelte-icons": "^1.6.1",

System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor             
    Memory: 9.50 GB / 31.92 GB
  Binaries:
    Node: 18.19.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (126.0.2592.113)
    Internet Explorer: 11.0.22621.3527
```

**Comment by shinokada** [comment]
You can remove flowbite plugin from tailwind.config.cjs.

```
// remove this line
plugins: [flowbitePlugin]
```

**Comment by michael-meetkai** [comment]
Thanks @shinokada, removing the plugin fixed the issue, then I just had to configure dark mode as the doc explains with 
```
darkMode: 'class'
```
because without the plugin it was defaulting to my machine preference.
