### ISSUE TITLE
Bage color won't update

### ISSUE THREAD

**Issue by koplas** [themesberg/flowbite-svelte#1400]
### Describe the bug

It is no longer possible to dynamically change the color of the Badge component. This seems to be introduced with https://github.com/themesberg/flowbite-svelte/commit/e7cb9d734142c04beef0ecfea485dacf7751c13a#diff-19a080e9a8d04d343b8dee72352ef93924862b0f0c20c506a7099a0a04f85c67R75-R82.

### Reproduction

Use the Badge component like this:
```Javascript
    <Badge title="test" color={colorVariable)}>Test</Badge>
```
Change the value of `colorVariable`.
The component will still have the same color.

On version `0.44.24` the color changed.

### Flowbite version and System Info

```shell
System:
    OS: Linux 6.1 Manjaro Linux
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 14.65 GB / 31.25 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.5.1 - /usr/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.8.2 - /usr/bin/npm
  Browsers:
    Chromium: 127.0.6533.72
  npmPackages:
    @sveltejs/kit: ^2.5.18 => 2.5.18
    flowbite-svelte: ^0.46.15 => 0.46.15
    svelte: ^4.2.7 => 4.2.18
    vite: ^5.3.5 => 5.3.5
```

**Comment by alistair-white-fortesium** [comment]
Noticed the same issue. Why was this made not reactive anymore?
