### ISSUE TITLE
TimelineItem's slot 'icon' should work when parent Timeline's order prop is 'default'

### ISSUE THREAD

**Issue by jpdom** [themesberg/flowbite-svelte#1406]
## Summary

Currently the slot 'icon' present in TimelineItem is only used if the parent Timeline prop "order" isn't set to (or left at) 'default'.

[Related Code](https://github.com/themesberg/flowbite-svelte/blob/e3c3b47c9eb268ff93f3a2fd7d3ee29159ccfbd4/src/lib/timeline/TimelineItem.svelte#L42C1-L50C8)

### Basic example
```svelte
<Timeline>
<TimelineItem>
<svelte:fragment slot="icon">
<p>I am NOT rendered!</p>
</svelte:fragment>
</TimelineItem>
</Timeline>
```
```svelte
<Timeline order='vertical'>
<TimelineItem>
<svelte:fragment slot="icon">
<p>I am rendered!</p>
</svelte:fragment>
</TimelineItem>
</Timeline>
```
### Motivation

This is one of those simple things that cause development hiccups so this should either be addressed in the docs or by changing the behaviour.

**Comment by shinokada** [comment]
![image](https://github.com/user-attachments/assets/442e43db-f7fa-4f4b-b10f-3f8f07b19e08)
Thanks.
