### ISSUE TITLE
It is too difficult to style rating icons (fill & stroke color) when using <Rating />

### ISSUE THREAD

**Issue by mattdeboard** [themesberg/flowbite-svelte#1409]
## Summary

There is no way to convey fill and stroke color information through the `Rating` component. 

Basically, the rating icons (`Star`, `Heart`, etc.) take `fillColor` and `strokeColor` props. Those should be exposed via the `Rating` component.

### Basic example

I propose a very simple API on the `Rating` component:

```ts
<Rating 
  id='my-rating-wrapper'
  iconFillColor='#f0f0f0' 
  iconStrokeColor='#0f0f0f'
  size={10}
  total={5}
  {rating}
/>
```

This would unroll to an array of icons (default `Star`) that would have each `fillColor` and `strokeColor` prop set to the value of the `iconFillColor` and `iconStrokeColor` props of `Rating`.

This proposal also implies the following:
1. One color for all icons
2. No support for gradients

### Motivation

`Rating` should expose an API for customizing its child components.

**Comment by shinokada** [comment]
Thank you for the suggestion. This will be in the next version.
