### ISSUE TITLE
Allow specifying the link `target` attribute in the `Button` component

### ISSUE THREAD

**Issue by th0rgall** [themesberg/flowbite-svelte#1420]
### Motivation

`<Button>` has a `href` attribute, but it does not allow the `target` attribute to be set. This is for example necessary to have to specify a button that should open a link in a new tab (`target="_blank"`). Currently, buttons can only open links in the same tab.

This issue is similar to this closed `<FooterLink>` issue: https://github.com/themesberg/flowbite-svelte/issues/403

**Comment by shinokada** [comment]
Since it has[ `...$$restProps`](
![image](https://github.com/user-attachments/assets/ed2ccf14-5202-412a-9f01-619d82785d9c)
), you should be able to add it.

**Comment by th0rgall** [comment]
Ah, thank you! I missed that. It indeed just works. 

I was looking at the `.d.ts` declaration and docs and didn't see a `target` property, but didn't realize that `[x: string]: any;` was present together with `...$$restProp`.
