### ISSUE TITLE
hide privacy indicator from timeline/GroupItem.svelte

### ISSUE THREAD

**Issue by thomas-topway-it** [themesberg/flowbite-svelte#1426]
## Summary

We are using this component https://github.com/themesberg/flowbite-svelte/blob/main/src/lib/timeline/GroupItem.svelte

however we don't need the privacy indicator (either "private" or "public") and we would like a way to remove it.

### Basic example

the indicator does not disappear when the value is undefined or the `isPrivate` property is missing
 
`isPrivate: undefined,`

alternatively, a class name with semantic meaning could be assigned to each sub-component, so that it can be hidden through css

### Motivation

despite the component being really useful, the private/public indicator is often unnecessary for many use-cases

**Comment by shinokada** [comment]
I can add `isPrivacy` prop to control the span block.

**Comment by thomas-topway-it** [comment]
great, thanks a lot !
