### ISSUE TITLE
[Feature] Dropdown components

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite-svelte#144]
New [Dropdowns](https://flowbite.com/docs/components/dropdowns/)

- [x] Dropdown example
- [x] Dropdown divider
- [x] Dropdown header
- [x] Multi-level dropdown
- [x] Dropdown with checkbox, Background hover, Helper text
- [x] Dropdown with radio, Background hover, Helper text
- [x] Dropdown with toggle switch
- [x] Dropdown with scrolling
- [x] Dropdown with search
- [x] Menu icon
- [x] Notification bell
- [x] User avatar, avatar with name
- [x] Dropdown navbar
- [x] Sizes
- [x] Placement, double placement

**Comment by shinokada** [comment]
Some notes about dropdown components.

1. Please keep the structure, Dropdown, DropdownHeader, DropdownDivider, DropdownItem.
2. Regarding the positions, please see the [Tooltip component](https://github.com/themesberg/flowbite-svelte/blob/main/src/lib/tooltips/Tooltip.svelte).

**Comment by jjagielka** [comment]
What is really ‘new’ in those Dropdowns? When the ‘new’ label was added at Flowbite.com and which changes triggered that?

**Comment by shinokada** [comment]
<img width="233" alt="image" src="https://user-images.githubusercontent.com/147320/179163546-13e9adfb-b1a0-45bc-960b-5b0be300bff2.png">

Flowbite add the new badge when they add new components or examples. I just updated the list that I we haven't covered yet.

<img width="411" alt="image" src="https://user-images.githubusercontent.com/147320/179163756-21cddaf0-fbf6-4420-840b-dd77d58f802b.png">

**Comment by jjagielka** [comment]
> 1. Please keep the structure, Dropdown, DropdownHeader, DropdownDivider, DropdownItem.

Why that requirement? Do you need all those components?

`<DropdownDivider />` can be implemented simply by an empty item: `<DropdownItem />`, because use of empty item has no other sense.

What is a difference between DropdownHeader and DropdownItem? Only the fact that it's on top and not active? Can't we use divider to achieve the same? Something like that:

```html
<Dropdown ... >
<DropdownItem acitve={false}>Header element</DropdownItem>
<DropdownItem/>
<DropdownItem>Item 1</DropdownItem>
...
</Dropdown>
```
This would simplify the API. Only Dropdown and DropdownItem

**Comment by shinokada** [comment]
I used have all in one component with many props. Then I found that using a component over props is more flexible and easy to understand.

Component names tells what for.

I think once we have many props in a component, it is time to create a new component. We just need a balance.

What do you think?

**Comment by shinokada** [comment]
A huge thanks to @jjagielka, most of the examples are completed.

**Comment by shinokada** [comment]
Completed.

**Comment by shinokada** [comment]
@jjagielka Can you have a look at the arrow position for the Dropdown left?

https://flowbite.com/docs/components/dropdowns/#placement
<img width="185" alt="image" src="https://user-images.githubusercontent.com/147320/180178641-8b553393-97e8-4ac6-b3c6-344581e45fec.png">

https://flowbite-svelte.com/dropdowns#Placement
<img width="183" alt="image" src="https://user-images.githubusercontent.com/147320/180178690-d6fdaec2-ae13-4e89-9374-998d105f7c13.png">

**Comment by ollyde** [comment]
I'm using " data-dropdown-placement="bottom"

Loading a list of users, seems to break when the layout changes. I see it flash on the bottom first.

<img width="515" alt="Screenshot 2023-09-05 at 10 20 58" src="https://github.com/themesberg/flowbite-svelte/assets/6940726/0bcaffaa-d5bf-4b7a-9745-d6949cffbb5d">
