### ISSUE TITLE
FileInput: Color attribute

### ISSUE THREAD

**Issue by cintek** [themesberg/flowbite-svelte#1441]
Add a color attribute to the FileInput so developers can change the color of the button that is part of the input.

Now there are only two colors which are depending on the theme you are using. In a light theme the button of the FileInput is black and if black is not an accent color in your theme the button is too outstanding.

To style the button of the FileInput you could generally use the [file-modifier](https://tailwindcss.com/docs/hover-focus-and-other-states#file-input-buttons) of TailwindCSS. I tried to do so but it had no effect. Maybe this is because of some file preprocessing or anything else. Does somebody have an idea?

**Comment by shinokada** [comment]
Can you use `<Fileupload class="your-tailwind-color" />` ?

**Comment by cintek** [comment]
In one project I'm working in we use `primary` as accent color but when I use `<Fileupload class="primary" />` this doesn't change anything.

**Comment by shinokada** [comment]
If you have updated your [tailwind.config.cjs](https://flowbite-svelte.com/docs/pages/quickstart#Configuration) you need to use `class="text-primary-500"`.
