### ISSUE TITLE
Forms Input Doc Page is 404 now?

### ISSUE THREAD

**Issue by larryhengl** [themesberg/flowbite-svelte#145]
Is it me or is the Forms Input doc page not available anymore?

https://flowbite-svelte.com/forms/input

**Comment by shinokada** [comment]
Thank you for the catch.
It is now, http://localhost:8000/forms/input-field.
I just updated the doc.

**Comment by larryhengl** [comment]
Nice. The related tile link also needs the same update.
Thanks!

https://flowbite-svelte.com/forms

<img width="266" alt="flowbite-input-tile" src="https://user-images.githubusercontent.com/2637196/179281374-758faa0e-b942-47d8-b80d-758f9a8d28fc.png">

**Comment by shinokada** [comment]
Thanks. I just fixed the links.
