### ISSUE TITLE
Indicator class is being replaced instead of merged

### ISSUE THREAD

**Issue by JackNeto** [themesberg/flowbite-svelte#1452]
### Describe the bug

When adding a class to an `<Indicator/>` component, all the default classes are replaced.
This used to work correctly in previous versions.

### Reproduction

https://stackblitz.com/~/github.com/JackNeto/flowbite-svelte-issue-template

### Flowbite version and System Info

```shell
System:
    OS: macOS 14.6.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 3.21 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.17.0/bin/npm
    pnpm: 8.15.4 - /opt/homebrew/bin/pnpm
  Browsers:
    Brave Browser: 129.1.70.119
    Chrome: 129.0.6668.70
    Safari: 17.6
  npmPackages:
    @sveltejs/kit: ^2.5.18 => 2.6.1
    flowbite-svelte: ^0.46.20 => 0.46.20
    svelte: 4.2.18 => 4.2.18
    vite: ^5.3.3 => 5.4.8
```

**Comment by rbozan** [comment]
Same with <Tabs> component..

**Comment by shinokada** [comment]
@JackNeto  @rbozan  The latest version should solve this. Please check it and let me know.

**Comment by JackNeto** [comment]
Yes this is working for me again on version 0.46.23.
Thank you very much.
