### ISSUE TITLE
Class composition fails in components

### ISSUE THREAD

**Issue by Alfgar** [themesberg/flowbite-svelte#146]
**Description**
I am trying to add classes to components but doing so remove the "base" class definition provided by the component. So for instance, for the SidebarWraper component, I tried:

```
<Sidebar>
  <SidebarWrapper class="border-2 border-red-700">
...
  </SidebarWrapper>
</Sidebar>
```

Per the component usage of classNames I was expecting the classes from the component to be combined with mine to generate:
```
<aside class="w-64" aria-label="Sidebar">
  <div class="overflow-y-auto py-4 px-3 bg-gray-50 rounded dark:bg-gray-800 border-2 border-red-700">
...
  </div><!--<SidebarWrapper>-->
</aside>
```

Instead I got:
```
<aside class="w-64" aria-label="Sidebar">
  <div class="border-2 border-red-700">
...
  </div><!--<SidebarWrapper>-->
</aside>
```

**Workaround/solution?**
Looking at the component code, the current definition is:
```
<script>import classNames from 'classnames';
export let divClass = 'overflow-y-auto py-4 px-3 bg-gray-50 rounded dark:bg-gray-800';
</script>
<div class={classNames(divClass, $$props.class)} {...$$restProps}>
	<slot />
</div>
```

This implementation will yield 2 class attributes: the first one, and that is ncluded in $$restProps. The second definition "wins".

My workaround was to revert the order of the attributes:
```
<script>import classNames from 'classnames';
export let divClass = 'overflow-y-auto py-4 px-3 bg-gray-50 rounded dark:bg-gray-800';
</script>
<div {...$$restProps} class={classNames(divClass, $$props.class)}>
	<slot />
</div>
```

Which yields the expected result.

This is such a widespread issue (every single component in the library uses that pattern!) I'm second-guessing myself... Am I missing something?

**Environment**
- Desktop, Chrome, Safari, Firefox, versions irrelevant

**Comment by jjagielka** [comment]
@Alfgar is correct. The pattern should be changed to the proposed one. I'm using similar one in my implementations:

```html
<script>
let elemClass;
$: elemClass = classNames(
		'inline-flex items-center justify-center mr-2',
		...,
		$$props.class
	);
</script>

<element {...$$restProps} class={elemClass}>
```

**Comment by shinokada** [comment]
Please see the updated version.
I updated all the forms and sidebar components.
