### ISSUE TITLE
InputAddon is no longer flush with Input inside a ButtonGroup

### ISSUE THREAD

**Issue by JackNeto** [themesberg/flowbite-svelte#1462]
### Describe the bug

This can be seen on the current documentation pages. The left side is no longer flush. The right side is ok though.

### Reproduction

Instead of creating a repo I'm just referring to the documentation: https://flowbite-svelte.com/docs/forms/input-field#Input_group
![Screenshot 2024-10-07 at 3 41 09 PM](https://github.com/user-attachments/assets/0750a225-d02c-4425-8e90-5fb82bd8aa1f)

### Flowbite version and System Info

```shell
System:
    OS: macOS 14.6.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 1.77 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.17.0/bin/npm
    pnpm: 8.15.4 - /opt/homebrew/bin/pnpm
  Browsers:
    Brave Browser: 129.1.70.123
    Chrome: 129.0.6668.90
    Safari: 17.6
  npmPackages:
    @sveltejs/kit: ^2.5.28 => 2.5.28
    flowbite-svelte: ^0.46.17 => 0.46.17
    svelte: ^4.2.19 => 4.2.19
    vite: ^5.4.6 => 5.4.6
```

**Comment by shinokada** [comment]
Same issue as https://github.com/themesberg/flowbite-svelte/issues/1460

**Comment by shinokada** [comment]
This could be related to https://github.com/themesberg/flowbite-svelte/pull/1438.
