### ISSUE TITLE
RadioButton not working after upgrading  0.46.20 to 0.46.22 

### ISSUE THREAD

**Issue by xmlking** [themesberg/flowbite-svelte#1463]
### Describe the bug

RadioButton not working after upgrading  0.46.20 to 0.46.22 

<img width="471" alt="image" src="https://github.com/user-attachments/assets/1d21d133-1cbe-4662-8ea2-b01edd918ea8">

<img width="471" alt="image" src="https://github.com/user-attachments/assets/0a6bd1d1-dc00-4a7b-8804-ae162aaeae0d">

### Reproduction

RadioButton not working after upgrading  0.46.20 to 0.46.22 

### Flowbite version and System Info

```shell
0.46.22
```

**Comment by shinokada** [comment]
Can you show me your code?

**Comment by xmlking** [comment]
https://github.com/xmlking/spectacular/blob/v0.4.2/apps/console-fb/src/lib/components/form/RadioFB.svelte

**Comment by xmlking** [comment]
Can you please share if you have any working example of this component

**Comment by shinokada** [comment]
https://flowbite-svelte.com/docs/forms/radio#RadioButton

**Comment by soberreu** [comment]
That example isn't working. Not on the website... not in my project

**Comment by Turokhunter** [comment]
For anyone waiting on the fix, you can imitate the desired effect with buttons for now.

![image](https://github.com/user-attachments/assets/efb03e0f-fa5f-4e15-8a6c-65d69cfe5478)
