### ISSUE TITLE
Gallery component doesn't accept `class` as a valid property

### ISSUE THREAD

**Issue by aldelucca1** [themesberg/flowbite-svelte#1471]
### Describe the bug

The Gallery component no longer accepts the `class` prop as a valid component property. When running svelte-check the following error is produced:
```
Error: Type '{ class: string; }' is not assignable to type 'HTMLAttributes<HTMLDivElement> & { items: ImgType[]; imgClass?: string | undefined; }'.
  Property 'items' is missing in type '{ class: string; }' but required in type '{ items: ImgType[]; imgClass?: string | undefined; }'. (ts)
```

### Reproduction

```
<Gallery class="grid-cols-6 gap-4">
    ...
</Gallery>
```

### Flowbite version and System Info

```shell
"flowbite": "^2.5.2",
"flowbite-svelte": "0.47.1",
"svelte": "^4.2.19",
"svelte-check": "^4.0.5"
```

**Comment by shinokada** [comment]
That's strange. When I run `pnpm check`, I don't get any error.

<img width="973" alt="image" src="https://github.com/user-attachments/assets/6c7fc0e1-7106-4273-a325-bf39041c6a31">

**Comment by shinokada** [comment]
Try `pnpm format && pnpm lint` to see any other problems.

**Comment by aldelucca1** [comment]
If this can't be reproduced it could be something specific to my setup, closing
