### ISSUE TITLE
Datepicker showing incorrect days

### ISSUE THREAD

**Issue by murunwas** [themesberg/flowbite-svelte#1496]
### Describe the bug

Datepicker showing incorrect days for previous month as shown on the image below:

![image](https://github.com/user-attachments/assets/885d1cdf-16c8-4293-8515-902c095d050f)

Displaying days in reverse order.

### Reproduction

1. go to this url https://flowbite-svelte.com/docs/components/datepicker
2. select any month and check previous month days.

### Flowbite version and System Info

```shell
version 0.47.3
```

**Comment by shinokada** [comment]
Solved by https://github.com/themesberg/flowbite-svelte/pull/1494
