### ISSUE TITLE
The side bar overlap content on https://flowbite-svelte.com/pages/getting-started

### ISSUE THREAD

**Issue by kuchaguangjie** [themesberg/flowbite-svelte#154]
Thanks for taking the time to fill out this bug report!

**Describe the bug**
The side bar overlap content on https://flowbite-svelte.com/pages/getting-started

**To Reproduce**

1. Open https://flowbite-svelte.com/pages/getting-started
2. Then you will see

**Screenshots**
![side-bar-issue](https://user-images.githubusercontent.com/4230959/179382750-155f3a13-b0e7-4781-801d-013ba39aa533.jpg)

**Desktop (please complete the following information):**

- Browser chrome
- Version 102.0.5005.115 (Official Build) (64-bit)

**Additional context**
I'm using linux minte mate (based on ubuntu 20.04)

**Comment by kuchaguangjie** [comment]
The issue happen when I set default zoom of the browser as 125%, when I resize the browser to 100%, the issue is gone. But .. still this can be improved, right ?

**Comment by shinokada** [comment]
I tried the 125% zoom to reproduce it but I can't see the same problem.

**Comment by kuchaguangjie** [comment]
Maybe it's also related to the screen size. When maximize chrome I saw the issue, if I resize the browser as smaller, the issue may be gone.

**Comment by shinokada** [comment]
I close the issue for now. Please let me know if you find more issue. Thank you.
