### ISSUE TITLE
Bundlephobia can't build package

### ISSUE THREAD

**Issue by DarkEye123** [themesberg/flowbite-svelte#156]
Go to the https://bundlephobia.com/package/flowbite-svelte

You will see error saying that app can't be build - tried with latest release (v0.21.7)
![image](https://user-images.githubusercontent.com/5730144/179396348-3f2e622a-b1d8-472c-a1d0-64831cc1fe5d.png)

```
/tmp/tmp-build/packages/build-flowbite-svelte-KsC/node_modules/flowbite-svelte/badges/Badge.svelte Module build failed (from ./node_modules/svelte-loader/index.js): Error: ParseError: Valid <svelte:...> tag names are svelte:head, svelte:options, svelte:window, svelte:body, svelte:self, svelte:component or svelte:fragment (30:1) 28: </script> 29: 30: <svelte:element this={href ? 'a' : 'span'} {href} {...$$restProps} class={badgeClass}> ^ 31: <slot /> 32: </svelte:element> at /var/www/bundlephobia/node_modules/svelte-loader/index.js:181:12 @ /tmp/tmp-build/packages/build-flowbite-svelte-KsC/node_modules/flowbite-svelte/index.js 9:0-57 9:0-57 @ /tmp/tmp-build/packages/build-flowbite-svelte-KsC/index.js
```

**Comment by shinokada** [comment]
This could be related to [this issue](https://github.com/themesberg/flowbite/issues/130).

**Comment by shinokada** [comment]
I think this is Bundlephobia's problem. It can't recognize `svelte:element`

<img width="587" alt="image" src="https://user-images.githubusercontent.com/147320/180389251-3263cd90-4587-447c-92b7-5dd9be9eef23.png">

I close the issue for now since it is related Bundlephobia's configuration.
Thank you for bring it up.
