### ISSUE TITLE
What is spanClass of <SidebarItem>?

### ISSUE THREAD

**Issue by kuchaguangjie** [themesberg/flowbite-svelte#159]
## Summary

What is spanClass of <SidebarItem>, could you add more description in the document?

### Basic example

` <SidebarItem label="Kanban" {spanClass} icon={{ name: ViewGrid }}>`

### Motivation

I'm not sure how to use it.

**Comment by shinokada** [comment]
If you see the [Flowbite](https://flowbite.com/docs/components/sidebar/#default-sidebar) example, you see a span under a li tag.

<img width="529" alt="image" src="https://user-images.githubusercontent.com/147320/179455062-857c6f92-1a06-4dc1-9494-1b1a7835befa.png">

It has `ml-3` class.

**Comment by kuchaguangjie** [comment]
Ok, so it's better for user to get familiar with `flowbite`.

**Comment by shinokada** [comment]
Or you can see the [source code](https://github.com/themesberg/flowbite-svelte/blob/main/src/lib/sidebars/SidebarItem.svelte).
