### ISSUE TITLE
[Feature] Badge component

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite-svelte#16]
[Badge component](https://flowbite.com/docs/components/badge/)

- [x] Default badge
- [x] Larger badge
- [x] Badges as links
- [x] Badges with icon
- [x] Notification badge
- [x] Button with badge
- [x] Badges with icon only
- [x] Dismissable badges

**Comment by shinokada** [comment]
Done.

**Comment by shinokada** [comment]
Thank you to @jjagielka https://github.com/themesberg/flowbite-svelte/pull/194.
Close the issue for now.

**Comment by shubhendumadhukar** [comment]
Hello,
Is there a way to override a badge's dismiss/close button's on:click event? I see it internally calls a `handleHide` button, but if I wanted to do something on badge dismiss, what would be the recommended approach?

**Comment by jjagielka** [comment]
The `Badge` component is currently being updated to the latest changes on Flowbite.com

It will be possible to react on the dismiss.
