### ISSUE TITLE
Toggle on:click not working with recent change 

### ISSUE THREAD

**Issue by xmlking** [themesberg/flowbite-svelte#165]
` on:click` on `Toggle` is not working with this change 

```
	<div>
		<Toggle color="orange"  bind:value={$form.enforcement} name="enforcement" id="enforcement"
				label="Enforcement" checked={$form.enforcement == 1} on:click={handleEnforcementClick}/>
		<ErrorMessage name="enforcement"/><span>{$form.enforcement}</span>
	</div>
```

**Comment by shinokada** [comment]
@jjagielka Can you have a look at this? Toggle uses Checkbox and Checkbox uses Radio component. What do you think to nest a component more than one component?

**Comment by shinokada** [comment]
I added `on:click` to Toggle, Checkbox and Radio components.
Please check v0.21.15 and let me know.

**Comment by jjagielka** [comment]
I'm currently re-writing those buttons once again. Found some svelte weaknesses with component 'inheritance'.

**Comment by xmlking** [comment]
click works fine now. but **value** binding on **Toggle** is missing. 
value binding is needed for [svelte-forms-lib](https://svelte-forms-lib-sapper-docs.vercel.app/field) validation to work. 

```svelte
	<div>
		<Toggle color="orange" bind:value={$form.enforcement} name="enforcement" id="enforcement"
				label="Enforcement" checked={$form.enforcement == 1} on:click={handleEnforcementClick}/>
		<ErrorMessage name="enforcement"/>
	</div>
```

**Comment by xmlking** [comment]
adding ` {value}`  to https://github.com/themesberg/flowbite-svelte/blob/main/src/lib/forms/Toggle.svelte  fixed above issue, 
```svelte
<Checkbox custom class="relative {$$restProps.class}" {value} {...$$restProps} on:click>
	<div class={classNames(common, colors[$$restProps.color ?? 'blue'], sizes[size])} />
	<slot />
</Checkbox>
```

**Comment by shinokada** [comment]
Thank you. Suggesting a solution makes my life easier.
Updated for v0.22.2. Please check it and let me know.

**Comment by jjagielka** [comment]
You should not bind to `value`. Toggle is just a special case of `checkbutton` and as such you should bind to `checked`.

I'll add that now.
