### ISSUE TITLE
Is it possible to open <SmallModal> programmingly without <ModalButton>?

### ISSUE THREAD

**Issue by kuchaguangjie** [themesberg/flowbite-svelte#175]
## Summary

I want to open a `<SmallModal>` programmingly without adding or click the `<ModalButton>`.
That's very common usage, Is that possible?

**Comment by kuchaguangjie** [comment]
e.g export an `open` property for `<SmallModal>`, true -> open, false -> close

**Comment by kuchaguangjie** [comment]
I've wrapped `<SmallModal>` and `<ModalButton>` as a new `<YesNoDialog>` component, which hide the `<ModalButton>` and use the exported `open` property to control show/hide of the dialog.
So it could work.

**Comment by kuchaguangjie** [comment]
BTW, it feels redundant to have multiple `<XxxModal>` tags, just for different size, it can be unified as a single tag, with `size` property.

**Comment by shinokada** [comment]
Yes, I agree. It will be nice to have the `size` prop to change it.

**Comment by jjagielka** [comment]
With #176 I think we can close that issue.
