### ISSUE TITLE
[Feature] Modal

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite-svelte#176]
[Modal](https://flowbite.com/docs/components/modal/)

- [x] Default modal
- [x] Pop-up modal
- [x] Form element
- [x] Crypto wallet 
- [x] Sizes 
- [x] Placement

**Comment by jjagielka** [comment]
I'm on it now.

**Comment by shinokada** [comment]
https://github.com/themesberg/flowbite-svelte/pull/189.

**Comment by shinokada** [comment]
@jjagielka I used to have `clickOutside` function.
What do you think adding it to the Modal component?

**Comment by jjagielka** [comment]
This is an ideological question. If you look at https://en.m.wikipedia.org/wiki/Modal_window you’ll find:
>   Users must interact with the modal window before they can return to the [parent](https://en.m.wikipedia.org/wiki/Tree_(data_structure)#Terminology) application.

Clicking outside it’s not a real interaction. Some tends even to force the focus trap to not allow leaving the modal without interaction. 

I did not implemented the click outside on purpose but you can challenge that approach stating that I did implement reaction to the Escape button.

**Comment by shinokada** [comment]
Thanks for the explanation. I go with it.

**Comment by mahyuddin** [comment]
Current Modal in Flowbite-Svelte implementation seems already different from the Modal examples in Flowbite-Svelte documentation. Any updates on the documentation?

**Comment by jjagielka** [comment]
What is different? Can you please show examples?

**Comment by mahyuddin** [comment]
For example, in documentation, the examples show to use Modal is by importing Modal from flowbite-svelte. But when i try, there is no Modal but there are SmallModal, MediumModal, LargeModal, SignInModal, ExtraLargeModal. There are even an additional ModalButton component. Is it obviously different from the current examples documentation?

**Comment by jjagielka** [comment]
Are you sure you use the latest version if flowbite-svelte? 
Can see only 'Modal.svelte' in the code.

**Comment by shinokada** [comment]
Completed. 
https://github.com/themesberg/flowbite-svelte/pull/220
