### ISSUE TITLE
Website content getting cut out due to side menu.

### ISSUE THREAD

**Issue by Hetarth02** [themesberg/flowbite-svelte#181]
**Describe the bug**

The content on the website and documentation are getting cut off due to the side-menu, which leads to not being able to read some of the information in its entirety.

**To Reproduce**

1. Go to [Flowbite Svelte](https://flowbite-svelte.com/)

**Expected behavior**

The content should be properly visible in its entirety without getting cut off. If possible, instead of using the browser default scroll-bar one can implement a minimal custom design for scroll-bar.
A proper view should be like the image below,

![image](https://user-images.githubusercontent.com/80420115/180592189-8b59c537-a9b1-4ea9-a282-3a01148d3c43.png)
> Image taken from [TailwindCSS docs](https://tailwindcss.com/docs/installation)

**Screenshots**

![image](https://user-images.githubusercontent.com/80420115/180592014-d6f261cb-6a99-4a69-a7b1-4a481cd96146.png)
![image](https://user-images.githubusercontent.com/80420115/180592056-a54f9caf-e996-4bfe-960b-da17f917b00a.png)

**Desktop (please complete the following information):**

- Browser: Brave
- Version: [1.41.100 Chromium: 103.0.5060.134 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by shinokada** [comment]
Can you check it now please?
I just updated the paddings.
Let me know if it fixes your problem.

**Comment by shinokada** [comment]
https://github.com/themesberg/flowbite-svelte/pull/182

Thanks to @Hetarth02 for the PR.
I close the issue for now.
