### ISSUE TITLE
Can we get more events for textboxes?

### ISSUE THREAD

**Issue by ptrxyz** [themesberg/flowbite-svelte#193]
## Summary

I would like to see some more basic events for the input fields (the ones with floating label, as well as normal input). And maybe keeping them consistent would also be nice (as of now, normal inputs do only forward `on:change` while floating inputs do also forward `on:blur` events).

To be honest, I think those make sense for all components, but they are for sure useful for text inputs.

### Motivation

I am going to use this for validation and would love to have a bit more control over the events. :)

I suggest to add some basic events like those:

## Events

- A: on:change
- B: on:keyup
- C: on:keydown
- D: on:keypress
- E: on:focus
- F: on:blur
- G: on:click
- H: on:mouseover
- I: on:mouseenter
- J: on:mouseleave
- K: on:paste

## Components and Events

- [x] Input (A, B, C, D, E, F, G, H, I, J, K)
- [x] File input (A, B, C, D, E, F, G, H, I, J, K)
- [x] Floating label (A, B, C, D, E, F, G, H, I, J, K)
- [x] Search (A, B, C, D, E, F, G, H, I, J, K)
- [x] Textarea (A, B, C, D, E, F, G, H, I, J, K)
- [x] Checkbox (A, B, C, D, E, F, G, H, I, J)
- [x] Radio (A, B, C, D, E, F, G, H, I, J)
- [x] Toggle (A, G, H, I, J)
- [x] Range  (A, B, C, D, G, H, I, J)
- [x] Buttons (A, B, C, D, G, H, I, J)
- [x] ButtonGroupItem (A, B, C, D, G, H, I, J)
- [x] Pagination buttons (A, B, C, D, G, H, I, J)
- [x] Dropdown / DropdownItem (A, B, C, D, G, H, I, J)
- [x] Tabs (A, B, C, D, G, H, I, J)
- [x] Sidebar items (A, B, C, D, G, H, I, J)
- [x] Navbar items / NavLi (A, B, C, D, G, H, I, J)

**Comment by shinokada** [comment]
Sure we can add all event as you suggested.
It will be helpful if you can list which components need these event as well.

**Comment by jjagielka** [comment]
By all means it's a valid request. Framework should provide all supported events.

**Comment by shinokada** [comment]
Added the components relating to this issue.

1. I added a question mark and I'd like to know if we should add these components as well.
2. Are there more components we need to take care of? Please add these in the comments.

**Comment by ptrxyz** [comment]
The list looks good, maybe also consider

- Buttons, ButtonGroupItem, Pagination buttons 
- Dropdowns / DropdownItem
- Tabs
- Sidebar items
- Navbar items / NavLi

**Comment by ptrxyz** [comment]
Svelte is working on making it possible to spread event handlers similar to $$props onto components. Maybe that might make things easier.

Sadly no ETA though and the discussions/issue are two years old with little updates.

See https://github.com/sveltejs/svelte/pull/6876

**Comment by shinokada** [comment]
Thanks. I just updated your first comment by adding more components and related events.
What do you think about the list? My understanding is that you need `on:focus` and `on:blur` for input fields, and Toggle needs only `on:change`.
What do you think?

**Comment by shinokada** [comment]
Added to v0.23.2.
Please check it and let me know.

**Comment by shinokada** [comment]
I just completed adding events and updated the doc. 
<img width="809" alt="image" src="https://user-images.githubusercontent.com/147320/183035388-663be67f-59c7-4f95-8952-fef299c21058.png">
Please let me know if I need to add more.
I close the issue for now.
