### ISSUE TITLE
Missing Tooltips

### ISSUE THREAD

**Issue by marahmanjs** [themesberg/flowbite-svelte#2]
One of the cool features of flowbite was the [tooltips](https://flowbite.com/docs/components/tooltips/) and would love to see it here. 

- [x] Triggering
- [x] Styles
- [x] Placement
- [x] Animation
- [x] Disable arrow

**Comment by shinokada** [comment]
Yes, it's coming soon. I just started it today.

**Comment by shinokada** [comment]
I just added [Tooltips](https://flowbite-svelte.vercel.app/tooltips). Please have a look.
