### ISSUE TITLE
Tooltip style rendering `undefined` 

### ISSUE THREAD

**Issue by dennismphil** [themesberg/flowbite-svelte#200]
**Describe the bug**
The tooltip that is being rendered is returning `undefined` in the style

**To Reproduce**

1. Go to https://flowbite-svelte.com/tooltips
2. Inspect the arrow rendered by tooltip
3. Notice `style="left:58px;top:undefinedpx;bottom:-4px"`

**Screenshots**

![2022-08-02_00-34-46](https://user-images.githubusercontent.com/4141366/182318828-513f03c8-4945-4780-b443-388e7a72c866.png)

**Desktop (please complete the following information):**

- Browser [Chrome]
- Version [103]

**Comment by shinokada** [comment]
I just updated to v0.22.29.
Can you try it and let me know.
Thank you.

**Comment by shinokada** [comment]
https://github.com/themesberg/flowbite-svelte/pull/205
Please have a look at it and let us know.

**Comment by shinokada** [comment]
I close the issue for now.

**Comment by dennismphil** [comment]
Thanks for closing this. Sorry I missed the notification on this
