### ISSUE TITLE
[Feature] Add ability to customize default tooltip classes

### ISSUE THREAD

**Issue by dennismphil** [themesberg/flowbite-svelte#201]
## Summary

A brief explanation of the feature.

Can we please add the ability to customize the tooltip?

### Basic example

```svelte
<Tooltip
    content="tooltip text"

    <!-- proposal -->
    textClass="font-xs z-100"
    arrowClass="..."
    containerClass="..."
>
    <Button ... />
</Tooltip>
```

![](https://user-images.githubusercontent.com/4141366/182371638-dc26d343-d9fd-42e4-af7a-a53f14a8bb9d.png)

If the proposal involves a new or changed API, include a basic code example. Omit this section if it's not applicable.

### Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

The z-index of other absolute positioned elements in the application interferes with the default z-index given. By giving the flexibility to customize the class of the tooltip elements, we solve this problem. Also, this provides developers to customize the font size, color, and allow for custom styling

**Comment by shinokada** [comment]
Can you use `class` in the Tooltip component:

```
<script>
	import { Tooltip, Button } from 'flowbite-svelte';
</script>

<div class="p-24" >
  <Tooltip content="Tooltip content" class="text-red-700">
    <Button>Default tooltip</Button>
  </Tooltip>
</div>
```

- https://sveltejs-kit-template-default-o1upse--5173.local.webcontainer.io/tooltip
- https://stackblitz.com/edit/sveltejs-kit-template-default-o1upse?file=tailwind.config.cjs,src%2Froutes%2Faccordion.svelte,src%2Froutes%2F__layout.svelte,src%2Fapp.css,src%2Froutes%2Fdatepicker.svelte,src%2Froutes%2Ftooltip.svelte&terminal=dev

**Comment by dennismphil** [comment]
Thanks for the detailed demo on stackblitz.

Just wanted to point out the shortcomings of this. 

1. We cannot customize the padding of the tooltip
2. We cannot change the font size due to the conflicting classes

![2022-08-03_05-52-16](https://user-images.githubusercontent.com/4141366/182613097-e1fba828-9b05-4eba-b18e-b82a905fa9b6.png)
s

**Comment by shinokada** [comment]
I updated the Tooltip component, v0.22.30.
You can find the doc at https://flowbite-svelte.com/tooltips#Custom_style.
Let me know what you think.

**Comment by dennismphil** [comment]
This works like magic. Thank you.  
  
Only a minor nit in the documentation .. Would be perfect if `tipClass` and `tipColor` is listed in the documentation here as well 

![](https://user-images.githubusercontent.com/4141366/182663922-58baf682-8e4a-48ec-a83a-8c5369db1fe2.png)

  
  
![Many thanks](https://sdk.bitmoji.com/render/panel/15f269e9-79ff-42f5-b6f8-df81e1cb3847-27f3d64a-b3a3-43b8-a269-f9caa01ea0d8-v1.png?transparent=1&palette=1)

**Comment by shinokada** [comment]
Yes, I will update the props. Thanks.
