### ISSUE TITLE
Sidebar Item Click Event

### ISSUE THREAD

**Issue by jalbertozeta** [themesberg/flowbite-svelte#202]
## Summary
Brief explanation of the feature.
Other than href I think we need to support different events like onClick or onFocus event if ever we need to use it in React Project not just ordinary page redirection

### Basic example

If the proposal involves a new or changed API, include a basic code example. Omit this section if it's not applicable.

### Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?
This is very important in React App

**Comment by shinokada** [comment]
Please see https://github.com/themesberg/flowbite-svelte/issues/193.

**Comment by shinokada** [comment]
Added to v0.23.2.
Please check it and let me know.
