### ISSUE TITLE
SignInCard usage not well documented

### ISSUE THREAD

**Issue by JordanGibson** [themesberg/flowbite-svelte#203]
Thanks for taking the time to fill out this bug report!

**Describe the bug**
`SignInCard` usage is unclear and documentation is very vague in the `Card` page, with a missing page entirely in "see more" (empty page at https://flowbite-svelte.com/cards/signin). Usage on how we should get the information from the `SignInCard `is unclear, and I'm unsure myself how to do it. How do we get the `SignInCard` input inside the login event handler `AuthFunctionType` function?

**To Reproduce**

N/A

**Code samples**
```
<SignInCard
	{login}
	rememberMe
	signup={{ name: 'Create account', href: '/' }}
	lostPassword={{ name: 'Lost password', href: '/' }}
/>
```

**Expected behavior**
Documentation should include clear information on how to retrieve the information which the user types in to the `SignInCard` component, or otherwise notation should be included in the types themselves.

**Additional context**

**Comment by shinokada** [comment]
@jjagielka updated the doc and I just merged it. https://github.com/themesberg/flowbite-svelte/pull/204#issuecomment-1206142666
Please have a look at it and let us know.

**Comment by JordanGibson** [comment]
@shinokada @jjagielka looks good - thanks for updating!
