### ISSUE TITLE
[Feature] Card component

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite-svelte#206]
[Card](https://flowbite.com/docs/components/card/#card-with-nav-tabs)

- [x] Default card
- [x] Card with button
- [x] Card with link
- [x] Card with image
- [x] Horizontal card (need update)
- [x] User profile card
- [x] Card with form inputs
- [x] E-commerce card
- [x] Call to action card
- [ ] Card with nav tabs
- [ ] Card full width tabs
- [x] Card with list
- [x] Pricing card
- [x] Testimonial card
- [ ] Crypto card

**Comment by jjagielka** [comment]
> Horizontal card (need update)

What update is needed? I don't see the difference between Flowbite.com

**Comment by shinokada** [comment]
In a small screen the horizontal card has different image size:

Flowbite:
<img width="692" alt="image" src="https://user-images.githubusercontent.com/147320/183098835-d36ce8a8-8bd6-49ea-b3bb-ffecd16b7c9a.png">

Flowbite-svelte:
<img width="666" alt="image" src="https://user-images.githubusercontent.com/147320/183099012-fe0a6a1a-3380-4da4-a87d-fec7c12cc3ca.png">

**Comment by shinokada** [comment]
Updates:
- https://github.com/themesberg/flowbite-svelte/pull/204
- https://github.com/themesberg/flowbite-svelte/pull/210

Thanks to @jjagielka.

**Comment by dorisip** [comment]
@shinokada Hi, is it possible to override the colors on a Card component? I don't see a way to pass that in right now. Thanks

**Comment by shinokada** [comment]
@dorisip Can you try `class`?

```
<Card class="your-color">
...
```

**Comment by jjagielka** [comment]
`$$restProps` passing to underlying `Frame` was missed. PR created.

`Card` is based on the `Frame` component. You can use `color` property in the same manner as with `Alert`.

**Comment by shinokada** [comment]
@jjagielka We need put this info in the doc.
What do you think_

**Comment by jjagielka** [comment]
This is something extra beyond Flowbite.com. We profit from `Frame` inheritance.

I have added the `Frame` props at the `Card` docs. I think we need a proper docs page for the `Frame` component.

**Comment by shinokada** [comment]
We can add it under the UTILS section.

**Comment by dorisip** [comment]
Thanks. I'll wait for the PR to be merged.

**Comment by shinokada** [comment]
Merged.
