### ISSUE TITLE
<Select> - can't init selected option according to bind:value

### ISSUE THREAD

**Issue by kuchaguangjie** [themesberg/flowbite-svelte#211]
**Describe the bug**
`<Select bind:value>`, can't init selected option according to the binded value.

**Screenshots**

**Desktop (please complete the following information):**

- Browser [chrome]
- Version [104.0.5112.79 (Official Build) (64-bit)]

**Additional context**
Using flowbite-svelte `0.23.3`.

**Comment by shinokada** [comment]
Do you mean you want to add a initial selected option?

**Comment by kuchaguangjie** [comment]
I mean if I use <Select bind:value="{category}">, then when I change the variable `category` programmingly, the selected option should be changed too, but it's not, in my test.

For example, when edit a post, I will load the post from database first, and show current catetory according to the value from database, then user can decide change it or not.

**Comment by kuchaguangjie** [comment]
This can be done using raw html `<select>` tag, e.g:

```
    <select id="categoryId" bind:value={categoryIdStr} class="textInput">
      {#each Object.entries(postCategories) as [categoryId, categoryName]}
        <option value="{categoryId}">{categoryName}</option>
      {/each}
    </select>
```

**Comment by shinokada** [comment]
It seems you are asking Select with Dropdown, https://flowbite.com/docs/forms/select/#select-with-dropdown . We haven’t made it yet.

**Comment by kuchaguangjie** [comment]
I see, seems the <Select> is just a <select> without <option> now.
Then the [Select with Dropdown](https://flowbite.com/docs/forms/select/#select-with-dropdown)  would be an very common & useful component.

**Comment by shinokada** [comment]
Please have a look at [this example](https://flowbite-svelte.com/forms/select#Select_with_dropdown).

**Comment by kuchaguangjie** [comment]
Thanks, though that looks a bit complex. I'll use the pure html `<select>` for now. And might check again later.

**Comment by shinokada** [comment]
Please share your code here when you are done.
I close the issue for now.

**Comment by kuchaguangjie** [comment]
You mean the html `<select>` code? It's just this one: https://github.com/themesberg/flowbite-svelte/issues/211#issuecomment-1207200081
where:
- `postCategories` is an k/v object, .e.g: 
```
  const postCategories = {
    0: "-", 1: "General", 2: "News", 3: "Knowledge", 4: "Notification", 5: "Job",
  }
```
- `categoryIdStr` is just a variable, e.g:
```
  let categoryIdStr
```
