### ISSUE TITLE
[Feature] Popover

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite-svelte#213]
[Popover](https://flowbite.com/docs/components/popover/)

- [x] Default popover
- [x] User profile
- [x] Company profile
- [x] Image popover
- [x] Description popover
- [x] Progress popover
- [x] Password strength
- [x] Placement
- [x] Triggering
- [x] Offset
- [x] Animation
- [x] Disable arrow

**Comment by shinokada** [comment]
https://github.com/themesberg/flowbite-svelte/pull/253

**Comment by jjagielka** [comment]
I think Animation section is covered in the docs.
