### ISSUE TITLE
Multiple Modals On One Page

### ISSUE THREAD

**Issue by GWoodmansey** [themesberg/flowbite-svelte#215]
Hello Shinokada-san,

I’m developing engineering software that has a complicated interface. I’m using Svelte, Tailwinds, and Flowbite for the front end. I have some specific requirements for modals in my code. 

The first thing I need is multiple modals from a single page. The code I have now looks like this:

```
<script>
  import { Button } from "flowbite-svelte";
  import { Modal } from "flowbite-svelte";

  let open = false;
</script>

<h1>Welcome to SvelteKit – Modal Test</h1>
<br />

<Button on:click={() => (open = true)}>Special Modal Button</Button>
<Modal title="My Dialog" bind:open>
  <p class="text-base leading-relaxed text-gray-500 dark:text-gray-400">
    I created this dialog!
  </p>
  <svelte:fragment slot="footer">
    <Button>O.K.</Button>
  </svelte:fragment>
</Modal>

<br />
<br />

<Button on:click={() => (open = true)}>Default modal</Button>
<Modal title="Terms of Service" bind:open>
  <p class="text-base leading-relaxed text-gray-500 dark:text-gray-400">
    With less than a month ...
  <p class="text-base leading-relaxed text-gray-500 dark:text-gray-400">
    The European Union’s General Data Protection Regulation ...
  </p>
  <svelte:fragment slot="footer">
    <Button>I accept</Button>
    <Button color="alternative">Decline</Button>
  </svelte:fragment>
</Modal>
```

This works, with one exception. Both buttons show the same dialog box.

What I should have is two independent modals that can be fired independently from each other. I can not get this working. What do you recommend?

Next issue I have is being able to fire a modal from from JavaScript code. I need this for complicated error checking that can only be done when multiple formulas are checked.

If you could get that working, and make an example that would be great.

Passing the modal size to the modal in your most recent update is a great improvement. 

どうかよろしくお願いします。

Regards,

Gordon

P.S. I don’t speak Japanese well, but lived in Tokyo for three years!

**Comment by shinokada** [comment]
@jjagielka Can you check this issue?

Thanks Gordon-san. I hope you are enjoying Tokyo.

**Comment by jjagielka** [comment]
You have two modals bind to the same variable so they open at the same time. 
Define two separate variables for opening the modals. 

let open1 = false;
let open2 = false;

**Comment by shinokada** [comment]
@GWoodmansey Regarding the first question, you need to create different variables like this REPL.

https://svelte.dev/repl/75f620f24aea4a57ae07f9f860eb3149?version=3.49.0

```
<script>
  import { Button } from "flowbite-svelte";
  import { Modal } from "flowbite-svelte";

  let modal1 = false;
	 let modal2 = false;

</script>

<h1>Welcome to SvelteKit – Modal Test</h1>
<br />

<Button on:click={() => (modal1 = true)}>Special Modal Button</Button>
<Modal title="My Dialog" bind:open={modal1}>
  <p class="text-base leading-relaxed text-gray-500 dark:text-gray-400">
   Modal 1
  </p>
  <svelte:fragment slot="footer">
    <Button>O.K.</Button>
  </svelte:fragment>
</Modal>

<br />
<br />

<Button on:click={() => (modal2 = true)}>Default modal</Button>
<Modal title="Terms of Service" bind:open={modal2}>
  <p class="text-base leading-relaxed text-gray-500 dark:text-gray-400">
    Modal2
  <p class="text-base leading-relaxed text-gray-500 dark:text-gray-400">
    The European Union’s General Data Protection Regulation ...
  </p>
  <svelte:fragment slot="footer">
    <Button>I accept</Button>
    <Button color="alternative">Decline</Button>
  </svelte:fragment>
</Modal>
```

I will add Multiple modal in the doc.

**Comment by GWoodmansey** [comment]
Hello Shinokada,

I'll start with Tokyo. I'm not in Tokyo now and haven't been back for a decade. My recent travels have been messed up by Covid! I want to see my in-laws.

Your solution worked and is elegant and simple. I like it.

The part that escaped me was the binding in the modal title. I've just started learning Svelte, Tailwinds, and Flowbite. Expect more idiot questions!

Keep up the great work. 

Regards,

Gordon
