### ISSUE TITLE
Out of the box install, getting error: Cannot find module 'svelte-heros' imported from...

### ISSUE THREAD

**Issue by benshawuk** [themesberg/flowbite-svelte#221]
**Describe the bug**
Installation instructions followed, as per: 
https://flowbite-svelte.com/pages/getting-started

500
Cannot find module 'svelte-heros' imported from '/Users/benshaw/Documents/Coding/learn/sk/sveltekit-demo/node_modules/flowbite-svelte/accordions/AccordionItem.svelte'
Error: Cannot find module 'svelte-heros' imported from '/Users/benshaw/Documents/Coding/learn/sk/sveltekit-demo/node_modules/flowbite-svelte/accordions/AccordionItem.svelte'

**Edit/Update:**
Running **npm install svelte-heros** seems to resolve the issue..
Maybe this default was removed from the latest svelte-kit installer?

**To Reproduce**
Follow instructions, exactly as per:  https://flowbite-svelte.com/pages/getting-started

**Code samples**
Try to use any Flowbite-svelte components, e.g.:

<script>
	import { Button } from 'flowbite-svelte';
</script>

<Button>Default</Button>

**Expected behavior**
Components appear and are functional, no error message appears

**Screenshots**

**Desktop (please complete the following information):**

- Browser [safari]
- Version 15.5
- MacOS 12.4

**Comment by shinokada** [comment]
Thank you.
I added it to the getting-started page.

**Comment by benshawuk** [comment]
Thank you for the swift response!
You might also want to let the guys know over at Flowbite, for their instructions too:
https://flowbite.com/docs/getting-started/svelte/

**Comment by shinokada** [comment]
Yep. Thank you for the reminder.
