### ISSUE TITLE
DropdownItem on:click event fired twice

### ISSUE THREAD

**Issue by M4rk3tt0** [themesberg/flowbite-svelte#226]
Thanks for taking the time to fill out this bug report!

**Describe the bug**
The DropdownItem on:click event is fired twice when you click it.

**To Reproduce**
The same behaviour can be seen on the [Flowbite Svelte website](https://flowbite-svelte.com/dropdowns#Events)

**Code samples**
```
<script>
    import { Dropdown, DropdownItem } from "flowbite-svelte";

    function handleClick() {
        console.log("Clicked");
    }
</script>

<Dropdown label="Dropdown button" class="w-44">
    <DropdownItem on:click={handleClick}>Click me</DropdownItem>
</Dropdown>
```

**Expected behavior**
The event should be fired once.

**Desktop (please complete the following information):**

- Browser Brave
- Version 1.42.95

**Comment by shinokada** [comment]
Thanks. I will fix the bug.
