### ISSUE TITLE
Import only one component, load all components

### ISSUE THREAD

**Issue by NormandoHall** [themesberg/flowbite-svelte#227]
Happens with every component. Network devtools in chrome, shows are loaded all components (+6MBs).

![image](https://user-images.githubusercontent.com/2943127/185195910-d119db78-1e88-4c72-b1ae-7a0ff0ee4c82.png)

Installed as described here: https://flowbite-svelte.com/pages/getting-started

Thanks

## Reproducible code

`npm run dev`

**index.svelte**

```svelte
<script>
  import { Badge } from 'flowbite-svelte';
</script>

<div>
  <Badge>Default</Badge>
</div>
```

**package.json**

```json
  "devDependencies": {
    "@iconify/json": "^2.1.93",
    "@sveltejs/adapter-node": "^1.0.0-next.78",
    "@sveltejs/kit": "^1.0.0-next.405",
    "@svitejs/svelte-preprocess-svg": "^1.0.2",
    "@tailwindcss/forms": "^0.5.2",
    "@unocss/preset-icons": "^0.45.1",
    "autoprefixer": "^10.4.8",
    "eslint": "^8.22.0",
    "eslint-plugin-svelte3": "^4.0.0",
    "flowbite": "^1.5.2",
    "flowbite-svelte": "^0.24.19",
    "nodemon": "^2.0.19",
    "postcss": "^8.4.16",
    "svelte": "^3.49.0",
    "svelte-heros": "^2.3.3",
    "svelte-preprocess": "^4.10.7",
    "svelte2tsx": "^0.5.13",
    "svgo": "^2.8.0",
    "tailwindcss": "^3.1.8",
    "unocss": "^0.45.6",
    "vite": "^3.0.7"
  },
```
**tailwind.config.cjs**

```js
module.exports = {
  content : [
    './src/app.html',
    './src/**/*.{html,js,svelte,ts}',
    './node_modules/flowbite-svelte/**/*.{html,js,svelte,ts}'
  ],
  theme : {
    extend : {
      colors : {
        'dark-purple' : '#081A51',
        'light-white' : 'rgba(255, 255, 255, 0.18)'
      }
    }
  },
  plugins : [
    require('@tailwindcss/forms'),
    require('flowbite/plugin')
  ],
  darkMode    : 'class',
  corePlugins : {
    // preflight : false
  }
};
```

**Comment by shinokada** [comment]
If you click other pages, then it won't download it again. 
Download it once and serve it on a browser.
Otherwise you download files on every page.

**Comment by NormandoHall** [comment]
Thanks for the Reply @shinokada, but I think this not a good thing. I use only a badge in one page and load all the components. Maybe this can't be handle by design. Meanwhile I will copy all the individual components under $lib folder and use only those I require.

Thanks for this great library.

**Comment by NormandoHall** [comment]
Me bad. This happens only in dev mode. After running build, loaded only used components. Sorry
