### ISSUE TITLE
Checked property of Radio button does not work

### ISSUE THREAD

**Issue by glowww** [themesberg/flowbite-svelte#232]
**Describe the bug**
The `checked` property of the Radio button does not work, it always checks the last radio button.

**To Reproduce**
https://svelte.dev/repl/92119d54fed845ed90d4c33eee41b5d1?version=3.49.0

It's not working on the Demo page either, as you can see in the screenshot.
![Screenshot_127](https://user-images.githubusercontent.com/29709299/185645923-88d32810-6bd6-4f53-8451-aa316f8936dc.jpg)

**Comment by jjagielka** [comment]
Check the svelte documentation: https://svelte.dev/docs#template-syntax-element-directives-bind-group

Radio button management is via `group` property not `checked`.
`checked` is used for checkbuttons.

**Comment by nickolasgregory** [comment]
#236 did not fix this example  
https://github.com/themesberg/flowbite-svelte/blob/main/src/routes/docs/components/forms.md?plain=1#L211
