### ISSUE TITLE
error classnames does not provide an export named 'default'

### ISSUE THREAD

**Issue by maku** [themesberg/flowbite-svelte#237]
**Describe the bug**
After creating a "fresh" sveltekit app and installing flowbite-svelte according docs I get an error :

```
500
The requested module '/node_modules/.pnpm/classnames@2.3.1/node_modules/classnames/index.js?v=0a8fa69e' does not provide an export named 'default'
SyntaxError: The requested module '/node_modules/.pnpm/classnames@2.3.1/node_modules/classnames/index.js?v=0a8fa69e' does not provide an export named 'default'

```

**To Reproduce**

1. create a typescript based sveltekit app (pnpm create svelte@latest -> skeleton project, using typescript syntax)
2. Install flowbite svelte (as described in https://flowbite-svelte.com/pages/getting-started)
3. pnpm run dev

**Comment by shinokada** [comment]
Please run:
```
npm i -D classnames
```

**Comment by maku** [comment]
@shinokada I do not understand. I installed "classnames" already (of course).

**Comment by howesteve** [comment]
Same thing here. Actually ```classnames``` was already installed as a dependency. But even installing it explicitly, the error remains.

**Comment by maku** [comment]
After updating all dependencies to the latest versions it works

**Comment by TheRevenantStar** [comment]
I hate to resurrect issues, but this one does persist; I see it installed as a dependency of flowbite-svelte
```
devDependencies:
flowbite-svelte 0.27.11
└── classnames 2.3.2
```
Installing `classnames` as a top-level dependency does resolve it, but feels like there is something more going on, this breaks the entire point of defining dependencies in package.json
```
devDependencies:
classnames 2.3.2
flowbite-svelte 0.27.11
└── classnames 2.3.2
```

To be clear, I am using `pnpm`

**Comment by schmurfy** [comment]
I got this too on a fresh new sveltekit app.

**Comment by stevefan1999-personal** [comment]
@maku I've got the same problem in a new skeleton SvelteKit app too. Reopen?

**Comment by shinokada** [comment]
@stevefan1999-personal and @schmurfy : Can you tell us the output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit,flowbite-svelte,vite,rollup,webpack --binaries --browsers`?

**Comment by stevefan1999-personal** [comment]
@shinokada Sure
```
  System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 51.74 GB / 63.93 GB
  Binaries:
    Node: 18.12.1 - ~\AppData\Local\nvs\default\node.EXE
    npm: 8.19.2 - ~\AppData\Local\nvs\default\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (107.0.1418.42)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.544
    flowbite-svelte: ^0.27.14 => 0.27.14
    svelte: ^3.46.0 => 3.53.1
    vite: ^3.1.0 => 3.2.3
```

**Comment by shinokada** [comment]
And your package.json please.

**Comment by jjagielka** [comment]
Seem like no issue anymore.

**Comment by shinokada** [comment]
I close the issue for now. Thank you for reporting and supporting us.
Feel free to open a new issue when you need it.
