### ISSUE TITLE
The navigation on the Date Picker Web page

### ISSUE THREAD

**Issue by ImaniAN** [themesberg/flowbite-svelte#248]
Thanks for taking the time to fill out this bug report!

**Describe the bug**

**To Reproduce**

1. Go to 'https://flowbite-svelte.com/datepicker'
2. Click on 'Theme icon'
3. Scroll down to 'end of the page'
4. See error: (There is us no navigation to other pages)

**Expected behavior**
A clear view of buttons and links. (Theme icon above button link)
The left side Navigation on every other page. (Lack of page UI consistency)

**Screenshots**

**Desktop (please complete the following information):**

- Browser: chrome
- Version: 104.0.5112.102 (Official Build) (64-bit)

**Additional context**
Go to this [LINK](https://flowbite-svelte.com/datepicker)

**Comment by shinokada** [comment]
Can you tell me what is 2. Click on 'Theme icon' ?
If you can give me a screenshot, it will be helpful.

**Comment by ImaniAN** [comment]
![Screenshot (159)](https://user-images.githubusercontent.com/32896144/186750143-13bcb76a-f708-4e2b-ab71-f77f0005568e.png)

The icon to change to dark mode is above the GitHub link button...

I have highlighted the issue in red. The components are functional but I don't know if they should "look" like that

**Comment by shinokada** [comment]
Thanks. 

Datepicker uses flowbite datepicker.js and I have to create a different layout for the datepicker page. I could not add the left side navigation in this page.
This is an experimental component. I added a warning at the top of the page.

![image](https://user-images.githubusercontent.com/147320/187099187-b52b8ed9-3627-4eb8-a5f7-33608c711b47.png)
