### ISSUE TITLE
Inaccurate documentation / Svelte

### ISSUE THREAD

**Issue by ollydixon** [themesberg/flowbite-svelte#249]
Not sure where to log this one.

https://github.com/themesberg/flowbite/issues/252

**Comment by shinokada** [comment]
Thank for pointing out this.
It slipped into the main while I was still in development.
It is not done yet and let you know once it's done.
I just removed the page and the component from the main branch and issued a new version.
 
BTW, you can bring all issues here relating to Flowbite-Svelte.
Thanks again.
