### ISSUE TITLE
`id` for wrapped components

### ISSUE THREAD

**Issue by jjagielka** [themesberg/flowbite-svelte#266]
## Summary

Why do you add the `id` property to wrapped components like in `Typography`. What if I don't need to set the `id` in my project? I will keep on getting errors that `id` is not set. And what about other attributes like `value` and `type` if we talk about `<li>` tag?

```svelte
<script lang="ts">
  import classNames from 'classnames';

  export let id: string;
  export let icon: boolean = false;
  export let liClass: string = '';
  let classLi: string = classNames(liClass, icon && 'flex items-center', $$props.class);
</script>

<li {id} class={classLi}><slot /></li>
```
### Basic example

If we pass `$$restProps` user can add whatever `<li>` attributes he wants, including `id`. So the implementation should be:

```svelte
<script lang="ts">
  import classNames from 'classnames';

  export let icon: boolean = false;
  export let liClass: string = '';
  let classLi: string = classNames(liClass, icon && 'flex items-center', $$props.class);
</script>

<li {...$$restProps} class={classLi}><slot /></li>
```

**Comment by shinokada** [comment]
Thanks for pointing out. I will fix it for all typography components.
