### ISSUE TITLE
Toast Component Dosent Hide with visible prop binded

### ISSUE THREAD

**Issue by dotnethelp** [themesberg/flowbite-svelte#269]
### Describe the bug

When Visible Property is binded , none of close button or timeout dosent work and there is an error in console.
![Screenshot 2022-09-06 005832](https://user-images.githubusercontent.com/65740469/188509875-628e93c6-3a79-4e5f-9c2b-afab00259d40.jpg)

### Reproduction

I copy Pase Exactly Autohide example in [doc](https://flowbite-svelte.com/toast) 

### Flowbite version and System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 5.84 GB / 15.82 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.1.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 105.0.5195.53
    Edge: Spartan (44.22000.120.0), Chromium (105.0.1343.27)
    Internet Explorer: 11.0.22000.120
```

**Comment by shinokada** [comment]
@jjagielka Is this the same issue we talked about?
@dotnethelp What is your flowbite-svelte version? And also can you try one of [dropdown](https://flowbite-svelte.com/dropdown) examples and let us know if it works.

**Comment by dotnethelp** [comment]
"devDependencies": {
		"@sveltejs/adapter-auto": "next",
		"@sveltejs/kit": "next",
		"autoprefixer": "^10.4.8",
		"flowbite-svelte": "^0.26.8",
		"postcss": "^8.4.16",
		"prettier": "^2.6.2",
		"prettier-plugin-svelte": "^2.7.0",
		"svelte": "^3.44.0",
		"svelte-check": "^2.7.1",
		"svelte-preprocess": "^4.10.7",
		"tailwindcss": "^3.1.8",
		"tslib": "^2.3.1",
		"typescript": "^4.7.4",
		"vite": "^3.1.0-beta.1"
	},
and dropdown examples work

**Comment by jjagielka** [comment]
@dotnethelp - Fixed, please update and check again
