### ISSUE TITLE
In the component Select, the props "value" does not work

### ISSUE THREAD

**Issue by CrystalBallBe** [themesberg/flowbite-svelte#273]
### Describe the bug

In the component Select, the props `value` does not work when its type is `number`.
I guess the reason is that the type of the props `value` is `string | number`, but the type of the `value` which is a member of `SelectOptionType` is `string`.

### Reproduction

```svelte
<script lang="ts">
  import { Card, Select } from "flowbite-svelte";
  import type { SelectOptionType } from "flowbite-svelte/types";

  const items: SelectOptionType[] = [
    { name: "aaa", value: "0" },
    { name: "bbb", value: "1" },
    { name: "ccc", value: "2" },
  ];
</script>

<Card>
  type of <code>value" is "number"
  <Select {items} value={0} />
</Card>
<Card>
  type of "value" is "string"
  <Select {items} value={"0"} />
</Card>
```
![image](https://user-images.githubusercontent.com/38453357/188658223-5c53100d-143d-4fb5-a448-46f9c61862d0.png)

### Flowbite version and System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 21.18 GB / 24.46 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 17.9.0 - /usr/local/bin/node
    Yarn: 3.2.2 - ~/.yarn/bin/yarn
    npm: 8.18.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Firefox: 104.0.2
  npmPackages:
    svelte: ^3.44.0 => 3.49.0
```

**Comment by CrystalBallBe** [comment]
I don't know why `number` can be used in the props `value`.  I think the props `value` should allow only `string`.

**Comment by shinokada** [comment]
Yes, you are right. Since returned value from a select option is always string, it should have only string. 
I will update it in the next version.
Thank you for your contribution.
