### ISSUE TITLE
Iconinput does not support "color" property

### ISSUE THREAD

**Issue by howesteve** [themesberg/flowbite-svelte#277]
As the title says, \<Iconinput\> does not support the "color" property, as it \<Input\> peer does. I think it's a good idea to implement matching features among them both.

**Comment by jjagielka** [comment]
New version of Input added. No more IconInput. You can insert icon via slot and control its color.

**Comment by howesteve** [comment]
Best news in the week. Thanks!

**Comment by shinokada** [comment]
Thank you for your contribution.
I close the issue for now.
If you have a problem. please let us know.
