### ISSUE TITLE
tabs components

### ISSUE THREAD

**Issue by alisalehi93** [themesberg/flowbite-svelte#279]
### Describe the bug

hi in tabs components like TabHead customclasses dosent work.

### Reproduction

				<TabHead {tabStyle} {tabId} customUlClass='justify-center'>

</TabHead>

### Flowbite version and System Info

```shell
"flowbite-svelte": "^0.26.14",
```

**Comment by shinokada** [comment]
Can you add `tabStyle='custome'` and let me know.

**Comment by alisalehi93** [comment]
thanks now works
