### ISSUE TITLE
Plain svelte support (without sveltekit)

### ISSUE THREAD

**Issue by ohmree** [themesberg/flowbite-svelte#28]
```
Failed to resolve import "$app/stores" from "node_modules/.pnpm/flowbite-svelte@0.13.5/node_modules/flowbite-svelte/navbar/DropdownNavbar.svelte". Does the file exist?
Failed to resolve import "$app/stores" from "node_modules/.pnpm/flowbite-svelte@0.13.5/node_modules/flowbite-svelte/navbar/Navbar.svelte". Does the file exist?
```

It seems like `DropdownNavbar` and `Navbar` hard depend on sveltekit, I assume this is for the routing functionality.
Could they be made router-agnostic?
If not I think this package should at least peer-depend on sveltekit (but I'd really like to be able to use it without sveltekit - in my template [`sveltesse-webext`](https://github.com/ohmree/sveltesse-webext)).

**Comment by shinokada** [comment]
Yes, it's a good point.
I will see what I can do.

**Comment by shinokada** [comment]
I removed SvelteKit `$app/stores`, `page` and `session`.

Can you update it and let me know:

```
npm i -D flowbite-svelte@latest
```

**Comment by shinokada** [comment]
I close the issue for now. If you have any problem, let me know.
