### ISSUE TITLE
drawer is not found in flowbite

### ISSUE THREAD

**Issue by Kokoserver** [themesberg/flowbite-svelte#283]
### Describe the bug

i tried   import { Drawer, Button, CloseButton } from 'flowbite-svelte', but the Drawer is not found.

### Reproduction

https://github.com/Kokoserver/iwaju-new/blob/master/frontend/src/lib/components/BookModel.svelte

### Flowbite version and System Info

```shell
the flowbite i installed 
"flowbite": "^1.5.3",
"flowbite-svelte": "^0.26.3",
```

**Comment by shinokada** [comment]
Can you update it and let me know.

```
npm i -D flowbite-svelte@latest
```

**Comment by shinokada** [comment]
I close the issue for now.
Please feel free to create another issue if you have any problems.
Thank you for your contribution.
