### ISSUE TITLE
Tooltip: when placement is left or right, first char is not shown properly

### ISSUE THREAD

**Issue by kuchaguangjie** [themesberg/flowbite-svelte#287]
### Describe the bug

Screenshots for "**Delete**" at `left` and "**Edit**" at `right`:

![placement left](https://user-images.githubusercontent.com/4230959/190296870-f65629c9-969d-43a5-afb3-35b72f3f0103.jpg)
![placement right](https://user-images.githubusercontent.com/4230959/190296883-38f17340-35c1-4b66-b2d1-83b9106acb09.jpg)

### Reproduction

Icons:
```
<Trash variation="solid" class="pt-1 align-middle" id="delete-btn-{rowIdx}"/>
<BookOpen variation="solid" class="pt-1 align-middle" id="edit-btn-{rowIdx}"/>
```

Tooltips:
```
<Tooltip triggeredBy="[id^='delete-btn-']" placement="left">Delete</Tooltip>
<Tooltip triggeredBy="[id^='edit-btn-']" placement="right">Edit</Tooltip>
```

### Flowbite version and System Info

```shell
  System:
    OS: Linux 5.14 Linux Mint 20.1 (Ulyssa)
    CPU: (8) x64 Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
    Memory: 6.90 GB / 15.55 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
  npmPackages:
    flowbite-svelte: ^0.26.18 => 0.26.18 
    svelte: ^3.50.1 => 3.50.1
```

**Comment by shinokada** [comment]
@jjagielka

**Comment by jjagielka** [comment]
The letter is covered by the underlying tooltip arrow. 

@kuchaguangjie : Seems like you play with positioning classes `absolute`, `fixed`, `relative` of the parent element. Can you please send wider extract of your code - including the parents of the icons and the tooltips?

**Comment by kuchaguangjie** [comment]
It's just within a `<td>`, and parent div has tailwind css class `flex-col`.

Here is the code:
```
        <td class="align-middle flex">
          <div class="delete flex-col" on:click={()=>deleteConfirm(row[itemActionByProp])}>
            <Wrapper>
              <Trash variation="solid" class="pt-1 align-middle" id="delete-btn-{rowIdx}"/>
              <Tooltip placement="left">Delete</Tooltip>
            </Wrapper>
          </div>
          {#if enableEdit === true}
            <div class="edit flex-col ml-1" on:click={()=>editHandler(row[itemActionByProp])}>
              <Wrapper>
                <BookOpen variation="solid" class="pt-1 align-middle" id="edit-btn-{rowIdx}"/>
                <Tooltip placement="right">Edit</Tooltip>
              </Wrapper>
            </div>
          {/if}
        </td>
```

**Comment by jjagielka** [comment]
And what's in the `Wrapper`? Which classes are used there?

**Comment by kuchaguangjie** [comment]
There is no `Wrapper` before, I added that after switch to smui's Tooltip. You can ignore that part, I've edited the comment above.

**Comment by kuchaguangjie** [comment]
And, I think you can't prevent users from using position property, should focus on support various case instead.

**Comment by jjagielka** [comment]
So far I can't reproduce, so it was just a guess.

**Comment by jjagielka** [comment]
@kuchaguangjie : Are you able to build a working example at REPL?

**Comment by shinokada** [comment]
You can use [this REPL template](https://svelte.dev/repl/930d39fbd10b4e5b8581fb20d3a3192e?version=3.50.1).

**Comment by kuchaguangjie** [comment]
I can't login svelte REPL, not sure why, thus can't save code there.
Here is the full code of my .svelte file, which reproduce the error on my machine:
```
<script>
  import {onMount} from "svelte";
  import {BookOpen, Trash} from "svelte-heros-v2";
  import {Tooltip} from "flowbite-svelte";

  onMount(async () => {
    void 0
  })
</script>

<div id="pageWrapper" class="page-data">
  <table class="page-table">
    <thead>
    <tr>
      <th class="action-field">actions</th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td class="align-middle flex">
        <div class="delete flex-col">
          <Trash variation="solid" class="pt-1 align-middle" id="delete-btn-1"/>
          <Tooltip triggeredBy="#delete-btn-1" placement="left">Delete</Tooltip>
        </div>
        <div class="edit flex-col ml-1">
          <BookOpen variation="solid" class="pt-1 align-middle" id="edit-btn-1"/>
          <Tooltip triggeredBy="#edit-btn-1" placement="right">Edit</Tooltip>
        </div>
      </td>
    </tr>
    </tbody>
  </table>
</div>

<style>
  /* header */
  th {
    @apply text-black;
  }

  /* page table */
  .page-table :is(th, tr, td) {
    @apply p-2 text-center border-neutral-100;
    border-width: 1px;
  }

  .page-data tr:hover {
    @apply bg-green-100;
  }

</style>
```

You need tailwindcss.

**Comment by jjagielka** [comment]
@shinokada : In the provided REPL template, why do you link tailwindcss in the version 2?
`<link rel="stylesheet" href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css"/>`

We use `"tailwindcss": "^3.1.8",` in `flowbite-svelte` `package.json`

**Comment by jjagielka** [comment]
Managed to run your example at [REPL](https://svelte.dev/repl/8ac1744766144f768bfccfec11a18674?version=3.50.1)

Still don't see the issue. Can you verify that REPL?

**Comment by kuchaguangjie** [comment]
@jjagielka Your code also works in my local machine, it doesn't have the issue mentioned above.
The difference between our code is that I don't have:
```
<svelte:head>
  <link rel="stylesheet" href="https://unpkg.com/flowbite@1.5.2/dist/flowbite.min.css" />
</svelte:head>
```
Adding above code also fix my local issue.

But I don't see the [doc](https://flowbite-svelte.com/pages/getting-started) or github readme mention that part, is that needed ?

**Comment by kuchaguangjie** [comment]
There is actually another issue (which is the actual reason that caused me switched to smui's tooltip):
Sometimes the tooltip won't disappear after mouse is gone, it stays there even click mouse far away in the page.

Screenshot:
![won't disappear](https://user-images.githubusercontent.com/4230959/190378126-51f0ed9b-13b8-4786-849a-2b3fa86aefea.jpg)

**Comment by shinokada** [comment]
@jjagielka It is the highest version that unpkg.com provides.
@kuchaguangjie Yes, it is in the doc. You need to install TailwindCSS.
![image](https://user-images.githubusercontent.com/147320/190382226-ad8aee1d-6d86-435b-a442-c73612688a63.png)

**Comment by jjagielka** [comment]
@shinokada He mentions that there's no doc that **Flowbite** css must be added.

`<link rel="stylesheet" href="https://unpkg.com/flowbite@1.5.2/dist/flowbite.min.css" />`

**Comment by jjagielka** [comment]
@kuchaguangjie : Evidently there's a bug in current code that if you move the mouse over the tooltip content that prevent the hidding. 

PR with the fix already created.

**Comment by shinokada** [comment]
@jjagielka You only need `<link rel="stylesheet" href="https://unpkg.com/flowbite@1.5.2/dist/flowbite.min.css" />` for REPL.
I will test if REPL works without it.

In [the doc](https://flowbite-svelte.com/pages/getting-started), we add it in the tailwind.config.cjs.

![image](https://user-images.githubusercontent.com/147320/190393675-b60b7d64-8e74-4f7c-869f-18b73aa51df9.png)

**Comment by shinokada** [comment]
Regarding REPL, it seems you don't need flowbite. But I only tested with Alert, so I'm not sure with other components.

**Comment by jjagielka** [comment]
In the above created [REPL](https://svelte.dev/repl/8ac1744766144f768bfccfec11a18674?version=3.50.1), if you remove the line with flowbite css than tooltips don't have the arrows.

**Comment by kuchaguangjie** [comment]
> In [the doc](https://flowbite-svelte.com/pages/getting-started), we add it in the tailwind.config.cjs.
I already added flowbite in `tailwind.config.cjs` when having the bug, here is my `tailwind.config.cjs`, I didn't change it:
```
const config = {
  content: [
    "./src/**/*.{html,js,svelte,ts}",
    "./node_modules/flowbite-svelte/**/*.{html,js,svelte,ts}",
  ],

  theme: {
    extend: {},
  },

  plugins: [
    require('flowbite/plugin')
  ],
  darkMode: 'class',
};

module.exports = config;

```

So, according to above issue, it's not sufficent, at least for the bug mentioned above.

**Comment by shinokada** [comment]
@kuchaguangjie Updated. Please run `npm i -D flowbite-svelte@latest` and let us know.

**Comment by kuchaguangjie** [comment]
I've upgraded flowbite to `"flowbite-svelte": "^0.26.19"`, and tested the code from [repl](https://svelte.dev/repl/8ac1744766144f768bfccfec11a18674?version=3.50.1):
- I think the 2nd issue (tooltip won't disappear) is fixed now.
- But the 1st issue (arrow covered text?) remains, if I don't include `flowbite.min.css` in the .svelte file; but include the css file fixed it, as already described in https://github.com/themesberg/flowbite-svelte/issues/287#issuecomment-1247886606

**Comment by jjagielka** [comment]
`flowbite.css` is a necessary component of the Flowbite tools. It must be included either explicitly or by default in the properly done configuration.

**Comment by jjagielka** [comment]
> or by default in the properly done configuration.

That comment was to @shinokada We need to make sure that css is included by default.

**Comment by shinokada** [comment]
@jjagielka:
From @zoltanszogyenyi :  Here's the part where Flowbite has unique styles: https://github.com/themesberg/flowbite/blob/main/plugin.js. ... It does have a bit of CSS different from Tailwind CSS for the forms, tooltips, popovers, file inputs, generally elements that need pseudo styling
But it's best to use the plugin require only and build your own purged CSS.

And we have the following in the tailwind.config.cjs file:

```  
plugins: [
    require('flowbite/plugin')
  ],
```

**Comment by jjagielka** [comment]
It's not solving the problem. Check the https://flowbite-svelte.com/components/tooltip - placement section suffers the first char covering. The arrow in other tooltips is to short - wrong offset.
The `popover` section shows arrow to far away from the content.

Seems adding plugin is not enough.

**Comment by jjagielka** [comment]
OK. Downgrading `flowbite` from v1.5.3 to v1.5.2 solves the issue. All `Popover` based components work perfect.

Need to find out what v1.5.3 introduced to cause the problems.

**Comment by jjagielka** [comment]
From Flowbite.com changelog:
```md
### v1.5.3

- fix popover / tooltip styles

### v1.5.2

- add new Popover component
```

**Comment by shinokada** [comment]
@zoltanszogyenyi Do you know the changes?

**Comment by jjagielka** [comment]
I've found the issue and created the PR.

However, I need to state that I really don't like those changes in flowbite.com. They show not consistent approach to building components.

**Comment by shinokada** [comment]
@kuchaguangjie I just merged @jjagielka 's PR and updated the version. Can you confirm this solves your issue please?

**Comment by kuchaguangjie** [comment]
It looks like this now:

- ![left](https://user-images.githubusercontent.com/4230959/191007537-1be98afb-2100-452a-a020-8156aa7b4c9e.jpg)
- ![right](https://user-images.githubusercontent.com/4230959/191007545-7d5e4362-a407-4baf-ace8-cfd222f7457a.jpg)

I think you can consider it fixed.
