### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by luke-hagar-sp** [themesberg/flowbite-svelte#290]
### Describe the bug

Flowbite-Svelte site is giving a 400 Error

![Screen Shot 2022-09-15 at 7 40 25 AM](https://user-images.githubusercontent.com/98849695/190406221-cc176523-4abd-4d30-92ea-00ee5fe9c92b.png)
![Screen Shot 2022-09-15 at 7 40 14 AM](https://user-images.githubusercontent.com/98849695/190406227-b1c6a9b2-20f2-484b-a8e2-c63eccc7739d.png)

### Reproduction

Navigate to https://flowbite-svelte.com

### Flowbite version and System Info

```shell
Not relevant
```

**Comment by shinokada** [comment]
Yes, I know. I just sent a support request to Vercel.

**Comment by luke-hagar-sp** [comment]
I'm using a preview build ATM just to view the site as needed

Link for anyone else: https://flowbite-svelte-update-git-fork-jjagielka-tooltip-themesberg.vercel.app

**Comment by luke-hagar-sp** [comment]
@shinokada Roger that

**Comment by shinokada** [comment]
Fixed.
