### ISSUE TITLE
<SidebarDropdownWrapper>: 1. arrow not change on open/close; 2. when isOpen='false', it's still open.

### ISSUE THREAD

**Issue by kuchaguangjie** [themesberg/flowbite-svelte#302]
### Describe the bug

1. The arrow on `SidebarDropdownWrapper` doesn't change when open or close the drop-down list:
  ![arrow](https://user-images.githubusercontent.com/4230959/191001460-1bb4400a-0f28-4082-ae66-03745f76d91b.jpg)
2. When set `isOpen="false"` on `<SidebarDropdownWrapper>`, it will still open; removing the `isOpen` property then it will close.

### Reproduction

1. open / close a `<SidebarDropdownWrapper>`.
2. set `isOpen="false"` on `<SidebarDropdownWrapper>`

### Flowbite version and System Info

```shell
System:
    OS: Linux 5.14 Linux Mint 20.1 (Ulyssa)
    CPU: (8) x64 Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
    Memory: 10.27 GB / 15.55 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.484 
    flowbite-svelte: ^0.26.25 => 0.26.25 
    svelte: ^3.50.1 => 3.50.1 
    vite: ^3.1.2 => 3.1.2 
```
```

**Comment by shinokada** [comment]
Can you try `isOpen={false}`?

**Comment by kuchaguangjie** [comment]
1. is fixed.
2. `isOpen={false}` works, but a string can be parsed as bool via `JSON.parse("false")`, frameworks may choose to support this.

**Comment by shinokada** [comment]
2. Please read the examples in [Svelte doc](https://svelte.dev/docs#template-syntax-svelte-options).
It is a convention to use `{false}`.
