### ISSUE TITLE
README.md update needed

### ISSUE THREAD

**Issue by jjagielka** [themesberg/flowbite-svelte#307]
### Describe the bug

README.md is outdated. Few components are missing there, like Popover, Label, Toolbar.

### Reproduction

- Visit https://github.com/themesberg/flowbite-svelte
- Scroll down to see the table of titles

### Flowbite version and System Info

```shell
N/A
```

**Comment by shinokada** [comment]
I will update it. But I don't think Flowbite has Label and Toolbar svg files.

**Comment by shinokada** [comment]
I will add the followings:

- Drawer
- Mega-menu
- Popover
- Video
- Heading
- Paragraph
- Blockquote
- Image
- List
- Link
- Text
- Horizontal line (HR)
