### ISSUE TITLE
Carousel swipe function

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite-svelte#31]
Carousel component need to add swipe function.

[This](https://tailwindcss.com/docs/touch-action) may be usefull.

**Comment by NibeluR** [comment]
still no progress on this? lmao

**Comment by shinokada** [comment]
I close the issue for now since we have added the swipe function.
Thank you for your contribution.
Please feel free to open a new issue when you are clear about the problem.

**Comment by teknosains** [comment]
> I close the issue for now since we have added the swipe function. Thank you for your contribution. Please feel free to open a new issue when you are clear about the problem.

Hi, what the props for swipe functionality? I couldnt find it on the Docs

**Comment by shinokada** [comment]
[Doc](https://flowbite-svelte.com/docs/components/carousel#Component_data)
