### ISSUE TITLE
Toggling modal causes layout shift

### ISSUE THREAD

**Issue by konstantinblaesi** [themesberg/flowbite-svelte#311]
### Describe the bug

> body.style.overflow = 'hidden';

Causes a layout shift, [see Modal.svelte](https://github.com/themesberg/flowbite-svelte/blob/main/src/lib/modals/Modal.svelte#L65) as the vertical scrollbar hides/shows when toggling the modal

### Reproduction

https://svelte.dev/repl/5df2a86df91c4b4d8a5829c9c5cf2e35?version=3.50.1

### Flowbite version and System Info

```shell
Latest from https://flowbite-svelte.com/components/modal or REPL
```

**Comment by jjagielka** [comment]
Why is that bug? Modal is full screen and does not require scrolling.

**Comment by konstantinblaesi** [comment]
Maybe not but personally I like the variant that doesn't jump around see https://flowbite-svelte.com/components/modal vs https://www.patternfly.org/v4/components/modal/
Doesn't it make sense that the scrollbar is part of the greyed out background and prevents layout from shifting by keeping it?

**Comment by jjagielka** [comment]
Removing the line `body.style.overflow = 'hidden'` will keep the scrollbar (if present) and will keep the possibility of scrolling the main content in the background of the modal, which would quite confusing for the user.

**Comment by konstantinblaesi** [comment]
Right that wouldn't work, but the linked patternfly example seems to have found some [solution in this variant](https://www.patternfly.org/v4/components/modal/#with-overflowing-content) which I found quite elegant.
The background doesn't change visually including the scrollbar, but only the modal body scrolls and has it's own scrollbar.

**Comment by jjagielka** [comment]
Those are two different cases:
- scrolling within modal if its content is too big - scrollbar attached to modal
- blocking the scrolling of the document body while not hiding the scrollbar - scrollbar attached to main document

The first one is quite straight forward and I can add it quickly. The second case it a bit tricky, at least it seems like it.

**Comment by shinokada** [comment]
@konstantinblaesi 
>  ... the scrollbar stays part of the greyed out background and prevents layout from shifting by keeping it?

I'm not sure what this means. Can you add an image to clarify?

@jjagielka 
>  the scrollbar stays part of the greyed out background and prevents layout from shifting by keeping it?

Are you talking when the modal content is large so that users need to scroll within the modal?

**Comment by konstantinblaesi** [comment]
@shinokada high level the problem is
* main page content
  * centered
  * scrollbar visible because content height > viewport height

Now we open the modal which in the case of flowbite-svelte
* hides the main content scrollbar using `body.style.overflow = 'hidden';` and thus changes the main contents width
* as a consequence the centered items of the main page jump to the right by the amount of pixels previously taken by the scrollbar
Apparently css `calc(100vw - 100%)` can give us the scrollbar width which some apply as padding, but I am not sure this is the right or succesful direction to go

Another library doesn't have this issue, but as as @jjagielka said it seems tricky and I am still searching a solution myself

If you want to see what I mean visually just open/close the modal and see the centered content
* jumping to the right https://flowbite-svelte.com/components/modal
* no jumping, it's staying in it's place https://www.patternfly.org/v4/components/modal/#with-overflowing-content

**Comment by jjagielka** [comment]
I have uploaded the PR to manage the internal scrolling in the modal (case 1)

As for the document body scrollbars I stay tuned for the proposal of the solution.

**Comment by jjagielka** [comment]
OK. I think I got that. PR updated with the background scrolling blocked.

In the `modal.md` docs I have added the section at the end to test that scrolling. Please test and let me know if that closes #311

**Comment by giray123** [comment]
Patternfly uses grid to place the main content. So the `body` actually is not overflowing the viewport, this is why it does not jump and you can not scroll the main content. (You can remove `overflow: hidden` on body and see that it does not scroll anyways.)

The way to do this AFAIK is to put a `padding-right` to the body when you place `overflow:hidden`. Padding-right should be the same width with the scroll bar width. Unfortunately, browsers put different-width scroll bars, so this feature also requires a custom designed scrollbar in which you explicitly set the scroll bar width.

If there is any other way than this that anybody knows, I would like to know as well.

**Comment by shinokada** [comment]
@konstantinblaesi Thanks for your explanation in details. Which operating system are you using? Can you paste the output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit,flowbite-svelte,vite,rollup,webpack --binaries --browsers`?
I'm using Mac and I don't see the same problem.

**Comment by konstantinblaesi** [comment]
@giray123 apparently grid is not needed. The trick is to put the scroll behavior on a container that is not the body because you cannot overlay the scrollbar of the body using position fixed / absolute elements. So one approach could look like this
* body(overflow: hidden)
  * main(height: 100vh; overflow: auto): we force the scrollbar here
    * div.some-big-child(e.g. fake with height: 200vh): this child is causing the main container to overflow
  * div#modal(position: fixed, ...): this can overlay the scrollbar of the main container

@shinokada I am on windows and the centered elements shift to the right because opening the modal hides the scrollbar, causing containers to expand and their centered children to shift to the right.

Compare the default behavior of flowbite-svelte

* modal closed: centered blue box is 411px from the left
![image](https://user-images.githubusercontent.com/5871169/191944829-4bc3dad0-0c44-4ccd-a3b5-a3172538c70c.png)
* modal open: centered blue box is 403px from the left
![image](https://user-images.githubusercontent.com/5871169/191944947-3de96bb6-9858-4767-a02d-0128aebe5b2f.png)

The centered and measured blue box shifts `411px - 403px = 8px` to the right because the wrapper width changes.

Now when you enable the fix you do not get this layout shift

modal  closed: centered blue box is 403px from the left
![image](https://user-images.githubusercontent.com/5871169/191945539-9acdad35-843d-4a23-9f1b-b587f3b228a8.png)
modal open: centered blue box is still 403px from the left
![image](https://user-images.githubusercontent.com/5871169/191945665-81cc816c-f9b5-47ec-9a78-0670dd98feff.png)

[I modified the REPL ](https://svelte.dev/repl/5df2a86df91c4b4d8a5829c9c5cf2e35?version=3.50.1) and hacked the workarounds into it just to demonstrate the idea

**Comment by konstantinblaesi** [comment]
@shinokada A colleague tested the scrollbar beahvior for me on mac using safari. Mac doesn't have this behavior because it's a system wide setting, but you can change this to always to get the windows behavior:
![image](https://user-images.githubusercontent.com/5871169/191949158-1f7bbe98-96cf-45b4-8bb5-519cfde77dc2.png)

**Comment by jjagielka** [comment]
@konstantinblaesi - I have uploaded the PR yesterday with exactly the same trick you described above. Can you please check it?
It's sill has some positioning problem (not fully center) but it's functional.

Link for the preview: https://flowbite-svelte-git-fork-jjagielka-modal-themesberg.vercel.app/

**Comment by konstantinblaesi** [comment]
@jjagielka I see no layout shifts, looks great thanks!

**Comment by jjagielka** [comment]
@konstantinblaesi At the bottom of the docs page, there's a big scrolling test. Can you please check it's behavior as well?

**Comment by konstantinblaesi** [comment]
@jjagielka works as expected for me, visually it could maybe use some top/bottom padding? 
![image](https://user-images.githubusercontent.com/5871169/191961322-f25b4488-cb81-4f20-8c6a-102e2df1f2c0.png)

**Comment by konstantinblaesi** [comment]
LGTM thanks! Offtopic, I just discovered the [dialog HTML element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog), is it worth using it if IE11 support is not a goal?

**Comment by jjagielka** [comment]
Yes, we were contemplating the use of `dialog` sometime ago, but without much progress.
Flowbite.com does not use it yet, so maybe it's too early. 

I will do some further testing of it during the weekend.

**Comment by shinokada** [comment]
@konstantinblaesi Do you get the same problem with the plain HTML/CSS from https://flowbite.com/docs/components/modal/?

**Comment by shinokada** [comment]
I just suggested about the `dialog` element in the [Flowbite issue](https://github.com/themesberg/flowbite/issues/292).

**Comment by shinokada** [comment]
I close the issue for now.
Thanks guys for your contribution.
