### ISSUE TITLE
Forward events in InputEvent like in regular Input

### ISSUE THREAD

**Issue by maku** [themesberg/flowbite-svelte#316]
IconInput should forward events like Input (on:blur, on:change, etc)

Also I would suggest to forward **on:input** also for Input component which is currently not the case

**Comment by giray123** [comment]
same as #312

**Comment by maku** [comment]
> 

yeah I saw the issue but it mentions only 1 event.  So to be "sure" I created another issue....

**Comment by shinokada** [comment]
Please update it to the latest version and let me know.

**Comment by maku** [comment]
@shinokada Great, works perfectly, thank you
