### ISSUE TITLE
Dropdown 

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite-svelte#32]
[Flowbite Dropdown](https://flowbite.com/docs/components/dropdowns/)
[Flowbite-Svelte Dropdown](https://flowbite-svelte.vercel.app/dropdowns/default)

- [x] Default
- [x] Divider
- [x] Header
- [x] Dropdown navbar
- [x] Sizing
- [x] Icon/img + dropdown
- [ ] Placement top
- [ ] Placement right
- [ ] Placement bottom
- [ ] Placement left
- [ ] Placement left start
- [ ] Placement right start
- [ ] Update Icon/img+dropdown by closing a dropdown by clicking the body and close another dropdown when you click another dropdown. The default dropdown has this functions already.
- [ ] Mouseover action to open a dropdown.

**Comment by jakubdonovan** [comment]
> [Dropdown](https://flowbite.com/docs/components/dropdowns/)
> 
>     * [x]  Default
> 
>     * [x]  Divider
> 
>     * [x]  Header
> 
>     * [x]  Dropdown navbar
> 
>     * [x]  Sizing
> 
>     * [ ]  Placement top
> 
>     * [ ]  Placement right
> 
>     * [ ]  Placement bottom
> 
>     * [ ]  Placement left
> 
>     * [ ]  Placement left start
> 
>     * [ ]  Placement right start

BUG: Dropdown does not close on click outside both on the default dropdown nor dropdown image

**Comment by shinokada** [comment]
I was thinking about it while I was creating the [ImgDropdown component](https://flowbite-svelte.vercel.app/dropdowns/image). The hesitation I had was conflict with other (modal) components and sidebar menu etc. I will find the best way.
Thank you for the suggestion.

**Comment by jakubdonovan** [comment]
> I was thinking about it while I was creating the [ImgDropdown component](https://flowbite-svelte.vercel.app/dropdowns/image). The hesitation I had was conflict with other (modal) components and sidebar menu etc. I will find the best way. Thank you for the suggestion.

Not if you add the event listener on dropdown (menu) mount and remove it on destroy

**Comment by shinokada** [comment]
Yes, that's right. 
I did that in [Svelte-sidebar](https://github.com/shinokada/svelte-sidebar/blob/main/src/lib/components/Hamburger.svelte#L27).

**Comment by shinokada** [comment]
The new version can:

- handle multiple dropdowns. If one is open Dropdown-1 and when you click Dropdown-2, the Dropdown-1 will close and Dropdown-2 opens. For this, I have to use Svelte/Store to keep the active dropdown id.
- close a dropdown by clicking the body. I have to use `z-50` on buttons, otherwise it doesn't work the #1.

The future version needs:

- to change the dropdown position depends on the button position using [`svelte:window`](https://svelte.dev/docs#template-syntax-svelte-window) to find the position.
- to add svelte transition (this should be easy one).

So please wait for v0.14.4.

**Comment by shinokada** [comment]
Moved to https://github.com/themesberg/flowbite-svelte/issues/144 and completed.
