### ISSUE TITLE
Can't end up with only required JS in Svelte project

### ISSUE THREAD

**Issue by cayolblake** [themesberg/flowbite-svelte#324]
### Describe the bug

1. I include any component from flowbite-svelte similar to what the docs mentions.
2. I end up with including JavaScript code that's not used by the component I'm using.
3. Everything possible related to remove dead/unused code has been utilized, with no luck (primarily uglify/terser).
4. There's a high possibility that the JavaScript being include is written in a way that allows for proper static analysis to spot if its needed or not.

### Reproduction

1. Create an empty Svelte project.
2. Include any flow bite-svelte component.
3. do `npm run build`
4. Observe a humongous build JS file.
5. Examine the file to find out its mostly flowbite-svelte code.

### Flowbite version and System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 380.29 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  npmPackages:
    flowbite-svelte: ^0.27.1 => 0.27.1
    svelte: ^3.49.0 => 3.50.1
    vite: ^3.1.0 => 3.1.3
```

**Comment by shinokada** [comment]
Are you checking `.svelte-kit` folder?
Where did you find unnecessary files?

**Comment by shinokada** [comment]
I close the issue for now.
Please feel free to open a new issue.
