### ISSUE TITLE
Input components should expose raw input element

### ISSUE THREAD

**Issue by maku** [themesberg/flowbite-svelte#328]
When using the Input components (Input, IconInput...) it is sometimes necessary to access the underlying input html element (e.g. for reset then input value programatically).

So I think it would be a good idea to provide an easy way for component users to get the reference....

**Comment by jjagielka** [comment]
@maku - with the latest changes you can do that. See the [Advanced usage](https://flowbite-svelte.com/forms/input-field#Advanced_usage) in the `Input` docs.

**Comment by maku** [comment]
@jjagielka thank you, I thought of a different approach, but of course you can achieve something similar this way...
