### ISSUE TITLE
Docs Sidemenu Scrolls Top at every navigation

### ISSUE THREAD

**Issue by giray123** [themesberg/flowbite-svelte#334]
### Describe the bug

This is not about the library but the documentation site [https://flowbite-svelte.com/](https://flowbite-svelte.com/)

Everytime a page is navigated, the sidebar on the left (that has all the components) scrolls to top. This makes browsing the site very difficult. I do not know if you are using Sveltekit under the hood, but this sidemenu should not be rendered on every page navigation and lie on the +layout.svelte (in case of Sveltekit).

Note: I also would like a search functionality but I ll create another feature request for that.

### Reproduction

https://flowbite-svelte.com

### Flowbite version and System Info

```shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 467.34 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.asdf/installs/nodejs/16.13.0/bin/node
    Yarn: 1.22.17 - ~/.asdf/shims/yarn
    npm: 8.1.0 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 105.0.5195.125
    Firefox: 104.0.1
    Safari: 16.0
  npmPackages:
    svelte: ^3.46.6 => 3.46.6
```

**Comment by shinokada** [comment]
For a new layout, this problem should not be happening.
I close the issue and thank you for your contribution.
