### ISSUE TITLE
<AccordionItem> - Customize header height

### ISSUE THREAD

**Issue by kuchaguangjie** [themesberg/flowbite-svelte#339]
The height of header slot of `<AccordionItem>` is pretty large, user might want to reduce its height.

Here is what I did to customize the height:
```
          :global(#currentFiltersWrapper h2, #currentFiltersWrapper h2 button ) {
            height: 20px;
            @apply mb-2;
          }
```

Maybe `header-height` and `header-margin-bottom` could be an option in the component? (the names are just examples)

**Comment by jjagielka** [comment]
New version of `Accordion` and `AccordionItem` implemented.

You can take look at the `Color option` section in `Accordion` docs how to customize items.
You can as well drop directly to `AccordionItem` the `class` prop.

```svelte example hideScript
<script>
  import {AccordionItem, Accordion} from 'flowbite-svelte'
</script>

<Accordion
  activeClasses="bg-blue-100 dark:bg-gray-800 text-blue-600 dark:text-white focus:ring-4 focus:ring-blue-200 dark:focus:ring-blue-800"
  inactiveClasses="text-gray-500 dark:text-gray-400 hover:bg-blue-100 dark:hover:bg-gray-800">
  <AccordionItem class="!py-2">
    <span slot="header">Header 2-1</span>
    <p class="mb-2 text-gray-500 dark:text-gray-400">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo ab necessitatibus sint explicabo ...</p>
  </AccordionItem>
  <AccordionItem class="!py-2">
    <span slot="header">Header 2-2</span>
    <p class="mb-2 text-gray-500 dark:text-gray-400">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo ab necessitatibus sint explicabo ...</p>
  </AccordionItem>
</Accordion>
```

**Comment by kuchaguangjie** [comment]
I suppose the new version has no tag yet ?

**Comment by shinokada** [comment]
I just publshed v0.27.5.

**Comment by kuchaguangjie** [comment]
Now, add `class` on `<AccordionItem>` can adjust header style, event without the `!` from tailwind.
e.g
`<AccordionItem id="1" open={false} color class="py-2">`
