### ISSUE TITLE
<Input type="number"> returns a string

### ISSUE THREAD

**Issue by risalfajar** [themesberg/flowbite-svelte#344]
### Describe the bug

Input type number should return a `number` instead of a `string`.
I suspect this is because in Input.svelte.d.ts:

```typescript
value?: string | undefined;
```

`value` is only either a string or an undefined.

### Reproduction

[REPL](https://svelte.dev/repl/2302dbebc6054ef8b5c21c29e78f1522?version=3.50.1)

### Flowbite version and System Info

```shell
System:
    OS: Linux 5.19 Pop!_OS 22.04 LTS
    CPU: (12) x64 AMD Ryzen 5 PRO 4650G with Radeon Graphics
    Memory: 11.71 GB / 27.30 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Brave Browser: 106.1.44.101
    Firefox: 105.0.1
  npmPackages:
    flowbite-svelte: ^0.27.4 => 0.27.4 
    svelte: ^3.50.1 => 3.50.1 
    vite: ^3.1.4 => 3.1.4
```

**Comment by shinokada** [comment]
All values returned from input tag is always string.

**Comment by risalfajar** [comment]
@shinokada it doesn't, after I changed the value once, it becomes a string

**Comment by risalfajar** [comment]
I discovered that if I remove `use:setType` and hard-code the `type=number`, it works.

[REPL](https://svelte.dev/repl/0ae74cc3911f44c78324a002fb502829?version=3.50.1)

**Comment by jjagielka** [comment]
I have uploaded PR #351 
Check the docs `forms/input` section `Advanced usage`. http://localhost:8080/forms/input-field#Advanced_usage

What do you think?

**Comment by risalfajar** [comment]
@jjagielka only the second input works, but maybe there's a cleaner way:
Why not make a separate component for it like `NumberInput.svelte` which hardcode the `type=number`, so it will always return a number. It also have the same props like in `Input.svelte`.

What do you think?

**Comment by jjagielka** [comment]
> only the second input works

Of course. Those two examples are to compare the behavior.

> Why not make a separate component for it like `NumberInput.svelte`

Then we would need yet another for `RangeInput`, `DateInput`, etc.

**Comment by risalfajar** [comment]
@jjagielka Input with type=date works fine, no need to make its own component.

Another solution is to convert the value to `number` inside the `Input` component, if type=number or type=range.

**Comment by shinokada** [comment]
As far as I remember all returned value from input field is string. 
User should convert it to appropreate type after submit. e.g. `parseInt()`.

**Comment by risalfajar** [comment]
> As far as I remember all returned value from input field is string. User should convert it to appropreate type after submit. e.g. `parseInt()`.

Actually that is not the case for Svelte, it have built-in parsing as you can see [here](https://svelte.dev/tutorial/numeric-inputs)

**Comment by risalfajar** [comment]
I've created a custom component by extending `Input.svelte`, for input that returns `number`.

[REPL](https://svelte.dev/repl/a871d50bd50a41a0b0277bcd7806e3b3?version=3.50.1)

What do you think?

**Comment by jjagielka** [comment]
OK. `Range` is covered as a separate component, so we don't need to handle it.

I've extended your [REPL](https://svelte.dev/repl/f0c220d76e2b427cb92bf702f9203ace?version=3.50.1) by `Number2Input` implemented as shown in `Advanced usage`. With that you don't need to make number conversion as that is handled by svelte.

**Comment by jjagielka** [comment]
Of course it should!

But it won't work as REPL does not use the latest Input version with the default slot added.

**Comment by risalfajar** [comment]
Ok so it'll work on a real project right?

Well I think that solution is great.

**Comment by jjagielka** [comment]
That solution is yet only a PR not merged to the main yet. 

You'll need to wait a while.

**Comment by risalfajar** [comment]
That's okay, I can use manual parsing for the time being, thanks!

**Comment by jjagielka** [comment]
@risalfajar - can we close that issue

Working example [REPL](https://svelte.dev/repl/f0c220d76e2b427cb92bf702f9203ace?version=3.50.1)

**Comment by risalfajar** [comment]
Feel free to close the issue.
I haven't closed the issue since the fix hasn't been up.

**Comment by risalfajar** [comment]
@jjagielka Hello, I've tried the new `NumberInput.svelte`

The number type works fine, but I think you forgot to add `{...$$restProps}` since I can't pass any props except `value` into it.
