### ISSUE TITLE
Ability to define whether modal should be full height on smaller widths/mobile

### ISSUE THREAD

**Issue by dmf3030** [themesberg/flowbite-svelte#346]
Currently modals will move to full height when on small screens or mobile.  This appears to come from this line in the modal.svelte

<div class="flex p-4 w-full {sizes[size]} h-full md:h-auto max-h-screen">

where h-auto is limited to md and above screen widths.  Im not sure if this is a bug or not, could be the authors preference but it feels a bit like a bug to me and certainly not what I would want for the modals.  I would prefer the modals stay at h-auto throughout the screen widths.  

Maybe we can have the option for h-full vs. h-auto?

**Comment by jjagielka** [comment]
That design is taken directly from Flowbite.com. All modals have the line like:
```html
<div class="relative p-4 w-full max-w-2xl h-full md:h-auto">
```
You should then issue that problem as a bug in Flowbite.com
https://github.com/themesberg/flowbite/issues

**Comment by shinokada** [comment]
I think there is the same concern in flowbite discord.
Please create an issue at Flowbite.
