### ISSUE TITLE
Card with list breaks on mobile

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite-svelte#357]
### Describe the bug

On the doc, the example on mobile breaks by pricings are out of the card container.

### Reproduction

See the doc.

### Flowbite version and System Info

```shell
Android mobile.
```

**Comment by jjagielka** [comment]
I can't see that. Can you please attache the screen shot?
![image](https://user-images.githubusercontent.com/6282254/193868167-f3c332b7-0219-423a-a9d9-7a4344bf8372.png)

**Comment by shinokada** [comment]
This is what I see after [the patch #358](https://github.com/themesberg/flowbite-svelte/pull/358)

![img3](https://user-images.githubusercontent.com/147320/193923568-9a651734-3aea-43c5-9ca2-193cceee3cf3.png)

**Comment by shinokada** [comment]
Also padding is different with ecommerce card.

![Screenshot_20221005-105723.png](https://user-images.githubusercontent.com/147320/193963238-86e8d077-ea82-4e0b-bbd2-5b4c28934df8.png)

**Comment by jjagielka** [comment]
Should that still be open?

**Comment by shinokada** [comment]
Thanks. Fixed.
