### ISSUE TITLE
The padding for large input needs to be 4

### ISSUE THREAD

**Issue by dennismphil** [themesberg/flowbite-svelte#36]
The padding for the large input needs to be 4. The padding seems to be hardcoded to `2.5`

https://github.com/shinokada/flowbite-svelte/blob/main/src/lib/forms/Input.svelte#L12 

![2022-04-15_17-05-10](https://user-images.githubusercontent.com/4141366/163653921-67a06b38-9f2e-4cda-9286-91b10a791b0d.png)

**Comment by shinokada** [comment]
Thank you for the catch. I will fix it right now!

**Comment by shinokada** [comment]
I just updated the package. Please let me know if you find any more bugs. Thanks.

```
npm i -D flowbite-svelte@latest
```

**Comment by dennismphil** [comment]
Thank you for the quick fix
