### ISSUE TITLE
A11y: visible, non-interactive elements with an on:click event must be accompanied by an on:keydown, on:keyup, or on:keypress event

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite-svelte#376]
### Describe the bug

[vite-plugin-svelte] /Users/shinichiokada/Svelte/FLOWBITE-SVELTE/flowbite-svelte-starter/node_modules/.pnpm/flowbite-svelte@0.27.6/node_modules/flowbite-svelte/drawer/Drawer.svelte:46:4 A11y: visible, non-interactive elements with an on:click event must be accompanied by an on:keydown, on:keyup, or on:keypress event.
[vite-plugin-svelte] /Users/shinichiokada/Svelte/FLOWBITE-SVELTE/flowbite-svelte-starter/node_modules/.pnpm/flowbite-svelte@0.27.6/node_modules/flowbite-svelte/carousels/Thumbnail.svelte:9:0 A11y: visible, non-interactive elements with an on:click event must be accompanied by an on:keydown, on:keyup, or on:keypress event.

### Reproduction

Fresh install v0.27.6.

```
pnpm dev
```

### Flowbite version and System Info

```shell
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 120.14 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Brave Browser: 106.1.44.112
    Chrome: 106.0.5249.119
    Chrome Canary: 109.0.5363.0
    Firefox: 105.0.3
    Safari: 16.0
  npmPackages:
    @sveltejs/kit: 1.0.0-next.403 => 1.0.0-next.403 
    flowbite-svelte: ^0.27.6 => 0.27.6 
    svelte: ^3.52.0 => 3.52.0 
    vite: ^3.1.8 => 3.1.8
```

**Comment by neospirit** [comment]
I updated to the latest version of flowbite-svelte (0.30.4) and I still have this warning
