### ISSUE TITLE
Allow passing down custom classes and ids without using a property

### ISSUE THREAD

**Issue by JoshuaPelealu** [themesberg/flowbite-svelte#38]
So the problem I've come into is that I can't put custom ids or classes to these components, and when I wanted to use the `type` property for a button, i have to use the `btnType` property which is inconvenient. 

Svelte actually supports passing down properties to its children. So for example, on the button component:
```svelte
// Instead of using the type={btnType}
<button type={btnType} class={buttonClass} on:click>
	{name}
	<slot />
</button>

// We can use $$restProps
<button {...$$restProps} class={buttonClass} on:click>
	{name}
	<slot />
</button>
```

Here's the official documentation:
https://svelte.dev/docs#template-syntax-attributes-and-props

**Comment by shinokada** [comment]
The reason I didn't use it that the doc says "not recommended"

> $$restProps contains only the props which are not declared with export. It can be used to pass down other unknown attributes to an element in a component. It shares the same optimisation problems as $$props, and is likewise not recommended.

But I can consider using this.

**Comment by shinokada** [comment]
I think the Button component should have the default value, I will update to the following:

```
<button {type} class={buttonClass} {...$$restProps} on:click>
  {name}
  <slot />
</button>
```

**Comment by shinokada** [comment]
I close the issue for now. Thank you for bring this up.
