### ISSUE TITLE
Badge, Toast, Popover page on Chrome problem

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite-svelte#381]
### Describe the bug

When you scroll the Badge page to the end of the page, it scrolls down even if there is no content.

![image](https://user-images.githubusercontent.com/147320/196068848-b212d3d8-7c14-4190-b07f-cfa324e0d563.png)

### Reproduction

Chrom and visit https://flowbite-svelte.com/components/badge.
Then scroll to the end and up.

### Flowbite version and System Info

```shell
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 98.25 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Brave Browser: 106.1.44.112
    Chrome: 106.0.5249.119
    Chrome Canary: 109.0.5363.0
    Firefox: 105.0.3
    Safari: 16.0
  npmPackages:
    @sveltejs/kit: 1.0.0-next.484 => 1.0.0-next.484 
    svelte: ^3.44.0 => 3.52.0 
    vite: ^3.1.0 => 3.1.8
```

**Comment by jjagielka** [comment]
Can be closed.
