### ISSUE TITLE
Append Target Page Content to Current One on Routing with Flowbite Components

### ISSUE THREAD

**Issue by seanwu1105** [themesberg/flowbite-svelte#384]
### Describe the bug

I try to use Flowbite `Action` and `Navbar` components on my root and about pages. However, after adding the components, it seems that SvelteKit append the contents of the target page to the current one and then remove the old contents in a noticeable time.

![Recording 2022-10-18 at 17 07 21](https://user-images.githubusercontent.com/14951000/196546229-97cb0ad3-a202-4d86-af5d-89d871de8231.gif)

Interestingly, this bug only happens after I add some Flowbite components, including `Action`, `Navbar` and `Card`. Some basic components, such as `P` and `A`, do not cause this issue.

### Reproduction

A minimal example to reproduce this bug can be found [here](https://github.com/seanwu1105/flowbite-routing-bug). The project is created according to [the instruction on the official website](https://flowbite-svelte.com/pages/getting-started). I can reproduce the bug on macOS and Ubuntu with Chrome and Brave browsers.

### Flowbite version and System Info

```shell
System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M1
    Memory: 84.47 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.4.0 - ~/.asdf/installs/nodejs/18.4.0/bin/node
    npm: 8.12.1 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Brave Browser: 106.1.44.108
    Chrome: 106.0.5249.119
    Safari: 15.6
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.517 
    flowbite-svelte: ^0.27.8 => 0.27.8 
    svelte: ^3.44.0 => 3.52.0 
    vite: ^3.1.0 => 3.1.8
```

**Comment by shinokada** [comment]
@jjagielka Card, Alert, Navbar components use Frame component.
I checked it with Accordion and Listgroup that also use Frame component has the same issue.

**Comment by jjagielka** [comment]
Quick workaround using simple `{#if transition}` added to `Frame` component.
PR uploaded.

**Comment by shinokada** [comment]
@seanwu1105 Can you try the new version and let us know.
