### ISSUE TITLE
Drawer with activateClickOutside

### ISSUE THREAD

**Issue by fadzril** [themesberg/flowbite-svelte#389]
### Describe the bug

Using drawer with `activateClickOutside={false}` didn't respect `backdrop={true}`.

Expected:-
- When using `backdrop={true}`and `activateClickOutside={false}`, it should disabled click outside but still enable backdrop layer

Result:-
- Using both properties above resulted backdrop missing from generated component

Reference:-
- https://github.com/themesberg/flowbite-svelte/blob/69ba822ef1f3710bdccbaf31006a94e1e3d19aae/src/lib/drawer/Drawer.svelte#L56

### Reproduction

https://svelte.dev/repl/121fc46a76a5436b86eeaa82cc269f5c?version=3.50.1

### Flowbite version and System Info

```shell
System:
    OS: macOS 11.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 193.45 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.8.0 - ~/.asdf/installs/nodejs/18.8.0/bin/node
    npm: 8.18.0 - ~/.asdf/installs/nodejs/18.8.0/bin/npm
  Browsers:
    Brave Browser: 101.1.38.109
    Chrome: 106.0.5249.119
    Firefox: 105.0.3
    Safari: 15.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.515
    flowbite-svelte: ^0.27.9 => 0.27.9
    svelte: ^3.46.0 => 3.51.0
    vite: ^3.0.4 => 3.1.7
```
```

**Comment by shinokada** [comment]
Can you check the new version?
And you can find the [doc](https://flowbite-svelte-d0wiy8jgs-themesberg.vercel.app/components/drawer#Disabling_only_outside_click).
