### ISSUE TITLE
Input autocomplete attributes

### ISSUE THREAD

**Issue by TheRevenantStar** [themesberg/flowbite-svelte#397]
## Summary

Add a property to set `autocomplete` on `<Input>` components

### Basic example
```
<Input
  type='password'
  name='password'
  placeholder='********'
  required
  autocomplete='current-password'
/>
```
### Motivation

Inclusion of `autocomplete` attributes improves user experience, especially for things like password managers.

**Comment by shinokada** [comment]
You can do it. Input component has `{...$$restProps}`, you can add any attribute.
Please try it and let us know.

```
<Input
  type='password'
  name='password'
  placeholder='********'
  required
  autocomplete='current-password'
/>
```

**Comment by TheRevenantStar** [comment]
My apologies, this does work, I simply spelt it incorrectly and my workflow was removing it from the element before svelte rendered it.

Thank you.
