### ISSUE TITLE
Additional Customizations for modal buttons

### ISSUE THREAD

**Issue by Gildedter** [themesberg/flowbite-svelte#40]
For example, if I wanted my modal button (in my Table column) to be displayed as an underlined link as shown [here](https://flowbite.com/docs/components/tables/) (Default Table, with `Edit` column)

**Comment by shinokada** [comment]
I haven't tried it but you can combine the [Table](https://flowbite-svelte.vercel.app/tables) component and the modal component like the followings:

```
<script>
import { SmallModal, Table, TableDefaultRow } from "flowbite-svelte";

const openFn = (id: string) => {
	modalIdStore.update((n) => (n = id));
	showModalId = get(modalIdStore);
	// console.log('showModalId', showModalId);
};

let itemEx = [
  ['Apple','Sliver','Laptop','$2999','<a href="/" on:click|preventDefault={()=>openFn(id)} class="text-blue-600 hover:underline dark:text-blue-500">Edit</a>'],
  ['Microsoft Surface Pro','White','Laptop PC','$1999','<a href="/" on:click|preventDefault={()=>openFn(id)} class="text-blue-600 hover:underline dark:text-blue-500">Edit</a>'],
  ['Magic Mouse 2','Black','Accessories','$99','<a href="/" on:click|preventDefault={()=>openFn(id)} class="text-blue-600 hover:underline dark:text-blue-500">Edit</a>']
]

</script>

<Table header={headerEx} {divClass} >
  <TableDefaultRow items={itemEx} html />
</Table>

<SmallModal
  id={idBasic}
  title="Basic Modal Title">
  Basic Modal Content
</SmallModal>

```

**Comment by Gildedter** [comment]
> I haven't tried it but you can combine the [Table](https://flowbite-svelte.vercel.app/tables) component and the modal component like the followings:
> 
> ```
> <script>
> import { SmallModal, Table, TableDefaultRow } from "flowbite-svelte";
> 
> const openFn = (id: string) => {
> 	modalIdStore.update((n) => (n = id));
> 	showModalId = get(modalIdStore);
> 	// console.log('showModalId', showModalId);
> };
> 
> let itemEx = [
>   ['Apple','Sliver','Laptop','$2999','<a href="/" on:click|preventDefault={()=>openFn(id)} class="text-blue-600 hover:underline dark:text-blue-500">Edit</a>'],
>   ['Microsoft Surface Pro','White','Laptop PC','$1999','<a href="/" on:click|preventDefault={()=>openFn(id)} class="text-blue-600 hover:underline dark:text-blue-500">Edit</a>'],
>   ['Magic Mouse 2','Black','Accessories','$99','<a href="/" on:click|preventDefault={()=>openFn(id)} class="text-blue-600 hover:underline dark:text-blue-500">Edit</a>']
> ]
> 
> </script>
> 
> <Table header={headerEx} {divClass} >
>   <TableDefaultRow items={itemEx} html />
> </Table>
> 
> <SmallModal
>   id={idBasic}
>   title="Basic Modal Title">
>   Basic Modal Content
> </SmallModal>
> ```

Thank you, will try this.

**Comment by Gildedter** [comment]
Finally tried this, but clicking the "link" just redirects me to my index page because of the `href`, also the column isn't rendered as a link, I'm formatting my data inside a `load` function, would that cause conflicts with how the `Table` component gets rendered?

**Comment by shinokada** [comment]
Can you use [Badge](https://flowbite-svelte.com/badges/default) or [Button}(https://flowbite-svelte.com/buttons/setup) component for `<a>` tag?

**Comment by Gildedter** [comment]
I'll get back to this after some tries

**Comment by shinokada** [comment]
Close for now. Feel free to add more comments.
