### ISSUE TITLE
Add 'target' prop to Link components

### ISSUE THREAD

**Issue by rdupz** [themesberg/flowbite-svelte#403]
## Summary

How to open a footer link in a new tab?

### Basic example
Would be cool if we could to this:
        `<FooterLink href="https://twitter.com/me" target="_blank">
Contact
</FooterLink>` 

Note the `target` prop.
### Motivation

This would gives the user more control on how the _a_ html element is created.

**Comment by shinokada** [comment]
Yes, the next release will have that. Thanks.

**Comment by shinokada** [comment]
Please update to v0.27.13 and let me know.

```
npm i -D flowbite-svelte@latest
```
