### ISSUE TITLE
Change background colors of modal and mobile navmenu

### ISSUE THREAD

**Issue by ethanfox** [themesberg/flowbite-svelte#404]
Is there not a way to change the background colors of modals and the nav menu on mobile? Not everyone is going ton want that one grey color

**Comment by shinokada** [comment]
# Navbar

Regarding `Navbar` component, can you try using the `color` prop?

```
<Navbar color="none"  let:hidden let:toggle>
```

For the [`NavLi`](https://flowbite-svelte-update-qe74t7ihe-themesberg.vercel.app/components/navbar#Props), you can change the `activeClass` and `nonActiveClass` if you need. 

# Modal

The Modal component doesn't have the default background color. If you are talking about backdrop color, then you can change it by using the ` backdropClasses` prop.

**Comment by ethanfox** [comment]
Im looking to change this color on the modal and that same color on the mobile nav drop down. I have not found any props that work.

<img width="830" alt="Screen Shot 2022-10-14 at 3 39 56 PM" src="https://user-images.githubusercontent.com/22962600/198904325-bc07fe35-8b5d-4680-b397-ec08af4ebdf3.png">
<img width="630" alt="Screenshot 2022-10-30 at 5 20 04 PM" src="https://user-images.githubusercontent.com/22962600/198904327-27c9d7ec-abcc-4c3f-bd1b-710eac8736f9.png">

**Comment by shinokada** [comment]
Any code?

**Comment by shinokada** [comment]
@ethanfox Can you try v0.27.14 and let us know.

**Comment by ethanfox** [comment]
> @ethanfox Can you try v0.27.14 and let us know.
> [Doc](https://flowbite-svelte.com/components/modal#Colors)
That only works with the colors shown in the docs. I should be able to pick whatever color I want. ie black

**Comment by shinokada** [comment]
Try `color="none"` and add your color.

**Comment by ethanfox** [comment]
> Try `color="none"` and add your color.
> 
> ```
> <Modal color="none" class="your-color-css" ...
> ```

That worked thank you!
