### ISSUE TITLE
[Feature Request] Success and Error validation for form input

### ISSUE THREAD

**Issue by dennismphil** [themesberg/flowbite-svelte#41]
It would be nice to have error validation red color styling baked into the component for form fields. 

something like `hasError={true}`

https://flowbite.com/docs/components/forms/#success-and-error-validation

**Comment by erolabzait** [comment]
Maybe something that can work with:
https://codechips.me/form-validation-svelte-vest/

**Comment by shinokada** [comment]
Please update to the latest version. We have implemented the error/success.
