### ISSUE TITLE
Form is not connected in Modal

### ISSUE THREAD

**Issue by logeFox** [themesberg/flowbite-svelte#413]
### Describe the bug

When submitting a form that is inside a modal, the submission is canceled because the form is not connected.
![image](https://user-images.githubusercontent.com/59316554/199773052-7d6b7f5d-15e3-4c31-b34b-51b8594a0878.png)
Before updating to the newest version of both svelte kit and flowbite-svelte there was no error as such.

### Reproduction

https://flowbite-svelte.com/components/modal#Form_element

### Flowbite version and System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700K
    Memory: 22.43 GB / 31.75 GB
Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.26)
    Internet Explorer: 11.0.19041.1566
npmPackages:
    @sveltejs/kit: next => 1.0.0-next.532
    flowbite-svelte: ^0.27.14 => 0.27.14
    svelte: ^3.44.0 => 3.52.0
    vite: ^3.1.0 => 3.2.2
```

**Comment by jjagielka** [comment]
See the doc `Modal -> Default modal`
> Any <button> element put in the modal will close it on click. To prevent that behaviour set autoclose=false property.

When you press the button the modal gets closed before it submits the values. To avoid it set `autoclose={false}` and manage to closing manually.

**Note:** I will set `autoclose` to `false` by default for the `Modal` component.

**Comment by logeFox** [comment]
Thank you it worked
