### ISSUE TITLE
[Bug] `devDependencies` vs `dependencies`

### ISSUE THREAD

**Issue by dennismphil** [themesberg/flowbite-svelte#42]
# Error

Took the latest package and noticed the following error that `@codewithshin/svelte-heroicons` package is missing

I believe [some code dependencies](https://github.com/themesberg/flowbite-svelte/blob/main/package.json#L27-L30) needs to be marked as `dependencies` for `flowbite-svelte` without which they won't get installed for the downstream packages

![2022-04-18_10-23-32](https://user-images.githubusercontent.com/4141366/163847278-3a2ab989-4b7f-4f39-97ae-62e1b911407c.png)

**Comment by shinokada** [comment]
Yes, I will update it.
Meanwhile, please install it.

```
npm i -D @codewithshin/svelte-heroicons
```

**Comment by shinokada** [comment]
I put back all the dependencies:

```
...
	"dependencies": {
		"@codewithshin/svelte-heroicons": "^1.1.3",
		"flowbite": "^1.4.2",
		"svelte-collapse": "^0.0.4"
	}
```

I close the issue. Please let me know if you have any issues.
