### ISSUE TITLE
Reverse Card Button Doesn't position correctly

### ISSUE THREAD

**Issue by jdgamble555** [themesberg/flowbite-svelte#421]
### Describe the bug

Not a big deal, but when you click the reverse button on the website, the screen goes blank.  You scroll back up and see the image is at the bottom.

### Reproduction

https://flowbite-svelte.com/components/card

### Flowbite version and System Info

```shell
Using Chrome
```

**Comment by shinokada** [comment]
@jjagielka Can you have a look into this?

**Comment by jjagielka** [comment]
The idea of the `reverse` button is the flip the ordering of items inside a card. So it's as expected that with `reverse={true}` the image is at the bottom if `Card` is vertical, and at the right if `Card` is horizontal.

The blank screen is a bug though. Seems like this happens only in Chrome, as Firefox does not suffer from it.

**Comment by jjagielka** [comment]
This Chrome issue is the one already raised: #381 and it concerns as well `Card`, `Alert` and few others.

**Comment by jjagielka** [comment]
Can be closed.
