### ISSUE TITLE
Speed dial component

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite-svelte#428]
## Summary

[Speed Dial ](https://flowbite.com/docs/components/speed-dial/)

- [x] Default speed dial [#](https://flowbite.com/docs/components/speed-dial/#default-speed-dial)
- [x] Square speed dial [#](https://flowbite.com/docs/components/speed-dial/#square-speed-dial)
- [x] Text inside button [#](https://flowbite.com/docs/components/speed-dial/#text-inside-button)
- [x] Text outside button [#](https://flowbite.com/docs/components/speed-dial/#text-outside-button)
- [x] Dropdown menu [#](https://flowbite.com/docs/components/speed-dial/#dropdown-menu)
- [x] Alternative menu [#](https://flowbite.com/docs/components/speed-dial/#alternative-menu)
- [x] Top right [#](https://flowbite.com/docs/components/speed-dial/#top-right)
- [x] Bottom right [#](https://flowbite.com/docs/components/speed-dial/#bottom-right)
- [x] Bottom left [#](https://flowbite.com/docs/components/speed-dial/#bottom-left)
- [x] Top left [#](https://flowbite.com/docs/components/speed-dial/#top-left)
- [x] Vertical [#](https://flowbite.com/docs/components/speed-dial/#vertical)
- [x] Horizontal [#](https://flowbite.com/docs/components/speed-dial/#horizontal)
- [x] Hover [#](https://flowbite.com/docs/components/speed-dial/#hover)
- [x] Click [#](https://flowbite.com/docs/components/speed-dial/#click)

**Comment by jjagielka** [comment]
I can take it.

**Comment by shinokada** [comment]
@jjagielka Thanks as always.
