### ISSUE TITLE
Modal outside click to close the modal

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite-svelte#429]
## Summary

Default modal [#](https://flowbite.com/docs/components/modal/#default-modal)

**Comment by jjagielka** [comment]
From Flowbite.com
> Use the data-modal-backdrop="static data attribute to prevent the modal from closing when clicking outside of it. This can be used with situations where you want to force the user to choose an option such as a cookie notice or when taking a survey.

If you want to really force the user to interact, you should remove the close button (x) as well and Flowbite.com doesn't do that.

On the other hand, if the information is not so important that can be ignored by the user, instead of modal one should use the interactive toast.

**Comment by jjagielka** [comment]
Other point is, we had that discussion already: https://github.com/themesberg/flowbite-svelte/issues/176#issuecomment-1200422420.
@zoltanszogyenyi what do you think?

**Comment by shinokada** [comment]
As an option you can click outside to close a modal.
See more https://github.com/themesberg/flowbite-svelte/pull/780#issuecomment-1556126951.
