### ISSUE TITLE
Default Checkbox checked attribute losed

### ISSUE THREAD

**Issue by arnWolff** [themesberg/flowbite-svelte#430]
### Describe the bug

Using `use:init={group}` makes default checked Checkboxes without any group defined losing their checked state. 

### Reproduction

Go to https://flowbite-svelte.com/forms/checkbox and see `<Checkbox checked>Checked state</Checkbox>` .

On loading, state is checked but once page is loaded, the state goes to unchecked.

### Flowbite version and System Info

```shell
Latest main branch
```

**Comment by arnWolff** [comment]
As a simple fix in `.\src\lib\forms\Checkbox.svelte`:

```
function init(_: HTMLElement, _group: string[]) {
    // we check for checkbox's group
    checked = _group.length ? _group.includes(value) : checked;
    return {
      update(_group: string[]) {
        checked = _group.includes(value);
      }
    };
  }
```

**Comment by jjagielka** [comment]
Well spotted. I'll correct it in the next update.
