### ISSUE TITLE
Toggle can't get default state

### ISSUE THREAD

**Issue by NormandoHall** [themesberg/flowbite-svelte#438]
### Describe the bug

As you can see in your demo page, toggle switches shows as off (unchecked).

This happens after https://github.com/themesberg/flowbite-svelte/pull/427 (v0.27.17)

### Reproduction

Look at https://flowbite-svelte.com/forms/toggle

### Flowbite version and System Info

```shell
System:
    OS: Linux 3.10 CentOS Linux 7 (Core)
    CPU: (4) x64 Intel Xeon Processor (Skylake, IBRS)
    Memory: 716.30 MB / 15.51 GB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 16.15.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
  npmPackages:
    @sveltejs/kit: ^1.0.0-next.529 => 1.0.0-next.551 
    flowbite-svelte: ^0.27.16 => 0.27.17 
    svelte: ^3.52.0 => 3.53.1 
    vite: ^3.2.3 => 3.2.4
```

**Comment by jjagielka** [comment]
Fixed with #434

**Comment by NormandoHall** [comment]
> Fixed with #434

Thanks. Can you release it?

**Comment by shinokada** [comment]
Released v0.28.0.

**Comment by NormandoHall** [comment]
Sorry, but this #434 no fix the issue

**Comment by shinokada** [comment]
It's been merged already.

**Comment by NormandoHall** [comment]
> It's been merged already.

If I install the latest npm package (0.28.0) still has the same issue.

**Comment by xmlking** [comment]
The toggle not working for me as well. I have 0.28.0

**Comment by jjagielka** [comment]
@shinokada it's merged but version was not increased

**Comment by shinokada** [comment]
Please try v0.28.1.

**Comment by NormandoHall** [comment]
> Please try v0.28.1.

Still has the issue. This issue comes from Checkbox component. When I render the page and set the default checkbox (or toggle) to true, shows ok, but after a second or less, switch to false.


This is my code in sveltekit:

```svelte
<script>
  import { Toggle, Checkbox } from 'flowbite-svelte';
  const values = {sicam: true}
</script>

<div class="relative inline-flex justify-around items-center">
  <Toggle class="cursor-pointer" name="sicam" color="purple" bind:checked={values.sicam}>SICAM</Toggle>
  <Checkbox class="cursor-pointer" name="enabled" color="orange" bind:checked={values.enabled}>Habilitar cuenta</Checkbox>
</div>
```

Seems as checkbox component when rendered, switch to false

**Comment by NormandoHall** [comment]
Yes, I was updated to 0.28.1. And yes, runs ok in REPL. For some reason I don't know, why this happens after 0.27.17.

When Render the component, shows that is enabled, but after a few milliseconds switch to false state. My code is the same code as always use.

I will investigate why happens and return with news. Thanks

**Comment by jjagielka** [comment]
In 0.27.17 I have introduced the `group` support at the initial component setup.
[Svelte doc: bind:group](https://svelte.dev/docs#template-syntax-element-directives-bind-group)

When you initialize checkbox component there's potential conflict between `checked` and `group` properties.
```svelte
<script>
  let group = [1,2];
</script>
<Checkbox bind:group value={1} />
<Checkbox bind:group value={2} />
<Checkbox bind:group value={3} checked />
```

This code should caused all three checkboxes checked, but what if:
```svelte
<script>
  let group = [1,2];
</script>
<Checkbox bind:group value={1} checked={false}/>
<Checkbox bind:group value={2} />
<Checkbox bind:group value={3} checked />
```
Since 0.28.1 `checked` property prevails.

**Comment by NormandoHall** [comment]
Thanks for the clarification. Now in 0.28.1 runs ok. I was missed to force npm to install the latest version. Now it is ok. 
Thanks again
