### ISSUE TITLE
After clicking the right menu, some pages  have double scroll bar

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite-svelte#440]
### Describe the bug

https://flowbite-svelte.com/forms/checkbox#References

For example, go to this [page](https://flowbite-svelte.com/forms/checkbox#References) and scroll to the end. It won't show the end of the page.

It happens when I click the right side menu or with `#menu-item`.

### Reproduction

https://flowbite-svelte.com/forms/checkbox#References

https://flowbite-svelte.com/forms/textarea#References

https://flowbite-svelte.com/forms/toggle#References

https://flowbite-svelte.com/forms/select#References

https://flowbite-svelte.com/components/alert#References

https://flowbite-svelte.com/components/card#References

https://flowbite-svelte.com/components/forms#References

And more ....

It happens with Chrome/Safari/Brave.

### Flowbite version and System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 272.63 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Brave Browser: 107.1.45.127
    Chrome: 107.0.5304.110
    Chrome Canary: 110.0.5428.0
    Firefox: 107.0
    Safari: 16.1
```

**Comment by jjagielka** [comment]
All those issues are connected with setting the class at that line in `app.html`:
```html
<div id="svelte" class="max-h-screen overflow-auto">%sveltekit.body%</div>
```
That `class` value was added to manage the `Modal` scrolling behavior, but on the above mentioned docs pages this is triggering sometimes double scroll bar of the page.

I think I have made further changes to the `Modal` component that this class is no longer needed, and we can come back to the initial:
```html
<div id="svelte">%sveltekit.body%</div>
```
This is however not clear to me why:
- this strange behavior is never observed on Firefox
- and even on Chrome is observed only on few pages but does not appear on others.

**Comment by shinokada** [comment]
Is it possible to remove the class from id="svelte" and add it to the page where we use Modal component?
