### ISSUE TITLE
Tabs not work since sveltekit udate from 1.0.0-next.559 to never version

### ISSUE THREAD

**Issue by ryou90** [themesberg/flowbite-svelte#451]
### Describe the bug

Since sveltekit update from 1.0.0-next.559 to never version.

### Reproduction

Create svelte file with Tabs, e.g. use example from [https://flowbite-svelte.com/components/tab](https://flowbite-svelte.com/components/tab).

First use sveltekit version 1.0.0-next.559 and then update to a never version.

### Flowbite version and System Info

```shell
  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz
    Memory: 7.71 GB / 15.72 GB
  Binaries:
    Node: 19.1.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.56)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/kit: 1.0.0-next.560 => 1.0.0-next.560
    flowbite-svelte: ^0.28.1 => 0.28.1
    svelte: ^3.53.1 => 3.53.1
    vite: ^3.2.4 => 3.2.4
```

**Comment by jjagielka** [comment]
Just tested with `@sveltejs/kit@1.0.0-next.561` and it works as expected.

**Comment by ryou90** [comment]
haha, yes you are right. Now it works for me too. Probably I had an error somewhere in the code. Thanks for clarifying :)
