### ISSUE TITLE
TreeView Component

### ISSUE THREAD

**Issue by kiryasolod** [themesberg/flowbite-svelte#455]
Hi, I'm going to use your library in my project. It's very cool, but unfortunately it does not have a treeview component which is gonna be a central stuff in my Tauri GUI application. It would be good to implement it myself but I'm sure that you will implement it anyway and my implementation probably won't be compatible or seamlessly integrated with your library. Thank you

**Comment by jjagielka** [comment]
Unfortunately TreeView component is not in scope of Flowbite.com and I doubt it will be as it's really complex if you want to make it good.

I was successfully using [FancyTree](https://github.com/mar10/fancytree) for years, but the disadvantage is that it's still jQuery based.

**Comment by shinokada** [comment]
Please request it in [the Flowbite issue page](https://github.com/issues)
