### ISSUE TITLE
Tooltip not working in Skeleton app

### ISSUE THREAD

**Issue by VaughanG** [themesberg/flowbite-svelte#456]
### Describe the bug

I used _npm create skeleton-app_ to generate a new Skeleton app to try Flowbite-Svelte components.
I am enjoying the Flowbite-Svelte components and everything seems to work but not the Tooltip. The Flowbite-Svelte button displays ok but there is no tooltip.
I tried all the examples on the _https://flowbite-svelte.com/components/tooltip_ page.
The Skeleton tooltip works ok but I am flummoxed that I cannot get the Flowbite-Svelte Tooltip to work.
+page.svelte
```
<script>
	import { Divider } from '@brainandbones/skeleton';
	
	import { Tooltip, Button } from 'flowbite-svelte';
	//import { tooltip } from '@brainandbones/skeleton';
</script>

<div>
<Divider borderWidth="border-t-8" borderStyle="border-solid" borderColor="border-primary-400"/>
</div>
<br>

<Button id="hover">Tooltip hover</Button>
<Tooltip triggeredBy="#hover">Hover tooltip content</Tooltip>
<!-- <button use:tooltip={{ content: 'Skeleton' }}>Trigger</button> -->
```
tailwind.config.cjs
```
module.exports = {
	darkMode: 'class',
	content: [
		'./src/**/*.{html,js,svelte,ts}',
		'./node_modules/flowbite-svelte/**/*.{html,js,svelte,ts}',
		require('path').join(require.resolve('@brainandbones/skeleton'), '../**/*.{html,js,svelte,ts}')
	],
	theme: {
		extend: {}
	},
	plugins: [
		require('@tailwindcss/forms'),
		require('@tailwindcss/typography'),
		require('@brainandbones/skeleton/tailwind/theme.cjs'),
		require('flowbite/plugin')
	]
};
```
The only error I can see is Visual Studio Code reporting a typescript error.
_Could not find a declaration file for module 'flowbite/plugin'. 'c:/sveltekitskeleton/createskeleton/csapp/node_modules/flowbite/plugin.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/flowbite` if it exists or add a new declaration (.d.ts) file containing `declare module 'flowbite/plugin';`_
I am not using TS in this app.
Thank you for helping.

### Reproduction

https://github.com/VaughanG/create-skeleton/tree/main/csapp

### Flowbite version and System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 6.18 GB / 15.85 GB
  Binaries:
    Node: 18.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (106.0.1370.42)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.557
    flowbite-svelte: ^0.28.1 => 0.28.1
    svelte: ^3.44.0 => 3.53.1
    vite: ^3.1.0 => 3.2.4
```

**Comment by jjagielka** [comment]
Seems like you have not installed the necessary dependencies (https://flowbite-svelte.com/pages/getting-started#Install_dependencies):
```
npm i -D flowbite flowbite-svelte classnames @popperjs/core
```

**Comment by VaughanG** [comment]
@jjagielka - I did install the dependencies - please see the package.json
```
"devDependencies": {
		"@brainandbones/skeleton": "^0.76.0",
		"@popperjs/core": "^2.11.6",
		"@sveltejs/adapter-auto": "next",
		"@sveltejs/kit": "next",
		"@tailwindcss/forms": "^0.5.3",
		"@tailwindcss/typography": "^0.5.8",
		"autoprefixer": "^10.4.13",
		"classnames": "^2.3.2",
		"flowbite": "^1.5.4",
		"flowbite-svelte": "^0.28.3",
		"postcss": "^8.4.19",
		"prettier": "^2.6.2",
		"prettier-plugin-svelte": "^2.7.0",
		"svelte": "^3.44.0",
		"svelte-preprocess": "^4.10.7",
		"tailwindcss": "^3.2.4",
		"vite": "^3.1.0"
	},
```
Tooltip works fine in Sveltekit apps but after adding Skeleton Tooltip stops working.

**Comment by VaughanG** [comment]
I am closing this issue as currently it is insoluble - I have heard back from Chris Simmonds of Skeleton and there is no way at present to make this work.
