### ISSUE TITLE
Modal Backdrop doesn't cover bottom of screen on mobile

### ISSUE THREAD

**Issue by 0xArbiter** [themesberg/flowbite-svelte#457]
### Describe the bug

As mentioned in title, on mobile devices and when previewing mobile the default modal backdrop does not cover the bottom 5% of the screen. Easily reproduced in developer mode with the default modal on the Flowbite site.

Confirmed in my own project, on iphone 12 pro, and on flowbite modal example on website. Screenshot attached.

### Reproduction

https://svelte.dev/repl/930d39fbd10b4e5b8581fb20d3a3192e?version=3.50.1

<img width="567" alt="Screen Shot 2022-11-28 at 9 06 46 PM" src="https://user-images.githubusercontent.com/85376859/204422416-75ba0bdd-cdc9-4244-9b6b-4325314b11fb.png">

### Flowbite version and System Info

```shell
System:
    OS: macOS 11.5
    CPU: (8) arm64 Apple M1
    Memory: 59.84 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.6.0 - /usr/local/bin/node
    npm: 8.5.1 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 107.1.45.131
    Chrome: 107.0.5304.110
    Safari: 14.1.2
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.560 
    flowbite-svelte: ^0.28.1 => 0.28.1 
    svelte: ^3.44.0 => 3.53.1 
    vite: ^3.1.0 => 3.2.4
```

**Comment by jjagielka** [comment]
This is as per design. Flowbite.com have introduced a special height class that is used modals in the mobile view:
```css
.h-modal {
  height: calc(100% - 2rem);
}
```

You need to issue the ticket on Flowbite.com to challenge that decision.

**Comment by 0xArbiter** [comment]
Thank you for that, I looked around and couldn't figure out why it was doing that. It looks terrible, do you happen to know why they did that? I'll take it over there though.
