### ISSUE TITLE
Accordion expand/collapse all, no dependency

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite-svelte#46]
- [x] As you can see in this [example](https://flowbite.com/tools/tailwind-cheat-sheet/), add expand/collapse all to accordion component.
- [x] No dependencies. Currently it uses `svelte-collapse`, but it should be able without the external dependency.

**Comment by shinokada** [comment]
No dependencies completed v.0.15.17.

**Comment by jjagielka** [comment]
Expand all - check that [REPL](https://svelte.dev/repl/11ec248832644aa4ac713a8d837118d6?version=3.50.1)

We can add it to the docs.

**Comment by jjagielka** [comment]
That can be closed. `Multiple mode` added to `Accordion` docs.

**Comment by shinokada** [comment]
Thanks for your support.
