### ISSUE TITLE
Dropdown doesnt close on click outside when no src is specified for an Avatar component.

### ISSUE THREAD

**Issue by cami7ord** [themesberg/flowbite-svelte#460]
### Describe the bug

Dropdown doesnt close on click outside when no src is specified for an Avatar component.

### Reproduction

1. Use any of the examples: https://flowbite-svelte.com/components/dropdown#User_avatar or https://flowbite-svelte.com/components/navbar#User_menu_dropdown
2. Remove the 'src' prop to the 'Avatar' component to show the placeholder icon.
3. Clicking outside of the avatar does not close the dropdown.

### Flowbite version and System Info

```shell
System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M1 Pro
    Memory: 1.47 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Safari: 15.6
```

**Comment by shinokada** [comment]
Can you try it on Firefox?
