### ISSUE TITLE
Pagination active page

### ISSUE THREAD

**Issue by ESchouten** [themesberg/flowbite-svelte#461]
## Summary

The current pagination component does not show which page is active (e.g. by coloring the active page buttons background), thus it's not clear which page is displayed.

### Basic example

The LinkType array required for the pages could include an optional boolean prop called active. When this value is true, the background could be colored with e.g. bg-primary-200

Additionally, the li classes can currently not be customized, the ul can. This should be made possible in order to customize the color of the buttons.

### Motivation

Currently, it's not clear which page is displayed.

**Comment by shinokada** [comment]
Please update to the latest version.
I close the issue for now.
Feel free to open a new issue.
