### ISSUE TITLE
TableBodyRow on:click event

### ISSUE THREAD

**Issue by ESchouten** [themesberg/flowbite-svelte#463]
## Summary

At the moment, navigation from a table row from flowbite is often done by placing an `<a href` in the last column. With the hoverable property in table, users expect the whole row to be clickable. However, placing an on:click event handler on the TableBodyRow element does not work at the moment.

### Basic example

<TableBodyRow on:click={() => goto('/users/{id}')}>

### Motivation

Users expect the whole row to be clickable. However, placing an on:click event handler on the TableBodyRow element does not work at the moment.

**Comment by shinokada** [comment]
We have added on:click event forwarding.
Can you paste your output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit,flowbite-svelte,vite,rollup,webpack --binaries --browsers`?

**Comment by ESchouten** [comment]
```
  System:
    OS: Linux 6.0 Fedora Linux 37 (Workstation Edition)
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
    Memory: 6.98 GB / 15.55 GB
    Container: Yes
    Shell: 5.2.9 - /bin/bash
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 107.0.5304.121
    Firefox: 107.0
  npmPackages:
    @sveltejs/kit: ^1.0.0-next.553 => 1.0.0-next.553 
    flowbite-svelte: ^0.28.0 => 0.28.0 
    svelte: ^3.53.1 => 3.53.1 
    vite: ^3.2.4 => 3.2.4
```

**Comment by ESchouten** [comment]
I updated flowbite to the latest minor version, and it's working now
