### ISSUE TITLE
Suggestions for giving more layout/colors options to the buttons, etc..

### ISSUE THREAD

**Issue by 524c** [themesberg/flowbite-svelte#468]
I have a fork with some extra options:
1) For colors to have a new and more flexible name that we can define in our applications, for example "brand".
2) More granularity in the rounded option, to allow for "squarer" buttons as a layout decision.
3) Add the "fullwidth" option, so the button takes over the entire space of the div wherever it is.

Here are some examples from a fork I made to meet my current needs:
<img width="589" alt="button fork-1" src="https://user-images.githubusercontent.com/527641/205490921-5c73cd80-120e-4d17-908c-9438115f4abe.png">

<img width="586" alt="button fork-2" src="https://user-images.githubusercontent.com/527641/205490924-080a7f4d-28c7-4821-8968-57067ca7f937.png">

**Comment by 524c** [comment]
@shinokada, @jjagielka,

If you are interested in these suggestions, I can share my fork 👍

**Comment by jjagielka** [comment]
1. Color management is a wider subject and must be thought over not only for the buttons. Current implementation supports colors as defined in Flowbite.com
2. Rounded - again Flowbite.com design - `rounded-lg` or `rounded-full`. Of course a hack like below can be used:
```html
<Button class="!rounded">More squerer button</Button>
```
3. Buttons width is not controlled by the framework. If you need full width button simply add `class="w-full"` to the button.

**Comment by 524c** [comment]
> 1. Color management is a wider subject and must be thought over not only for the buttons. Current implementation supports colors as defined in Flowbite.com

Yes, I cited the button as an example, but this flexibility I am talking about would apply to all components 👍

> 2. Rounded - again Flowbite.com design - `rounded-lg` or `rounded-full`. Of course a hack like below can be used:
> 
> ```
> <Button class="!rounded">More squerer button</Button>
> ```

Catering to all users' wishes is impossible, so having more flexibility can be helpful.
In my case I don't want the square button, just slightly rounded 😁

> 
> 3. Buttons width is not controlled by the framework. If you need full width button simply add `class="w-full"` to the button.

```html
      <!-- signup -->
      <div class="my-5">
        <Button
          size="lg"
          fullwidth
          outline
          on:click={() => {
            errorsCleanup();
            loginPageMode = LoginPageMode.signup;
          }}>criar conta</Button>
      </div>
```
I do so today with a dedicated fullscreen option. Of course, class="xxx" is there to do anything.

**Comment by jjagielka** [comment]
ad. 2
>  Idon't want the square button, just slightly rounded 

I think you've misunderstood the example. Please compare those:
```html
<Button pill>Full rounded</Button>
<Button>Standard</Button>
<Button class="!rounded-md">More squarer button</Button>
<Button class="!rounded">Even more squarer button</Button>
<Button class="!rounded-none">Square button</Button>
```

ad. 3
> I do so today with a dedicated fullwidth option. Of course, class="xxx" is there to do anything.

If you can achieve what you want with the simple class setting, or have even more control with classes like `w-3/4`, `w-48`, `w-screen` or `w-full`, why would we need the `fullwidth` option

**Comment by shinokada** [comment]
For color management, you can set `primary` and others in the [tailwind.config.cjs](https://github.com/shinokada/flowbite-svelte-blocks/blob/main/tailwind.config.cjs) for your needs.

**Comment by jjagielka** [comment]
Can we close then?

**Comment by shiftlabs1** [comment]
@shinokada  not all components have or use the primary color option . Take Input for e.g , the only options are base,red and green , and that prop would not accept anything else . These hard coded and limited colors in components should at least include primary if they cant be completely flexible

**Comment by jjagielka** [comment]
In fact Flowbite.com does not propose colors to the `input` component. The red and green versions are not to customize the `input` but are reaction to data validation: `green` - data valid, `red` - data invalid.

In fact that `color` prop should not be exported but should be connected internally to the `data validation` state of the component.

**Comment by v79** [comment]
I do feel that the hard-coding of colours is pretty restrictive. I was looking at Toast - most toast implementations have semantic meaning - warning, info, error, danger etc. But Flowbite doesn't do this, instead all you can do is specify a color - and only those colours which are defined in `Frame.svelte` it seems.

I'm learning that you can then override it by setting `color='none'` and then override the `divClass` prop - but you have to update the VSCode Tailwind Extension to make it work with `divClass`. And because svelte doesn't support {#if} syntax in attributes, I can't even make it semantic - I can't write something like `divClass="{#if notification.type === 'error'} bg-red-200{/if}"`.

I fear Flowbite might just be a bit _too_ opinionated for me, when it comes to look-and-feel. I could fork?
