### ISSUE TITLE
Allow extend of class for all components

### ISSUE THREAD

**Issue by vfxturjo** [themesberg/flowbite-svelte#471]
## Summary

The components looks so nice! But, sometimes i need to tweak the class a bit. if the components accepted `class=" extended_classes "` then it would be very helpful.

### Basic example

for Button modification, i have to use `btnClass="LOTS_OF_THINGSSSS......... then_my_thing"`. wouldnt it be nice, if we could write what we want to extend only??

### Motivation

I know extending only one or two elements in a website kind-of breaks the design system. but only sometimes it is needed. I can use divs to modify but it is becoming combersome sometimes and:
1. extra lines of code
2. extra indentation
for simple modification... 😢 

Flowbite is for clean beautiful code right?? i guess implementing this will help others too. 
People will have flexibility, and also will be warned/reminded- extend when it is necessary, avoid if possible.

An idea for implementing can be something like this-
apply the original flowbite classes like "components" layer, which can be extended with the "utilities" layer of tailwind css. [reference here ](https://tailwindcss.com/docs/reusing-styles#extracting-classes-with-apply)
I may be wrong about this lazy approach, but this thing works or not, there are other ways to enable extension of classess, like string join to the original class and etc... 

thanks in advance!

**Comment by jjagielka** [comment]
Maybe it's not enough stated in the docs, but all components support the `class` attribute.

For example you can control width of the button without touching it's look and feel:
```html
<Button color="red" class="w-full">Red full width button</Button>
```
Other examples alike `Button with badge`
```html
<Button>
  Messages<Badge rounded class="ml-2 w-5 h-5">2</Badge>
</Button>
```
Notification badge:
```html
<Button class="relative" size='sm'>
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-7 h-7"><path stroke-linecap="round" stroke-linejoin="round" d="M21.75 6.75v10.5a2.25 2.25 0 01-2.25 2.25h-15a2.25 2.25 0 01-2.25-2.25V6.75m19.5 0A2.25 2.25 0 0019.5 4.5h-15a2.25 2.25 0 00-2.25 2.25m19.5 0v.243a2.25 2.25 0 01-1.07 1.916l-7.5 4.615a2.25 2.25 0 01-2.36 0L3.32 8.91a2.25 2.25 0 01-1.07-1.916V6.75" /></svg>
  <span class="sr-only">Notifications</span>
  <Badge rounded index color="!red">20</Badge>
</Button>
```

**Comment by vfxturjo** [comment]
Whoa! 😲 

i used to go to the reference file to see what props are allowed,
![image](https://user-images.githubusercontent.com/44445014/205514988-385ee4f8-6e19-4bba-a058-a0bd223d9fcc.png)
used to ctrl+click to go to the declaration to see:
![image](https://user-images.githubusercontent.com/44445014/205515064-74114298-1327-4699-a141-f53b898c6f92.png)
didn't see class prop there so...

Didn't know the components accepted the class prop!
**Thank you so much!!! 💘** 

it will be helpful to add this info in:
![image](https://user-images.githubusercontent.com/44445014/205515311-b8c913e9-003a-49d7-ac60-a8bec66b75a6.png)
A: I recommend here, inside the EXTEND section (centralized announcement).
B: or here, after prop section of each component (messy way)

also, [adding the info in the docs](https://github.com/themesberg/flowbite-svelte/issues/472#issue-1475086681) will also be very helpful!

thank you! 😄

**Comment by jjagielka** [comment]
Can be closed I suppose.

**Comment by shinokada** [comment]
Thank you for your contribution. I close the issue for now. Please feel free to create new ones.
