### ISSUE TITLE
Allow peek of general info for all components with hover tooltip in vscode

### ISSUE THREAD

**Issue by vfxturjo** [themesberg/flowbite-svelte#472]
## Summary

I want to see some important info about components when i hover over it in vscode.
such as:
1. valid prop names with valid values
2. (optional) classes applied to the component

### Basic example

when i hover over NavLi component, vscode tooltip shows: `(alias) class NavLi import NavLi`
but something like these would be helpful: 

#### example 1: NavLi
NavLi: Navbar list element
use inside NavUl component

props:
**href**: string = "" 
**active**: boolean = _false_ | true 
**activeClass**: string = _'text-white bg-blue-700 md:bg-transparent md:text-blue-700 md:dark:text-white dark:bg-blue-600 md:dark:bg-transparent'_
**nonActiveClass**: string = _'text-gray-700 hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 dark:text-gray-400 md:dark:hover:text-white --dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent'_

more info: https://flowbite-svelte.com/components/navbar

#### example 2: Navbar
NavBar: Navigation bar
can be used to show a list of navigation links positioned on the top side of your page

props:
**navClass**: string = _'px-2 sm:px-4 py-2.5 w-full'_
**navDivClass**: string = _'mx-auto flex flex-wrap justify-between items-center '_
**fluid**: boolean = _true_ | false
**color**  = _'navbar'_ | 'gray' | 'red' \| 'yellow' \| 'green' \| 'indigo' \| 'default' \| 'purple' \| 'pink' \| 'blue' \| 'light' \| 'dark' \| 'dropdown' \| 'navbar' \| 'navbarUl' \| 'form' \| 'none' 

more info: https://flowbite-svelte.com/components/navbar

### Motivation
for easier use of Flowbite-svelte... also, the link to the related page (as shown above in "more info" part of doc) will make the examples related to the component more accessible.

thanks in advance!

**Comment by shinokada** [comment]
I'm not sure how to add these to the library. Don't you create a VScode plugin for these?

**Comment by vfxturjo** [comment]
# Method 1: manually typing the docs:
example 1:
the setup:
![image](https://user-images.githubusercontent.com/44445014/205735258-872e7c76-97a2-4ca0-848a-29fcda5763f7.png)
the result:
![image](https://user-images.githubusercontent.com/44445014/205735613-cdeae02d-cfa5-46bb-b207-8939a773b00d.png)

ref: https://github.com/sveltejs/language-tools/blob/HEAD/docs/README.md#documenting-components
works nice! but manual editing is needed. and when you modify your component, you have to edit the docs again and again.

# Method 2: Automatic Docs
here, the documentation will  be automatically created by an npm package.
check this: https://github.com/alexprey/sveltedoc-parser
and this: https://github.com/carbon-design-system/sveld
I don't know wheather manually adding extra bit of info is possible or not. (but sometimes it is needed, i.e NavLi works inside NavUI component) 
But the creation of docs will be easier, no need to worry about making the docs because it is automatically done.

I hope now you understand that the hover docs is possible and no plugins are needed for this.
When making the components, please add the docs (manually or automatically)

**Comment by shinokada** [comment]
I think the current version has [component documents](https://flowbite-svelte.com/docs/pages/ide-support).
I close the issue for now.
Please feel free to open a new issue.
Thank you for your contribution.
