### ISSUE TITLE
[Feature] Input fields

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite-svelte#48]
[Input forms](https://flowbite.com/docs/forms/file-input/)

- [x] Sizes
- [x] Input fields
- [x] Input sizes
- [x] Disabled state
- [x] Validation
- [x] Input group
- [x] Helper text
- [x] Search input
- [ ] Dropdown

**Comment by major-mayer** [comment]
Would it be possible to add a suffix slot/ prop to the text/ number input field?
This would be very useful to show the user for example the format that the number has.
Svelte Material UI does this, for example: https://sveltematerialui.com/demo/textfield#suffixed

**Comment by jjagielka** [comment]
@major-mayer 
Here's an example [REPL](https://svelte.dev/repl/3dbf8550f4ea4b40a50fde3719f89930?version=3.52.0) how to achieve a similar effect.

**Comment by major-mayer** [comment]
Great thanks for the example!
