### ISSUE TITLE
Modal gets clipped if put inside an element with drop shadow

### ISSUE THREAD

**Issue by risalfajar** [themesberg/flowbite-svelte#480]
### Describe the bug

I put a `Modal` inside a div with `drop-shadow-*` tailwind class. This is what happens
![image](https://user-images.githubusercontent.com/28381124/206647002-3db0b3b8-604d-4c9a-b8c4-53233f7cee90.png)

If I remove `drop-shadow-*` it works just fine.

### Reproduction

[REPL](https://svelte.dev/repl/eae5c13e237e44a7aee6b1e10465dd84?version=3.50.1)

### Flowbite version and System Info

```shell
System:
    OS: Linux 6.0 Pop!_OS 22.04 LTS
    CPU: (12) x64 AMD Ryzen 5 PRO 4650G with Radeon Graphics
    Memory: 17.53 GB / 27.30 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Brave Browser: 106.1.44.101
  npmPackages:
    flowbite-svelte: ^0.27.11 => 0.27.11 
    svelte: ^3.52.0 => 3.52.0 
    vite: ^3.1.8 => 3.1.8
```

**Comment by jjagielka** [comment]
This is an interesting case. It seems there's a strange behaviour (incompatibility) between class `fixed` and `drop-shadow`.
I've extracted that to minimal example, but it should be asked at Tailwindcss.
[REPL](https://svelte.dev/repl/07fc64c1eb2d4f588f2250876f14772c?version=3.54.0)
*(Note! You need to touch the left pane for it to render properly)*

**Comment by risalfajar** [comment]
@jjagielka I've searched in their repo, here's the [solution](https://github.com/tailwindlabs/tailwindcss/discussions/9029).

In short: replace `drop-shadow` with `shadow` class.

So I think this issue can be closed then?

**Comment by jjagielka** [comment]
Yes. That's exactly the issue. The child position is affected and as we use `overflow-hidden` in modal, it causes clipping.

Yes, we can close the issue. It has to be treated as a **known limitation**.

Thanks for finding out the solution at Tailwindcss. :)

**Comment by risalfajar** [comment]
Okay, thanks for giving me a direction beforehand :) closing this.
