### ISSUE TITLE
Popover triggered by click doesn't close when clicked outside of the popover

### ISSUE THREAD

**Issue by dorisip** [themesberg/flowbite-svelte#481]
### Describe the bug

The Popover component that is triggered by `click`  doesn't close when you click outside of the popover.

This happens only on Safari (Version 16.1 (18614.2.9.1.12))

### Reproduction

You can reproduce the problem in the example shown in the flowbite svelte page: https://flowbite-svelte.com/components/popover#Triggering

### Flowbite version and System Info

```shell
Safari (Version 16.1 (18614.2.9.1.12))

flowbite-svelte@0.28.3
```

**Comment by jjagielka** [comment]
Thanks for reporting. Just to be sure:
- 'only on Safari' or 'only on Safari v16.1' ?

I'm assuming you have checked some other browsers and it works. Correct?

**Comment by dorisip** [comment]
@jjagielka It works on Chrome, Firefox but not on Safari. I only have one Safari version at the moment, so I'm unsure if it's a specific Safari version.

**Comment by dorisip** [comment]
Also noticed on safari, it works (it closes) when you open the popover, click inside the popover and then click outside the popover.

**Comment by dorisip** [comment]
Also noticed on safari, it works (it closes) when you open the popover, click inside the popover and then click outside the popover.

**Comment by jjagielka** [comment]
@dorisip  When you click the button, does it has (and keep) a focus? Does it have the blue border around it?

Popover listens for the `focusout` event.

**Comment by jjagielka** [comment]
Seems it's a know Safari issue - no focus events on buttons and links.
https://itnext.io/fixing-focus-for-safari-b5916fef1064

I will try to apply suggestions from that article.

@shinokada  You should have caught it, you're Mac user. :)

**Comment by shinokada** [comment]
This thread has been closed because it has not had recent activity. Please open a new issue for related bugs and link to relevant comments in this thread.
