### ISSUE TITLE
NavBar Hamburger button lag

### ISSUE THREAD

**Issue by vfxturjo** [themesberg/flowbite-svelte#485]
### Describe the bug

NavBar is reactive to the size of window. when window size is small (for example: phones) the NavBar shows hamburger menu. Thats good.

But after clicking the hamburger menu, it opens after around 200-300ms delay, before starting the animation. the animation should start immediately.

### Reproduction

It is happening in my app, and also in the website example.

you can see it by:
1. open -> https://flowbite-svelte.com/components/navbar
2. make the browser window size narrow enough so that the hamburger button is shown, like this
![image](https://user-images.githubusercontent.com/44445014/206838240-5a65aaeb-c5c8-418b-b8ed-7ef09ae57fe7.png)
3. Click on the hamberger button and observe the delay

By the way, original flowbite website doesn't have the delay. you can see from this link ( https://flowbite.com/docs/components/navbar/ ) and with same procedure. 

### Flowbite version and System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i3-8130U CPU @ 2.20GHz    
    Memory: 2.30 GB / 7.90 GB
  Binaries:
    Node: 16.17.0 - D:\_installed software\NodeJS\node.EXE   
    npm: 9.1.3 - D:\_installed software\NodeJS\npm.CMD       
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.42)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    flowbite-svelte: ^0.28.4 => 0.28.4 
    svelte: ^3.52.0 => 3.53.1 
    vite: ^3.2.3 => 3.2.5
```

**Comment by shinokada** [comment]
@jjagielka

**Comment by jjagielka** [comment]
`src/lib/navbar/NavbarUl.svelte:24`
```svelte
  <div {...$$restProps} class={_divClass} transition:slide={{ delay: 250, duration: 500, easing: quintOut }}>
```

This is not my code, I don't know why that delay was introduced here.

**Comment by shinokada** [comment]
We can export it the params as a prop.

**Comment by galaczi** [comment]
Am I the only one who still feels there is a delay?
