### ISSUE TITLE
Button "yellow" & "light" with gradient is rendering black

### ISSUE THREAD

**Issue by Rar9** [themesberg/flowbite-svelte#486]
### Describe the bug
 Button "yellow" with gradient is rendering black 

### Reproduction

`<Button gradient color="yellow">test</Button>`
`<Button gradient color="light">test</Button>`

### Flowbite version and System Info

```shell
"flowbite": "^1.5.5",
"flowbite-svelte": "^0.28.11
```

**Comment by Rar9** [comment]
This is extremely disappointing.

So better to change to different more flexible library

**Comment by jjagielka** [comment]
You can always use the `custom` mode in the same way as with all colorful components:
```html
<Button color="none" class="bg-gradient-to-r from-yellow-500 via-gray-600 to-sky-700">
```

**Comment by shinokada** [comment]
I close the issue for now.
Thank you for your contribution.
Feel free to open a new issue.
