### ISSUE TITLE
Forward on:contextmenu

### ISSUE THREAD

**Issue by adwinjb** [themesberg/flowbite-svelte#487]
## Summary

Binding custom context menus is currently not possible due to this event not being forwarded.

### Basic example

Forward the event just as it's done with on:click

### Motivation

It would enable easier access to bind custom context menus without having to wrap components in regular <div></div> which sometimes breaks component design.

**Comment by jjagielka** [comment]
That sounds reasonable, but we need to be careful which components should forward that. 

For example, in my opinion there's no sense for context menu on buttons or dropdowns.

**Comment by adwinjb** [comment]
I can understand wanting to be careful with forwarding certain events, but I don't see the harm in forwarding contextmenu on some or all of them as it's relatively harmless and I don't see a chance for many people to be accidentally (mis)using it. Maybe there's something regarding event forwarding that I don't know about?

For example in our app, we use right click on a lot of components that might seem odd to have it on (including dropdowns), this is to be able to apply filters on the values of the component without cluttering the UI.

**Comment by shinokada** [comment]
No objection. But we need to check WAI-ARIA so that we component should/shouldn't to have it.

**Comment by shinokada** [comment]
Just for your note: Current `svelte:element` has [problems](https://github.com/sveltejs/kit/issues/8217) with event forwarding.

**Comment by shinokada** [comment]
@adwinjb Can you suggest which components you want to add to?

**Comment by adwinjb** [comment]
@shinokada absolutely, these are the ones I've got it on so far with custom components that I've just copied from your source code

- TableBodyHeadCell
- TableBodyRow
- Card
- Input
- Textarea
- Select

**Comment by shinokada** [comment]
I think TableBodyHeadCell is deprecated.
