### ISSUE TITLE
TypeScript error when using `class="divide-y"` in table code from docs

### ISSUE THREAD

**Issue by tqwewe** [themesberg/flowbite-svelte#495]
### Describe the bug

I am trying to use the table code provided in the documentation, but when I include the `class="divide-y"` attribute, I get the following TypeScript error:

> Type 'string' is not assignable to type 'never'

### Reproduction

Simply copy the code from the svelte table docs in a typescript project.

```html
<script>
  import { Table, TableBody, TableBodyCell, TableBodyRow, TableHead, TableHeadCell } from 'flowbite-svelte';
</script>

<Table>
  <TableHead>
    <!-- ... -->
  </TableHead>
  <TableBody class="divide-y"> <!-- Typescript error here on class attribute -->
    <TableBodyRow>
        <!-- ... -->
    </TableBodyRow>
  </TableBody>
</Table>
```

### Flowbite version and System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 1.96 GB / 32.00 GB
    Shell: 0.68.1 - /Users/ari/.cargo/bin/nu
  Binaries:
    Node: 18.12.0 - ~/Library/Caches/fnm_multishells/48147_1671124697592/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/kit: ^1.0.0 => 1.0.0 
    flowbite-svelte: ^0.28.11 => 0.28.11 
    svelte: ^3.54.0 => 3.55.0 
    vite: ^4.0.0 => 4.0.1
```

**Comment by shinokada** [comment]
I'm not sure why it has type error, because the [component](https://github.com/themesberg/flowbite-svelte/blob/main/src/lib/tables/TableBody.svelte) has a simple code;

```
<tbody {...$$props}>
  <slot />
</tbody>
```

Do you have other codes that has type errors?

**Comment by shinokada** [comment]
[stackblitz example](https://stackblitz.com/edit/sveltejs-kit-template-default-c47jfs?file=src/routes/+page.svelte)

**Comment by tqwewe** [comment]
I just upgraded from `flowbite-svelte` `0.28.11` to `0.29.1` and the problems seems to be resolved. It also seems to have fixed some other type errors too apparently just from the upgrade.

**Comment by tqwewe** [comment]
I realised it actually didnt solve my error 🤦 It mustve been delayed after reloading VSCode.

**Comment by tqwewe** [comment]
When I ctrl click on the TableBody, this is the types file it shows:
```ts
/** @typedef {typeof __propDef.props}  TableBodyProps */
/** @typedef {typeof __propDef.events}  TableBodyEvents */
/** @typedef {typeof __propDef.slots}  TableBodySlots */
export default class TableBody extends SvelteComponentTyped<{
    [x: string]: never;
}, {
    [evt: string]: CustomEvent<any>;
}, {
    default: {};
}> {
}
export type TableBodyProps = typeof __propDef.props;
export type TableBodyEvents = typeof __propDef.events;
export type TableBodySlots = typeof __propDef.slots;
import { SvelteComponentTyped } from "svelte";
declare const __propDef: {
    props: {
        [x: string]: never;
    };
    events: {
        [evt: string]: CustomEvent<any>;
    };
    slots: {
        default: {};
    };
};
export {};
```

**Comment by shinokada** [comment]
Can you try v0.29.2?
Please use `tableBodyClass="your-class-here"` and let me know.

**Comment by tqwewe** [comment]
`tableBodyClass` works now.
But I feel like the prop name is a little strange, since its the one and only prop `TableBody` has. It would be nice if it could still be `class="..."`. Or even `divided` prop to add `divide-y` automatically.

But I'll close this issue for now, thanks for the fast responses!

**Comment by shinokada** [comment]
Yes, I will change it so that you can use `class`.

**Comment by alexander-mart** [comment]
@themesberg can we fix the document page? I can't find doc repo.

Code (tableBodyClass prop):
https://github.com/themesberg/flowbite-svelte/blob/main/src/lib/tables/TableBody.svelte#L2

Docs (class prop):
https://flowbite-svelte.com/docs/components/table
