### ISSUE TITLE
Can we use Windi CSS instead of Tailwind?

### ISSUE THREAD

**Issue by JohanHeyvaert** [themesberg/flowbite-svelte#501]
## Summary

I've just learned about Windi CSS (https://windicss.org/) and it looks like a superior alternative to Tailwind. According to what I've read it also offers better performance. 

Do you think that Flowbite can be used together with Windi (instead of Tailwind)?

### Motivation

Most importantly: improved performance (for developers and users).
(interesting read BTW: https://antfu.me/posts/reimagine-atomic-css)

**Comment by shinokada** [comment]
@JohanHeyvaert You should ask this question at Flowbite, https://github.com/themesberg/flowbite/issues.

**Comment by JohanHeyvaert** [comment]
OMG, I'd totally missed that Flowbite isn't just for Svelte (I'd never heard of it before)... 
That explains why this package is so feature rich!

I'll post this question there, thanks for your advice!
