### ISSUE TITLE
Popover fights inline for Chromium browsers

### ISSUE THREAD

**Issue by Lachee** [themesberg/flowbite-svelte#502]
### Describe the bug

In chromium based browsers (tested Chrome and Edge), the popover will move the inline blocks it's attached too. This results in the inline block being moved away from the mouse, unfocusing the popover (making it disappear) which causes the inline block to move back and restart the cycle. 

The overall result is that the popover flashes and the page layout goes crazy as shown in the video below:
https://i.lu.je/2022/firefox_CXvlZWJgJA.mp4
(video shows it working correctly on Firefox, then switches to Chrome where is misbehaves) 

This does not happen with Firefox, which behaves correctly.

### Reproduction

https://gist.github.com/Lachee/e0c5cfa98343190852e3e4c68d07a008

### Flowbite version and System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 19.21 GB / 31.95 GB
  Binaries:
    Node: 16.16.0 - D:\Program Files\nodejs\node.EXE
  Browsers:
    Chrome: 108.0.5359.125
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.54)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/kit: ^1.0.1 => 1.0.1
    flowbite-svelte: ^0.28.11 => 0.28.11
    svelte: ^3.55.0 => 3.55.0
    vite: ^4.0.2 => 4.0.2
```

## Addendum
This happens in Flowbite-Svelte 0.29.3 too

**Comment by jjagielka** [comment]
There are some know issues with Chrome and `display: inline-block` css as quick web search shows. I'm not specialist here so I'm in no position to solve it.

However I'd recommend the different approach to that issue. Try to re-use the same popover for multiple elements instead of connecting each `Item` with it's own `Popover`. Check the example: https://flowbite-svelte.com/components/tooltip#Placement

Quick and dirty example of how to apply that method to your case you can find here: https://gist.github.com/jjagielka/0fb03a78164e3c393b0d32a8af77f7a2

**Comment by Lachee** [comment]
> There are some know issues with Chrome and `display: inline-block` css as quick web search shows. I'm not specialist here so I'm in no position to solve it.
> 
> However I'd recommend the different approach to that issue. Try to re-use the same popover for multiple elements instead of connecting each `Item` with it's own `Popover`. Check the example: https://flowbite-svelte.com/components/tooltip#Placement
> 
> Quick and dirty example of how to apply that method to your case you can find here: https://gist.github.com/jjagielka/0fb03a78164e3c393b0d32a8af77f7a2

This gist works. Will need to tidy it up as getItem is actually asynchronous behind the scenes but does the job. Don't like having to have a root popover tho, so i might make a new component called ItemPopoverContext that just encapsulates whatever needs a popover :3

**Comment by jjagielka** [comment]
When each time you create the popover/tooltip there's a hidden div created.
Your initial solution is creates a DOM like:
```html
<span class="inline-block">..</span><div hidden>popup</div><span class="inline-block> ...
```
And once you put the mouse over the popover it it gets visible and "destroys" the flow of `inline-block`s, although it shouldn't as its position is fixed/absolute

Knowing that the second solution to your problem would be then to supply the `inline-block` class to popover.
```svelte
<Popover triggeredBy=".{pid}" strategy="fixed" class="z-[9999] inline-block">
...
```

**Comment by jjagielka** [comment]
@Lachee - are you happy with the solution 2? Can we close the issue?
