### ISSUE TITLE
[Feature] Textarea input

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite-svelte#51]
[Textarea input](https://flowbite.com/docs/forms/textarea/)
- [x] Textarea 
- [x] WYSIWYG editor
- [x] Comment box
- [x] Chatroom input

https://github.com/umaranis/svelte-lexical Is a good option to use.

**Comment by jjagielka** [comment]
I think we can close that one now.

**Comment by shinokada** [comment]
Thanks.
