### ISSUE TITLE
Form input validation does not change input background color

### ISSUE THREAD

**Issue by developomp** [themesberg/flowbite-svelte#510]
### Describe the bug

How it looks like in Flowbite-svelte:
![image](https://user-images.githubusercontent.com/40858122/210162704-84f44f4e-37d7-4268-8677-e6bd0735e936.png)

How it should look like:
![image](https://user-images.githubusercontent.com/40858122/210162706-2afe850e-c93f-469c-bfd6-c5c036ca7bc2.png)

### Reproduction

Demonstrated in:
- https://flowbite-svelte.com/forms/input-field#Validation
- https://flowbite.com/docs/components/forms/#form-validation

### Flowbite version and System Info

```shell
System:
    OS: Linux 6.1 Arch Linux
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 6.33 GB / 15.41 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.3.0 - /usr/bin/node
    Yarn: 1.22.19 - ~/.npm-global/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
```

**Comment by jjagielka** [comment]
That's an inconsistency of Flowbite.com. Take a look at:
- https://flowbite.com/docs/forms/input-field/#validation

**Comment by developomp** [comment]
Ah. Thank you for letting me know. However, I still think this is worth "fixing" as the text in the svelte component is completely unreadable.

https://flowbite.com/docs/forms/input-field/#validation
![image](https://user-images.githubusercontent.com/40858122/210166842-e2e78821-986b-465a-a2b8-e6c3e76b7a39.png)

https://flowbite-svelte.com/forms/input-field#Validation
![image](https://user-images.githubusercontent.com/40858122/210166843-ce2974b3-2279-4f10-b1bd-7222baaa7fb5.png)

**Comment by developomp** [comment]
FYI, the placeholder text color seems to be fixed but as soon as you start typing the text becomes completely unreadable again.

**Comment by shinokada** [comment]
@developomp Please update it to @0.29.9 and let us know.
