### ISSUE TITLE
Search input button is not clickable

### ISSUE THREAD

**Issue by developomp** [themesberg/flowbite-svelte#511]
### Describe the bug

The "search" button in search input is not clickable whereas the one from the original website is.

### Reproduction

Demonstrated in:
- https://flowbite-svelte.com/forms/input-field#Search_input
- https://flowbite.com/docs/forms/search-input/#search-bar-example

### Flowbite version and System Info

```shell
System:
    OS: Linux 6.1 Arch Linux
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 5.47 GB / 15.41 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.3.0 - /usr/bin/node
    Yarn: 1.22.19 - ~/.npm-global/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
```

**Comment by jjagielka** [comment]
You should use https://flowbite-svelte.com/forms/search-input for `Search` component.
This implementation here is for `Input` element completeness. However bug noted.

**Comment by jjagielka** [comment]
Correction added to PR #512

**Comment by shinokada** [comment]
Updated v0.29.8

**Comment by jjagielka** [comment]
So we can close, can't we?

**Comment by shinokada** [comment]
I close the issue for now.
Please feel free to create another issue.
Thank you for your contribution.
