### ISSUE TITLE
Modal is not centered for custom width and height

### ISSUE THREAD

**Issue by dennismphil** [themesberg/flowbite-svelte#523]
### Describe the bug

Modal is not centered when a custom width or height is provided.

Suggested code change:

https://github.com/themesberg/flowbite-svelte/blob/main/src/lib/modals/Modal.svelte#L127

![2023-01-10_21-19-49](https://user-images.githubusercontent.com/4141366/211724150-fda0ce17-ad62-451f-afcd-6ab805df29fb.png)

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-tzb7ta?file=src/routes/+page.svelte

![2023-01-10_21-13-39](https://user-images.githubusercontent.com/4141366/211723443-9ce5557d-4e94-481c-9ab2-5a651a0b0cf6.png)

### Flowbite version and System Info

```shell
"flowbite": "^1.5.4",
"flowbite-svelte": "0.28.4",
```

**Comment by dennismphil** [comment]
May be related to https://github.com/themesberg/flowbite-svelte/pull/519

**Comment by jjagielka** [comment]
@dennismphil - new PR sent #526 
Can you check if that address your issue as well?
