### ISSUE TITLE
Listgroup items not typed

### ISSUE THREAD

**Issue by 1r00t** [themesberg/flowbite-svelte#534]
### Describe the bug

When using Listgroup I get a type error for items.
Here is the example I use from the docs:
```js
<script lang="ts">
    import { Listgroup } from 'flowbite-svelte'

    let links = [
        { name: "Accordions", href: "/accordions", current: true },
        { name: "Alerts", href: "/alerts" },
        { name: "Badges", href: "/badges"  },
        { name: "Breadcrumbs", href: "/breadcrumbs" },
    ];
</script>

<Listgroup active items={links} let:item class="w-48">
	{item.name}
</Listgroup>
```

I get the following type error for `let:item` on `<Listgroup />`:
```
Property 'item' does not exist on type '{}'.
```

![grafik](https://user-images.githubusercontent.com/9479785/212664712-1683aee8-263b-4d57-8bee-70f89139c7d3.png)

### Reproduction

https://svelte.dev/repl/930d39fbd10b4e5b8581fb20d3a3192e?version=3.55.1

### Flowbite version and System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 12.69 GB / 15.62 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 109.0.5414.74
    Firefox: 108.0.2
  npmPackages:
    @sveltejs/kit: ^1.0.0 => 1.1.1
    flowbite-svelte: ^0.29.9 => 0.29.10
    svelte: ^3.54.0 => 3.55.1
    vite: ^4.0.0 => 4.0.4
```

**Comment by dippa-1** [comment]
Same issue here.
For a temporary workaround you can insert `@ts-nocheck` just below the `<script>` tag inside your .svelte file.

It will disable type checking for this file so no more compiler errors.

**Comment by dippa-1** [comment]
I'm using a `{#each ...}` loop with `ListgroupItem` inside `Listgroup`. Does the same
