### ISSUE TITLE
Admin dashboard

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite-svelte#536]
## Summary

- [Github repo](https://github.com/themesberg/flowbite-admin-dashboard)

It would be nice to have a Svelte version. If we make this, I think we need to create a new repo.

### Basic example

- [Demo](https://flowbite-admin-dashboard.vercel.app/)

**Comment by MSufianS** [comment]
> ## Summary
> * [Github repo](https://github.com/themesberg/flowbite-admin-dashboard0
> 
> It would be nice to have a Svelte version. If we make this, I think we need to create a new repo.
> 
> ### Basic example
> * [Demo](https://flowbite-admin-dashboard.vercel.app/)

Typo: [https://github.com/themesberg/flowbite-admin-dashboard](url)

**Comment by zoltanszogyenyi** [comment]
Hey @shinokada, @MSufianS,

I have created a repository on behalf of the Themesberg organization and I've already invited @shinokada as a maintainer.

It should be licensed under the MIT license and when a stable release will be made we will reference it in the original dashboard README file and preview it.

https://github.com/themesberg/flowbite-svelte-admin-dashboard

Cheers,
Zoltan

**Comment by shinokada** [comment]
Moved to https://github.com/themesberg/flowbite-svelte-admin-dashboard.
