### ISSUE TITLE
ToggleDarkTheme should not use localStorage

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite-svelte#540]
### Describe the bug

[ToggleDarkTheme should not use localStorage](https://github.com/themesberg/flowbite-react/issues/546)

Flowbite-Svelte uses `localStorage` in the DarkMode component.
We need to show cookie consent in order to be compliant with the General Data Protection Regulation (GDPR). And the popup can be added for the message in the DarkMode component.

### Reproduction

DarkMode module.

### Flowbite version and System Info

```shell
N/A
```

**Comment by zoltanszogyenyi** [comment]
Hey @shinokada,

I wouldn't rush into this, not yet. All of the major libraries and frameworks do this without a consent opt-in and I will also contact a GDPR lawyer to sort things out - so please hold off the issue for a few days.

Additionally, even if we are to implement some form of consent it would probably be better to show it in the form of a tooltip or popover on top of the theme switcher when the user hovers - there is no need to show a whole cookie modal just for this.

This would severely affect the UI/UX of the website for a GDPR compliance reason that is not yet sorted out.

Thanks,
Zoltan

**Comment by zoltanszogyenyi** [comment]
Hey @shinokada,

It looks like we will hold this off for now. One of the creators of Material UI also stepped into the discussion and advised us that it does not in fact violate the GDPR laws - considering that every other major CSS framework does the same thing we won't be removing this from the localStorage or showing a cookie modal unless we set other cookies.

https://github.com/themesberg/flowbite-react/issues/546

Cheers,
Zoltan

**Comment by shinokada** [comment]
Thanks, @zoltanszogyenyi . I close the issue for now.
