### ISSUE TITLE
 flowbite-svelte layout/grid page 

### ISSUE THREAD

**Issue by 3goats** [themesberg/flowbite-svelte#542]
Hi just started playing with your excellent flowbite-svelte UI framework. The only thing I'm struggling with is getting started with a decent page layout. Is there anything like a grid planned or is there something that already exists that can handle getting a basic page built? 

Ideally it would be great if there was a boilerplate that included the headers/footers and maybe a simple nav bar.

Motivation here is really speed. I want to use Sveltkit/flowbite-svelte to buildout some internal demo apps but don't have much time to spend on this.

**Comment by shinokada** [comment]
Flowibite-Svelte is a UI component and does not provide layouts. It is up to you how you use them.
But there are a couple of starters you can use.

- [flowbite-svelte-starter](https://github.com/shinokada/flowbite-svelte-starter)
- [flowbite-svelte-blocks](https://github.com/shinokada/flowbite-svelte-blocks)
- [flowbite-sveltekit-responsive-sidebar-layout](https://sveltekit-sidebar-layout.vercel.app/)

**Comment by carlskii** [comment]
Thanks for this. I also see that Skeleton provides an App Bar, App Rail and App Shell: 

https://www.skeleton.dev/components/app-bar
https://www.skeleton.dev/components/app-rail
https://www.skeleton.dev/components/app-shell

Some components that provide this would be a great starting point.

**Comment by ESchouten** [comment]
I agree, Skeletons [AppShell](https://www.skeleton.dev/components/app-shell) is IMO my most missed feature of Flowbite Svelte

**Comment by shinokada** [comment]
I just create a issue on https://github.com/themesberg/flowbite/issues/560.

**Comment by shinokada** [comment]
I close the issue for now.
Thank you for your contribution.
Please feel free to open a new issue when you are clear about the problem.

**Comment by shinokada** [comment]
@3goats After discussion on this PR, https://github.com/themesberg/flowbite-svelte/pull/1058 we decided not to have layout components.
But please feel free to use the above link for your reference.
Sorry.
