### ISSUE TITLE
Drawer only opening once when outsourced to component

### ISSUE THREAD

**Issue by davbauer** [themesberg/flowbite-svelte#543]
### Describe the bug

The Drawer Component does not work as expected when exported as an component.

As you will see in the REPL, the 'Drawer' opens and closes as expected, but when reopening the 'Drawer' a second time it will not open anymore.

Not sure if its a fault of me missing something..

Thanks in advance!

### Reproduction

https://svelte.dev/repl/9d23c1c5253148328c125d17e62e186d?version=3.55.1

### Flowbite version and System Info

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 331.44 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.4.0 - /opt/homebrew/bin/node
    npm: 9.2.0 - /opt/homebrew/bin/npm
  Browsers:
    Brave Browser: 109.1.47.171
    Chrome: 109.0.5414.87
    Safari: 16.2
  npmPackages:
    @sveltejs/kit: ^1.0.0 => 1.1.1 
    flowbite-svelte: ^0.29.10 => 0.29.10 
    svelte: ^3.54.0 => 3.55.1 
    vite: ^4.0.0 => 4.0.4
```

**Comment by shinokada** [comment]
You are not changing the state of `hidden4`. Try this:

```
<script>
    import { Button, CloseButton, Drawer, Input, Label } from "flowbite-svelte";
    import DrawerComponent from "./DrawerComponent.svelte";
    let hidden4 = true
$: 	console.log('app: ', hidden4)
</script>


<div class="text-center">
    <Button on:click={() => (hidden4 = !hidden4)}>Show drawer form</Button>
 </div>

<DrawerComponent drawerHidden={hidden4} />
```

**Comment by davbauer** [comment]
Thanks for the fast response,
but this only fixed the problem partially as you can see with the code you provided:
https://svelte.dev/repl/5fffa7913e5e47ce899c93c3fb80cfa5?version=3.55.1

When now opening the drawer, and closing it via the 'X' in the drawer and clicking again 'Show drawer form' it will only show in the second click..

I expect it to open when clicking the 'Show drawer form', getting closed via the 'X' and being able to get reopened again on the first click.

**Comment by angrytongan** [comment]
You need to bind `hidden4` in the parent:

```svelte
<DrawerComponent bind:drawerHidden={hidden4} />
```

**Comment by davbauer** [comment]
Svelte REPL is not working for me right now. I am gonna try it later tho, thx!

**Comment by shinokada** [comment]
Thank you for your contribution! We are closing this issue for now due to inactivity. If you encounter any other problems in the future, please feel free to open a new issue. We appreciate your help in making our project better!
