### ISSUE TITLE
Issues with Tabbable fields in Modals

### ISSUE THREAD

**Issue by mikerowe81** [themesberg/flowbite-svelte#546]
### Describe the bug

Issue 1 - conditional elements
If a `<Modal>` contains conditional elements (e.g. `<Accordion>` or `{#if}{/if}`) that contain tabbable fields, you will not be able to tab to these fields once the elements are created.

Issue 2 - hidden elements
If a `<Modal>` contains hidden (`display: none`) tabbable elements, the focus will get stuck on the previous visible element and the tab key will stop working.

### Reproduction

https://svelte.dev/repl/80dbfeb4d85249db8cb9a909c15fbf26?version=3.55.1

### Flowbite version and System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 5.60 GB / 31.96 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 109.0.5414.75
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/kit: ^1.0.1 => 1.0.1
    flowbite-svelte: ^0.29.11 => 0.29.11
    svelte: ^3.55.0 => 3.55.0
    vite: ^4.0.1 => 4.0.1
```

**Comment by shinokada** [comment]
I close the issue for now since we added the requested function.
Thank you for your contribution.
Please feel free to open a new issue when you are clear about the problem.
