### ISSUE TITLE
Datepicker: prop 'datepickerFormat' only working in single field

### ISSUE THREAD

**Issue by davbauer** [themesberg/flowbite-svelte#547]
### Describe the bug

When adding the `datepickerFormat` prop to a `Datepicker` component it won't work when range prop passed to it.

I expect it to use my provided format.

### Reproduction

Bug not reproduceable in Svelte-REPL (error on compilation)

Code: 

```ts
<script lang='ts'>
	import { Datepicker } from 'flowbite-svelte';
</script>

<Datepicker range datepickerFormat="dd/mm/yyyy" /> <br>
<Datepicker datepickerFormat="dd/mm/yyyy" />
```

Result:

![Screenshot 2023-01-21 at 11 58 24](https://user-images.githubusercontent.com/89662560/213863864-77a9239f-4d92-43f6-a8de-5c8f206639b5.jpg)

### Flowbite version and System Info

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 584.30 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.4.0 - /opt/homebrew/bin/node
    npm: 9.2.0 - /opt/homebrew/bin/npm
  Browsers:
    Brave Browser: 109.1.47.171
    Chrome: 109.0.5414.87
    Safari: 16.2
  npmPackages:
    @sveltejs/kit: ^1.0.0 => 1.2.0 
    flowbite-svelte: ^0.29.10 => 0.29.11 
    svelte: ^3.54.0 => 3.55.1 
    vite: ^4.0.0 => 4.0.4
```

**Comment by shinokada** [comment]
Yup. The date picker component is experimental.

**Comment by davbauer** [comment]
Is there already a way to bind the value from a `Datepicker` componen tho? If yes, I couldn't find a way..

**Comment by shinokada** [comment]
This component uses the external library, flowbite-datepicker. That's why it is not fully integrated.

**Comment by shinokada** [comment]
Thank you for your contribution! We are closing this issue for now due to inactivity. If you encounter any other problems in the future, please feel free to open a new issue. We appreciate your help in making our project better!
