### ISSUE TITLE
Submit form not response

### ISSUE THREAD

**Issue by MSufianS** [themesberg/flowbite-svelte#550]
### Describe the bug

I click submit on form no response.

Refer: https://flowbite-svelte.com/components/modal

### Reproduction

I fixed my problem when I remove this line or not using "autoclose",

https://github.com/themesberg/flowbite-svelte/blob/d52920fe869183639788607475b148c80fe283fa/src/lib/modals/Modal.svelte#L119

### Flowbite version and System Info

```shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 89.22 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    npm: 9.2.0 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Safari: 16.2
```

**Comment by jjagielka** [comment]
I think we can close that one.

**Comment by shinokada** [comment]
Thank you for your contribution. We close the issue for now. Please feel free to open a new issue.
