### ISSUE TITLE
Theming components

### ISSUE THREAD

**Issue by EliasGit117** [themesberg/flowbite-svelte#555]
## Summary
Make components use some abstract classes from theme. It will give possibility to overwrite some style for own need. For example background for Card component. Right now I'm just wrapping existing components above yours.

### Basic example

Card component. Instead of using "bg-gray-100 dark:hover:bg-gray-700" why not write like "bg-card"? So people would be capable to customize the appereance of components just ones in theme.

### Motivation

To make UI kit more reusable and customizable

**Comment by tutkli** [comment]
Found the same issue while working with Inputs. This would be useful if you want to use brand colors.

**Comment by shinokada** [comment]
Why not extend your `tailwind.config.cjs` and use it?

**Comment by tutkli** [comment]
Sorry @shinokada , what do you mean by that?

**Comment by shinokada** [comment]
The [`tailwind.config.cjs`](https://github.com/themesberg/flowbite-svelte/blob/main/tailwind.config.cjs) has sample codes to add a custom theme.
The following code is not tested, but something like this.
```
theme: {
    extend: {
      backgroundColor: {
        'bg-card': 'bg-gray-100 dark:hover:bg-gray-700',
      },
    },
  },
```

Then you can use `bg-card` to the props.
Hope it makes sense.

**Comment by EliasGit117** [comment]
@shinokada but I will need to pass it every time

**Comment by shinokada** [comment]
Once you set your theme, you can use the class globally.

**Comment by alexauvray** [comment]
What if the component is generating a nested div? How can I style it?

Here, the <Card> component is generating a div which has `p-4 sm:p-6` as class. 

How can I add another class to that nested generated element?


```
<div class="bg-white dark:bg...>
    <img class="rounded-t-lg" src="https://i.....>
          <div class="p-4 sm:p-6">
```
