### ISSUE TITLE
Datepicker: scrolling issue

### ISSUE THREAD

**Issue by Jedliu** [themesberg/flowbite-svelte#558]
### Describe the bug

1. The datepicker popup doesn't scroll along when the page scrolls. When click and select a date, there will be two datepicker popups.
2. The datepicker popup is hidden if the datepicker input is near the end of the page

### Reproduction

1. Go to the page [https://flowbite-svelte.com/datepicker](https://flowbite-svelte.com/datepicker). Click on the datepicker and scroll the page then select the date.
![two popup instances](https://user-images.githubusercontent.com/771703/216741000-31f3fdff-4279-4217-ac42-cf1cb3cbc207.jpg)

2. Go to the page [https://flowbite-svelte.com/datepicker](https://flowbite-svelte.com/datepicker).  Scroll one of the datepicker near the end of the page and then click the input.
![invisible popup](https://user-images.githubusercontent.com/771703/216741199-25305e10-23db-438c-bcc0-bbf5d598363e.jpg)

### Flowbite version and System Info

```shell
Browser: Chrome, Safari, Brave Browser
```

**Comment by Destaq** [comment]
Also noticed; commenting to bump the issue.

**Comment by shinokada** [comment]
Currently no plan to update the datepicker component. We will be happy to see your PRs.

**Comment by shinokada** [comment]
Thank you for your contribution! We are closing it for now due to inactivity. If you encounter any other problems in the future, please feel free to open a new issue. We appreciate your help in making our project better!
