### ISSUE TITLE
Fluid width Navbar?

### ISSUE THREAD

**Issue by wrabit** [themesberg/flowbite-svelte#561]
## Summary

To allow fluid width of navbar to fill outer container instead of using `container` class. The design I am building requires the header to be 100% width of the viewport. 

### Basic example

<Navbar let:container={false} />

### Motivation

To be more diverse in the layout design of the designer's choice.

**Comment by shinokada** [comment]
Thank you for your issue.
I think you can ask this to [Flowbite issue](https://github.com/themesberg/flowbite/issues).

**Comment by wrabit** [comment]
'container' is just user preference? For example, in their own docs page, they omitted it..

**Comment by shinokada** [comment]
@jjagielka Any thoughts?

**Comment by wrabit** [comment]
Looking at the component, seems we can just:

`<Navbar let:hidden let:toggle fluid={false}>`

Seems like it's the wrong way though - I would say fluid=true should be the 100% width.

**Comment by jjagielka** [comment]
Yes, you're right. It should be reversed. I'll correct it in the minute.
