### ISSUE TITLE
Correct type for inputs

### ISSUE THREAD

**Issue by isaacfink** [themesberg/flowbite-svelte#562]
## Summary

Brief explanation of the feature.
Would be cool if the input with type number automatically enforces the correct type, right now it doesn't 

### Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

On a recent project I had to specify a number of rows and columns for a grid, I realized that this only works initially but not if I change the value with an input field and after some debugging I saw that the value changes from a number to a string, svelte does have the correct behavior by default

**Comment by shinokada** [comment]
Please read [this thread](https://github.com/themesberg/flowbite-svelte/issues/344)
