### ISSUE TITLE
Sidebar custom icons

### ISSUE THREAD

**Issue by troncomputers** [themesberg/flowbite-svelte#57]
Is there a chance to use custom icons in `Sidebar` for example [PhosphorIcons](https://phosphoricons.com/)?

**Comment by shinokada** [comment]
Yes, if they have Svelte icons.
I will create Svelte icons for Phosphoricons.

Meanwhile you can use following icons:
- [Svelte-Lucide](https://www.npmjs.com/package/svelte-lucide) 
- [Svelte-heros](https://www.npmjs.com/package/svelte-heros) 
- [Svelte-simples](https://www.npmjs.com/package/svelte-simples) 
- [Svelte-feathericons](https://www.npmjs.com/package/@codewithshin/svelte-feathericons)

**Comment by shinokada** [comment]
I think you can use [Phosphor-Svelte](https://www.npmjs.com/package/phosphor-svelte).

**Comment by troncomputers** [comment]
How am I able to style selected icon in links variable
```typescript
  let links = [
    {
      id: uid++,
      name: 'Dashboard',
      href: '/',
      icon: Horse,
    },
    {
      id: uid++,
      name: 'E-commerce',
      icon: Horse,
      href: '/',
      subtext: '3',
    },
    {
      id: uid++,
      name: 'Kanban',
      icon: Heart,
      href: '/',
      subtext: 'Pro',
    },
    {
      id: uid++,
      name: 'Inbox',
      icon: Heart,
      href: '/',
    },
    {
      id: uid++,
      name: 'Users',
      icon: Heart,
      href: '/',
    },
    {
      id: uid++,
      name: 'Sign In',
      icon: Heart,
      href: '/',
    },
    {
      id: uid++,
      name: 'Setting',
      icon: Heart,
      href: '/',
    },
  ];
```
Phosphor icons styling 

```svelte
<Heart color="#AE2983" weight="fill" size="{32}" />
```

**Comment by shinokada** [comment]
Try as Phosphor does and let me know.

**Comment by shinokada** [comment]
Close it for now.
