### ISSUE TITLE
Select should support `any` type values for options

### ISSUE THREAD

**Issue by vsergeev** [themesberg/flowbite-svelte#588]
## Summary

Currently, `Select` only supports `string | number` typed [values](https://github.com/themesberg/flowbite-svelte/blob/v0.29.7/src/lib/forms/Select.svelte#L6) and [items](https://github.com/themesberg/flowbite-svelte/blob/v0.29.7/src/lib/types.ts#L186). However, it should accept `any` typed value.

### Basic example

```
const items = [
  { name: 'Stem bolt', value: {price: 5, quantity: 1000}},
  { name: 'Phaser', value: {price: 1000, quantity: 6}},
];

let value;

...

<Select bind:value={value} {items} />
```

### Motivation

`Select` is more useful with generically typed values and already works with them, only the typechecking fails. Svelte itself advertises this support natively: https://svelte.dev/tutorial/select-bindings

**Comment by shinokada** [comment]
I will see if the following type works:

```
export type SelectOptionType<T> = {
  name: string | number;
  value: T;
};
```

So that you can use it like this:

```
type ProductType = {
  price: number;
  quantity: number;
};

const items: SelectOptionType<ProductType>[] = [
  { name: 'Stem bolt', value: { price: 5, quantity: 1000 } },
  { name: 'Phaser', value: { price: 1000, quantity: 6 } },
];
```

But I have to test it first.

**Comment by mike-lloyd03** [comment]
I like this change. However, I'm not sure how to make the best use of it. If I pass an object as a value in a form, the form action on the server receives text `[Object object]`. How can I get the form action to receive the actual JSON object?

**Comment by vsergeev** [comment]
You'd need to serialize the values if you're POSTing them for a form, e.g. with a custom submit handler, since HTTP only supports basic URL encoded form data. Using non-string types in input components like this is more of a convenience in purely client-side contexts.
