### ISSUE TITLE
Sidebar Dropdown Wrapper custom transition not being applied

### ISSUE THREAD

**Issue by BrunoFrancaSouza** [themesberg/flowbite-svelte#589]
### Describe the bug

When using [Multi-level dropdown ](https://flowbite-svelte.com/components/sidebar#Multi-level_dropdown) inside the `Sidebar.svelte` component is impossible to pass a custom transition value to be applied when the user clicks on the button to show or hide the `SidebarDropdownItem.svelte` child items.

I was not able to find a way to do it. I think the problem is [at this line](https://github.com/themesberg/flowbite-svelte/blob/main/src/lib/sidebars/SidebarDropdownWrapper.svelte#L45), which hardcode the transition value and does not have in count any external parameter.

### Reproduction

https://svelte.dev/repl/265252f5de9f4fe0ab039af2b0421cff

### Flowbite version and System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 7.63 GB / 15.93 GB
  Binaries:
    Node: 18.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1265.0), Chromium (110.0.1587.57)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/kit: ^1.5.0 => 1.8.5 
    flowbite-svelte: ^0.30.4 => 0.30.4
    svelte: ^3.54.0 => 3.55.1
    vite: ^4.0.0 => 4.1.4
```

**Comment by shinokada** [comment]
Can you update v0.30.5 and let us know.

**Comment by BrunoFrancaSouza** [comment]
Working as expected! 😃

Thank you!
