### ISSUE TITLE
Style a component nested generated div

### ISSUE THREAD

**Issue by alexauvray** [themesberg/flowbite-svelte#597]
What if the component is generating a nested div? How can I style it?

Here, the Flowbite <Card> component is generating a div which has `p-4 sm:p-6` as class. 

How can I add another class to that nested generated element?

```
<div class="bg-white dark:bg...>
    <img class="rounded-t-lg" src="https://i.....>
          <div class="p-4 sm:p-6">
```

**Comment by shinokada** [comment]
Can you tell us a specific component name, please?

**Comment by shinokada** [comment]
I close the issue for now.
Please feel free to open a new issue.
Thank you for your contribution.
