### ISSUE TITLE
[Feature] Rating component

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite-svelte#6]
Add [Rating](https://flowbite.com/docs/components/rating/) component.

The Flowbite library doesn't have it, but it will be nice to have .5 stars as well. 

- [x] Update the rating page to one page.
- [x] Default rating
- [x] Rating with text
- [x] Rating count
- [x] Star sizing
- [x] Advanced rating
- [x] Score rating
- [x] Rating comment
- [x] Review content

**Comment by jakobsturm** [comment]
Working on it!
