### ISSUE TITLE
Multi select

### ISSUE THREAD

**Issue by ZekyTheWolf** [themesberg/flowbite-svelte#600]
### Describe the bug

When using <Selecct /> component with option multiple set to true, it appears like this: 

![image](https://user-images.githubusercontent.com/99070546/222957518-dd4b2382-6c56-47f3-b2f1-5b9742fec64d.png)

And when trying to log output, just getting in console <empty string>

### Reproduction

```svelte
<script>
  import { Select, Label } from 'flowbite-svelte';
  let selected;
  let countries = [
    {value:"us", name: "United States"},
    {value:"ca", name: "Canada"},
    {value:"fr", name: "France"},
  ]
</script>

<Label>Select an option
  <Select class="mt-2" items={countries} bind:value={selected} multiple />
</Label>
```

### Flowbite version and System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 7.57 GB / 15.86 GB
  Binaries:
    Node: 19.5.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.4.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1344.0), Chromium (110.0.1587.63)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    flowbite-svelte: ^0.26.31 => 0.26.31
    vite: ^3.2.5 => 3.2.5
```

**Comment by shinokada** [comment]
I think that is the default behavior of HTML.

- [Add multiple to this example](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select)
- [example](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select_multiple)

**Comment by ZekyTheWolf** [comment]
So... What is actually fix for this? Im not sure...

**Comment by shinokada** [comment]
What fix do you want?

**Comment by shinokada** [comment]
We have added [it](https://flowbite-svelte.com/docs/forms/select#MultiSelect).

I close the issue for now.
Thank you for your contribution.
Please feel free to open a new issue.
