### ISSUE TITLE
Missing TypeScript support?

### ISSUE THREAD

**Issue by jones1008** [themesberg/flowbite-svelte#63]
**Describe the bug**
When importing any component the IDE throws the error `Cannot resolve definitions for module 'flowbite-svelte'`:
```svelte
<script lang="ts">
import {Button} from 'flowbite-svelte'
</script>
```

Upon further inspection, we noticed that the `index.d.ts` file is missing in `node_modules/flowbite-svelte`

**To Reproduce**

1. TypeScript based svelte installation
2. try to import the button with `import {Button} from 'flowbite-svelte'`
3. See IDE error: `Cannot resolve definitions for module 'flowbite-svelte'`

**Expected behavior**
The types are resolved.

**Solution?**
Generate `index.d.ts` for proper TypeScript support?

**Comment by shinokada** [comment]
Thank you reporting the bug. I just updated to v0.15.14. Please update it and let me know.

```
npm i -D flowbite-svelte@latest
```

**Comment by jones1008** [comment]
yep, thanks! Works now :)
