### ISSUE TITLE
Add the ability to theme

### ISSUE THREAD

**Issue by bmikaili** [themesberg/flowbite-svelte#630]
Theming doesn't seem to work like stated here:

https://flowbite.com/docs/customize/theming/

Is this something that will be supported in the future?

**Comment by shinokada** [comment]
Can you have a look at [this file](https://github.com/themesberg/flowbite-svelte/blob/main/tailwind.config.cjs)?

**Comment by bmikaili** [comment]
Thanks! That works. I was confused because in the link I sent it does so without extends syntax, but with the file you showed it worked fine.
