### ISSUE TITLE
Modal - can't scroll inside text area

### ISSUE THREAD

**Issue by aidvai-sp** [themesberg/flowbite-svelte#633]
### Describe the bug

When using `<Textarea>` component inside of `<Modal>`, I can't scroll inside the `<Textarea>`, even when it shows the scroll bar. I think I found the problem (as much as I tested), but I don't know how to fix it. I also found that when modal has scroll bar, I can scroll inside text area without any problems.

> Note: All the following steps, that happen inside browser, were done inside Edge

Some kind of a fix, that I found inside browser inspector:
1. Right click on text area -> Inspect
2. When `<textarea>` is selected in `Elements` window, press on `Event Listeners`
3. Find `wheel`
4. Inside `wheel`, find element `div#modal.p-6.space-y-6.flex-1.overflow-y-auto.overscroll-contain`
5. Press `Toggle Passive`

After doing these steps, it allows scrolling inside the `<textarea>`, but then there is an error in the console: 
```
Unable to preventDefault inside passive event listener invocation.
preventWheelDefault @ VM58:4206
eval @ VM58:222
```

I also found, that this error might be here: `Modal.svelte` -> `function preventWheelDefault(e)` -> line 80, mainly `e.preventDefault()`.

I guess `isScrollable` function wrongly calculates, because it doesn't take `textarea` size into account, but I might be very wrong.

### Reproduction

https://svelte.dev/repl/ba6de962057f49f2bf32f0e833825ca7?version=3.57.0

### Flowbite version and System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz    
    Memory: 15.75 GB / 31.92 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 111.0.5563.111
    Edge: Spartan (44.19041.1266.0), Chromium (111.0.1661.54)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/kit: ^1.14.0 => 1.14.0
    flowbite-svelte: ^0.34.2 => 0.34.2
    svelte: ^3.57.0 => 3.57.0
    vite: ^4.2.1 => 4.2.1
```

**Comment by shinokada** [comment]
Did you try [Scrolling behaviour ](https://flowbite-svelte.com/components/modal#Scrolling_behaviour)?

**Comment by aidvai-sp** [comment]
But it's not the same? The example that you linked shows how the modal scrolls when there is too much content inside of it, but in my repl it doesn't scroll. More specifically, it doesn't scroll inside the text area, that has too much content and that is inside the modal

**Comment by jjagielka** [comment]
I'll take a look at that.

**Comment by shinokada** [comment]
I think the last commit solved the issue.
I close the issue for now.
Thank you for your contribution. Please feel free to open another issue.
