### ISSUE TITLE
Flowbite Svelte Docs Redesign

### ISSUE THREAD

**Issue by zoltanszogyenyi** [themesberg/flowbite-svelte#634]
## Summary

Together with Robert (designer of Flowbite) we have now finally created the [new docs design](https://www.figma.com/file/dPNSc2GnxMbP2zmGbB4iKI/Flowbite?node-id=1-231693) for Flowbite Svelte in Figma.

The designs include both a landing page and documentation pages that include a sidebar, main content area, code blocks, and other sections that are needed for proper documentation - these are all needed if we want to make Flowbite Svelte a competitive UI library in the Svelte space.

The designs have been carefully worked over by me as well to ensure that it still has the "Flowbite" vibe to them and is properly configured for the content that we already have on the website, meaning that other than a general redesign we will not need to create much more new content other than some descriptions for the main page.

Here are some examples:

<img width="777" alt="Screenshot 2023-03-31 at 10 03 53" src="https://user-images.githubusercontent.com/8052108/229047785-9ea0115e-3a84-47e4-92e3-411e6518eba7.png">

<img width="769" alt="Screenshot 2023-03-31 at 10 03 58" src="https://user-images.githubusercontent.com/8052108/229047796-555e3a84-d3c0-4db6-a133-0e0874aa4a59.png">

<img width="783" alt="Screenshot 2023-03-31 at 10 04 07" src="https://user-images.githubusercontent.com/8052108/229047804-f6b9f369-6d7a-4a5d-ba22-71ea51b074c1.png">

<img width="1043" alt="Screenshot 2023-03-31 at 10 04 17" src="https://user-images.githubusercontent.com/8052108/229047811-aff9cb0c-7bb6-4d7f-827e-3210359fa0ce.png">

<img width="702" alt="Screenshot 2023-03-31 at 10 04 21" src="https://user-images.githubusercontent.com/8052108/229047817-97b95286-9449-43b2-92e7-502df64d1ec7.png">

### Basic example

This will change how the website looks, but it won't change much of the underlying content - but this is a much-needed update that we hope that the open-source community will undertake as an exciting part of the evolution of Flowbite Svelte.

### Motivation

We are doing this because the current documentation UI/UX is not suitable for large-scale adoption of Flowbite Svelte and it was improvised from the beginning - now that we have a proper design for the docs we should make it a reality and give the look and feel the Flowbite Svelte docs truly deserves.

@shinokada I worked on these new docs with Robert for almost 2 weeks and we've carefully planned out the colors and even most of the text - some of the landing page text still has to be written in context but much of the content is already done.

I won't be able to help very much in coding it because I really need to focus on the main library now - I suggest we create a new PR for this issue and start redesigning the current documentation to match the one I provided in Figma.

**Comment by shinokada** [comment]
It looks awesome!

**Comment by zoltanszogyenyi** [comment]
@shinokada some of the features in the design ar the same as what we have on the original [Flowbite Docs](https://flowbite.com/docs/getting-started/introduction/) especially the code blocks so you can take code or inspiration from there as well!

I hope we can get this done for Flowbite Svelte :P

**Comment by shinokada** [comment]
@zoltanszogyenyi I think we can close this for now.

- [x] Svelte UI components
- [x] Dark mode integration
- [x] Works with Tailwind CSS
- [x] Design with Figma
- [x] Community contributors
- [x] Component pages
- [x] Get started
- [x] bug fixes

**Comment by zoltanszogyenyi** [comment]
We can close it now - awesome job @jjagielka @shinokada <3
