### ISSUE TITLE
[New Feature] Jumbotron

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite-svelte#638]
[Jumbotron](https://flowbite.com/docs/components/jumbotron/)

- [ ] [Default jumbotron](https://flowbite.com/docs/components/jumbotron/#default-jumbotron)
- [ ] [Background image](https://flowbite.com/docs/components/jumbotron/#default-jumbotron)
- [ ] [Featured video](https://flowbite.com/docs/components/jumbotron/#featured-video)
- [ ] [Authentication form](https://flowbite.com/docs/components/jumbotron/#authentication-form)
- [ ] [Gradient background](https://flowbite.com/docs/components/jumbotron/#gradient-background)
- [ ] [Jumbotron with cards](https://flowbite.com/docs/components/jumbotron/#jumbotron-with-cards)

**Comment by vasucp1207** [comment]
@shinokada, what should be the preferred api for this,

```svelte
<Jumbotron 
   title={title} 
   description={description} 
   link1={link1} 
   link2={link2} 
   bgImg={bgImg} 
/>
```
OR

```svelte
<Jumbotron>
  <div></div>
  <div></div>
  <Button></Button>
  <Button></Button>
</Jumbotron>
```

**Comment by shinokada** [comment]
We found that there is no consistent structure in the Flowbite Jumbotron, so we didn't create it. I think it should belong to [blocks](https://flowbite-svelte-blocks.vercel.app/).

If you want to proceed, I think the second one is more flexible for users since they can add more items.

**Comment by shinokada** [comment]
I consider this component as a block so I close the issue for now.
