### ISSUE TITLE
Remove SingleCheckbox.svelte

### ISSUE THREAD

**Issue by orefalo** [themesberg/flowbite-svelte#64]
https://github.com/themesberg/flowbite-svelte/blob/59b37b5a8f3bea06ecd8b8fdf5cc5ac5967dd149/src/lib/forms/SingleCheckbox.svelte#L1

Hi, since this file was removed from index.js, I would recommend removing it from the source code.
It is indeed a duplicate of the more powerful `<Checkbox>`, even if it's not as easy to use.

My 2c

**Comment by shinokada** [comment]
Thanks for the catch. I removed it and will be on the next release.
