### ISSUE TITLE
index.js missing from package.json

### ISSUE THREAD

**Issue by shridhardamle** [themesberg/flowbite-svelte#647]
### Describe the bug

"main": "index.js" line is missing from node_modules/flowbite-svelte/package.json 

### Reproduction

"main": "index.js" line is missing from node_modules/flowbite-svelte/package.json That breaks compiling the code. Moved back from latest 0.3x.x version to 0.29.x and it started compiling.

### Flowbite version and System Info

```shell
flowbite-svelte 0.34.x 👎

flowbite-svelte 0.29.x 👍
```

**Comment by shinokada** [comment]
If you don’t specify the “main” field, Node.js will just look for an “index.js” file in the root directory by default.
But I will put it back in the next version update.
Thanks.

**Comment by shridhardamle** [comment]
Thanks for quick response @shinokada . Flowbite is very cool.

**Comment by terrisgit** [comment]
0.33.1 works. 0.34.1 doesn't.

**Comment by shinokada** [comment]
Can you try the latest version and let me know.

**Comment by shridhardamle** [comment]
I just pulled flowbite-svelte@latest and got 

    "flowbite": "^1.6.4",
    "flowbite-svelte": "^0.34.9",

flowbite-svelte's package.json contains following line ..

"main": "dist/index.js",

I got following error while building ...

Failed to resolve entry for package "flowbite-svelte". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." entry in "flowbite-svelte" package
error during build:
Error: Failed to resolve entry for package "flowbite-svelte". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." entry in "flowbite-svelte" package


I had to make a few things to the package.json to make it work. Basically copied quite a bit from 29.x build.

Attached is the package.json that worked.

[package.json.zip](https://github.com/themesberg/flowbite-svelte/files/11197753/package.json.zip)

**Comment by shridhardamle** [comment]
FWIW 0.34.9 works as is with your starter https://github.com/themesberg/flowbite-svelte/tree/main/starters/svelte-ts-starter/

**Comment by dev-guy** [comment]
0.34.9 doesn't work for me and I'm using the latest NodeJS 19.

**Comment by shinokada** [comment]
Before you build, you need to remove package-lock or pnpm-lock file and remove dist directory and try it again.

**Comment by terrisgit** [comment]
How do I build? Do you mean run npm install or something else? Or should I just wait for the next release?

**Comment by shinokada** [comment]
The current recommended Node version is 18. 
Please try it with Node 18 and let us know if you still have the problem.

**Comment by shinokada** [comment]
Thank you for your contribution! We are closing this issue for now due to inactivity. If you encounter any other problems in the future, please feel free to open a new issue. We appreciate your help in making our project better!

**Comment by Chimildic** [comment]
I have still error with `0.40.2` version. How to fix? Except replacement package like **shridhardamle** [described](https://github.com/themesberg/flowbite-svelte/issues/647#issuecomment-1502815828). Error occurs with node 18 and 20.

```
[vite:resolve] Failed to resolve entry for package "flowbite-svelte". 
The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." entry in "flowbite-svelte" package
```

**Comment by krg-digital** [comment]
Well, if it helps anyone else: my issue was that I needed to close and restart the dev server for Vite to "optimize" dependency.

**Comment by vincenzoml** [comment]
I have this issue and restarting doesn't help, what to do?

**Comment by shinokada** [comment]
@vincenzoml What is your output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit,flowbite-svelte,vite,rollup,webpack --binaries --browsers`?

**Comment by vincenzoml** [comment]
@shinokada 

```
  System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 25.20 GB / 31.25 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.6.0 - /usr/bin/node
    npm: 9.8.1 - /usr/bin/npm
  npmPackages:
    @sveltejs/kit: ^1.20.4 => 1.25.0 
    flowbite-svelte: ^0.44.15 => 0.44.15 
    svelte: ^4.0.5 => 4.2.0 
    vite: ^4.4.2 => 4.4.9 
    ```

**Comment by shinokada** [comment]
Run `pnpm i -D flowbite-svelte-icons`.

**Comment by vincenzoml** [comment]
I am unsure what was going on, because vscode would complete the icon names from the import; maybe I had installed it in the parent folder (I found a node-modules dir there). Anyway reinstalling the package fixed the issue.
