### ISSUE TITLE
NavLi active state is not updated when used with (group) routing

### ISSUE THREAD

**Issue by benny856694** [themesberg/flowbite-svelte#650]
### Describe the bug

I used the following code, the project (forked from starter project) is [here](https://github.com/benny856694/flowbite-svelte-starter)
```
<NavUl {hidden}>
		<NavLi href="/" active={$page.route.id === '/(auth)'}>Home</NavLi>
		<NavLi href="/about" active={$page.route.id === '/(auth)/about'}>About</NavLi>
</NavUl>
```
the active state of NavLi is only updated the first time loading

### Reproduction

clone the project, and switch between `home` and `about` page

### Flowbite version and System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12500
    Memory: 4.68 GB / 15.70 GB
  Binaries:
    Node: 18.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1485.0), Chromium (112.0.1722.34)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/kit: 1.7.2 => 1.7.2
    flowbite-svelte: ^0.29.13 => 0.29.13
    svelte: ^3.55.1 => 3.55.1
    vite: ^4.1.2 => 4.1.2
```

**Comment by shinokada** [comment]
Thank you for your contribution! We are closing it for now due to inactivity. If you encounter any other problems in the future, please feel free to open a new issue. We appreciate your help in making our project better!
