### ISSUE TITLE
Dropping a file on the Dropzone does not work

### ISSUE THREAD

**Issue by Corbie-42** [themesberg/flowbite-svelte#655]
### Describe the bug

Dropping a file to the Dropzone does not work. The file is opened in the Browser instead.

### Reproduction

1. Go to https://flowbite-svelte.com/forms/file-input#Dropzone
2. Drop any file on the Dropzone

### Flowbite version and System Info

```shell
Flowbite version: 0.34.9

System:
  OS: Windows 10
Browsers:
  Chrome: 111.0.5563.147
  Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.39)
  Internet Explorer: 11.0.19041.1566
  Firefox: 102.9.0esr
```
Tested with all installed browsers.

**Comment by joshua1** [comment]
I am experiencing the same issue

**Comment by shinokada** [comment]
The component has the following event forwarding, so it is up to you how you want to handle it.

```
  on:focus
  on:blur
  on:mouseenter
  on:mouseleave
  on:mouseover
  on:dragenter
  on:dragleave
  on:dragover
  on:drop
```

Please note that Flowbite-Svelte it a UI library.

**Comment by shinokada** [comment]
Thank you for your contribution! We are closing it for now. If you encounter any other problems in the future, please feel free to open a new issue. We appreciate your help in making our project better!
