### ISSUE TITLE
Add half rating icons to Rating

### ISSUE THREAD

**Issue by Hoidi** [themesberg/flowbite-svelte#658]
## Summary

Addings half filles rating icons, or maybe linearly filled. 

### Basic example

Maybe add a property to `Rating` that's something like this: `fillIncrement: 'whole' | 'half' | 'linearly' = 'whole'` 

### Motivation

Lots of rating systems use only five stars and limiting the look of them to only whole stars does not always look the greatest and often forces me to have to display the acual number aswell.

**Comment by Destaq** [comment]
Seconded, would make existing solutions much less verbose.

Managed to put something together like this (without Flowbite-Svelte) a couple months ago, and just sharing here for reference in case anyone would like to make a PR / doesn't want to wait (for something that may never happen).

```svelte
<span class="flex items-center">
    {#each Array(roundedDownDifficultyRating) as _}
        <slot name="ratingUp">
            <!-- Heroicon name: solid/star -->
            <svg
                class="text-yellow-400 h-4 w-4 flex-shrink-0"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 20 20"
                fill="currentColor"
                aria-hidden="true"
            >
                <path
                    fill-rule="evenodd"
                    d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zM8.94 6.94a.75.75 0 11-1.061-1.061 3 3 0 112.871 5.026v.345a.75.75 0 01-1.5 0v-.5c0-.72.57-1.172 1.081-1.287A1.5 1.5 0 108.94 6.94zM10 15a1 1 0 100-2 1 1 0 000 2z"
                    clip-rule="evenodd"
                />
            </svg>
        </slot>
    {/each}
    {#if remainingDifficultyRating > 0}
        <svg
            class="text-gray-300 dark:text-gray-500 h-4 w-4 flex-shrink-0"
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 20 20"
            fill="pink"
            aria-hidden="true"
        >
            <defs>
                <linearGradient id="grad">
                    <stop
                        offset="50%"
                        stop-color="rgb(227 160 8 / var(--tw-text-opacity))"
                    />
                    <stop offset="50%" stop-color="currentColor" />
                    <stop offset="100%" stop-color="currentColor" />
                </linearGradient>
            </defs>
            <path
                fill="url(#grad)"
                fill-rule="evenodd"
                d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zM8.94 6.94a.75.75 0 11-1.061-1.061 3 3 0 112.871 5.026v.345a.75.75 0 01-1.5 0v-.5c0-.72.57-1.172 1.081-1.287A1.5 1.5 0 108.94 6.94zM10 15a1 1 0 100-2 1 1 0 000 2z"
                clip-rule="evenodd"
            />
        </svg>
    {/if}
    {#each Array(grayStarsDifficultyRating) as _}
        <slot name="ratingDown">
            <svg
                class="text-gray-300 dark:text-gray-500 h-4 w-4 flex-shrink-0"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 20 20"
                fill="currentColor"
                aria-hidden="true"
            >
                <path
                    fill-rule="evenodd"
                    d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zM8.94 6.94a.75.75 0 11-1.061-1.061 3 3 0 112.871 5.026v.345a.75.75 0 01-1.5 0v-.5c0-.72.57-1.172 1.081-1.287A1.5 1.5 0 108.94 6.94zM10 15a1 1 0 100-2 1 1 0 000 2z"
                    clip-rule="evenodd"
                />
            </svg>
        </slot>
    {/each}
</span>
```

**Comment by shinokada** [comment]
Please use v0.35.4 and read the [doc](https://flowbite-svelte.com/docs/components/rating)

**Comment by Destaq** [comment]
> Please use v0.35.4 and read the [doc](https://flowbite-svelte.com/docs/components/rating).
> 
> 
> 
> @Destaq, it's important to maintain a constructive tone and avoid sarcasm. As volunteers, we dedicate our personal time to develop this library and support its users.

@shinokada I'm sorry if my comment came off badly. I was intending to have the exact opposite effect -- didn't want to feel like I was burdening contributors with the expectation that this should be implemented. My apologies for the phrasing, then; I have only respect for the work you do.

**Comment by shinokada** [comment]
@Destaq Thank you for your reply. Please test the latest version and let me know.

**Comment by Destaq** [comment]
> @Destaq Thank you for your reply. Please test the latest version and let me know.

Tested and working great.

**Comment by shinokada** [comment]
There was a bug and the fix will be released in the next verion.
