### ISSUE TITLE
Backdrop of Flowbite's Modal not applying to Flowbite's Drawer

### ISSUE THREAD

**Issue by Akash-Sharma-1** [themesberg/flowbite-svelte#659]
### Describe the bug

Hi,
Thank you for providing these awesome Svelte components !  

**What am I using ?** 
I have been encountering an issue while using both `Drawer` and `Modal`
In my usecase, Modal component has backdrop enabled while the Drawer has the backdrop as disabled and the Modal is placed on top of Drawer. 

**Whats the issue ?** 
Whenver you have already opened your Drawer and then you open the Modal , it applies backdrop to everything in the background except for the Drawer.

Ideally, it should be applying this backdrop to all the background elements including the Drawer.
Are there any workarounds for this ? 

Thanks :) 

### Reproduction

https://svelte.dev/repl/e9e7c9fa237c480a891b438d40b242af?version=3.58.0

There are 2 components used here - a drawer (with no backdrop) and a modal (with backdrop)
The button to open Modal is inside the Drawer.
When u open the modal, it applies backdrop to the background but doesn't apply backdrop to the drawer 

### Flowbite version and System Info

```shell
System:
    OS: Linux 5.19 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 1.27 GB / 15.31 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
    npm: 9.3.1 - ~/.nvm/versions/node/v18.14.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Firefox: 112.0
```

**Comment by shinokada** [comment]
We need to increase `z-50` value for the backdrop. We will update it in the next version. Thank you.

**Comment by Akash-Sharma-1** [comment]
Ohh, understood !
Thanks for the response :)
