### ISSUE TITLE
Following the Getting Started instructions results in ButtonGroup and other styles failing

### ISSUE THREAD

**Issue by chinch64** [themesberg/flowbite-svelte#661]
### Describe the bug

I have followed the instructions at https://flowbite-svelte.com/pages/getting-started#Install_Tailwind_CSS to install a svelte-vite tailwind project as follows:

```
npm create vite@latest myapp -- --template svelte
cd myapp
npm install
```

```
npx svelte-add@latest tailwindcss
npm i
```
 
`npm run dev`

`npm i flowbite flowbite-svelte classnames @popperjs/core`

Replacing contents of tailwind.config.cjs with 

```
const config = {
  content: [
    "./src/**/*.{html,js,svelte,ts}",
    "./node_modules/flowbite-svelte/**/*.{html,js,svelte,ts}",
  ],
 
  theme: {
    extend: {},
  },
 
  plugins: [
    require('flowbite/plugin')
  ],
  darkMode: 'class',
};
 
module.exports = config;
```

and then replacing App.Svelte contents with

```
<script>
import { Alert } from 'flowbite-svelte';
import { ButtonGroup, Button } from 'flowbite-svelte';
</script>
 
<div class="p-8">
<Alert>
<span class="font-medium">Info alert!</span> Change a few things up and try submitting again.
</Alert>
 
<ButtonGroup>
<Button>Profile</Button>
<Button>Settings</Button>
<Button>Messages</Button>
</ButtonGroup>
```
gives a perfect alert box but the button group buttons are all rounded, and unjoined as per the image below.  Some other flowbite-tailwind components are similarly affected, such as tabs and menus.

<img width="358" alt="image001-1" src="https://user-images.githubusercontent.com/126532080/232354198-79fa9cca-f627-4ff4-aa9e-d95d1f8ced56.png">

### Reproduction

As above. 

### Flowbite version and System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
    Memory: 54.43 GB / 63.92 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 112.0.5615.86
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.48)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    flowbite-svelte: ^0.34.9 => 0.34.9
    svelte: ^3.55.1 => 3.58.0
    vite: ^4.2.0 => 4.2.1
```

**Comment by shinokada** [comment]
I confirmed the bug. Thanks.

https://stackblitz.com/edit/vitejs-vite-k6v8vw?file=src/App.svelte

**Comment by shinokada** [comment]
What do you have in app.css.

Can you change the content of app.css to the following?

```
@tailwind base;
@tailwind components;
@tailwind utilities;
```

**Comment by shinokada** [comment]
Please read the [Customization page](https://flowbite-svelte.com/docs/pages/customization).

I close the issue for now.
Thank you for your contribution.
Please feel free to open a new issue.
