### ISSUE TITLE
doc: «ariaLabel» instead of «} ariaLabel»?

### ISSUE THREAD

**Issue by alexander-mart** [themesberg/flowbite-svelte#662]
### Describe the bug

doc: «ariaLabel» instead of «} ariaLabel»?

Doc page:
- https://flowbite-svelte.com/components/navbar#References

Search around repo:
- https://github.com/themesberg/flowbite-svelte/blob/main/src/routes/props/ChevronUp.json#LL1
- https://github.com/themesberg/flowbite-svelte/blob/main/src/routes/props/ChevronLeft.json#LL1
- https://github.com/themesberg/flowbite-svelte/blob/main/src/routes/props/ChevronDown.json#LL1
- https://github.com/themesberg/flowbite-svelte/blob/main/src/routes/props/InformationCircle.json#LL1
- https://github.com/themesberg/flowbite-svelte/blob/main/src/routes/props/UserCircle.json#LL1
- https://github.com/themesberg/flowbite-svelte/blob/main/src/routes/props/Star.json#LL1
- https://github.com/themesberg/flowbite-svelte/blob/main/src/routes/props/Menu.json#LL1

### Reproduction

—

### Flowbite version and System Info

```shell
—
```

**Comment by alexander-mart** [comment]
Let me know, if it mistake, i can sumbit a PR

**Comment by shinokada** [comment]
Thanks for pointing out. Yes, they are typos. We use https://www.npmjs.com/package/createprops to auto-generate all the props, but it has some limitations and those are one of them.

If you change it manually, it will be overwritten in the future. So it will be better to update the https://www.npmjs.com/package/createprops to generate props properly.
