### ISSUE TITLE
Tabs are difficult to use in a Modal

### ISSUE THREAD

**Issue by vsergeev** [themesberg/flowbite-svelte#664]
### Describe the bug

Due to a non-overridable ~~`p-6` padding~~ `space-y-6` spacing in `Modal`: https://github.com/themesberg/flowbite-svelte/blob/v0.34.9/src/lib/modals/Modal.svelte#L151 , the divider in a nested `Tabs` component is improperly spaced, and generally makes it difficult to use this component inside of a `Modal`.

edit: fix the responsible CSS class 

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-ul25mf?file=src%2Froutes%2F%2Bpage.svelte

### Flowbite version and System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/kit: ^1.15.4 => 1.15.4 
    flowbite-svelte: ^0.34.9 => 0.34.9 
    svelte: ^3.58.0 => 3.58.0 
    vite: ^4.2.1 => 4.2.1
```

**Comment by jjagielka** [comment]
I think the problem is not padding but `space-y-6`. I'll will have a closer look at it.

For now the quick solution to your problem, would be to simply wrap the `Tab` element with `<div>` around it.

**Comment by vsergeev** [comment]
Ah yeah, you're right -- `space-y-6` was the culprit. The wrapped `<div>` solution works fine for me. I'll close for now.
