### ISSUE TITLE
Code remaining feature sections for the homepage

### ISSUE THREAD

**Issue by zoltanszogyenyi** [themesberg/flowbite-svelte#666]
## Summary

- [ ] Code remaining feature sections for the homepage.

<img width="624" alt="Screenshot 2023-04-20 at 13 42 42" src="https://user-images.githubusercontent.com/8052108/233342930-274bd4b5-4b8f-4c4e-9b33-415a61213c5a.png">

Source in Figma: https://www.figma.com/file/dPNSc2GnxMbP2zmGbB4iKI/Flowbite?node-id=1%3A231693&t=UO2nxuSeEw5W1x2i-1

**Comment by shinokada** [comment]
We need to update the content.

**Comment by shinokada** [comment]
I close the issue for now.
Please feel free to open a new issue.
Thank you for your contribution.
