### ISSUE TITLE
Redirect old pages to new URLs

### ISSUE THREAD

**Issue by zoltanszogyenyi** [themesberg/flowbite-svelte#671]
### Describe the bug

In order to prevent a huge SEO penalization we need to `301` redirect all previous URL formats.

For example, Google indexed the navbar as such:

https://flowbite-svelte.com/components/navbar

This now returns a 404 error which is super super bad. We need to 301 redirect it to:

https://flowbite-svelte.com/docs/components/navbar

This is a HUGE priority and should be fixed in matters of minutes and hours.

### Reproduction

Just go to the URL.

### Flowbite version and System Info

```shell
Doesn't matter.
```

**Comment by zoltanszogyenyi** [comment]
This applies in fact too all of the previous URLs including:

https://flowbite-svelte.com/typography/...
https://flowbite-svelte.com/forms/...
https://flowbite-svelte.com/pages/...

We need to 301 redirect the old ones to use the `docs/` prefix otherwise we will literally lose all backlinks from other websites and the SEO positions.

**Comment by jjagielka** [comment]
Go on test it.

**Comment by zoltanszogyenyi** [comment]
Looks good! I'll merge it @shinokada so we prevent downtime for the URLs. Thanks @jjagielka.
