### ISSUE TITLE
ExampleDarkMode.svelte and GitHub.svelte util components

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite-svelte#680]
### Describe the bug

- [x] When you click the moon icon, it should change to the sun icon.
- [ ] When you click "Edit on GitHub", it should go to the file. Currently all links go to https://github.com/themesberg/flowbite-svelte.

### Reproduction

N/A

### Flowbite version and System Info

```shell
N/A
```

**Comment by jjagielka** [comment]
> When you click "Edit on GitHub", it should go to the file

Which file should it go? [Alert in lib](https://github.com/themesberg/flowbite-svelte/blob/main/src/lib/alert/Alert.svelte) or [Alert in docs](https://github.com/themesberg/flowbite-svelte/blob/main/src/routes/docs/components/alert.md)?

**Comment by shinokada** [comment]
For example, the button, Edit on GitHub in the Default accordion on the accordion page, should go to `https://github.com/themesberg/flowbite-svelte/blob/main/src/routes/docs/components/accordion.md#default-accordion`.

![image](https://user-images.githubusercontent.com/147320/233867036-8fe1eef2-a903-401d-9f53-0168472aab9c.png)

And the button in the Always open section in the same page should go to `https://github.com/themesberg/flowbite-svelte/blob/main/src/routes/docs/components/accordion.md#always-open`.

**Comment by jjagielka** [comment]
So the answer is it should redirect to the docs (markdown pages) in GitHub, not to the component implementation. OK. Noted.
