### ISSUE TITLE
Undefined in generation.

### ISSUE THREAD

**Issue by orefalo** [themesberg/flowbite-svelte#69]
https://github.com/themesberg/flowbite-svelte/blob/f3640e2c2342a563a8af29970c8f851d470f8d78/src/lib/buttons/Button.svelte#L80

if $$prop.class is not defined, this code generates undefined in the html.

as in...

"text-gray-900 hover:text-white border border-gray-800 hover:bg-gray-900 focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-xs py-2 px-3 text-center mr-2 mb-2 dark:border-gray-600 dark:text-gray-400 dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-gray-800 items-center inline-flex undefined"

note the undefined at the end.

**Comment by shinokada** [comment]
Thanks for the bug report. I just fixed changing it to:

```
{$$props.class ? $$props.class : ''}
```

v0.15.29

**Comment by shinokada** [comment]
Close this for now. Please let me know if you find more bugs.
