### ISSUE TITLE
Svelte resolve configuration warning.

### ISSUE THREAD

**Issue by olafurw** [themesberg/flowbite-svelte#701]
### Describe the bug

I was building my project and got this warning.

```
13:20:01 [vite-plugin-svelte] WARNING: The following packages use a svelte resolve configuration in package.json that has conflicting results and is going to cause problems future.

flowbite-svelte@0.34.9

Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#conflicts-in-svelte-resolve for details.
```

### Reproduction

https://github.com/olafurw/flowbite-svelte-701

### Flowbite version and System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 7.07 GB / 31.73 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.58)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/kit: ^1.15.8 => 1.15.8
    flowbite-svelte: ^0.34.9 => 0.34.9
    svelte: ^3.58.0 => 3.58.0
    vite: ^4.3.1 => 4.3.1
```

**Comment by shinokada** [comment]
We already have [those lines](https://github.com/themesberg/flowbite-svelte/blob/main/package.json#L723).

Can you remove the npm-lock/pnpm-lock file and node_modules directory and install it again?

**Comment by olafurw** [comment]
Same warning after a delete of the lock file and the `node_modules`. I'm also getting this for another library `svelte-focus-trap@1.2.0` just as an FYI but that one hasn't been updated in a while, so I'm guessing they don't have those lines setup.

We have 

```
    "flowbite": "^1.6.5",
    "flowbite-svelte": "^0.34.9",
```

Which are the latest versions. Could there be something in our own configs that cause this?

Our tailwind looks like this, which is pretty close to the starter setup.

```
import type { Config } from 'tailwindcss';
import fontFamily from './src/lib/theme/fontFamily';
import colors from './src/lib/theme/colors';

export default {
    content: [
        './src/**/*.{html,js,svelte,ts}',
        './node_modules/flowbite-svelte/**/*.{html,js,svelte,ts}'
    ],

    theme: {
        fontFamily: fontFamily,
        extend: {
            colors: colors
        }
    },

    plugins: [require('flowbite/plugin')],
    darkMode: 'class'
} satisfies Config;
```

**Comment by shinokada** [comment]
Can you install Flowbite-svelte on a fresh sveltekit/svelte and if it gives the same error? If not, install other dependencies and check if it gives an error?

**Comment by shinokada** [comment]
Did you https://flowbite-svelte.com/docs/pages/quickstart ?

You don't have tailwind.config.cos.

**Comment by olafurw** [comment]
Updated, same error. Added workflow to see it build on Ubuntu, doesn't happen there. Perhaps it's a Win/Linux thing.

https://github.com/olafurw/flowbite-svelte-701/actions/runs/4797964706/jobs/8535611487

**Comment by olafurw** [comment]
Yup, seems to be a Windows vs Linux thing, you can see in the Build tab here (sorry for the job names, forgot to change them)

https://github.com/olafurw/flowbite-svelte-701/actions/runs/4798028123/jobs/8535755553

**Comment by olafurw** [comment]
Fixed with @sveltejs/vite-plugin-svelte@2.1.1

https://github.com/sveltejs/vite-plugin-svelte/releases/tag/%40sveltejs%2Fvite-plugin-svelte%402.1.1

**Comment by shinokada** [comment]
If you are using SvelteKit, it already has it. 
Have you tried SvelteKit?

**Comment by olafurw** [comment]
It was a bug on their end, it's linked here above in the timeline. Here's the bug.

https://github.com/sveltejs/vite-plugin-svelte/issues/634
