### ISSUE TITLE
Hide mobile nav / dropdown after navigating for Navbar component

### ISSUE THREAD

**Issue by jnaklaas** [themesberg/flowbite-svelte#703]
## Summary

When navigation using the Navbar component on mobile  it stays open by default, taking up the majority of the space above the fold after navigating to a new page. 

### Basic example
```
<Navbar let:hidden let:toggle>
  <NavHamburger on:click={toggle} />
  <NavUl {hidden}
    <NavLi href="/">Home</NavLi>
    <NavLi href="/contact" rel="external">Contact</NavLi>
  </NavUl>
</Navbar>
```

The current workaround with `rel=external` attribute, takes longer to load the next page.
Would be nice if NavUl hides after navigation on default, or by using some prop. Or any other solution, really.

### Motivation

Better UX!

**Comment by dskelton-cos** [comment]
I found this did the trick:  
add the on:click handler to toggle the NavUl

`<NavUl {hidden} on:click={() => setTimeout(toggle, .5)}>`

https://github.com/themesberg/flowbite-svelte/blob/2bd095f1f197783f0c4161bda3c22ebd6008859a/src/routes/%2Blayout.svelte#L66

**Comment by jnaklaas** [comment]
> I found this did the trick: add the on:click handler to toggle the NavUl
> 
> `<NavUl {hidden} on:click={() => setTimeout(toggle, .5)}>`
> 
> https://github.com/themesberg/flowbite-svelte/blob/2bd095f1f197783f0c4161bda3c22ebd6008859a/src/routes/%2Blayout.svelte#L66

Hi David, thanks for the suggestion. I tried this, but I'm afraid it didn't work.

**Comment by shinokada** [comment]
How about using `    <NavLi on:click={toggle} href="/about">About</NavLi>`?

```
<script>
  import { Navbar, NavBrand, NavLi, NavUl, NavHamburger } from 'flowbite-svelte';
</script>

<Navbar let:hidden let:toggle>
  <NavBrand href="/">
    <img src="https://flowbite.com/docs/images/logo.svg" class="mr-3 h-6 sm:h-9" alt="Flowbite Logo" />
    <span class="self-center whitespace-nowrap text-xl font-semibold dark:text-white"> Flowbite </span>
  </NavBrand>
  <NavHamburger on:click={toggle} />
  <NavUl {hidden}>
    <NavLi href="/" active={true}>Home</NavLi>
    <NavLi on:click={toggle} href="/testdir">testdir 1</NavLi>
    <NavLi on:click={toggle} href="/testdir">testdir 2</NavLi>
  </NavUl>
</Navbar>
```

**Comment by jnaklaas** [comment]
> How about using `<NavLi on:click={toggle} href="/about">About</NavLi>`?
> 
> ```
> <script>
>   import { Navbar, NavBrand, NavLi, NavUl, NavHamburger } from 'flowbite-svelte';
> </script>
> 
> <Navbar let:hidden let:toggle>
>   <NavBrand href="/">
>     <img src="https://flowbite.com/docs/images/logo.svg" class="mr-3 h-6 sm:h-9" alt="Flowbite Logo" />
>     <span class="self-center whitespace-nowrap text-xl font-semibold dark:text-white"> Flowbite </span>
>   </NavBrand>
>   <NavHamburger on:click={toggle} />
>   <NavUl {hidden}>
>     <NavLi href="/" active={true}>Home</NavLi>
>     <NavLi on:click={toggle} href="/testdir">testdir 1</NavLi>
>     <NavLi on:click={toggle} href="/testdir">testdir 2</NavLi>
>   </NavUl>
> </Navbar>
> ```

Great, thanks!

**Comment by shinokada** [comment]
I close the issue for now.
Please feel free to open a new issue.
Thank you for your contribution.

**Comment by jnaklaas** [comment]
I had to enhance it a little more, because on desktop it messed up styling:

```html
<script>
  import { Navbar, NavBrand, NavLi, NavUl, NavHamburger } from 'flowbite-svelte';
  
  let viewportW;
  const mobileNavBreakpoint = 768
</script>

<svelte:window bind:innerWidth={viewportW}/>

<Navbar let:hidden let:toggle fluid=true>
  <NavHamburger on:click={toggle}/>
  <NavUl {hidden}>
      <NavLi class="rounded-none md:border-b border-transparent" href="{item.href}" active={route === item.href} on:click={(viewportW < mobileNavBreakpoint) ? toggle : null}>{item.title}</NavLi>
  </NavUl>
</Navbar>
```

**Comment by JackNeto** [comment]
I have the same issue and cannot make this work with the examples given
