### ISSUE TITLE
Provide support for RTL

### ISSUE THREAD

**Issue by kefahi** [themesberg/flowbite-svelte#704]
## Summary

TailwindCSS 3.3 brings the necessary semantics for supporting RTL.  It will be great to have flowbite support this so that RTL implementations are possible.

### Basic example

Mainly allows using xx-start xx-end as opposed to xx-right and xx-left.  [Check this explanation](https://tailwindcss.com/blog/tailwindcss-v3-3#simplified-rtl-support-with-logical-properties) in their latest release notes.

### Motivation

RTL support would make flowbite ready for more international implementations for languages like Arabic, Persian, Urdu, Hebrew and so forth.

**Comment by shinokada** [comment]
Is this meant for Flowbite? If it is so, you can make an issue at https://github.com/themesberg/flowbite/issues.

For Flowbite-Svelte, you can use `class='your-class'` for many components.

**Comment by EssaAlshammri** [comment]
Hi @kefahi 
I tried that it by setting `<html lang="ar" dir="rtl">`

and it works.

I tried a bunch of components and all seems working fine.
