### ISSUE TITLE
doc: redirect from removed doc page to actual (compiler-speed)

### ISSUE THREAD

**Issue by alexander-mart** [themesberg/flowbite-svelte#707]
### Describe the bug

Redirect from:
https://flowbite-svelte.com/pages/faster-compiling-speed
(404)

To:
https://flowbite-svelte.com/docs/pages/compiler-speed

### Reproduction

--

### Flowbite version and System Info

```shell
--
```

**Comment by shinokada** [comment]
Thank you for this issue.
We have moved the page from https://flowbite-svelte.com/pages/faster-compiling-speed to https://flowbite-svelte.com/docs/pages/compiler-speed.
