### ISSUE TITLE
Accessibility 35 issues for home page

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite-svelte#716]
### Describe the bug

![image](https://user-images.githubusercontent.com/147320/235587389-b26bb4bc-b9b1-4064-89cb-9f91781ecf75.png)

### Reproduction

Install Axe devtools chrome extension and run a test.

### Flowbite version and System Info

```shell
N/A
```

**Comment by jjagielka** [comment]
@shinokada with your latest changes of A11y would be worth to re-run that check.
