### ISSUE TITLE
Ability to edit accordion content padding

### ISSUE THREAD

**Issue by jordigagomerino** [themesberg/flowbite-svelte#717]
## Summary
In the AccordionItem.svelte line 75. There is a padding defined but there is no way to change this.
```
    <div class={ctx.flush ? 'py-5' : 'p-5'}>
```
I propose to create a new prop "wrapperClass" and use as variable
```
  export let wrapperClass: string | undefined = undefined;

  let classWrapper: string;
  $: classWrapper = classNames(
    ctx.flush ? 'py-5' : 'p-5',
    wrapperClass
  );
```
```
    <div class={wrapperClass}>
```

### Basic example
Just a accordion without having y paddings on the content, or at least a smaller padding.
### Motivation
I'm making a project at work where he have some rules with categories, each category is a AccordionItem, but the accordion content have a top and bottom padding that doesn't look how we want.

**Comment by jordigagomerino** [comment]
There is a way that is applying a negative margin to the slot element -my-5 for example or calculate it as if you start by 5, -my-4 if you want  py-1. But I feel it a little tricky. In my case works but maybe for other cases is not a good option.

**Comment by shinokada** [comment]
I mentioned a similar thing in this [PR](https://github.com/themesberg/flowbite-svelte/pull/712#issuecomment-1529148134). I will update it soon.

**Comment by shinokada** [comment]
Four new props are added to [AccordionItem](https://flowbite-svelte.com/docs/components/accordion#AccordionItem):

By setting your class to these props should fix the problem.

![image](https://user-images.githubusercontent.com/147320/235800822-2c8fac5d-cb72-46f0-9e65-2d0fbb2d8587.png)

**Comment by jordigagomerino** [comment]
Great! Thank you!
