### ISSUE TITLE
Card `size` prop missing Type

### ISSUE THREAD

**Issue by huntabyte** [themesberg/flowbite-svelte#722]
### Describe the bug

The `Card` component is importing `SizeType` which isn't exported from `types`.

**Card.d.ts**:

![image](https://user-images.githubusercontent.com/64506580/236001840-0586f3b5-7dd6-437b-bed6-3c76ba5885cc.png)

**types.d.ts**:
![image](https://user-images.githubusercontent.com/64506580/236001940-b5549a78-b57f-4fb0-991c-93a6b34520c4.png)

Therefore no typehints for the size prop on Card Component.

### Reproduction

Screenshots provided.

### Flowbite version and System Info

```shell
flowbite-svelte: 0.34.10
```

**Comment by shinokada** [comment]
Thank you for this issue.
It seems when I package it there are quite a few `export` are missing from the `types.d.ts`.

```
AlignType
AuthFunctionType
ButtonType
Buttontypes
Buttonshadows
CarouselIconType
Colors
drawerTransitionTypes
FormColorType
Gradientduotones
ImgType
InputType
SizeType
FormSizeType
ReviewType
SelectOptionType
SidebarType
SidebarCtaType
Textsize
```

I will manually overwrite the file.

**Comment by shinokada** [comment]
Thanks for the issue.
Please test it with the latest version.
