### ISSUE TITLE
on:mouseenter for Card

### ISSUE THREAD

**Issue by rbozan** [themesberg/flowbite-svelte#724]
## Summary

Can not add the mouseenter event (or whatever other event) to a `Card`.

### Basic example

```ts
<Card
	padding="none"
	horizontal
    on:mouseenter={() => console.log('hover')}
>
test
</Card>
```

### Motivation

Now I have to wrap the Card in another component which does support it like `div` or `a`. Pretty cumbersome. 

If it is actually supported, I can not find it in the documentation. So whether something has to be developed or documented is the question.

**Comment by shinokada** [comment]
Thank you for raising this issue.
It is a bug not even forwarding in the Frame component in the Card component.
I will fix it and release a new version soon.
