### ISSUE TITLE
Date Picker Placeholders

### ISSUE THREAD

**Issue by Pedroglp** [themesberg/flowbite-svelte#725]
## Summary

The datepicker/calendar placeholders is not a property being always in English. This makes the component not ready for global usage.
Ideally these values should be property to:
* Be able to be customized
* Be regionalizaed

### Basic example

<Datepicker class='text-xs text-light' datepickerTitle='Data da Consulta' inputPlaceholder='My Text' size='sm'/>

### Motivation

This makes the component more flexible and supported by region.

**Comment by shinokada** [comment]
Thank you for raising this issue.
I understand your concern regarding the Datepicker component being in English, which limits the component's global usability. 

Please note that the Datepicker component is currently in an experimental stage, and we appreciate your feedback.
