### ISSUE TITLE
`null` should be an acceptable `value` type of `<Input />` 

### ISSUE THREAD

**Issue by huntabyte** [themesberg/flowbite-svelte#727]
### Describe the bug

The current acceptable types for `value` on an Input component are `string | number | undefined`.

The `Input` component should align as closely to the svelte/elements `HTMLInputAttributes` as possible, which has `value` typed as `any`. But if `any` isn't acceptable - adding `null` to the type options would suffice.

### Reproduction

```svelte
<script lang="ts">
	// some object I'm pulling from a DB which could possibly be null
	let fullName: string | null = null;
</script>

<!-- TypeError but still works as expected -->
<Input bind:value={fullName} />
```

### Flowbite version and System Info

```shell
0.34.10
```

**Comment by huntabyte** [comment]
If the team is against `any` - then would adding `null` as a type option for the input value be acceptable?

**Comment by shinokada** [comment]
The disadvantages of having both null and undefined are:

Increased complexity: Having both null and undefined in your type union can make your code more complex, as you need to handle both cases when checking for the absence of a value. This can lead to more verbose and error-prone code.

Readability: Allowing both null and undefined can make your code harder to read and understand.

A solution for your case can be converting the null value to undefined using a ternary operator before returning the result:

```
// Let's assume you have a function called `getFullNameFromDB` that retrieves the full name from the database
async function getFullNameFromDB(id: number): Promise<string | null> {
  // Implementation for fetching fullName from the database
}

async function fetchData(id: number): Promise<string | undefined> {
  const fullName = await getFullNameFromDB(id);
  // convert null to undefined
  return fullName !== null ? fullName : undefined;
}
```

**Comment by huntabyte** [comment]
There are other types and schemas that handle such on the server-side and if the code was as simple as the example I provided, sure that could work, unfortunately that's not the case.

Why is `value` even bound as a prop to the `Input`, shouldn't it just be a part of `restProps` considering the value isn't used anywhere else inside the component?

Should a UI library really tell me how to structure/type the data throughout the rest of my app? I understand the "implications" of having both `null` and `undefined` in the union type but should I have to adapt all existing data structures to a UI libraries opinion for an input element?

**Comment by jjagielka** [comment]
> shouldn't it just be a part of restProps considering the value isn't used

If var is part of `restProps` you won't be able to bind it i.e. `bind:value`

**Comment by huntabyte** [comment]
> > shouldn't it just be a part of restProps considering the value isn't used
> 
> If var is part of `restProps` you won't be able to bind it i.e. `bind:value`

Oh yeah I forgot about that gotcha. Regardless, `null` should be provided as an optional type for it considering it causes no issues with the behavior of the input.

**Comment by shinokada** [comment]
I think there are quite a few variables using `string | undefined `. If we decide to change it, we need to consider other cases as well.
