### ISSUE TITLE
Footprint increases 6MB when importing TableSearch

### ISSUE THREAD

**Issue by SupaHam** [themesberg/flowbite-svelte#73]
**Describe the bug**
Without importing `TableSearch` chrome lists 4.3MB transferred. After using it, the number climbs to 10MB, an increases by 5-6MB when using `TableSearch` component. I've explored <https://flowbite-svelte.com/tables> and the total transferred is 1.9MB. The majority of this traffic is from `svelte-heros` svgs being downloaded, the entire repository it seems. I am running this in dev mode which is okay for this scenario, but I am curious where the configurations lie to ensure I can control this behaviour.

**To Reproduce**

1. `import {TableSearch} from 'flowbite-svelte';`

**Expected behavior**
Not to download all unused SVGs.

**Screenshots**
Before importing `TableSearch`
![image](https://user-images.githubusercontent.com/1299921/168845725-4bb4b59d-c970-481c-8359-2cf22871f388.png)

After importing `TableSearch`
![image](https://user-images.githubusercontent.com/1299921/168845548-a5f34757-8e3c-46f5-829f-5fb3708143db.png)

**Desktop (please complete the following information):**

- Chrome
- `"flowbite": "^1.4.5"`

**Comment by shinokada** [comment]
Thank you for the issue. 
It happens for the localhost but not in production.
Please check [the same page](https://flowbite-svelte.com/tables) or [Heroicon page](https://flowbite-svelte.com/icons/heroicons). It doesn't load all icons.

If you still worry about it, you can uninstall Svelte-heros and you just copy necessary icons from the repo to your repo.

Let me know what you think. 
Thanks again for reporting the issue.

**Comment by SupaHam** [comment]
Thanks for the quick response. It's good to see that this is automatically factored in. Would you happen to know of any resources regarding this optimisation and how it's configured?

**Comment by shinokada** [comment]
Since Svelte is a compiler, Svelte does all for you.
You can build it and preview your project and check it.

```
npm run build
npm run preview
```

**Comment by shinokada** [comment]
Closing the issue for now.
Thanks again for taking time to report the issue.
Please let me know when you find more.
