### ISSUE TITLE
`Dropdown` and `Tooltip` do not take scale of parents into account for positioning

### ISSUE THREAD

**Issue by rbozan** [themesberg/flowbite-svelte#739]
### Describe the bug

I have a SVG element which changes in scale (`transform: scale(..)`) and I have some `Dropdown`s as children. These are however not placed correctly whenever the scale is under 1. 

WIth a scale under 1:
![image](https://user-images.githubusercontent.com/7997154/236669291-99fabd6e-c081-4339-a27b-58e73684f04d.png)
(overflows on X axis)

With a scale of 1:
![image](https://user-images.githubusercontent.com/7997154/236669313-f1de94f1-4c1c-4cef-b24c-27e8beef16df.png)

The same is also true for `Tooltip`
### Reproduction

-

### Flowbite version and System Info

```shell
System:
    OS: Linux 5.15 NixOS 22.11 (Raccoon) 22.11 (Raccoon)
    CPU: (4) x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
    Memory: 2.85 GB / 11.57 GB
    Container: Yes
    Shell: 5.9 - /run/current-system/sw/bin/zsh
  Binaries:
    Node: 18.14.1 - /run/current-system/sw/bin/node
    Yarn: 1.22.19 - /run/current-system/sw/bin/yarn
    npm: 9.3.1 - /run/current-system/sw/bin/npm
  Browsers:
    Firefox: 110.0
  npmPackages:
    @sveltejs/kit: ^1.5.0 => 1.16.0 
    flowbite-svelte: ^0.34.4 => 0.34.10 
    svelte: ^3.54.0 => 3.58.0 
    vite: ^4.2.0 => 4.3.4 
```

**Comment by shinokada** [comment]
Can you add your code so that we can see what's wrong?

**Comment by shinokada** [comment]
I close the issue for now due to inactivity.
Thank you for your contribution and feel free to open a new issue.
