### ISSUE TITLE
Toggle, Checkbox, and Input checkbox don't change checked attribute

### ISSUE THREAD

**Issue by jersmart** [themesberg/flowbite-svelte#74]
**Describe the bug**
When using `<Toggle>`, `Checkbox`, `<Input type="checkbox">`, the `checked` property doesn't change when clicking the element.

**To Reproduce**

1. Add a Toggle, Checkbox, or Input type="checkbox":
```
<script type="ts">
  import { Checkbox, Input, Toggle } from "flowbite-svelte";
  let c1: boolean = false, c2: boolean = false, c3: boolean = false, c4: boolean = false;
</script>

<Toggle id="t1" name="t1" label="test" bind:checked={c1}></Toggle>
<Checkbox id="cb1" name="cb1" label="test" bind:checked={c2}></Checkbox>
<Input type="checkbox" id="i1" name="i1" label="test" bind:checked={c3}/>
<input type="checkbox" id="i2" name="i2" bind:checked={c4}>

<div class="text-red-500">{c1}, {c2}, {c3}, {c4}</div>
```
3. Toggle each of the elements
4. Notice the only binding that changes is the last one using the builtin input

**Expected behavior**
these elements should work the same as `<input type="checkbox" bind:checked={thing}>` in svelte.

**Screenshots**

**Desktop (please complete the following information):**

- Chrome
- Version 101.0.4951.64 (Official Build) (64-bit)

**Comment by shinokada** [comment]
Thanks for taking the time to fill out this bug report!

1. I just updated to v0.15.36. Can you update it and let me know.

```
npm i -D flowbite-svelte@latest
```

2. Since there are dedicated components for checkbox. I removed checkbox from the InputType. 

Let me know what you think.

**Comment by shinokada** [comment]
Closing the issue for now.
Thanks again taking time to report the issue.
Please let me know when you find more.
