### ISSUE TITLE
💡 Feature Request: Multiselect Dropdown

### ISSUE THREAD

**Issue by mariusdkm** [themesberg/flowbite-svelte#756]
A multi select dropdown, where you can search for elements and select one or multiple of them.

Just like here the multi dropdown https://react-select.com or here https://multiselect.janosh.dev/

There are no libraries in svelte that have a multiselect that also use tailwind css for styling.
(And none that have a floating label)

I would implement this for flowbite-svelte and make a PR is this possible or should I first add this to the main flowbite repo?
And afterwards add it here?

Thanks

**Comment by shinokada** [comment]
I think  #841 solved this problem.
I close the issue for now.
Thank you for your contribution.
Please feel free to open a new issue.
