### ISSUE TITLE
Alert new properties without default

### ISSUE THREAD

**Issue by BCsabaEngine** [themesberg/flowbite-svelte#757]
### Describe the bug

After upgrading from 0.34.1 to 0.35.1 the Alert cannot be instantiated without props.

The minimum Alert is ```<Alert dismissable={false} accent={false}>```

### Reproduction

Try to use ```<Alert>....</Alert>```, build and svelte-check shows this as error.

### Flowbite version and System Info

```shell
0.35.1
```

**Comment by shinokada** [comment]
Can you show us your code?

https://svelte.dev/repl/0bf3cd6600ff4625b7dd7af0885b23e6?version=3.59.1

![image](https://github.com/themesberg/flowbite-svelte/assets/147320/02bfb7d2-3af4-43fb-96e1-c5e838680432)

**Comment by Torbet** [comment]
Getting same error here using typescript:

**Comment by shinokada** [comment]
Thanks. This is related to the [Frame component](https://github.com/themesberg/flowbite-svelte/blob/main/src/lib/utils/Frame.svelte).

@jjagielka Can you have a look at it?

**Comment by BCsabaEngine** [comment]
0.35.2 solves this problem. Thank you!
