### ISSUE TITLE
Change to a customizable navbar interface

### ISSUE THREAD

**Issue by k-kinzal** [themesberg/flowbite-svelte#77]
## Summary

Thanks for the great project!

The [Navbar](https://flowbite-svelte.com/navbars/default) component is too large and I want to split it into smaller components.

### Basic example

For example:
```html
<Navbar class="text-lg" style="...">
  <Brand class="..." style="...">
        <img src="/images/flowbite-svelte-logo-30.png" alt="flowbite-svelte" />
        <span>Flowbite Svelte</span>
  </Brand>
  <NavItem href="/" class="..." style="...">Home</NavItem>
  <NavItem href="https://github.com/shinokada/flowbite-svelte"  class="..." style="...">GitHub</NavItem>
  <NavItem href="https://flowbite-svelte.vercel.app"  class="..." style="...">Design</NavItem>
</Navbar>
```

I don't think it has to be this structure, but the content within `Brand` and `NavItem` should be changeable, as in this structure.

### Motivation

With this change, more use cases can take advantage of flowbite-svelte's Navbar.
For example we can change the Navbar menu by adding icons to it.
```html
<NavItem href="..."><span><i class="fa fa-github">GitHub</span></NavItem>
```

However, I also understand that this change is not flowbite-svelte-like.
If the proposal does not fit, please close this issue.

**Comment by shinokada** [comment]
I like your suggestions. I will let you know once it's done.
I'm thinking to use Navbar, NavBrand, NavHamburger, NavUl, NavLi names.

I think other components also need some structure changes.
Thank you for great suggestions.

**Comment by shinokada** [comment]
I just update Navbar components.

Please have a look at the [Navbar page](https://flowbite-svelte.com/navbar) for the details.
Let me know what you think.

**Comment by shinokada** [comment]
I added Svelte transition as well.
I close the issue for now.
If you have any more issues, let me know.
Thank you.
