### ISSUE TITLE
Flowbite-Svelte website/components flicker on load

### ISSUE THREAD

**Issue by Destaq** [themesberg/flowbite-svelte#770]
### Describe the bug

I've noticed that when using the `flowbite-svelte` library, upon initial load, it seems that many Flowbite styles are only applied *after* the HTML elements are rendered.

This leads to an unpleasant UI, and hopefully a way can be found around this. The issue also occurs with the official website — see the video below.

https://github.com/themesberg/flowbite-svelte/assets/61620873/55d99e61-89f2-41b1-8e90-2735684719b8

### Reproduction

Reproduction is the docs site for `flowbite-svelte`. Note that the font, navbar issues may be due to non-SSR things. But definitely, at least for the input element, we can see that the border only gets added after.

### Flowbite version and System Info

Attaching my own versions, which should be somewhat similar to whichever ones are hosting the official website.

```shell
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1
    Memory: 268.98 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.6.0 - /opt/homebrew/bin/node
    Yarn: 1.22.11 - /opt/homebrew/bin/yarn
    npm: 9.4.0 - /opt/homebrew/bin/npm
  Browsers:
    Brave Browser: 113.1.51.114
    Safari: 16.4
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.589 
    flowbite-svelte: ^0.30.0 => 0.30.4 
    svelte: ^3.55.1 => 3.55.1 
    vite: ^4.0.0 => 4.1.1 
```

**Comment by Destaq** [comment]
The issue also occurs in production builds, albeit with a much smaller (time-wise) flicker since assets are optimized.

**Comment by shinokada** [comment]
It could be because of `+page.js` in each directory:

```
// src/routes/components/[slug]/+page.js
/** @type {import('./$types').PageLoad} */
export async function load({ params }) {
  const post = await import(`../${params.slug}.md`);
  const { title, dir } = post.metadata;
  const content = post.default;

  return {
    content,
    title,
    dir
  };
}
```

Will this happen after installing Flowbite-svelte to your project?

**Comment by Destaq** [comment]
> It could be because of `+page.js` in each directory:
> 
> 
> 
> ```
> 
> // src/routes/components/[slug]/+page.js
> 
> /** @type {import('./$types').PageLoad} */
> 
> export async function load({ params }) {
> 
>   const post = await import(`../${params.slug}.md`);
> 
>   const { title, dir } = post.metadata;
> 
>   const content = post.default;
> 
> 
> 
>   return {
> 
>     content,
> 
>     title,
> 
>     dir
> 
>   };
> 
> }
> 
> ```
> 
> 
> 
> Will this happen after installing Flowbite-svelte to your project?

Well, my current project that uses `flowbite-svelte` also has this issue, even though it does not have any +page.js/ts files.

I do wonder whether it might just be due to Svelte itself. It looks like slots (which this library relies on a lot) are rendered at a weird point in component lifecycles. I've made a pure Svelte minimum reproduction here: https://github.com/Destaq/flicker/blob/main/src/routes/+page.svelte

Though that would not explain why even the input button has styling flickers in the video?

If there's anything else you need me to repro / log / help with, please let me know and I'll get on it ASAP. This seems like quite a significant problem given that it even occurs on the documentation website.

**Comment by shinokada** [comment]
I tested it with Flowbite, Flowbite-Svelte on a fresh SvelteKit and it doesn't have any problem even I have `+page.js`.

I suspect of flickering is due to SSR. I need to check it more.

**Comment by Destaq** [comment]
> I tested it with Flowbite, Flowbite-Svelte on a fresh SvelteKit and it doesn't have any problem even I have `+page.js`.
> 
> I suspect of flickering is due to SSR. I need to check it more.

Would just like to bring up a potentially related issue that I found for the website / a component. Specifically, it appears that not only these styles flicker, but also DarkMode flickers.

If you go to the Flowbite-Svelte site, turn on dark mode, and then force reload (Cmd-Shift-R), then the page is initially in light mode, and then renders dark mode. The same happens during normal loads but it is a bit less obvious.

Been trying to look into this for the past few hours myself (the original issue that is), but no luck yet unfortunately.

**Comment by Destaq** [comment]
At least managed to identify one thing though. If we edit a slot component in `node_modules`, and reload (r in the CLI), for example like this for `Input.svelte`:

```svelte
<Wrapper class="relative w-full" show={$$slots.left || $$slots.right}>
    <span>HERE IS A CHANGE</span>
    {#if $$slots.left}
        <div class="{floatClass} left-0 pl-2.5 pointer-events-none">
            <slot name="left" />
        </div>
    {/if}
    ...
```

Then there will be first a flicker with the new text, and then it will settle to a final state without the `HERE IS A CHANGE` text. However, if you import the `Input.svelte` locally (by e.g. creating a new module), then `HERE IS A CHANGE` stays there forever. Sadly, the flicker (for the border in this case) still happens. But potentially this could be of some insight.

**Comment by Destaq** [comment]
A workaround is to do this:

```svelte
<script>
    import { onMount } from "svelte";
    let mounted = false;
    onMount(() => {
        localStorage.getItem("color-theme") === "dark" ||
        (!("color-theme" in localStorage) &&
            window.matchMedia("(prefers-color-scheme: dark)").matches)
            ? window.document.documentElement.classList.add("dark")
            : window.document.documentElement.classList.remove("dark");
        mounted = true;
    });
</script>

{#if mounted}
    <slot />
{/if}
```

in the main `+layout.svelte` page. Then, all flickering and styling issues are resolved. However, first contentful paint worsens by a magnitude of 10 on dev. I'm pretty sure that the above is just because I am essentially artificially disabling SSR.

**Comment by Destaq** [comment]
I have overcome the `DarkMode` flickering, which involved rewriting the entire component as per this video: https://www.youtube.com/watch?v=3GpZkVBjXfE&ab_channel=Huntabyte.

**Comment by shinokada** [comment]
@Destaq Do you think you can update DarkMode component and create a PR?

**Comment by Destaq** [comment]
> @Destaq Do you think you can update DarkMode component and create a PR?

Well I could try. However, the new non-flickering method requires additions to not only a component, but also amendments to `+page.server.ts` and some hooks. In short, it's just applicable to SSR SvelteKit use of `flowbite-svelte`. So I'm not sure that it would be possible to make a meaningful PR that would work for all uses of the component.

**Comment by shinokada** [comment]
We need to try to avoid a BREAKING CHANGE if it is possible. But if it's inevitable, then we have to.
We also need to update the [doc](https://flowbite-svelte.com/docs/components/darkmode).

**Comment by Destaq** [comment]
> We need to try to avoid a BREAKING CHANGE if it is possible. But if it's inevitable, then we have to. We also need to update the [doc](https://flowbite-svelte.com/docs/components/darkmode).

What I mean is that this issue is specific to one usecase of `flowbite-svelte`. When using the library with SvelteKit and SSR, then there is the flickering problem. To resolve said problem, you need to use certain characteristics of SvelteKit / SSR like the server pages.

So, I don't know if it is possible to make a PR. Not all users of the library are using it presumably with SSR + SvelteKit. So, the new DarkMode component wouldn't work for them.

**Comment by shinokada** [comment]
I think this issue is solved.
Thank you for your contribution.
Please feel free to open a new issue.
