### ISSUE TITLE
 Error while preprocessing  ... colors is not defined

### ISSUE THREAD

**Issue by MiruhiMiruhi** [themesberg/flowbite-svelte#78]
**Describe the bug**
Error compiling upon updating to `flowbite-svelte ^0.15.38`

**To Reproduce**

1. Run `npm i -D flowbite-svelte@latest`
2. Build project
3. See error

Error:
```
[vite] Internal server error: Error while preprocessing <Project Directory>/node_modules/flowbite-svelte/carousels/Indicator.svelte - colors is not defined
  Plugin: vite-plugin-svelte
  File: <Project Directory>/node_modules/flowbite-svelte/carousels/Indicator.svelte
```

**Comment by shinokada** [comment]
Thank you for taking time to report the bug.
The Indicator.svelte has no colors type nor prop.

Could you try the following and let me know.

```
// remove the lock file
rm ./package-lock.json
// remove the node_modules dir
rm -rf ./node_modules
// install npm
npm i
```

**Comment by shinokada** [comment]
I close this for now. Please let me know if you find more issues. Thank you.
