### ISSUE TITLE
Tooltip - Arrow is always in the middle

### ISSUE THREAD

**Issue by niklas-stegmann** [themesberg/flowbite-svelte#781]
### Describe the bug

The arrow of the tooltip component is always in the middle since the new version.

I upgraded from 34.12 to the latest version and had this error. When I go back to my last version, it works as expected.

Can be reproduced on the official website https://flowbite-svelte.com.

**Hint:**
It seems like it broke on merge request #759, because on the merge before that (#755) the tooltip works as expected.

### Reproduction

1. Go to https://flowbite-svelte.com/docs/components/tooltip
2. Hover over "Toggle dark mode"

![image](https://github.com/themesberg/flowbite-svelte/assets/32418474/df403c14-3a48-4aae-afeb-2958769e3b01)

### Flowbite version and System Info

```shell
See public flowbite-svelte page
```

**Comment by shinokada** [comment]
@niklas-stegmann You are right. https://flowbite-svelte-8bphrm0xq-themesberg.vercel.app/ which is before #759 works.
@jjagielka Can you have a look at it?
