### ISSUE TITLE
New outsideclose for Modal doesn't work with small content

### ISSUE THREAD

**Issue by Blackwidow-sudo** [themesberg/flowbite-svelte#786]
### Describe the bug

The new `outsideclose` prop for the `Modal` works in general, but it has issues regarding the clickable area outside. For example if the modal is only slotted with a short `<p>Are you John Doe?</p>`, the modal only closes when the click outside happens far enough from the borders of the `div[id="modal"]`.

The issue is that the visible modal is smaller than the actual `div[id="modal"]`, as seen in the screenshot:
![outsideclose-bug](https://github.com/themesberg/flowbite-svelte/assets/60359431/967e4330-2737-4b90-86c2-be02e3ac82cc)

### Reproduction

REPL Example:
https://svelte.dev/repl/02d6cb69117a48bf8150d070d7e866a8?version=3.59.1

Example:
```svelte
<script lang="ts">
  import { Button, Modal } from 'flowbite-svelte';

  let open = false;
</script>

<Button on:click={() => (open = !open)}>Default modal</Button>

<Modal title="Who are you?" autoclose outsideclose bind:open>
  <p>Are you John Doe?</p>
  <svelte:fragment slot="footer">
    <Button on:click={() => alert('Handle "success"')}>I accept</Button>
    <Button color="alternative">Decline</Button>
  </svelte:fragment>
</Modal>
```

### Flowbite version and System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (12) x64 AMD Ryzen 5 1600 Six-Core Processor
    Memory: 3.47 GB / 7.73 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.15.0 - ~/.local/share/pnpm/node
    npm: 9.5.0 - ~/.local/share/pnpm/npm
  npmPackages:
    @sveltejs/kit: ^1.5.0 => 1.18.0 
    flowbite-svelte: ^0.36.4 => 0.36.4 
    svelte: ^3.54.0 => 3.59.1 
    vite: ^4.3.0 => 4.3.8
```

**Comment by shinokada** [comment]
Have you tried it on your localhost? 
When I tried you code, I don't have the same problem as REPL.
There are quite few limitations with Svelte REPL.

**Comment by Blackwidow-sudo** [comment]
> Have you tried it on your localhost? 
> When I tried you code, I don't have the same problem as REPL.
> There are quite few limitations with Svelte REPL.

Yes the screenshot is actually from my local project.
