### ISSUE TITLE
Svelte Component Hover Hint Text in VScode

### ISSUE THREAD

**Issue by Maxiviper117** [themesberg/flowbite-svelte#792]
## Summary

Currently, in Vscode when using Svelte components like the ones from Flowbite-svelte, many of them contain a number of props and options, meaning a lot of back and forth between the documentation and code to see what's available beyond using the intellisence when typing props to use.

As well as trying to quickly open a Flowbite-svelte component is not straight forward because it is from a node module, meaning CMD+click / Ctrl+click takes you to the components `.d.ts` file instead of straight to the `.svelte` file to see what we can use.

A proposed alternative would be to make use of the HTML hover in VS Code, I'm not sure about other IDEs.

### Basic example

Currently, when you hover over an imported svelte component, like with this `NavBar` component, we only see this:

```js
(alias) class Navbar
import Navbar
```
![image](https://github.com/themesberg/flowbite-svelte/assets/11472492/e1d9e188-8fa5-46ed-ae5c-008795650960)

But by adding in this comment clock with the `@component` tag anywhere in the svelte component (preferable at the top). Any text inside of it is shown in the hover hint. 

It also Supports Markdown format

```html
<!--
    @component
    
    ... any text here is shown in hover hint ...
    
    It also Supports Markdown format.
    
    # Heading
    
    ```js
        let text;
    ```

-->
```
Here in this example I have a component called `Shell` with the above comment block included in it.

Now when we hover over the `<Shell ... />` component we see that text.
![image](https://github.com/themesberg/flowbite-svelte/assets/11472492/5ca20c50-cfd2-405f-b086-f919970c580a)


### Motivation

Using this hover hint means we can add some brief context of what the component does and reveal all props and/or options of the component we can use, which provides quicker reference of usage instead of always going back to the documentation on the website to see how it is used and what the component contains for props and options.

Additionally, we can provide direct links to the documentation of each component, allowing for quick access to detailed information about each component on their respective page on the website.

**Comment by Maxiviper117** [comment]
Seems this functionality originates from this:

https://github.com/SoftwareBrothers/better-docs

Where it is typically used to document React and Vue components automatically also to show props making used of JSDoc, but using it with the html comment block seems to offer similar functions for .svelte component.

**Comment by shinokada** [comment]
Something like this?

<img width="815" alt="image" src="https://github.com/themesberg/flowbite-svelte/assets/147320/f3d97036-cfb7-4998-98e8-fee8640f5c91">


```
<!--
  @component
  @prop divClass: string = 'w-full md:block md:w-auto';
  @prop ulClass: string = 'flex flex-col p-4 mt-4 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium';
  @prop hidden: boolean = true;
  @prop slideParams: SlideParams = { delay: 250, duration: 500, easing: quintOut };
  @prop activeClass: string = 'text-white bg-blue-700 md:bg-transparent md:text-blue-700 md:dark:text-white dark:bg-blue-600 md:dark:bg-transparent';
  @prop nonActiveClass: string = 'text-gray-700 hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent';
  
-->
```

**Comment by Maxiviper117** [comment]
Indeed, could also add in a url link to the component in the comment block as well.

Like:

```html
<!--
  @component
  @prop divClass: string = 'w-full md:block md:w-auto';
  @prop ulClass: string = 'flex flex-col p-4 mt-4 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium';
  @prop hidden: boolean = true;
  @prop slideParams: SlideParams = { delay: 250, duration: 500, easing: quintOut };
  @prop activeClass: string = 'text-white bg-blue-700 md:bg-transparent md:text-blue-700 md:dark:text-white dark:bg-blue-600 md:dark:bg-transparent';
  @prop nonActiveClass: string = 'text-gray-700 hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent';
  
  src: https://flowbite-svelte.com/docs/components/navbar
-->
```

**Comment by shinokada** [comment]
Please see the progress so far at #792.
