### ISSUE TITLE
Checkbox behavior different than standard HTML in `formData`

### ISSUE THREAD

**Issue by bbtgnn** [themesberg/flowbite-svelte#794]
### Describe the bug

This issue occurs with standard form handling (without js usage) – aka submitting a `<form method='post'>` with `<Button type='submit'>`

As you can test in the repo:
- A flowbite checkbox **without** `value` prop, returns `{ value: "" }` in `FormData`
- Instead, a default HTML checkbox **without** `value` prop, returns `{ value: "on" }` in `FormData`

imo, the behavior should comply with HTML standards.
(if it's instead intender behavior, then let me know)

p.s. Thanks for your work! ✨ 

### Reproduction

I made a very simple test repo here, please clone and then `npm run dev`
https://github.com/bbtgnn/sveltekit-action-flowbite-checkbox-error

Click the submit button on the homepage, and see the logs in the node console.

### Flowbite version and System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 319.84 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.15.0/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 112.0.2
    Safari: 16.4
  npmPackages:
    @sveltejs/kit: ^1.5.0 => 1.19.0 
    flowbite-svelte: ^0.36.5 => 0.36.5 
    svelte: ^3.54.0 => 3.59.1 
    vite: ^4.3.0 => 4.3.8
```

**Comment by shinokada** [comment]
I just updated and it will be in the next version.
Thank you for your contribution.
