### ISSUE TITLE
Toast component

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite-svelte#8]
Add [Toast](https://flowbite.com/docs/components/toast/) component.

- [x] Default toast
- [x] Colors
- [x] Simple toast
- [x] Undo button
- [x] Toast message
- [x] Push notification
- [x] Interactive toast
- [x] Positioning

**Comment by jjagielka** [comment]
- Undo button
- Push notification
- Interactive toast
- Positioning

Added in the awaiting PR

**Comment by shinokada** [comment]
Completed. Thanks to @jjagielka.
