### ISSUE TITLE
Component updates don't work in grouped routes

### ISSUE THREAD

**Issue by UnlimitedBytes** [themesberg/flowbite-svelte#829]
### Describe the bug

When you use the flowbite components inside layouts which are part of a routes group they don't receive any updates from Svelte. So for example when you add a navigation bar to a `+layout.svelte` file in a group like `(app)` the navigation component will no longer receive updates to it's props.

So for example: 
```html
<!-- src/routes/(app)/+layout.svelte -->
<script lang="ts">
    import { page } from '$app/stores';
    import { Navbar, NavBrand, NavLi, NavUl, NavHamburger } from 'flowbite-svelte';

    $: activeUrl = $page.url.pathname;
</script>

<Navbar let:hidden let:toggle>
    <NavBrand href="/">
        <img src="https://flowbite.com/docs/images/logo.svg" class="mr-3 h-6 sm:h-9" alt="Flowbite Logo" />
        <span class="self-center whitespace-nowrap text-xl font-semibold dark:text-white"> Flowbite </span>
    </NavBrand>

    <NavHamburger on:click={toggle} />

    <NavUl {hidden}>
        <NavLi href="/" active={activeUrl == '/'}>Home</NavLi>
        <NavLi href="/about" active={activeUrl == '/about'}>About</NavLi>
    </NavUl>
</Navbar>

<slot />
``` 
will result in the ``active`` prop only getting updated when you reload the page. While CSR is happening the prop will not update and the "Home" link will be highlighted after going to the "About" page.

### Reproduction

Here is an app which I setup following the instructions on https://flowbite-svelte.com/docs/pages/introduction which includes a `src/routes/(app)/+layout.svelte`, `src/routes/(app)/+page.svelte` and `src/routes/(app)/about/+page.svelte` to showcase the issue using the ``Navbar`` component.

https://github.com/UnlimitedBytes/flowbite-csr-issue

### Flowbite version and System Info

```shell
System:
    OS: Windows 11 22621
    Memory: 5.73 GB / 34.36 GB
  Binaries:
    Node: 18.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1702.0), Chromium (114.0.1823.37)
  npmPackages:
    @sveltejs/kit: ^1.5.0 => 1.20.1
    flowbite-svelte: ^0.37.4 => 0.37.4
    svelte: ^3.54.0 => 3.59.1
    vite: ^4.3.0 => 4.3.9
```

**Comment by nash-an** [comment]
This seems to still be happening as of version 0.43.1.
```
    @sveltejs/kit: ^1.20.4 => 1.22.5
    flowbite-svelte: ^0.43.1 => 0.43.1
    svelte: ^4.0.5 => 4.2.0
```


Happens with the activeUrl prop in a parent component/wrapper, and only in a svelte grouped route.
For example, this code will only apply the activeClass styling on a full page refresh (for example if I loaded to /orders) but if I change pages after, the activeClass does not update.


```html
routes/(app)/+layout.svelte

<script lang="ts">
</script>

<Navbar>
    <NavUl {activeUrl}>
        <NavLi href="/">Home</NavLi>
        <NavLi href="/orders">Orders</NavLi>
        <NavLi href="/contact">Contact</NavLi>
        <NavLi href="/about">About</NavLi>
    </NavUl>
</Navbar>
```

**Comment by shinokada** [comment]
You need to use {#key activeUrl}

```
{#key activeUrl}
<Navbar let:hidden let:toggle>
  <NavUl {hidden} {activeUrl}>
      <NavLi href="/">Home</NavLi>
      <NavLi href="/about">About</NavLi>
      <NavLi href="/contact">Contact</NavLi>
      <NavLi href="/orders">Orders</NavLi>
      <NavLi href="/profile">Profile</NavLi>
  </NavUl>
</Navbar>
{/key}
```

**Comment by shinokada** [comment]
Demo at https://stackblitz.com/edit/sveltejs-kit-template-default-pg2vp5?file=src%2Froutes%2F(app)%2F%2Blayout.svelte

**Comment by f0o** [comment]
> You need to use {#key activeUrl}
> 
> ```
> {#key activeUrl}
> <Navbar let:hidden let:toggle>
>   <NavUl {hidden} {activeUrl}>
>       <NavLi href="/">Home</NavLi>
>       <NavLi href="/about">About</NavLi>
>       <NavLi href="/contact">Contact</NavLi>
>       <NavLi href="/orders">Orders</NavLi>
>       <NavLi href="/profile">Profile</NavLi>
>   </NavUl>
> </Navbar>
> {/key}
> ```

This doesnt seem to work in:
```
		"svelte": "^4.2.8",
		"@sveltejs/kit": "^2.0.6",
		"flowbite": "^2.2.1",
		"flowbite-svelte": "^0.44.21",
		"flowbite-svelte-icons": "^0.4.5",
```

The active class goes away but it's not added to any page you browse to.
