### ISSUE TITLE
A way to programmatically add tabs to Interactive tabs 2

### ISSUE THREAD

**Issue by Gildedter** [themesberg/flowbite-svelte#83]
## Summary
Been using the new `Interactive Tabs 2` and upon initializing it with an empty tab collection, no headers are added, only tab contents appear.

### Motivation
I'm designing a form for import pdfs, where an imported form is added as a new tab upon the `file-input` `on:change` event

**Comment by shinokada** [comment]
Can you give an example of how to use it?

**Comment by Gildedter** [comment]
```
<script lang="ts">
  function handleChange() {
      if (files && files.id) {
          tabhead.push(tab1);
      }
  }

  let tab1= { name: "tab 1", id: 1 };
  let tab2 = { name: "tab 2", id: 2 };
  let tabhead = [];
  let selected = "";
  let files: any;

  // TODO: implement select filters (loan application, payments, etc.)
</script>

  <FileInput id="import-file" label="Import" bind:value={files} on:change={handleChange} />
  
<InteractiveTabHead tabs={tabhead}>
  <TabContent tab={tab1} />
  <TabContent tab={tab1} divClass="rounded-lg dark:bg-gray-800">
    <Tsble source={files} />
  </TabContent>
  <TabContent tab={tab2} divClass="rounded-lg dark:bg-gray-800">
    <Table source={files} />
  </TabContent>
</InteractiveTabHead>
```

**Comment by shinokada** [comment]
How about reassigning the `tabhead` using [this example](https://svelte.dev/tutorial/updating-arrays-and-objects)?

**Comment by Gildedter** [comment]
> How about reassigning the `tabhead` using [this example](https://svelte.dev/tutorial/updating-arrays-and-objects)?

Works perfectly thanks, any chance for a closable tab? Like a browser tab but its made from `Interactive Tab 2`

**Comment by shinokada** [comment]
Closing the issue for now since the original question was solved.
Thank you for your contribution and feel free to create issues when you find more.
