### ISSUE TITLE
TimelineItem type definition missing

### ISSUE THREAD

**Issue by lym8356** [themesberg/flowbite-svelte#831]
### Describe the bug

In the documentation, I can see TimelineItem has 6 props that can be customized.
But in the type definition file, there are only 4
![image](https://github.com/themesberg/flowbite-svelte/assets/12198009/88663c44-567a-40b8-8f3e-9a0c62c2737d)

### Reproduction

<TimelineItem
                title={"Update " + (i+1)}
                date={new Date(siteLog.dateAdded).toLocaleDateString("en-US", {
                    year: "numeric",
                    month: "long",
                    day: "numeric",
                })}
                customLiClass=""  // THIS LINE GIVES ERROR
            >
                <svelte:fragment slot="icon">
                    <span
                        class="flex absolute -left-3 justify-center items-center w-6 h-6 bg-primary-200 rounded-full ring"
                    >
                        <MdiTask />
                    </span>
                </svelte:fragment>
                <p class="mb-4 text-base font-normal text-textPrimary-400 text-start">
                    {siteLog.description}
                </p>
            </TimelineItem>

### Flowbite version and System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 37.93 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 114.0.5735.90
    Safari: 16.3
  npmPackages:
    "flowbite": "^1.6.5",
    "flowbite-svelte": "^0.35.3"
```

**Comment by shinokada** [comment]
There will be six type definitions in the coming version.

<img width="627" alt="image" src="https://github.com/themesberg/flowbite-svelte/assets/147320/f9123e80-4c3f-489a-aaf0-39ee835e2969">

**Comment by shinokada** [comment]
I close the issue for now.
Thank you for your contribution.
Please feel free to open a new issue.
