### ISSUE TITLE
Playground for trying out the components

### ISSUE THREAD

**Issue by vasucp1207** [themesberg/flowbite-svelte#834]
## Summary

Would like to have a playground environment where we can experiment with Svelte components, we can use sandpack for building the playground. We can also used it for reporting the issues.

### Motivation

I believe having a playground for trying out components would greatly benefit developers.

**Comment by shinokada** [comment]
Please create a fork from [this stackblitz](https://stackblitz.com/edit/sveltejs-kit-template-default-efqgaq?file=src%2Froutes%2F%2Blayout.svelte).
