### ISSUE TITLE
Popover arrow icon not inheriting background color

### ISSUE THREAD

**Issue by SiNONiMiTY** [themesberg/flowbite-svelte#839]
I am trying to replicate the flowbite-admin-dashboard project using flowbite-sveltekit

But I am encountering this issue
https://github.com/themesberg/flowbite-svelte-admin-dashboard/issues/7#issuecomment-1579826244

Repository is available here
https://github.com/SiNONiMiTY/flowbite-sveltekit-admin-dashboard/tree/main

StackBlitz Demo **remove arrow={false}**
https://stackblitz.com/edit/stackblitz-starters-yxsqgm?file=src%2Flib%2Flayouts%2FSidebar.svelte

**Comment by jjagielka** [comment]
The StackBlitz demo doesn't work. Can you please supply some screen shots with the issue you ask to resolve?

**Comment by SiNONiMiTY** [comment]
> The StackBlitz demo doesn't work. Can you please supply some screen shots with the issue you ask to resolve?

The issue I am describing is in the issue but here is the screenshot
![image](https://github.com/themesberg/flowbite-svelte/assets/9588282/0c563fd8-531b-4d93-b5f3-37b82719cc9e)

You can see that the popover icon is colored differently, however, this works fine if I swap popover to tooltip component

**Comment by jjagielka** [comment]
Somehow you have answered yourself. Use the right tool for the problem. Your use case is for using `Tooltip`.

Popover is supposed to show more advanced information (allowing even the interaction in the popover itself - like embedded form). `Popover` requires a `title` props to be set. Add the `title` to your case and check if you still have coloring issue.

**Comment by SiNONiMiTY** [comment]
> Somehow you have answered yourself. Use the right tool for the problem. Your use case is for using `Tooltip`.
> 
> Popover is supposed to show more advanced information (allowing even the interaction in the popover itself - like embedded form). `Popover` requires a `title` props to be set. Add the `title` to your case and check if you still have coloring issue.

Yes I already tried adding title, thats why I opened the issue, they both perform the same task, the difference is that popover is can perform showing advance information.

![image](https://github.com/themesberg/flowbite-svelte/assets/9588282/661898b3-9256-4afb-b758-3fc02b7d5ab0)

Then why the more advanced component has a regression.

**Comment by jjagielka** [comment]
That's really strange behavior. Still your StackBlitz doesn't work for me (I don't know why). I'll try to reproduce that in my set up to analyze that.

**Comment by SiNONiMiTY** [comment]
> That's really strange behavior. Still your StackBlitz doesn't work for me (I don't know why). I'll try to reproduce that in my set up to analyze that.

can you see if the branch you are running is named "issue"...

You might be on the main branch...

Thank you for your time in taking a look at this 😁

**Comment by jjagielka** [comment]
Just uploaded a PR that address the issues. Please do check it out.

**Comment by SiNONiMiTY** [comment]
@jjagielka just tested out your PR

Here are the code snippets that I used to test

```
<!-- This works fine -->
<Tooltip id="settings-popover" defaultClass="px-3 py-2 text-sm font-medium rounded-lg text-white bg-gray-900 dark:bg-gray-700" transition={fade} params={{duration: 300}}>
    Settings page
</Tooltip>
```

![image](https://github.com/themesberg/flowbite-svelte/assets/9588282/861506b1-0f41-4bee-b821-9c60d6164f9f)

```
<!-- This one here has an incorrectly colored arrow icon -->
<Popover id="settings-popover" defaultClass="px-3 py-2 text-sm font-medium rounded-lg text-white bg-gray-900 dark:bg-gray-700" transition={fade} params={{duration: 300}}>
    Settings page
</Popover>
```

![image](https://github.com/themesberg/flowbite-svelte/assets/9588282/d0dd42a5-4929-46be-a12b-b61da08d19de)

The border now works properly, but the arrow icon color still seems off

**Comment by SiNONiMiTY** [comment]
@shinokada why closed the issue, the arrow still has incorrect background color, only the border was fixed

**Comment by shinokada** [comment]
I didn't close it. GitHub closes it automatically. I just reopened it.

**Comment by SiNONiMiTY** [comment]
> I didn't close it. GitHub closes it automatically. I just reopened it.

Thanks for your hard work @shinokada  @jjagielka, I am also trying to pinpoint the issue 😊

**Comment by jjagielka** [comment]
The issue with your case is the usage of the `defaultClass`. This prop is to sets the padding in the lower part of the popover. (Probably lack in documentation). To achieve what you want use `class` property.
```svelte
<Popover id="settings-popover" class="text-sm font-medium text-white !bg-gray-900 dark:!bg-gray-700">
    Settings page
</Popover>
```
Notice that I removed the transition prop as well as `fade` is the default one. If you want to use other transition you need to put it back of course.

**Comment by jjagielka** [comment]
Is that issue addressed? Can we close it?

**Comment by SiNONiMiTY** [comment]
Hi @jjagielka, I cannot achieve the same effect by only using the "class" property. I even tried copying the base "defaultClass" property and just add the css classes that I use and still, the arrow has the incorrect color.

For the meantime I just used Tooltip. I will be encountering this issue once again when I need the Popover component.

Currently in the middle of prototyping a project UI so I need to be fast and can't focus on finding what is the root cause of this issue. Will get back to this once there is free time. Thanks :)

**Comment by jjagielka** [comment]
Hmm. Here's the working example [REPL](https://svelte.dev/repl/42177b740ef24e79be5634d5992dcf9c?version=3.59.1)

*Note: Sometimes tailwindcss is not applied straight away. You need to touch the code until you see red and green button.*

**Comment by SiNONiMiTY** [comment]
@jjagielka 

![image](https://github.com/themesberg/flowbite-svelte/assets/9588282/f7dab32e-922c-4877-83da-036a92e7eb80)

Wow, Just tried reusing the code I have been using and it magically works on the REPL

I think we can close this issue now. Thanks for all of the efforts you have put into this :)
