### ISSUE TITLE
Website's home page CSS is off at xl breakpoint

### ISSUE THREAD

**Issue by Etchelon** [themesberg/flowbite-svelte#84]
**Describe the bug**
![image](https://user-images.githubusercontent.com/4141889/171066137-13d0cf0c-c602-426b-b0a3-ce6b6119d114.png)

**To Reproduce**
At a width of 1536px the issue appears, then gradually goes away as the width further increases

**Desktop (please complete the following information):**

- Browser: Edge
- Version: doesn't really matter

**Comment by shinokada** [comment]
Thanks. I just updated.
