### ISSUE TITLE
Docs don't follow compiler speed guidelines

### ISSUE THREAD

**Issue by chinmaykh** [themesberg/flowbite-svelte#844]
## Summary

The compiler speed guidelines [(here)](https://flowbite-svelte.com/docs/pages/compiler-speed) show us how to dramatically improve speed by only importing what is necessary. Yet all the docs still feature full-fledged imports. This makes the development really slow - `npm run dev` takes forever.

### Basic example

Within src > routes > docs > components > alert.md.
```
import Alert from 'flowbite-svelte/Alert.svelte'
import { Alert } from 'flowbite-svelte'
```

This is from the docs itself!  The guidelines are your own, don't you think you can benefit from it?

### Motivation

This UI library is quickly becoming my favourite to use with sveltekit. It looks modern and beautiful and integrates well with svelte. As contributors, we can make it easy on ourselves by importing what is necessary only.

**Comment by shinokada** [comment]
The guideline I wrote is for small projects. Since this repo uses all the components, there is no point to import individually.

**Comment by chinmaykh** [comment]
Ah, cool!
