### ISSUE TITLE
Breaks in Jest

### ISSUE THREAD

**Issue by ispyinternet** [themesberg/flowbite-svelte#846]
### Describe the bug

When trying to test components that use flowbite-svelte for some reason:

`Cannot find module 'flowbite-svelte'`

Don't think it is to do with the jest config, as I have other node module packages that are being resolved fine, e.g:

```
	import { Accordion, AccordionItem } from "carbon-components-svelte";
	import { Input, Label, Button, Spinner } from 'flowbite-svelte';
```

No problems with `carbon-components-svelte`, I even tried to mimick their build steps to supply a commonjs lib alternative see:

https://github.com/carbon-design-system/carbon-components-svelte/blob/master/rollup.config.js
https://github.com/carbon-design-system/carbon-components-svelte/blob/master/package.json#LL6C1-L8C31

But same error `Cannot find module 'flowbite-svelte'`

I have no idea now what is causing this.

### Reproduction

Will take some time to strip a repo together, posting for some initial thoughts / suggestions

### Flowbite version and System Info

```shell
System:
    OS: Linux 4.14 Amazon Linux 2
    CPU: (4) x64 Intel(R) Xeon(R) CPU E5-2651 v2 @ 1.80GHz
    Memory: 11.15 GB / 14.68 GB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.19 - ~/.npm-global/bin/yarn
    npm: 8.15.1 - ~/.npm-global/bin/npm
  npmPackages:
    @sveltejs/kit: ^1.5.0 => 1.20.2 
    flowbite-svelte: ^0.37.4 => 0.37.4 
    svelte: ^3.54.0 => 3.59.1 
    vite: ^4.2.0 => 4.3.9
```

**Comment by shinokada** [comment]
Is it possible to see your repo?

**Comment by ispyinternet** [comment]
while trying to strip back to demo repo, it turns out carbon-components also wasn't working so put this down to a jest config / resolution / transformation issue.

Moved to vitest and everything is working great.
