### ISSUE TITLE
Support searching for documentation from root website page

### ISSUE THREAD

**Issue by Destaq** [themesberg/flowbite-svelte#849]
## Summary

Currently, if one navigates to [flowbite-svelte.com](https://flowbite-svelte.com/), there is no way to immediately search for documentation (e.g. with a search bar, cmd-K, etc.) Users must first click on the `Docs` navitem, and only then does the navbar update and cmd-K functionality appear.

It would be more helpful if this navbar was the default one, to save one click.

### Motivation

Quality of life improvement. Also, if you go to [the official Flowbite website](https://flowbite.com/), you can see that this is the behavior there.

**Comment by shinokada** [comment]
Yes, we will add the search icon in the home page.

**Comment by shinokada** [comment]
Since there is limited space on the home page, the search feature is hidden on a small screen.
