### ISSUE TITLE
Carousel componet makes error moving images array

### ISSUE THREAD

**Issue by God-lives** [themesberg/flowbite-svelte#852]
### Describe the bug

when "images" arrays are changed, "imageShowingIndex" value must set to zero in Carousel.svelte

examples:

 let images1 = [
  {
    id: 0,
    name: "Cosmic timetraveler",
    imgurl: "/images/carousel/cosmic-timetraveler-pYyOZ8q7AII-unsplash.webp",
    attribution: "cosmic-timetraveler-pYyOZ8q7AII-unsplash.com",
  },
  {
    id: 1,
    name: "Cristina Gottardi",
    imgurl: "/images/carousel/cristina-gottardi-CSpjU6hYo_0-unsplash.webp",
    attribution: "cristina-gottardi-CSpjU6hYo_0-unsplash.com",
  },  
];

let images2 = [
  {
    id: 0,
    name: "Cosmic timetraveler",
    imgurl: "/images/carousel/cosmic-timetraveler-pYyOZ8q7AII-unsplash.webp",
    attribution: "cosmic-timetraveler-pYyOZ8q7AII-unsplash.com",
  },
];

When applying images1 to the Carousel and then trying to apply images2, a TypeError occurs with the message "Cannot read properties of undefined (reading 'imgurl')".

### Reproduction

https://[gs.gongsilbox.com/map/one?lat=36.33179&lng=127.40194&zoom=12&r=81ff0759-31c8-4e45-a79b-f0869a50dbd4](https://gs.gongsilbox.com/map/one?lat=36.33179&lng=127.40194&zoom=12&r=81ff0759-31c8-4e45-a79b-f0869a50dbd4)

### Flowbite version and System Info

```shell
flowbite-svelte v0.37.5
```

**Comment by God-lives** [comment]
when "images" arrays are changed, "imageShowingIndex" value must set to zero in Carousel.svelte.
Please solve this simple problem as soon as possible

**Comment by shinokada** [comment]
Please [fork this](https://stackblitz.com/edit/sveltejs-kit-template-default-efqgaq?file=README.md) and add your code.

**Comment by God-lives** [comment]
i got it

**Comment by God-lives** [comment]
https://stackblitz.com/edit/sveltejs-kit-template-default-bfygkw?file=src%2Froutes%2F%2Bpage.svelte,src%2Froutes%2F%2Blayout.svelte

i forked it. check it please~

**Comment by God-lives** [comment]
Additionally, even if the number of thumbnail images increases, their size should remain consistent, and I'd like to add previous and next buttons. As the number of images increases, the thumbnails start to look odd.

**Comment by shinokada** [comment]
I close the issue for now since we updated the carousel API.
Thank you for your contribution.
Please feel free to open a new issue.
