### ISSUE TITLE
Documentation on how to "style" a component by default.

### ISSUE THREAD

**Issue by rbozan** [themesberg/flowbite-svelte#861]
## Summary

Some basic documentation on how to style a `<Button>` component for example without wrapping it in another component.

Even adding a simple class by default like `.button` (allowing me to configure that) would help as it would distinguish that it is a `<Button>`.

### Basic example

A good example of a framework which allows this is : https://chakra-ui.com/docs/styled-system/customize-theme

### Motivation

I can not currently style a "button" using CSS as the Button component could be a `<button>` (in html) or a `<a>` without any indication whether it was the `<Button>` component.

**Comment by shinokada** [comment]
From v0.38, I started adding how to customize in the props section as you see in the example below.
Is that what you want?

![prop](https://github.com/themesberg/flowbite-svelte/assets/147320/93e39c2d-6641-4ffe-96bc-53683903070e)

**Comment by shinokada** [comment]
We don't have that yet. I can see the benefit of doing it that way. Hopefully, it will come in the future version.

**Comment by shinokada** [comment]
@rbozan You can take this approach.

1. Create your button component in the lib dir:

```
// src/lib/MyButton.svelte
<script>
  import { Button } from 'flowbite-svelte'
</script>

<Button color="green" pill class="p-8">

<slot />

</Button>
```

2. Use it in your project

```
<script>
  import MyButton from "$lib/MyButton.svelte"
</script>

<MyButton>My New Button</MyButton>
```

![image](https://github.com/themesberg/flowbite-svelte/assets/147320/3ba1afee-f29f-4a5a-a25b-3fcd3cf25dfd)


https://sveltejskittemplatedefaultefqg-kxp3--5173--77657b1e.local-corp.webcontainer.io/customization

**Comment by shinokada** [comment]
I close the issue for now.
Thank you for your contribution.
Please feel free to open a new issue.
