### ISSUE TITLE
Support "on:click" event in the "A" component

### ISSUE THREAD

**Issue by holinux** [themesberg/flowbite-svelte#862]
## Summary

The "A" component (https://flowbite-svelte.com/docs/typography/link) support "href" but does not support "on:click". 

### Basic example

<A  on:click={() =>show_modal()}>Open Modal</A>

### Motivation

Sometimes I need to use "A" to open a modal window, instead of linking to another URL.

**Comment by shinokada** [comment]
Sure. I will add it to the next version.
