### ISSUE TITLE
Multiselect adding the SelectOptionType object and not Value property to the bound:value array

### ISSUE THREAD

**Issue by wil-den** [themesberg/flowbite-svelte#864]
### Describe the bug

Maybe this is expected behaviour?
I give a list of items to the Multiselect component. 
The items in the list are of the shape { name: , value: }
I bind an array to hold the selected items.

What I expected to find in the selectedItems array was the value property from the items contained in the item list and not the complete object itself.

Obviously I can work around this myself but I wanted to know if this is what you expected?

### Reproduction

Not sure if this is a bug or not so I have not reproduced this

### Flowbite version and System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 3.86 GB / 15.73 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.51)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    flowbite-svelte: ^0.37.5 => 0.37.5
    svelte: ^3.55.1 => 3.58.0
    vite: ^4.2.0 => 4.2.1
```

**Comment by shinokada** [comment]
@vasucp1207 Can you reply to this?

**Comment by vasucp1207** [comment]
Thanks for clarifying fixes this in https://github.com/themesberg/flowbite-svelte/pull/870

**Comment by itaibaruch** [comment]
Hi, the fix did the job. 
But we missing the case that `value` property has a list defined, if so the component should pre-select them.

Here is a StackBlitz: https://stackblitz.com/edit/sveltejs-kit-template-default-l9zfbe?file=src%2Froutes%2F%2Bpage.svelte

**Comment by vasucp1207** [comment]
> Hi, the fix did the job. But we missing the case that `value` property has a list defined, if so the component should pre-select them.
> 
> Here is a StackBlitz: https://stackblitz.com/edit/sveltejs-kit-template-default-l9zfbe?file=src%2Froutes%2F%2Bpage.svelte

Fixed in https://github.com/themesberg/flowbite-svelte/pull/892
