### ISSUE TITLE
Numeric input type bindings not working (tested with Input and FloatingLabelInput)

### ISSUE THREAD

**Issue by joh-ku** [themesberg/flowbite-svelte#877]
### Describe the bug

With flowbites [Input](https://flowbite-svelte.com/docs/forms/input-field) or [Floating Label Input](https://flowbite-svelte.com/docs/forms/floating-label) Components, numeric [type bindings](https://svelte.dev/tutorial/numeric-inputs) do not work.

Does not work:
```
<script lang="ts">
	import { FloatingLabelInput, Input } from 'flowbite-svelte';
        let someVar = {propertyA:0, propertyB:0};
</script>

<FloatingLabelInput type="number" bind:value={someVar.propertyA} />
<Input type="number" bind:value={someVar.propertyB} />
```
When editing Input or FloatingLabelInput , `propertyA` or `propertyB` will afterwards be of type `string`.

Works:
```
<script lang="ts">
        let someVar = {propertyA:0, propertyB:0};
</script>

<input type="number" bind:value={someVar.propertyA} />
<input type="number" bind:value={someVar.propertyB} />
```

When editing input , `propertyA` or `propertyB` will afterwards be of type `number`.

### Reproduction

Open the below Stackblitz example and watch the console when changing input data:

https://stackblitz.com/edit/sveltejs-kit-template-default-5tujtj?file=src%2Froutes%2F%2Bpage.svelte

### Flowbite version and System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
    Memory: 4.23 GB / 15.78 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @sveltejs/kit: ^1.5.0 => 1.20.2
    flowbite-svelte: ^0.37.5 => 0.37.5
    svelte: ^3.54.0 => 3.59.1
    vite: ^4.3.0 => 4.3.9

Google Chrome 114.0.5735.134 (Official Build) (64-bit)
```

**Comment by jjagielka** [comment]
And have you tried [NumberInput](https://flowbite-svelte.com/docs/forms/input-field#Number_input)?

**Comment by joh-ku** [comment]
Using [Number input](https://flowbite-svelte.com/docs/forms/input-field#Number_input) works. But I still consider this an inconsistency in the API, as it is not compliant with standard HTML input types. Why would I expect a string binding when explicitly setting `type="number"` on my component? Also, especially [Floating labels](https://flowbite.com/docs/forms/floating-label/) provide some neat additional styling that goes well together with numeric input types.

**Comment by joh-ku** [comment]
Why do you need [use:setType={type}](https://github.com/themesberg/flowbite-svelte/blob/86ea2a967185daff48fefca675667260a5f12110/src/lib/forms/FloatingLabelInput.svelte#L108)? Couldn't we just use `{type}` instead?

**Comment by shinokada** [comment]
@jjagielka Do you have anything to reply?

**Comment by jjagielka** [comment]
@joh-ku - If you make just `{type}` then you can't bind the `value`.

```svelte
<input {type} bind:value ... />
```
```
'type' attribute cannot be dynamic if input uses two-way binding svelte(invalid-type)
(property) type?: HTMLInputTypeAttribute | null | undefined
```
