### ISSUE TITLE
[Feature] Sorting for tables

### ISSUE THREAD

**Issue by dennismphil** [themesberg/flowbite-svelte#88]
## Summary

A brief explanation of the feature.

It would be nice to implement a sortable table 

### Basic example

If the proposal involves a new or changed API, include a basic code example. Omit this section if it's not applicable.

```jsx
<Table sortable ...>
  <TableDefaultRow items={itemEx} html />
</Table>
```

**Comment by risalfajar** [comment]
Any updates?

**Comment by shinokada** [comment]
Please see [Sorting by column](https://flowbite-svelte.com/docs/components/table#Sorting_by_column).
I close the issue for now.
Thank you for your contribution.
