### ISSUE TITLE
Not respect the color setting for label if default input is disabled

### ISSUE THREAD

**Issue by elton2048** [themesberg/flowbite-svelte#884]
### Describe the bug

The label overrides the original color if the corresponding input element is disabled, that seems fine. However when toggle back the input element into normal state, the label does not revert back to original color setting. This causing strange behaviour as the original state of the input element decides the label color.

It should either keeping the original color or change the label color according to the state of input element, which I think the original intention is the latter one according to the code.

I can help with a PR if necessary.

Corresponding code:

https://github.com/themesberg/flowbite-svelte/blob/079ca8795814e7c3b482cfb27ddfec5fd23fc683/src/lib/forms/Label.svelte#L20

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-5as3bp?file=src%2Flib%2FMyButton.svelte

### Flowbite version and System Info

```shell
System:
    OS: macOS 13.4
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Memory: 1.85 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.7.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 9.5.0 - /usr/local/bin/npm
    Watchman: 2023.05.15.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 80.1.4.95
    Chrome: 114.0.5735.198
    Safari: 16.5
    Safari Technology Preview: 16.4
  npmPackages:
    flowbite-svelte: ^0.38.5 => 0.38.5
    svelte: ^3.55.1 => 3.58.0
    vite: ^4.1.0 => 4.2.1
```

**Comment by shinokada** [comment]
You can use class:

```
<Label for="default_disabled" class="text-green-700">Disabled</Label>
```

**Comment by elton2048** [comment]
> You can use class:
> 
> ```
> <Label for="default_disabled" class="text-green-700">Disabled</Label>
> ```

Yes it can be modified by using explicit class to set the color, but the point is it created different result with the same code logic in different flow, which makes developer confused

**Comment by shinokada** [comment]
This is what I can think of at the moment:

```
  import { Button, Input, Label } from 'flowbite-svelte'

  let normal = null
  let disabled = 'disabled'

  function changeState() {
    if (normal === null) {
      normal = 'disabled'
    } else {
      normal = null
    }

    if (disabled === null) {
      disabled = 'disabled'
    } else {
      disabled = null
    }
  }
</script>

<Label for="normal" style={!disabled ? 'color: gray;' : 'color: green;'}>Normal</Label>
<Input id="normal" name="normal" disabled={normal} />

<Label for="default_disabled" style={disabled ? 'color: gray;' : 'color: green;'}>Disabled</Label>
<Input id="default_disabled" name="default_disabled" {disabled} />

<Button color="green" class="my-2 p-3" on:click={changeState}>Change</Button>
```
