### ISSUE TITLE
Linkable images in Carousel? 

### ISSUE THREAD

**Issue by maietta** [themesberg/flowbite-svelte#899]
## Summary

I chose Flowbite-Svelte UI because I thought it had everything I needed for my project. Looks fantastic. It was only when I went and added a carousel that I realized there is no option to add links to for each image item in the array. I think that would be a great addition. I may investigate performing a PR with this as an optional element.

I really don't want to use yet another dependency in my project to add this functionality.

**Comment by shinokada** [comment]
Do you mean adding a link to images? If it is so, I can add the function.

**Comment by maietta** [comment]
> Do you mean adding a link to images? If it is so, I can add the function.

I thought I responded yesterday, but I didn't. Sorry for the late response.

The goal is to have an optional href or link value per image and then allow that imagine to become clickable so that it can take the user to the hyperlink target.
