### ISSUE TITLE
Fail in List group with buttons event.detail

### ISSUE THREAD

**Issue by javiersanp** [themesberg/flowbite-svelte#903]
### Describe the bug

In the List group with buttons example, on click on one item, an alert message with the properties of the clicked item is expected. Instead, the alert is void. The event.detail contains the value 1. It's expected to contain any of the buttons items array.

### Reproduction

URL: https://flowbite-svelte.com/docs/components/list-group#List_group_with_buttons
Click on Profile, Settings or Message.

### Flowbite version and System Info

```shell
v0.39.2

  System:
    OS: Linux 5.4 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
    Memory: 7.27 GB / 15.57 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    npm: 8.12.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Chromium: 114.0.5735.198
```

**Comment by mdhruvil** [comment]
@javiersanp  I think it is fixed now. Please check it.

**Comment by shinokada** [comment]
I close the issue for now.
Please feel free to open a new issue.
Thank you for your contribution.
