### ISSUE TITLE
Full Astro support (or documentation)

### ISSUE THREAD

**Issue by silveltman** [themesberg/flowbite-svelte#914]
## Summary

Full support, including typescript, in Astro. Not when importing in Svelte components in the Astro projects, but also when directly importing in a .astro file.

If this already has full support, then please add it to the docs. 

### Motivation

More people can use it, which is a great thing!

I'm wondering if all the manual export statements in the package.json do contribute to this feature. Or is there another reason those lines are added to the package.json?

**Comment by shinokada** [comment]
Check [this discord](https://discord.com/channels/902911619032576090/1062320251615854633), please.
