### ISSUE TITLE
[Feature] [Table] Support classes for `th` in the table header and rows

### ISSUE THREAD

**Issue by dennismphil** [themesberg/flowbite-svelte#92]
## Summary

Can we please make the padding also adjustable for the table header and the rows. Right now they are hardcoded in [Table](https://github.com/themesberg/flowbite-svelte/blob/main/src/lib/tables/Table.svelte#L13) and the [DefaultRow](https://github.com/themesberg/flowbite-svelte/blob/main/src/lib/tables/TableDefaultRow.svelte#L24) to

```tsx
// Table
<th scope="col" class="px-6 py-3">
...
```

### Basic example

```tsx
 <Table thClass={thClass} ...>
   ...
 </Table>
```

**Comment by shinokada** [comment]
Please update to the v0.17.5

```sh
npm i -D flowbite-svelte@latest
```

And let me know.

Please note that I will update all table components soon and the structure will be different.

**Comment by dennismphil** [comment]
Blocked with this #93 bug. Will test as soon as I find a resolution

**Comment by dennismphil** [comment]
Tested and this works great in Table class..

However, can we also fix this in the [TableDefaultRow](https://github.com/themesberg/flowbite-svelte/blob/main/src/lib/tables/TableDefaultRow.svelte#L24)

**Comment by shinokada** [comment]
@dennismphil I'm updating whole Table components. Could you wait a day or so please?

**Comment by dennismphil** [comment]
Sure. Thank you

**Comment by shinokada** [comment]
I just updated to v0.18.0. It has new structure and flexible.
Please update/test and let me know.

**Comment by shinokada** [comment]
Closing the issue for now.
Please feel free to create issues when you find more.
Thank you for your contribution.
