### ISSUE TITLE
Excessive CSS size - 120KB CSS without any components?

### ISSUE THREAD

**Issue by khromov** [themesberg/flowbite-svelte#922]
### Describe the bug

I'm starting a new flowbite-svelte project. I have a root layout with this content:

```html
<script>
	import '../app.postcss';
	import DarkMode from 'flowbite-svelte/DarkMode.svelte';
	let darkmodebtn =
		'text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-lg p-2.5 fixed right-4 top-2 z-50';
</script>

<DarkMode btnClass={darkmodebtn} />

<slot />
```

When I build the project, the generated CSS file is 120KB in size. Even removing the `DarkMode` component still produces a 120KB bundle. It does seem like some sort of purging is not working properly, as the file size comes from the `app.postcss` import. I have Tailwind projects where the CSS for the entire project is 5-10KB, which includes all used styles.

From `npm run build`:

```
.svelte-kit/output/client/_app/immutable/assets/0.a71a8c67.css          119.17 kB │ gzip: 16.49 kB
```

I thought loading the components directly instead of from the global import would work, but it does not change anything.

### Reproduction

Follow the quickstart:
https://flowbite-svelte.com/docs/pages/quickstart

Paste the code from my message in `src/routes/+layout.svelte`

### Flowbite version and System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 43.09 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.5.0 - ~/.nvm/versions/node/v19.5.0/bin/node
    npm: 9.3.1 - ~/.nvm/versions/node/v19.5.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Firefox: 115.0.1
    Safari: 16.5.1
    Safari Technology Preview: 17.0
  npmPackages:
    @sveltejs/kit: ^1.20.4 => 1.22.1 
    flowbite-svelte: ^0.39.2 => 0.39.2 
    svelte: ^4.0.0 => 4.0.5 
    vite: ^4.3.6 => 4.4.2 
```
```

**Comment by shinokada** [comment]
If you want to reduce the compiled CSS, then you need to modify the `tailwind.config.cjs`:

```
const config = {
  content: [
    "./src/**/*.{html,js,svelte,ts}",
    // "./node_modules/flowbite-svelte/**/*.{html,js,svelte,ts}",
    // add components you are using here
  ],

  plugins: [
    require('flowbite/plugin')
  ],

  darkMode: 'class',
  
  theme: {
    extend: {
      colors: {
        // flowbite-svelte
        primary: { 50: '#FFF5F2', 100: '#FFF1EE', 200: '#FFE4DE', 300: '#FFD5CC', 400: '#FFBCAD', 500: '#FE795D', 600: '#EF562F', 700: '#EB4F27', 800: '#CC4522', 900: '#A5371B'},
      }
    }
  }
};

module.exports = config;
```

This will create the compiled CSS to 12-13k.

**Comment by khromov** [comment]
Thank you! Hope that there will be a way to purge unused styles in the future! 🌞

**Comment by jsonMartin** [comment]
I also just noticed the large default Bundle size for Flowbite Svelte after deploying my app to Production. 

So, I went into the `tailwind.config.cjs` file and added only specfic imports as recommended by @shinokada. However, I'm not sure the best way to do this. 

Would this be the recommended way to include multiple components?
```
content: [
    "./src/**/*.{html,js,svelte,ts}",

    // Only include flowbite-svelte components being used?
    "./node_modules/flowbite-svelte/**/{buttons,badges,footer,forms,modals,carousels,typography}/*.{html,js,svelte,ts}",
  ],
```
Doing this reduced the CSS bundle size of my application from **167.23 kB (21.3kB gzip) -> 117.43kB (15.6kB gzip)**. 

However, the code above still imports all components inside the directory. For example, I'm only using a couple of form elements so I don't need all of them. I'm assuming I could also further improve this by only importing specific components within these folders, such as:
```
"./src/**/*.{html,js,svelte,ts}",
"./node_modules/flowbite-svelte/**/forms/{Input,Label,Select}*.{html,js,svelte,ts}",
"./node_modules/flowbite-svelte/**/device-mockup/{DeviceMockup,Tablet,Ios}*.{html,js,svelte,ts}",
...
```
But this starts to get unwieldy and likely would prove more cumbersome to manage vs the bundle gains. 

Are there any plans to automatically purge unused styles from Flowbite Svelte?

**Comment by shinokada** [comment]
This could be one of tasks for the future CLI.

**Comment by shinokada** [comment]
Please try [this](https://flowbite-svelte.com/docs/pages/faq-and-tips#My_compiled_CSS_size_is_more_than_120K._How_can_I_make_it_smaller?) and let me know.
I close the issue for now.
Please feel free to open a new issue.
Thank you for your contribution.
