### ISSUE TITLE
doc page is broken

### ISSUE THREAD

**Issue by alebo611** [themesberg/flowbite-svelte#925]
### Describe the bug

Not an issue with the actual software, but the doc page about <Img> seems to be broken:
https://flowbite-svelte.com/docs/typography/image

### Reproduction

go to https://flowbite-svelte.com/docs/typography/image

### Flowbite version and System Info

```shell
N/A
```

**Comment by jjagielka** [comment]
@shinokada - seems like `srcset` is not supported by all browsers. That makes a page crash.

**Comment by jjagielka** [comment]
Can be closed.
