### ISSUE TITLE
[Bug][Tooltip][0.17.4 onwards] Failed to resolve import "$app/env"

### ISSUE THREAD

**Issue by dennismphil** [themesberg/flowbite-svelte#93]
**Describe the bug**  
Updated the version to `v0.17.5` and started seeing an error. Investigating this issue and will update as I find a resolution.

I see some changes was done to the Tooltip.svelte [quite recently](https://github.com/themesberg/flowbite-svelte/commit/d0cc06e991e5677463a5625b4abaee2a6edef3fc). 

![2022-06-16_04-34-09](https://user-images.githubusercontent.com/4141366/174061463-254e2673-8745-4cc0-ae5e-64229c2cb6c1.png)

**Comment by shinokada** [comment]
I assume you are using Sveltejs.
The `browser` is for SvelteKit.
I will update it soon.
Thank you for the issue.

**Comment by shinokada** [comment]
Please update to v0.17.6 and let me know.

**Comment by dennismphil** [comment]
Tested and this works flawlessly now. Thank you for the quick fix. Closing
