### ISSUE TITLE
Reactive class for Accordion component

### ISSUE THREAD

**Issue by elton2048** [themesberg/flowbite-svelte#931]
### Describe the bug

The class attribute for `Accordion` component is not reactive, i.e. changing the class variable in `script` part does not aligned the same value in corresponding component

I suspect other components get the same issue but I haven't check those.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-skz5cw?file=src%2Froutes%2F%2Bpage.svelte

Check the class in website inspector to see the result. Or check the video below

https://github.com/themesberg/flowbite-svelte/assets/11803493/949c6fa2-b812-4cb8-aba0-6afbc61ad2cc

### Flowbite version and System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Memory: 33.29 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.7.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 9.5.0 - /usr/local/bin/npm
    Watchman: 2023.05.15.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 80.1.4.95
    Chrome: 114.0.5735.198
    Safari: 16.5.1
    Safari Technology Preview: 16.4
  npmPackages:
    svelte: ^3.55.1 => 3.58.0
    vite: ^4.1.0 => 4.2.1
```

**Comment by jjagielka** [comment]
Yes. It's a bug in `Accordion`. There's:
```svelte
let frameClass = twMerge(defaultClass, $$props.class);
```
and should be:
```svelte
  let frameClass: string;
  $: frameClass = twMerge(defaultClass, $$props.class);
```
