### ISSUE TITLE
Upgrading flow-bite svelte to 40.1 breaks tooltips

### ISSUE THREAD

**Issue by TristanBrotherton** [themesberg/flowbite-svelte#935]
### Describe the bug

After upgrading flowbite svelte from 0.38.5 to 0.40.1 the tooltip components break and no longer get any positioning. 

### Reproduction

n/a

### Flowbite version and System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 648.69 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.1
  npmPackages:
    @sveltejs/kit: ^1.20.4 => 1.22.3 
    flowbite-svelte: ^0.38.5 => 0.38.5 
    svelte: ^4.0.0 => 4.0.5 
    vite: ^4.2.1 => 4.4.4
```

**Comment by shinokada** [comment]
You need to install `@floating-ui/dom`.

**Comment by TristanBrotherton** [comment]
I did install @floating-ui/dom as part of the upgrade process.

**Comment by shinokada** [comment]
You have ` flowbite-svelte: ^0.38.5 => 0.38.5 `.

Run `pnpm i -D flowbite-svelte@latest`.

**Comment by xTVaser** [comment]
I'm seeing similar problems and I've confirmed `@floating-ui/dom` is installed (it's a transitive of the latest version)
```
  System:
    OS: Windows 10 10.0.22621
    CPU: (32) x64 AMD Ryzen 9 7950X 16-Core Processor
    Memory: 6.40 GB / 31.15 GB
  Binaries:
    Node: 18.17.0 - ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
    Yarn: 1.22.19 - ~\scoop\apps\yarn\current\bin\yarn.CMD
    npm: 9.6.7 - ~\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1992.0), Chromium (115.0.1901.183)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    flowbite-svelte: ^0.40.2 => 0.40.2
    svelte: ^4.1.1 => 4.1.1
    vite: ^4.4.7 => 4.4.7
```

On version 0.40.2:
![image](https://github.com/themesberg/flowbite-svelte/assets/13153231/036c64e2-21d2-444c-9451-921682284755)
> rogue diamond shaped element with the same color as the tooltip, for some items it makes them grow in size (seen here)

On version 0.39.3:
![image](https://github.com/themesberg/flowbite-svelte/assets/13153231/171eb082-8b06-4dcf-a477-7ec13d0e26f6)

**Comment by jjagielka** [comment]
Can you please extract the code from your app to make a isolated example of that bug?

Please provide the class / style settings of the parent element.

**Comment by erskingardner** [comment]
I'm also seeing this. Adding @floating-ui/dom doesn't help.

**Comment by erskingardner** [comment]
https://svelte.dev/repl/8d9d45ee20c64bbcb56ec6a44ff1a344?version=4.1.1

**Comment by jjagielka** [comment]
To make it styled you need to include tailwind css. In REPL this can be made by adding:
```svelte
<svelte:head>
	<script src="https://cdn.tailwindcss.com"></script>
</svelte:head>
```

As for the bug - there's an error in documentation to use `style={light|dark}` however it should be `type={light|dark}`. 
The code example in the docs shows correctly that usage of `type`

**Comment by erskingardner** [comment]
Confirmed that changing the `style` prop to `type` fixes the issue for me and works with the latest version of flowbite-svelte

**Comment by xTVaser** [comment]
Can also confirm that switching from `style` to `type` fixes my issue on the latest version.
