### ISSUE TITLE
Can not listen to `on:click` on `Listgroup` to get the actual clicked item

### ISSUE THREAD

**Issue by fkrauthan** [themesberg/flowbite-svelte#937]
### Describe the bug

When using a `Listgroup` and listening to the `on:click` event the `detail` section of that event always contains the number `1` instead of the clicked item.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-tymbzp?file=src%2Froutes%2F%2Bpage.svelte

### Flowbite version and System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 18.34 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    pnpm: 8.6.8 - /opt/homebrew/bin/pnpm
  Browsers:
    Brave Browser: 114.1.52.130
    Chrome: 114.0.5735.198
    Edge: 113.0.1774.57
    Safari: 16.3
  npmPackages:
    @sveltejs/kit: ^1.20.4 => 1.22.3
    flowbite-svelte: ^0.40.1 => 0.40.1
    svelte: ^4.0.5 => 4.0.5
    vite: ^4.4.2 => 4.4.4
```

**Comment by fkrauthan** [comment]
For this to fix we have two options:

1. Change `on:click` to a custom event that populates as `detail` the passed in `item` (works as the documentation says it should but would be a breaking change in terms of how it currently works)
2. Add `on:select` with a custom event and keep `on:click` as is (slightly awkwards API but no breaking change)

I personally prefer `1`.

**Comment by jjagielka** [comment]
`on:click` event sends the `MouseEvent` object as a parameter.
And according the web standards - [Click event](https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event) on MDN:
> The [MouseEvent](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent) object passed into the event handler for click has its [detail](https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/detail) property set to the number of times the [target](https://developer.mozilla.org/en-US/docs/Web/API/Event/target) was clicked. In other words, detail will be 2 for a double-click, 3 for triple-click, and so forth.

**Comment by fkrauthan** [comment]
Yeah that makes sense. However the flowbite-svelte docs: https://flowbite-svelte.com/docs/components/list-group#List_group_with_buttons say that `detail` suppose to include the `item` (as shown in the non working example). And their seem to be no other way to retrieve the actual clicked item. As you can't even create your own `ListgroupItem` under `ListGroup` as that creates a nested `ListgroupItem` within a second `ListgroupItem`.

**Comment by jjagielka** [comment]
OK. I get your point. I'll change it.
