### ISSUE TITLE
The sizing (especially between `Button` and `Input`s) is off in some cases

### ISSUE THREAD

**Issue by fkrauthan** [themesberg/flowbite-svelte#940]
### Describe the bug

In some cases the height of `Input` and `Button` even when using the same size is off.

E.g. to get a `Button` the same size as a `Search` the `Search` needs to be `size=md` and the `Button` needs to be `size=sm` so they have the same size.

My sample shows a couple of combos where the height is not the same which can cause to some bad UX.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-kprzxd?file=src%2Froutes%2F%2Bpage.svelte

### Flowbite version and System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 18.34 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    pnpm: 8.6.8 - /opt/homebrew/bin/pnpm
  Browsers:
    Brave Browser: 114.1.52.130
    Chrome: 114.0.5735.198
    Edge: 113.0.1774.57
    Safari: 16.3
  npmPackages:
    @sveltejs/kit: ^1.20.4 => 1.22.3
    flowbite-svelte: ^0.40.1 => 0.40.1
    svelte: ^4.0.5 => 4.0.5
    vite: ^4.4.2 => 4.4.4
```

**Comment by shinokada** [comment]
Thank you for the issue.
I think it is related to padding, text size etc and it is difficult to control all the sizes.
Ideally it should be the same size as you mentioned. 
I hope we can solve this issue for all the components in future.

Please feel free to create PR to fix this problem.
I close the issue for now.
Thank you for your contribution.
