### ISSUE TITLE
Clicking chevron on MultiSelect submits form

### ISSUE THREAD

**Issue by JayXTQ** [themesberg/flowbite-svelte#952]
### Describe the bug

Clicking on the chevron on the MultiSelect submits the form, you need to click the chevron in able to add stuff to the multi select.

### Reproduction

Just make a form with a multiselect with some dummy items to work with. Try add an item and see if the issue reproduces.

Here is a dummy I made and it reproduces the error:

`<script lang="ts">
    import { MultiSelect } from "flowbite-svelte";
    let selected: any[] = [];
    let countries = [
        {value:"us", name: "United States"},
        {value:"ca", name: "Canada"},
        {value:"fr", name: "France"},
    ]
</script>

<form method="POST">
    <MultiSelect items={countries} bind:value={selected} />
</form>`

### Flowbite version and System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M2
    Memory: 34.92 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    npm: 9.5.1 - /usr/local/bin/npm
    pnpm: 8.6.3 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 110.0.5481.177
    Safari: 16.5.2
  npmPackages:
    @sveltejs/kit: ^1.22.1 => 1.22.1 
    flowbite-svelte: ^0.40.2 => 0.40.2 
    svelte: ^4.0.5 => 4.0.5 
    vite: ^4.3.0 => 4.3.9
```

**Comment by jessielaf** [comment]
@shinokada I am still experiencing this on 0.44
