### ISSUE TITLE
NavLi acrive status in group route

### ISSUE THREAD

**Issue by Tihomir971** [themesberg/flowbite-svelte#957]
### Describe the bug

<NavLi href="/" active={$page.url.pathname === '/'} rel="external">Home</NavLi>
active status doesn't work when in group route

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-xjoa3r

### Flowbite version and System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.3 - /usr/local/bin/pnpm
  npmPackages:
    @sveltejs/kit: ^1.22.0 => 1.22.0 
    flowbite-svelte: ^0.38.5 => 0.38.5 
    svelte: ^4.0.4 => 4.0.4 
    vite: ^4.3.9 => 4.3.9
```

**Comment by shinokada** [comment]
I think the new version solved this issue.
I will close this and thank you for your contribution.
