### ISSUE TITLE
Wrapping the Button class inside a component will make autoclose stop working

### ISSUE THREAD

**Issue by alebo611** [themesberg/flowbite-svelte#962]
### Describe the bug

If I have a Modal, and a component inside that modal that in turn contains a button, then autoclose will not work anymore.
 It only works for buttons directly in the modal.

### Reproduction

`<Modal autoclose>
<ButtonWrapper></ButtonWrapper>
</Modal>`

ButtonWrapper.svelte:
`<Button>Will not autoclose</Button>`

### Flowbite version and System Info

```shell
"flowbite": "^1.6.5",
    "flowbite-svelte": "^0.37.4",
```

**Comment by jjagielka** [comment]
I can't confirm that behaviour. Please check that [REPL example](https://svelte.dev/repl/46f560793cdb401aaa148025316258e2?version=4.1.2).

This shows the correct ring behaviour as well (see #961)

Did I misunderstand your issues?

**Comment by alebo611** [comment]
Thanks, I try the latest version then.
