### ISSUE TITLE
aria labels should be props

### ISSUE THREAD

**Issue by Ennoriel** [themesberg/flowbite-svelte#964]
## Summary

The `nav` `Pagination ` component has a default `aria-label` value to `Page navigation`. This needs to be updatable in some way.

This also applies to (at least):
- [Anchor.svelte](https://github.com/themesberg/flowbite-svelte/blob/7dff5630dfd482a828c45611f129c432b94908de/src/routes/layouts/component/Anchor.svelte#L32)
- [DarkMode.svelte](https://github.com/themesberg/flowbite-svelte/blob/7dff5630dfd482a828c45611f129c432b94908de/src/lib/darkmode/DarkMode.svelte#L37)

### Basic example

```
<script>
  export let navAriaLabel = "Page navigation";
</script>

<nav aria-label={navAriaLabel}>
```

### Motivation

This is necessary when we use another language than English or when the component is used in another way (not a page navigation for instance)

**Comment by shinokada** [comment]
Thank you for the issue. I will add fixes in the next version.

**Comment by shinokada** [comment]
I close the issue for now.
Please feel free to open a new issue.
Thank you for your contribution.
