### ISSUE TITLE
Separate triggeredBy and reference for Popover component

### ISSUE THREAD

**Issue by Chimildic** [themesberg/flowbite-svelte#966]
### Describe the bug

I use `popover` component and need to separate `triggeredBy` and `reference` elements. I mean that `popover` display on other element than trigger element. For example, button click fire popover above text field.

In previous version of component with `popperjs/core`, we can override `options` attribute for the purpose.
```html
<script lang="ts">
  import { Popover } from 'flowbite-svelte'
  let options = document.querySelector('#text-field')
</script>

<Popover options={options} triggeredBy="#button" trigger="click">...</Popover>
```

New version of component with `floating-ui/dom` have bugs.

1. In `dom.autoUpdate()` mixed up arguments. 
```js
// now
dom.autoUpdate(node, _triggerEl, updatePosition)
// must be
dom.autoUpdate(_triggerEl, node, updatePosition)
```

Because first is `reference`, second is `floating` according [docs](https://floating-ui.com/docs/autoupdate).

2. When `floating-ui/dom` fire `updatePosition()`, you use `computePosition` with `reference = triggerEl`. But for my purpose reference must be equal to element from `options`.
```js
// now
dom.computePosition(triggerEl, floatingEl, {...})

// must be
let referenceEl;

function init(node, _triggerEl) {
    floatingEl = node;
    referenceEl= _triggerEl;
    let cleanup = dom.autoUpdate(referenceEl, node, updatePosition);
    return {
        update(_triggerEl) {
            cleanup();
            cleanup = dom.autoUpdate(referenceEl, node, updatePosition);
        },
        destroy() {
            cleanup();
        }
    };
}

function updatePosition() {
    dom.computePosition(referenceEl, floatingEl, {...})
   //   ...
}
```

### Reproduction

above

### Flowbite version and System Info

```shell
Browsers:
  Edge: Spartan (44.22000.120.0), Chromium (115.0.1901.188)
npmPackages:
  flowbite-svelte: ^0.40.2
  svelte: ^3.44.0 => 3.59.2
  vite: ^2.9.13 => 2.9.16
```

**Comment by jjagielka** [comment]
1. In dom.autoUpdate() mixed up arguments.
Good catch. Evident mismatch. I have changed the variable name `triggerEl` to `referenceEl` so it is easier to catch such typos.

2. Added `reference` prop.
Slightly different implementation that you've proposed but should match what you're asking for.
Please check `External reference` examples in both `Tooltip` and `Popover` and tell me if that's what you've wanted.

**Comment by Chimildic** [comment]
No, I don't see any examples that separate `reference` from `triggeredBy`. In case `floating-ui/dom`,  only methods like `autoUpdate`, `computePosition` contain argument `reference` in order to relative calculate anchor position. 

`flowbite` and `flowbite-svelte` assume that popover need to appper only around `triggeredBy`. I saw hack with `options` attribute in source code. But when install last version, hack broke down (my description above).
```
  <Frame
    use={init}
    options={triggerEl}
    ...
  </Frame>
```

**Comment by jjagielka** [comment]
Try now: https://flowbite-svelte.com/docs/components/tooltip#External_reference

**Comment by shinokada** [comment]
![image](https://github.com/themesberg/flowbite-svelte/assets/147320/666109d2-c750-4673-9dba-d7205a6b1d00)

This needs `dark: text-whte`.

**Comment by jjagielka** [comment]
Nope. In fact it needs `dark:border-gray-600`.
