### ISSUE TITLE
Navbar navDivClass does not override container class

### ISSUE THREAD

**Issue by LessiKai** [themesberg/flowbite-svelte#970]
### Describe the bug

When providing the navDivClass property on a Navbar to override existing style classes, the container class is not removed. 

### Reproduction

```<Navbar navDivClass=""></Navbar>```
Resulting class list for nav -> div: "container".

### Flowbite version and System Info

```shell
System:
    OS: macOS 13.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.05 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.11.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 115.0.5790.170
    Safari: 16.2
  npmPackages:
    @sveltejs/kit: ^1.20.4 => 1.22.4 
    flowbite-svelte: ^0.41.2 => 0.41.2 
    svelte: ^4.0.5 => 4.1.2 
    vite: ^4.4.2 => 4.4.8
```

**Comment by jjagielka** [comment]
You can switch off the ‘container’ class by setting  the ‘fluid’ prop.

**Comment by LessiKai** [comment]
> 

Thank you very much. This deserves a better documentation i guess.

**Comment by shinokada** [comment]
I close the issue for now.
Thank you for your contribution.
