### ISSUE TITLE
Bug: Mousing over social tooltip icons on Flowbite Svelte homepage scrolls the page down

### ISSUE THREAD

**Issue by jsonMartin** [themesberg/flowbite-svelte#972]
### Describe the bug

On the **homepage**, when scroll position is not at the top of the page, mousing over tooltip social icons in the header scrolls the page down:

https://github.com/themesberg/flowbite-svelte/assets/4033621/8093e510-3c92-4648-9e62-0c5bbf71f95c

This does not appear to be happening on other component pages, I have just observed it on the homepage so far.

### Reproduction

Happening live on main site at: [https://flowbite-svelte.com/](https://flowbite-svelte.com/)

### Flowbite version and System Info

```shell
Latest main branch
```

**Comment by shinokada** [comment]
I think this issue is solved in the current website.
Thank you for your contribution.
I close the issue for now.
Please feel free to open a new issue.
