### ISSUE TITLE
Expose type definitions for components

### ISSUE THREAD

**Issue by mcmxcdev** [themesberg/flowbite-svelte#973]
## Summary

We want to be able to abstract e.g. `Button` component so that we can provide default props to it and customize it further like this:

```svelte
<script lang="ts">
  import { Button } from 'flowbite-svelte' // No ButtonProps import??
  import type { SizeType } from 'flowbite-svelte/dist/types'

  export let size: SizeType = 'lg'
</script>

<Button {size}>
  <slot />
</Button>
```

I have been working with https://mantine.dev/ recently and it exports props for each and every component for easy use as developer:
https://mantine.dev/guides/typescript/#components-props-types

I was able to find `SizeType` and imported it in the example above, but we would need way more type definitions for e.g. `color`, `href` and many more and it would make more sense to have one import for all `Button` props.

Am I looking in the wrong place or are they simply not exposed? It's probably a deal breaker for us if there are no type definitions.

**Comment by carlocorradini** [comment]
Same here.
Exporting TS types is super useful:
```ts
import type { SizeType } from "flowbite-svelte/types"
```

**Comment by shinokada** [comment]
v0.44.0 should solve this issue.

**Comment by PudottaPommin** [comment]
You can do with this approach for now

```svelte
<script lang="ts">
  import { Button } from 'flowbite-svelte' // No ButtonProps import??

  export let size: Button['$$prop_def']['size']= 'lg'
</script>

<Button {size}>
  <slot />
</Button>
```

**Comment by shinokada** [comment]
For now, this should work:

- add export * from './types.js' to the node_modules/flowbite-svelte/dist/dist/index.d.ts file 
- add export * from './types.d.ts' to the node_modules/flowbite-svelte/dist/dist/index.js file

I tried to add it while packaging, but it was removed in the package.
I will figure it out.

**Comment by shinokada** [comment]
Can you test v0.44.12 and let me know.

```
<script lang="ts">
  import type {SizeType} from 'flowbite-svelte'
  import { Button } from 'flowbite-svelte';

  export let size: SizeType = 'lg'
</script>

<Button>Default</Button>
<Button color="alternative">Alternative</Button>
<Button color="dark">Dark</Button>
<Button {size}>
  <slot />
</Button>
```

**Comment by shinokada** [comment]
I close the issue for now.
Thank you for your contribution.
Please feel free to open a new issue.
