### ISSUE TITLE
AccordianItem header slot not updating when open or after closing

### ISSUE THREAD

**Issue by wil-den** [themesberg/flowbite-svelte#974]
### Describe the bug

Forgive me but this maybe due to my lack of experience or knowledge here.

I have an AccordianItem in which i pass a string value to the header slot.
This string value is based upon an underlying array's length.
The string value is a reactive declaration.
When the Accordian is closed the value of the string in the header slot updates when the array length changes. 

However when I open the Accordian and remove items from the array, the header value does not change. When I close the Accordian the header value does not change or update. If i navigate away to another page and then back, the header value is now correct.

What am I missing here?

### Reproduction

Because I am unsure if this is a me issue or a flowbite issue I have not tried to replicate it.

### Flowbite version and System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 5.32 GB / 15.73 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.188)
    Internet Explorer: 11.0.19041.1566
```

**Comment by shinokada** [comment]
I close the issue for now since we do not have enough information.
Thank you for your contribution.
Please feel free to open a new issue when you are clear about the problem.
