### ISSUE TITLE
[Feature request] Forward `close` events for closeable components

### ISSUE THREAD

**Issue by selfagency** [themesberg/flowbite-svelte#975]
## Summary

It is essential to have a way to trigger functions when closeable components are closed. This includes:

- Banner
- Modal
- Toast

Please add event forwarders to their close buttons that forward to the parents.

### Basic example

```svelte
<script>
  let error;
  $: error = undefined;

  function setError(message) {
    error = message;
  }

  function clearError() {
    error = undefined;
  }
</script>

{#if error}
  <Toast position="none" color="red" transition={fly} params={{ x: 200 }} class="my-6" on:close={clearError}>
    <Icon name="exclamation-circle-outline" slot="icon" color="red" />
    {error}
  </Toast>
{/if}
```

### Motivation

There is presently no way to trigger functions when a closeable object is closed.

**Comment by shinokada** [comment]
Banner component has the `on:click` event forwarding already: 
https://github.com/themesberg/flowbite-svelte/blob/main/src/lib/banner/Banner.svelte#L44

**Comment by selfagency** [comment]
@jjagielka @shinokada would probably be good to make the events consistently named. like, if you close the banner, it should also dispatch `on:hide` too.
