### ISSUE TITLE
Change page on click with Bottom Navbar

### ISSUE THREAD

**Issue by gschurck** [themesberg/flowbite-svelte#986]
## Summary

How can I make the BottomNavItem from Bottom Navigation Bar easily clickable with a link ?
The classic navigation bar uses `href` attributes, but as bottom navbar uses buttons we can not use `href`/`<a>` with it, and using `on:click={() => goto('/')}` doesn't work either on the component directly...
What's the best way to accomplish this ? 
Thanks 

### Motivation

The goal would be to have an ouf-of-the-box working bottom navbar to change page on click, like for the classic navbar.

**Comment by shinokada** [comment]
You can use `a` tag in the slot:

```
  <BottomNavItem btnName="Home">
    <a href="/">
    <svg class="w-6 h-6 mb-1 text-gray-500 dark:text-gray-400 group-hover:text-primary-600 dark:group-hover:text-primary-500" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
      <path d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z"></path>
    </svg>
    </a>
  </BottomNavItem>
  ```

**Comment by gschurck** [comment]
That's what I did first as a workaround, but it's not ideal as it only adds the link on the icon and not the whole button.
So if we click anywhere else on the button it just doesn't work.

**Comment by shinokada** [comment]
@gschurck The next version will be like this, https://flowbite-svelte-gytntqwjt-themesberg.vercel.app/docs/components/bottom-navigation#Adding_links_and_active_class.

**Comment by shinokada** [comment]
@gschurck Can you update to the latest and let me know.

**Comment by gschurck** [comment]
It works like a charm, thanks.
