### ISSUE TITLE
Make button styles reactive

### ISSUE THREAD

**Issue by frailbongat** [themesberg/flowbite-svelte#99]
## Summary

We want to make button styling reactive.

### Basic example

if I change the button from normal to disabled then the styling should also be updated.

### Motivation

This will improve the button component and make it much easier to use.

**Comment by frailbongat** [comment]
Hi again @shinokada, what do you think of this?

If you agree, you can assign this to me so I can submit a PR. Cheers 🍻

**Comment by shinokada** [comment]
@frailbongat Does the Flowbite have it?

@zoltanszogyenyi What do you think?

**Comment by frailbongat** [comment]
@shinokada this is not a flowbite specific but a svelte specific enhancement.

Here's a scenario:

I have an input field and a button coming from here(flowbite-svelte)

I want to make the button disabled when the field is empty and enabled the button when the field has a value

When field is empty:
Button style should be disable styling
Button is unclickable

When field has value:
Button style should be default styling
Button is clickable

These are all right in the first load but, typing on the fields doesn't update button styling

**Comment by frailbongat** [comment]
I can send a gif later when I get home, if it's not clear yet. Thanks @shinokada 🙏

**Comment by shinokada** [comment]
Yes, I understand it. 
Thank you for your explanation.

1. May be you can check if all fields are empty in the onSubmit function?

```html
<script>
const onSubmit =()=>{
  // check here if all fields are empty
}
</script>

<form on:submit|preventDefault={onSubmit}>
<Input class="mb-6" placeholder="First name" label="First name" bind:ref/>
<Input class="mb-6" placeholder="Last name" label="Last name"/>

<Button type="submit" >Submit</Button>
</form>
```

2. I think it should be the role for validation not for UI.

What do you think?

**Comment by frailbongat** [comment]
Yes, that is also an option.

### Point 1 

Reactivity could even work via conditions in svelte e.g.
```svelte
{#if disabled}
  <Button disabled>Submit</Button>
{:else}
  <Button>Submit</Button>
{/if}
```

I just think by default button styles should be reactive (check gif below)

### Point 2

I think button styles are reactive by default if you applied it via svelte like so,
```svelte
{#if disabled}
  <button disabled class="[classes for disabled goes here]">Submit</button>
{:else}
  <button class="[classes for active/enabled goes here]">Submit</button>
{/if}
```

In your case, you apply it like this
```svelte
<script>
  let styles

  if (disabled) styles = '[classes for disabled goes here]'
  else styles = 'classes for active/enabled goes here]'
</script>

<button disabled class="{styles}">Submit</button>
```

The current solution is a better setup I believe, it just need a little adjustment to make it reactive, e.g.
```svelte
<script>
  let styles

  $: if (disabled) styles = '[classes for disabled goes here]'
  else styles = 'classes for active/enabled goes here]'
</script>

<button disabled class="{styles}">Submit</button>
```

### Additional Information
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/45723778/174473695-b07fa01c-0b1b-4e00-9b7b-6969a975613c.gif)

**Comment by shinokada** [comment]
Thanks.
You can go ahead and add an example in the doc page.
But there may be a chance that I/we may not accept the PR, if it is ok for you.
