### ISSUE TITLE
Huge JavaScript and css bundle sizes.

### ISSUE THREAD

**Issue by guratr** [themesberg/flowbite-svelte#990]
### Describe the bug

I installed library according [guide from ](https://flowbite-svelte.com/docs/pages/quickstart) on an empty project, then added NavBar, Modal, ListGroup and Timeline components from first examples from documentation.
After running `npm run build` my bundle sizes are extremely big.
![image](https://github.com/themesberg/flowbite-svelte/assets/1502853/d1769494-72fb-435b-b568-2d79f09fc7f3)

I removed library and added the same components directly from Flowbite(again using same examples from docs), and here's the results.
![image](https://github.com/themesberg/flowbite-svelte/assets/1502853/05cfb4b7-a096-4351-bec4-17f0b1dcdd3d)

I have seen this [discussion](https://github.com/themesberg/flowbite-svelte/issues/922) about ways to reduce css size, although i don't think that approach could scale.
But i could't find the same for javascript size, which is way more important for performance.

My tailwind.config.cjs with Flowbite-Svetle
```
const config = {
    content: [
        './src/**/*.{html,js,svelte,ts}',
        './node_modules/flowbite-svelte/**/*.{html,js,svelte,ts}'],
    theme: {
        extend: {}
    },
    plugins: [require('flowbite/plugin')]
};
module.exports = config;
```

After using Flowbite directly 
```
const config = {
    content: [
        './src/**/*.{html,js,svelte,ts}',
        "./node_modules/flowbite/**/*.js"
    ],
    theme: {
        extend: {}
    },
    plugins: [require('flowbite/plugin')]
};
module.exports = config;
```

### Reproduction

Follow the quickstart:
https://flowbite-svelte.com/docs/pages/quickstart

### Flowbite version and System Info

```shell
System:
    OS: macOS 13.5
    CPU: (8) arm64 Apple M2
    Memory: 57.09 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.5.0 - /opt/homebrew/bin/node
    npm: 9.8.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 115.0.5790.170
    Safari: 16.6
  npmPackages:
    flowbite-svelte: ^0.43.2 => 0.43.2 
    svelte: ^4.0.5 => 4.2.0 
    vite: ^4.4.5 => 4.4.9
```

**Comment by shinokada** [comment]
I tested in some cases:

1. plain Sveltekit without flowbite-svelte

```
  content: [
    './src/**/*.{html,js,svelte,ts}',
  ],
```

```
immutable find . -type f -exec du -h {} +
4.0K    ./nodes/2.ce583c9c.js
4.0K    ./nodes/1.064a352c.js
4.0K    ./nodes/0.80f7bad1.js
8.0K    ./entry/app.41393bd2.js
24K     ./entry/start.7bf215a5.js
4.0K    ./chunks/singletons.14d09f33.js
8.0K    ./chunks/index.0719bd3d.js
4.0K    ./chunks/scheduler.e108d1fd.js
16K     ./assets/0.8e59a230.css
16K     ./assets/_layout.8e59a230.css
```


2. Adding all flowbite-svelte

```
  content: [
    './src/**/*.{html,js,svelte,ts}',
    './node_modules/flowbite-svelte/**/*.{html,js,svelte,ts}'
  ],
```

```
immutable find . -type f -exec du -h {} +
4.0K    ./nodes/2.ce583c9c.js
4.0K    ./nodes/0.5f88361b.js
4.0K    ./nodes/1.152fde98.js
24K     ./entry/start.295a1058.js
8.0K    ./entry/app.fc0053eb.js
4.0K    ./chunks/singletons.f1f498ce.js
8.0K    ./chunks/index.0719bd3d.js
4.0K    ./chunks/scheduler.e108d1fd.js
120K    ./assets/0.c628d5d3.css
120K    ./assets/_layout.c058472c.css
```

3. Only accordion:

```
  content: [
    './src/**/*.{html,js,svelte,ts}',
    './node_modules/flowbite-svelte/dist/accordion/*.{html,js,svelte,ts}'
  ],
```

```
immutable find . -type f -exec du -h {} +
4.0K    ./nodes/2.ce583c9c.js
4.0K    ./nodes/1.2c764f57.js
4.0K    ./nodes/0.db8a7a87.js
8.0K    ./entry/app.d326ae7c.js
24K     ./entry/start.6aac0807.js
4.0K    ./chunks/singletons.a3014a24.js
8.0K    ./chunks/index.0719bd3d.js
4.0K    ./chunks/scheduler.e108d1fd.js
20K     ./assets/_layout.652e6244.css
20K     ./assets/0.652e6244.css
```

4. accordion and buttons dir

```
  content: [
    './src/**/*.{html,js,svelte,ts}',
    './node_modules/flowbite-svelte/dist/accordion/*.{html,js,svelte,ts}',
    './node_modules/flowbite-svelte/dist/buttons/*.{html,js,svelte,ts}'
  ],
```

```
immutable find . -type f -exec du -h {} +
4.0K    ./nodes/1.ac343be3.js
4.0K    ./nodes/2.ce583c9c.js
4.0K    ./nodes/0.a86d586a.js
24K     ./entry/start.3945a2e6.js
8.0K    ./entry/app.d83ed961.js
4.0K    ./chunks/singletons.6dc213d8.js
8.0K    ./chunks/index.0719bd3d.js
4.0K    ./chunks/scheduler.e108d1fd.js
40K     ./assets/_layout.96668095.css
40K     ./assets/0.96668095.css
```

One of the reasons is that all components have component docs and some of them are bigger than actual code. (Shall we remove them?)

One way is to create more subdirectories. 
e.g.
components
forms
typography
utilities

So that uses can import like this:

```
  content: [
    './src/**/*.{html,js,svelte,ts}',
    './node_modules/flowbite-svelte/dist/components/**/*.{html,js,svelte,ts}',
  ],
```

If you have any other solutions, please let me know.

**Comment by AdrianGonz97** [comment]
Hey @shinokada, I've written a Vite plugin for [Skeleton](https://skeleton.dev) (but should also work with Flowbite) that's aimed to tackle this CSS bundle size issue from Tailwind. In short, it extracts selectors from the chunks that are outputted by Rollup, which guarantees that only the selectors that you _actually_ use are included in the bundle.

It's still new, so bugs are to be expected, but results are promising!

Feel free to check it out! 
https://github.com/AdrianGonz97/vite-plugin-tailwind-purgecss

**Comment by shinokada** [comment]
@AdrianGonz97 Thanks. I will have a look at it.

**Comment by shinokada** [comment]
@AdrianGonz97 Thank you for your repo. It's excellent. This is the result using vite-plugin-tailwind-purgecss.

1. Without `'./node_modules/flowbite-svelte/**/*.{html,js,svelte,ts}'` in tailwind.config.cjs:

```
16K     ./assets/_layout.2e8a2793.css
16K     ./assets/0.2e8a2793.css
```

2. WITH `'./node_modules/flowbite-svelte/**/*.{html,js,svelte,ts}'` in tailwind.config.cjs

```
120K    ./assets/0.45987672.css
120K    ./assets/_layout.9381f94d.css
```

3. Using vite=plugin-tailwind-purgecss

```
44K     ./assets/0.45987672.css
44K     ./assets/_layout.9381f94d.css
```

It is about 66% down.

**Comment by shinokada** [comment]
@AdrianGonz97 I added your repo in this page, https://flowbite-svelte.com/docs/pages/faq-and-tips#My_compiled_CSS_size_is_more_than_120K._How_can_I_make_it_smaller?
