### ISSUE TITLE
Allow specifying Z-Index for Modal

### ISSUE THREAD

**Issue by Coronon** [themesberg/flowbite-svelte#994]
## Summary

I want to use the awesome `Modal` component but need to specify a custom `z-index` for my use case.
While I can add a custom class to the backdrop, there is no way to override classes on the actual modal div.

### Basic example

```jsx
<Modal defaultClass="z-100">
    // ...
</Modal>
```

### Motivation

Use the modal with other components with higher `z-index`.

**Comment by shinokada** [comment]
Two props will be exported in the next version:

```
  export let backdropClass: string = 'fixed inset-0 z-40 bg-gray-900 bg-opacity-50 dark:bg-opacity-80';
  export let dialogClass: string = 'fixed top-0 left-0 right-0 h-modal md:inset-0 md:h-full z-50 w-full p-4 flex';
```

**Comment by shinokada** [comment]
Please update to the latest version and let me know.

**Comment by Coronon** [comment]
Thank you for these quick changes :)

While they do work, the new prop is not documented anywhere and `getPlacementClasses()` takes precedence over them, which again limit's the users ability to define their own styling. There is also no corresponding `classDialog` prop as with `backdrop` and `default` that avoids having to respecify all props in `dialogClass`:

To increamse my z-index I now have to write:

``` jsx
<Modal dialogClass="fixed top-0 left-0 right-0 h-modal md:inset-0 md:h-full z-[1000] w-full p-4 flex" />
```

I would strongly prefer the following:
```jsx
<Modal classDialog="z-[1000]" />
```

This would also allow the library to change their default dialog styles without the user having to copy them into their code again :)
Please take a look at the PR I submitted, which implements all these things: #996

**Comment by Coronon** [comment]
Correction: The code compiles but I constantly get intellisense errors as the new props are not included in the TypeScript declarations.

**Comment by shinokada** [comment]
https://github.com/themesberg/flowbite-svelte/pull/1030 should solve this issue.
